// SPDX-License-Identifier: GPL-3.0-or-later
// PKHeX WinForms 26.08.26 language resources.
export const battlePass4Labels: Record<
  "zh" | "en" | "ja",
  Record<string, string>
> = {
  zh: {
    "BattlePassType.Custom": "自定义",
    "BattlePassType.Download": "下载",
    "BattlePassType.Friend": "好友",
    "BattlePassType.Other1": "其他1",
    "BattlePassType.Other2": "其他2",
    "BattlePassType.Other3": "其他3",
    "BattlePassType.Rental": "租借",
    SAV_BattlePass: "对战通行证编辑器",
    "ModelBR.CoolBoy": "酷男孩",
    "ModelBR.CoolGirl": "酷女孩",
    "ModelBR.Dawn": "小光",
    "ModelBR.Joe": "乔",
    "ModelBR.Kruger": "鲁德格",
    "ModelBR.LittleGirl": "小女孩",
    "ModelBR.Lucas": "明辉",
    "ModelBR.MuscleMan": "壮汉",
    "ModelBR.Mysterial": "谜团",
    "ModelBR.None": "(无)",
    "ModelBR.Sashay": "丝黛",
    "ModelBR.YoungBoy": "少年",
    "ModelBR.YoungGirl": "少女",
    "PictureTypeBR.FullBody": "全身",
    "PictureTypeBR.HeadShot": "半身",
    "SAV_BattlePass.B_Cancel": "取消",
    "SAV_BattlePass.B_Down": "v",
    "SAV_BattlePass.B_Export": "导出",
    "SAV_BattlePass.B_FDelete": "X",
    "SAV_BattlePass.B_Import": "导入",
    "SAV_BattlePass.B_Save": "保存",
    "SAV_BattlePass.B_UnlockCustom": "解锁所有自定义通行证",
    "SAV_BattlePass.B_UnlockRental": "解锁所有租借通行证",
    "SAV_BattlePass.B_Up": "^",
    "SAV_BattlePass.CHK_Available": "通行证可用",
    "SAV_BattlePass.CHK_Friend": "好友通行证",
    "SAV_BattlePass.CHK_Issued": "通行证已发放",
    "SAV_BattlePass.CHK_PresetGreeting": "预设口号",
    "SAV_BattlePass.CHK_PresetLose": "预设口号",
    "SAV_BattlePass.CHK_PresetSentOut": "预设口号",
    "SAV_BattlePass.CHK_PresetShift1": "预设口号",
    "SAV_BattlePass.CHK_PresetShift2": "预设口号",
    "SAV_BattlePass.CHK_PresetWin": "预设口号",
    "SAV_BattlePass.CHK_Rental": "租借通行证",
    "SAV_BattlePass.f_CATCHPHRASES": "口号",
    "SAV_BattlePass.f_CREATOR": "创建者",
    "SAV_BattlePass.f_MAIN": "主界面",
    "SAV_BattlePass.f_PKM": "宝可梦",
    "SAV_BattlePass.GB_Appearance": "外观",
    "SAV_BattlePass.GB_Creator": "创建者",
    "SAV_BattlePass.GB_PKM1": "宝可梦1",
    "SAV_BattlePass.GB_PKM2": "宝可梦2",
    "SAV_BattlePass.GB_PKM3": "宝可梦3",
    "SAV_BattlePass.GB_PKM4": "宝可梦4",
    "SAV_BattlePass.GB_PKM5": "宝可梦5",
    "SAV_BattlePass.GB_PKM6": "宝可梦6",
    "SAV_BattlePass.GB_Records": "记录",
    "SAV_BattlePass.GB_Trainer": "训练家",
    "SAV_BattlePass.L_Badge": "徽章：",
    "SAV_BattlePass.L_Bag": "背包：",
    "SAV_BattlePass.L_BattlePasses": "对战通行证：",
    "SAV_BattlePass.L_Battles": "对战数：",
    "SAV_BattlePass.L_BirthDay": "生日（日）:",
    "SAV_BattlePass.L_BirthMonth": "生日（月）:",
    "SAV_BattlePass.L_Bottom": "下装:",
    "SAV_BattlePass.L_Country": "国家:",
    "SAV_BattlePass.L_CreatorName": "创建者:",
    "SAV_BattlePass.L_Face": "面部:",
    "SAV_BattlePass.L_Glasses": "眼镜:",
    "SAV_BattlePass.L_Greeting": "问候语:",
    "SAV_BattlePass.L_Hair": "发型:",
    "SAV_BattlePass.L_Hands": "手部:",
    "SAV_BattlePass.L_Head": "头部:",
    "SAV_BattlePass.L_Language": "语言:",
    "SAV_BattlePass.L_Lose": "失败时:",
    "SAV_BattlePass.L_Model": "角色形象:",
    "SAV_BattlePass.L_Name": "名称:",
    "SAV_BattlePass.L_PassDesign": "通行证设计:",
    "SAV_BattlePass.L_PictureType": "图片类型:",
    "SAV_BattlePass.L_PKM1Box": "盒子:",
    "SAV_BattlePass.L_PKM1Flags": "旗标:",
    "SAV_BattlePass.L_PKM1Slot": "槽:",
    "SAV_BattlePass.L_PKM2Box": "盒子:",
    "SAV_BattlePass.L_PKM2Flags": "旗标:",
    "SAV_BattlePass.L_PKM2Slot": "槽:",
    "SAV_BattlePass.L_PKM3Box": "盒子:",
    "SAV_BattlePass.L_PKM3Flags": "旗标:",
    "SAV_BattlePass.L_PKM3Slot": "槽:",
    "SAV_BattlePass.L_PKM4Box": "盒子:",
    "SAV_BattlePass.L_PKM4Flags": "旗标:",
    "SAV_BattlePass.L_PKM4Slot": "槽:",
    "SAV_BattlePass.L_PKM5Box": "盒子:",
    "SAV_BattlePass.L_PKM5Flags": "旗标:",
    "SAV_BattlePass.L_PKM5Slot": "槽:",
    "SAV_BattlePass.L_PKM6Box": "盒子:",
    "SAV_BattlePass.L_PKM6Flags": "旗标:",
    "SAV_BattlePass.L_PKM6Slot": "槽:",
    "SAV_BattlePass.L_PlayerID": "玩家ID:",
    "SAV_BattlePass.L_RecordColosseumBattles": "竞技场对战数:",
    "SAV_BattlePass.L_RecordCourtyardColosseumClears": "城堡竞技场:",
    "SAV_BattlePass.L_RecordCrystalColosseumClears": "水晶竞技场:",
    "SAV_BattlePass.L_RecordFreeBattles": "自由对战数:",
    "SAV_BattlePass.L_RecordGatewayColosseumClears": "闸门竞技场:",
    "SAV_BattlePass.L_RecordMagmaColosseumClears": "熔岩竞技场:",
    "SAV_BattlePass.L_RecordMainStreetColosseumClears": "街道竞技场:",
    "SAV_BattlePass.L_RecordNeonColosseumClears": "娱乐戏院竞技场:",
    "SAV_BattlePass.L_RecordStargazerColosseumClears": "天文台竞技场:",
    "SAV_BattlePass.L_RecordSunnyParkColosseumClears": "阳光公园竞技场:",
    "SAV_BattlePass.L_RecordSunsetColosseumClears": "日落竞技场:",
    "SAV_BattlePass.L_RecordWaterfallColosseumClears": "水上竞技场:",
    "SAV_BattlePass.L_RecordWiFiBattles": "Wi-Fi对战数:",
    "SAV_BattlePass.L_Region": "居住地:",
    "SAV_BattlePass.L_RegionCode": "地区代码:",
    "SAV_BattlePass.L_SelfIntroduction": "自我介绍:",
    "SAV_BattlePass.L_SentOut": "派出宝可梦时:",
    "SAV_BattlePass.L_Shift1": "宝可梦切换1时:",
    "SAV_BattlePass.L_Shift2": "宝可梦切换2时:",
    "SAV_BattlePass.L_Shoes": "鞋子:",
    "SAV_BattlePass.L_SID": "里ID:",
    "SAV_BattlePass.L_SkinColor": "皮肤颜色:",
    "SAV_BattlePass.L_TID": "表ID:",
    "SAV_BattlePass.L_Top": "上装:",
    "SAV_BattlePass.L_TrainerTitle": "训练家头衔:",
    "SAV_BattlePass.L_Win": "胜利时:",
    "SkinColorBR.Dark": "深色",
    "SkinColorBR.Light": "浅色",
    "SkinColorBR.Tan": "棕褐色",
  },
  en: {
    "BattlePassType.Custom": "Custom",
    "BattlePassType.Download": "Download",
    "BattlePassType.Friend": "Friend",
    "BattlePassType.Other1": "Other 1",
    "BattlePassType.Other2": "Other 2",
    "BattlePassType.Other3": "Other 3",
    "BattlePassType.Rental": "Rental",
    SAV_BattlePass: "Battle Pass Editor",
    "ModelBR.CoolBoy": "Cool Boy",
    "ModelBR.CoolGirl": "Cool Girl",
    "ModelBR.Dawn": "Dawn",
    "ModelBR.Joe": "Joe",
    "ModelBR.Kruger": "Kruger",
    "ModelBR.LittleGirl": "Little Girl",
    "ModelBR.Lucas": "Lucas",
    "ModelBR.MuscleMan": "Muscle Man",
    "ModelBR.Mysterial": "Mysterial",
    "ModelBR.None": "(None)",
    "ModelBR.Sashay": "Sashay",
    "ModelBR.YoungBoy": "Young Boy",
    "ModelBR.YoungGirl": "Young Girl",
    "PictureTypeBR.FullBody": "Full Body",
    "PictureTypeBR.HeadShot": "Head Shot",
    "SAV_BattlePass.B_Cancel": "Cancel",
    "SAV_BattlePass.B_Down": "v",
    "SAV_BattlePass.B_Export": "Export",
    "SAV_BattlePass.B_FDelete": "X",
    "SAV_BattlePass.B_Import": "Import",
    "SAV_BattlePass.B_Save": "Save",
    "SAV_BattlePass.B_UnlockCustom": "Unlock All Custom Passes",
    "SAV_BattlePass.B_UnlockRental": "Unlock All Rental Passes",
    "SAV_BattlePass.B_Up": "^",
    "SAV_BattlePass.CHK_Available": "Pass Available",
    "SAV_BattlePass.CHK_Friend": "Friend Pass",
    "SAV_BattlePass.CHK_Issued": "Pass Issued",
    "SAV_BattlePass.CHK_PresetGreeting": "Preset Catchphrase",
    "SAV_BattlePass.CHK_PresetLose": "Preset Catchphrase",
    "SAV_BattlePass.CHK_PresetSentOut": "Preset Catchphrase",
    "SAV_BattlePass.CHK_PresetShift1": "Preset Catchphrase",
    "SAV_BattlePass.CHK_PresetShift2": "Preset Catchphrase",
    "SAV_BattlePass.CHK_PresetWin": "Preset Catchphrase",
    "SAV_BattlePass.CHK_Rental": "Rental Pass",
    "SAV_BattlePass.f_CATCHPHRASES": "Catchphrases",
    "SAV_BattlePass.f_CREATOR": "Creator",
    "SAV_BattlePass.f_MAIN": "Main",
    "SAV_BattlePass.f_PKM": "Pokémon",
    "SAV_BattlePass.GB_Appearance": "Appearance",
    "SAV_BattlePass.GB_Creator": "Creator",
    "SAV_BattlePass.GB_PKM1": "Pokémon 1",
    "SAV_BattlePass.GB_PKM2": "Pokémon 2",
    "SAV_BattlePass.GB_PKM3": "Pokémon 3",
    "SAV_BattlePass.GB_PKM4": "Pokémon 4",
    "SAV_BattlePass.GB_PKM5": "Pokémon 5",
    "SAV_BattlePass.GB_PKM6": "Pokémon 6",
    "SAV_BattlePass.GB_Records": "Records",
    "SAV_BattlePass.GB_Trainer": "Trainer",
    "SAV_BattlePass.L_Badge": "Badge:",
    "SAV_BattlePass.L_Bag": "Bag:",
    "SAV_BattlePass.L_BattlePasses": "Battle Passes:",
    "SAV_BattlePass.L_Battles": "Battles:",
    "SAV_BattlePass.L_BirthDay": "Birth Day:",
    "SAV_BattlePass.L_BirthMonth": "Birth Month:",
    "SAV_BattlePass.L_Bottom": "Bottom:",
    "SAV_BattlePass.L_Country": "Country:",
    "SAV_BattlePass.L_CreatorName": "Created By:",
    "SAV_BattlePass.L_Face": "Face:",
    "SAV_BattlePass.L_Glasses": "Glasses:",
    "SAV_BattlePass.L_Greeting": "Greeting:",
    "SAV_BattlePass.L_Hair": "Hair:",
    "SAV_BattlePass.L_Hands": "Hands:",
    "SAV_BattlePass.L_Head": "Head:",
    "SAV_BattlePass.L_Language": "Language:",
    "SAV_BattlePass.L_Lose": "Lose:",
    "SAV_BattlePass.L_Model": "Character:",
    "SAV_BattlePass.L_Name": "Name:",
    "SAV_BattlePass.L_PassDesign": "Pass Design:",
    "SAV_BattlePass.L_PictureType": "Picture Type:",
    "SAV_BattlePass.L_PKM1Box": "Box:",
    "SAV_BattlePass.L_PKM1Flags": "Flags:",
    "SAV_BattlePass.L_PKM1Slot": "Slot:",
    "SAV_BattlePass.L_PKM2Box": "Box:",
    "SAV_BattlePass.L_PKM2Flags": "Flags:",
    "SAV_BattlePass.L_PKM2Slot": "Slot:",
    "SAV_BattlePass.L_PKM3Box": "Box:",
    "SAV_BattlePass.L_PKM3Flags": "Flags:",
    "SAV_BattlePass.L_PKM3Slot": "Slot:",
    "SAV_BattlePass.L_PKM4Box": "Box:",
    "SAV_BattlePass.L_PKM4Flags": "Flags:",
    "SAV_BattlePass.L_PKM4Slot": "Slot:",
    "SAV_BattlePass.L_PKM5Box": "Box:",
    "SAV_BattlePass.L_PKM5Flags": "Flags:",
    "SAV_BattlePass.L_PKM5Slot": "Slot:",
    "SAV_BattlePass.L_PKM6Box": "Box:",
    "SAV_BattlePass.L_PKM6Flags": "Flags:",
    "SAV_BattlePass.L_PKM6Slot": "Slot:",
    "SAV_BattlePass.L_PlayerID": "Player ID:",
    "SAV_BattlePass.L_RecordColosseumBattles": "Colosseum Battles:",
    "SAV_BattlePass.L_RecordCourtyardColosseumClears": "Courtyard Colosseum:",
    "SAV_BattlePass.L_RecordCrystalColosseumClears": "Crystal Colosseum:",
    "SAV_BattlePass.L_RecordFreeBattles": "Free Battles:",
    "SAV_BattlePass.L_RecordGatewayColosseumClears": "Gateway Colosseum:",
    "SAV_BattlePass.L_RecordMagmaColosseumClears": "Magma Colosseum:",
    "SAV_BattlePass.L_RecordMainStreetColosseumClears":
      "Main Street Colosseum:",
    "SAV_BattlePass.L_RecordNeonColosseumClears": "Neon Colosseum:",
    "SAV_BattlePass.L_RecordStargazerColosseumClears": "Stargazer Colosseum:",
    "SAV_BattlePass.L_RecordSunnyParkColosseumClears": "Sunny Park Colosseum:",
    "SAV_BattlePass.L_RecordSunsetColosseumClears": "Sunset Colosseum:",
    "SAV_BattlePass.L_RecordWaterfallColosseumClears": "Waterfall Colosseum:",
    "SAV_BattlePass.L_RecordWiFiBattles": "Wi-Fi Battles:",
    "SAV_BattlePass.L_Region": "Sub Region:",
    "SAV_BattlePass.L_RegionCode": "Region Code:",
    "SAV_BattlePass.L_SelfIntroduction": "Self-Introduction:",
    "SAV_BattlePass.L_SentOut": "Pokémon Sent Out:",
    "SAV_BattlePass.L_Shift1": "Pokémon Shift 1:",
    "SAV_BattlePass.L_Shift2": "Pokémon Shift 2:",
    "SAV_BattlePass.L_Shoes": "Shoes:",
    "SAV_BattlePass.L_SID": "SID:",
    "SAV_BattlePass.L_SkinColor": "Skin Color:",
    "SAV_BattlePass.L_TID": "TID:",
    "SAV_BattlePass.L_Top": "Top:",
    "SAV_BattlePass.L_TrainerTitle": "Trainer Title:",
    "SAV_BattlePass.L_Win": "Win:",
    "SkinColorBR.Dark": "Dark",
    "SkinColorBR.Light": "Light",
    "SkinColorBR.Tan": "Tan",
  },
  ja: {
    "BattlePassType.Custom": "オリジナル",
    "BattlePassType.Download": "ダウンロード",
    "BattlePassType.Friend": "フレンド",
    "BattlePassType.Other1": "その他1",
    "BattlePassType.Other2": "その他2",
    "BattlePassType.Other3": "その他3",
    "BattlePassType.Rental": "レンタル",
    SAV_BattlePass: "バトルパス",
    "ModelBR.CoolBoy": "おにいさん",
    "ModelBR.CoolGirl": "おねえさん",
    "ModelBR.Dawn": "ヒカリ",
    "ModelBR.Joe": "ジョー",
    "ModelBR.Kruger": "ルトガー",
    "ModelBR.LittleGirl": "おんなのこ",
    "ModelBR.Lucas": "コウキ",
    "ModelBR.MuscleMan": "マッチョ",
    "ModelBR.Mysterial": "ミステリオ",
    "ModelBR.None": "(なし)",
    "ModelBR.Sashay": "リボン",
    "ModelBR.YoungBoy": "しょうねん",
    "ModelBR.YoungGirl": "しょうじょ",
    "PictureTypeBR.FullBody": "ぜんしん",
    "PictureTypeBR.HeadShot": "バストアップ",
    "SAV_BattlePass.B_Cancel": "キャンセル",
    "SAV_BattlePass.B_Down": "v",
    "SAV_BattlePass.B_Export": "ｴｸｽﾎﾟｰﾄ",
    "SAV_BattlePass.B_FDelete": "X",
    "SAV_BattlePass.B_Import": "ｲﾝﾎﾟｰﾄ",
    "SAV_BattlePass.B_Save": "保存",
    "SAV_BattlePass.B_UnlockCustom": "オリジナルパス全て解放",
    "SAV_BattlePass.B_UnlockRental": "レンタルパス全て解放",
    "SAV_BattlePass.B_Up": "^",
    "SAV_BattlePass.CHK_Available": "使えるパス",
    "SAV_BattlePass.CHK_Friend": "フレンドパス",
    "SAV_BattlePass.CHK_Issued": "発行したパス",
    "SAV_BattlePass.CHK_PresetGreeting": "プリセット",
    "SAV_BattlePass.CHK_PresetLose": "プリセット",
    "SAV_BattlePass.CHK_PresetSentOut": "プリセット",
    "SAV_BattlePass.CHK_PresetShift1": "プリセット",
    "SAV_BattlePass.CHK_PresetShift2": "プリセット",
    "SAV_BattlePass.CHK_PresetWin": "プリセット",
    "SAV_BattlePass.CHK_Rental": "レンタルパス",
    "SAV_BattlePass.f_CATCHPHRASES": "セリフ",
    "SAV_BattlePass.f_CREATOR": "さくせいしゃ",
    "SAV_BattlePass.f_MAIN": "メイン",
    "SAV_BattlePass.f_PKM": "ポケモン",
    "SAV_BattlePass.GB_Appearance": "スタイル",
    "SAV_BattlePass.GB_Creator": "さくせいしゃ",
    "SAV_BattlePass.GB_PKM1": "ポケモン1",
    "SAV_BattlePass.GB_PKM2": "ポケモン2",
    "SAV_BattlePass.GB_PKM3": "ポケモン3",
    "SAV_BattlePass.GB_PKM4": "ポケモン4",
    "SAV_BattlePass.GB_PKM5": "ポケモン5",
    "SAV_BattlePass.GB_PKM6": "ポケモン6",
    "SAV_BattlePass.GB_Records": "プレイきろく",
    "SAV_BattlePass.GB_Trainer": "トレーナー",
    "SAV_BattlePass.L_Badge": "バッジ",
    "SAV_BattlePass.L_Bag": "バッグ",
    "SAV_BattlePass.L_BattlePasses": "バトルパス",
    "SAV_BattlePass.L_Battles": "せんとうかいすう",
    "SAV_BattlePass.L_BirthDay": "うまれた日",
    "SAV_BattlePass.L_BirthMonth": "うまれた月",
    "SAV_BattlePass.L_Bottom": "ボトム",
    "SAV_BattlePass.L_Country": "国",
    "SAV_BattlePass.L_CreatorName": "さくせいしゃ",
    "SAV_BattlePass.L_Face": "かお",
    "SAV_BattlePass.L_Glasses": "メガネ",
    "SAV_BattlePass.L_Greeting": "あいさつ",
    "SAV_BattlePass.L_Hair": "かみ",
    "SAV_BattlePass.L_Hands": "うで",
    "SAV_BattlePass.L_Head": "あたま",
    "SAV_BattlePass.L_Language": "言語",
    "SAV_BattlePass.L_Lose": "まけた",
    "SAV_BattlePass.L_Model": "ベーススタイル",
    "SAV_BattlePass.L_Name": "名前",
    "SAV_BattlePass.L_PassDesign": "パスデザイン",
    "SAV_BattlePass.L_PictureType": "プリントタイプ",
    "SAV_BattlePass.L_PKM1Box": "ボックス",
    "SAV_BattlePass.L_PKM1Flags": "フラグ",
    "SAV_BattlePass.L_PKM1Slot": "スロット",
    "SAV_BattlePass.L_PKM2Box": "ボックス",
    "SAV_BattlePass.L_PKM2Flags": "フラグ",
    "SAV_BattlePass.L_PKM2Slot": "スロット",
    "SAV_BattlePass.L_PKM3Box": "ボックス",
    "SAV_BattlePass.L_PKM3Flags": "フラグ",
    "SAV_BattlePass.L_PKM3Slot": "スロット",
    "SAV_BattlePass.L_PKM4Box": "ボックス",
    "SAV_BattlePass.L_PKM4Flags": "フラグ",
    "SAV_BattlePass.L_PKM4Slot": "スロット",
    "SAV_BattlePass.L_PKM5Box": "ボックス",
    "SAV_BattlePass.L_PKM5Flags": "フラグ",
    "SAV_BattlePass.L_PKM5Slot": "スロット",
    "SAV_BattlePass.L_PKM6Box": "ボックス",
    "SAV_BattlePass.L_PKM6Flags": "フラグ",
    "SAV_BattlePass.L_PKM6Slot": "スロット",
    "SAV_BattlePass.L_PlayerID": "プレイヤーID",
    "SAV_BattlePass.L_RecordColosseumBattles": "コロシアムバトル",
    "SAV_BattlePass.L_RecordCourtyardColosseumClears": "キャッスルコロシアム",
    "SAV_BattlePass.L_RecordCrystalColosseumClears": "クリスタルコロシアム",
    "SAV_BattlePass.L_RecordFreeBattles": "フリーバトル",
    "SAV_BattlePass.L_RecordGatewayColosseumClears": "ゲートコロシアム",
    "SAV_BattlePass.L_RecordMagmaColosseumClears": "マグマコロシアム",
    "SAV_BattlePass.L_RecordMainStreetColosseumClears": "ストリートコロシアム",
    "SAV_BattlePass.L_RecordNeonColosseumClears": "カジノシアターコロシアム",
    "SAV_BattlePass.L_RecordStargazerColosseumClears": "スタービューコロシアム",
    "SAV_BattlePass.L_RecordSunnyParkColosseumClears": "サニーパークコロシアム",
    "SAV_BattlePass.L_RecordSunsetColosseumClears": "サンセットコロシアム",
    "SAV_BattlePass.L_RecordWaterfallColosseumClears": "ウォーターコロシアム",
    "SAV_BattlePass.L_RecordWiFiBattles": "Ｗｉ－Ｆｉバトル",
    "SAV_BattlePass.L_Region": "地域",
    "SAV_BattlePass.L_RegionCode": "リージョンコード",
    "SAV_BattlePass.L_SelfIntroduction": "じこしょうかい",
    "SAV_BattlePass.L_SentOut": "ポケモンとうじょう",
    "SAV_BattlePass.L_Shift1": "ポケモンこうたい１",
    "SAV_BattlePass.L_Shift2": "ポケモンこうたい２",
    "SAV_BattlePass.L_Shoes": "くつ",
    "SAV_BattlePass.L_SID": "裏ID",
    "SAV_BattlePass.L_SkinColor": "肌の色",
    "SAV_BattlePass.L_TID": "ID",
    "SAV_BattlePass.L_Top": "トップ",
    "SAV_BattlePass.L_TrainerTitle": "かたがき",
    "SAV_BattlePass.L_Win": "かった",
    "SkinColorBR.Dark": "Dark",
    "SkinColorBR.Light": "Light",
    "SkinColorBR.Tan": "Tan",
  },
};
