// SPDX-License-Identifier: GPL-3.0-or-later
// PKHeX WinForms 26.08.26 Resources/text labels.
export const br4Labels: Record<"zh" | "en" | "ja", Record<string, string>> = {
  zh: {
    SAV_Gear: "装扮配件编辑器",
    "GearCategory.Badges": "徽章",
    "GearCategory.Bags": "背包",
    "GearCategory.Bottom": "下装",
    "GearCategory.Face": "面部",
    "GearCategory.Glasses": "眼镜",
    "GearCategory.Hair": "发型",
    "GearCategory.Hands": "手部",
    "GearCategory.Head": "头部",
    "GearCategory.Shoes": "鞋子",
    "GearCategory.Top": "上装",
    "ModelBR.CoolBoy": "酷男孩",
    "ModelBR.CoolGirl": "酷女孩",
    "ModelBR.Dawn": "小光",
    "ModelBR.Joe": "乔",
    "ModelBR.Kruger": "鲁德格",
    "ModelBR.LittleGirl": "小女孩",
    "ModelBR.Lucas": "明辉",
    "ModelBR.MuscleMan": "壮汉",
    "ModelBR.Mysterial": "谜团",
    "ModelBR.None": "(无)",
    "ModelBR.Sashay": "丝黛",
    "ModelBR.YoungBoy": "少年",
    "ModelBR.YoungGirl": "少女",
    "SAV_Gear.B_Cancel": "取消",
    "SAV_Gear.B_Clear": "重置装扮为默认",
    "SAV_Gear.B_Save": "保存",
    "SAV_Gear.B_UnlockAll": "解锁所有装扮",
    "SAV_Gear.CHK_Electivire": "电击魔兽",
    "SAV_Gear.CHK_Groudon": "固拉多",
    "SAV_Gear.CHK_Kyogre": "盖欧卡",
    "SAV_Gear.CHK_Lucario": "路卡利欧",
    "SAV_Gear.CHK_Pachirisu": "帕奇利兹",
    "SAV_Gear.CHK_Roserade": "罗丝雷朵",
    "SAV_Gear.DGV_Category": "分类",
    "SAV_Gear.DGV_Gear": "装扮",
    "SAV_Gear.DGV_Model": "角色风格",
    "SAV_Gear.DGV_Obtained": "获得",
    "SAV_Gear.GB_ShinyOutfits": "异色服装",
  },
  en: {
    SAV_Gear: "Gear Editor",
    "GearCategory.Badges": "Badges",
    "GearCategory.Bags": "Bags",
    "GearCategory.Bottom": "Bottom",
    "GearCategory.Face": "Face",
    "GearCategory.Glasses": "Glasses",
    "GearCategory.Hair": "Hair",
    "GearCategory.Hands": "Hands",
    "GearCategory.Head": "Head",
    "GearCategory.Shoes": "Shoes",
    "GearCategory.Top": "Top",
    "ModelBR.CoolBoy": "Cool Boy",
    "ModelBR.CoolGirl": "Cool Girl",
    "ModelBR.Dawn": "Dawn",
    "ModelBR.Joe": "Joe",
    "ModelBR.Kruger": "Kruger",
    "ModelBR.LittleGirl": "Little Girl",
    "ModelBR.Lucas": "Lucas",
    "ModelBR.MuscleMan": "Muscle Man",
    "ModelBR.Mysterial": "Mysterial",
    "ModelBR.None": "(None)",
    "ModelBR.Sashay": "Sashay",
    "ModelBR.YoungBoy": "Young Boy",
    "ModelBR.YoungGirl": "Young Girl",
    "SAV_Gear.B_Cancel": "Cancel",
    "SAV_Gear.B_Clear": "Reset Gear to Default",
    "SAV_Gear.B_Save": "Save",
    "SAV_Gear.B_UnlockAll": "Unlock All Gear",
    "SAV_Gear.CHK_Electivire": "Electivire",
    "SAV_Gear.CHK_Groudon": "Groudon",
    "SAV_Gear.CHK_Kyogre": "Kyogre",
    "SAV_Gear.CHK_Lucario": "Lucario",
    "SAV_Gear.CHK_Pachirisu": "Pachirisu",
    "SAV_Gear.CHK_Roserade": "Roserade",
    "SAV_Gear.DGV_Category": "Category",
    "SAV_Gear.DGV_Gear": "Gear",
    "SAV_Gear.DGV_Model": "Character Style",
    "SAV_Gear.DGV_Obtained": "Obtained",
    "SAV_Gear.GB_ShinyOutfits": "Shiny Outfits",
  },
  ja: {
    SAV_Gear: "パーツ",
    "GearCategory.Badges": "バッジ",
    "GearCategory.Bags": "バッグ",
    "GearCategory.Bottom": "ボトム",
    "GearCategory.Face": "かお",
    "GearCategory.Glasses": "メガネ",
    "GearCategory.Hair": "かみ",
    "GearCategory.Hands": "うで",
    "GearCategory.Head": "あたま",
    "GearCategory.Shoes": "くつ",
    "GearCategory.Top": "トップ",
    "ModelBR.CoolBoy": "おにいさん",
    "ModelBR.CoolGirl": "おねえさん",
    "ModelBR.Dawn": "ヒカリ",
    "ModelBR.Joe": "ジョー",
    "ModelBR.Kruger": "ルトガー",
    "ModelBR.LittleGirl": "おんなのこ",
    "ModelBR.Lucas": "コウキ",
    "ModelBR.MuscleMan": "マッチョ",
    "ModelBR.Mysterial": "ミステリオ",
    "ModelBR.None": "(なし)",
    "ModelBR.Sashay": "リボン",
    "ModelBR.YoungBoy": "しょうねん",
    "ModelBR.YoungGirl": "しょうじょ",
    "SAV_Gear.B_Cancel": "キャンセル",
    "SAV_Gear.B_Clear": "パーツをリセット",
    "SAV_Gear.B_Save": "保存",
    "SAV_Gear.B_UnlockAll": "全てのパーツ解放",
    "SAV_Gear.CHK_Electivire": "エレキブル",
    "SAV_Gear.CHK_Groudon": "グラードン",
    "SAV_Gear.CHK_Kyogre": "カイオーガ",
    "SAV_Gear.CHK_Lucario": "ルカリオ",
    "SAV_Gear.CHK_Pachirisu": "パチリス",
    "SAV_Gear.CHK_Roserade": "ロズレイド",
    "SAV_Gear.DGV_Category": "カテゴリ",
    "SAV_Gear.DGV_Gear": "パーツ",
    "SAV_Gear.DGV_Model": "ベーススタイル",
    "SAV_Gear.DGV_Obtained": "獲得",
    "SAV_Gear.GB_ShinyOutfits": "色違いセット",
  },
};
