// SPDX-License-Identifier: GPL-3.0-or-later
// PKHeX WinForms 26.08.26 language resources.
export const brTrainer4Labels: Record<
  "zh" | "en" | "ja",
  Record<string, string>
> = {
  zh: {
    SAV_Trainer4BR: "训练家资料",
    "SAV_Trainer4BR.B_Cancel": "取消",
    "SAV_Trainer4BR.B_MaxCash": "+",
    "SAV_Trainer4BR.B_Save": "保存",
    "SAV_Trainer4BR.CHK_PostGame": "通关后",
    "SAV_Trainer4BR.GB_Colosseums": "竞技场",
    "SAV_Trainer4BR.GB_Profile": "个人信息",
    "SAV_Trainer4BR.GB_Records": "记录",
    "SAV_Trainer4BR.L_BirthDay": "生日（日）:",
    "SAV_Trainer4BR.L_BirthMonth": "生日（月）:",
    "SAV_Trainer4BR.L_Country": "国家:",
    "SAV_Trainer4BR.L_Coupons": "宝可券数:",
    "SAV_Trainer4BR.L_Hours": "时:",
    "SAV_Trainer4BR.L_Language": "语言:",
    "SAV_Trainer4BR.L_Minutes": "分:",
    "SAV_Trainer4BR.L_PlayerID": "玩家ID:",
    "SAV_Trainer4BR.L_RecordColosseumBattles": "竞技场对战数:",
    "SAV_Trainer4BR.L_RecordCourtyardColosseumClears": "城堡竞技场:",
    "SAV_Trainer4BR.L_RecordCrystalColosseumClears": "水晶竞技场:",
    "SAV_Trainer4BR.L_RecordFreeBattles": "自由对战数:",
    "SAV_Trainer4BR.L_RecordGatewayColosseumClears": "闸门竞技场:",
    "SAV_Trainer4BR.L_RecordMagmaColosseumClears": "熔岩竞技场:",
    "SAV_Trainer4BR.L_RecordMainStreetColosseumClears": "街道竞技场:",
    "SAV_Trainer4BR.L_RecordNeonColosseumClears": "娱乐戏院竞技场:",
    "SAV_Trainer4BR.L_RecordStargazerColosseumClears": "天文台竞技场:",
    "SAV_Trainer4BR.L_RecordSunnyParkColosseumClears": "阳光公园竞技场:",
    "SAV_Trainer4BR.L_RecordSunsetColosseumClears": "日落竞技场:",
    "SAV_Trainer4BR.L_RecordTotalBattles": "总对战数:",
    "SAV_Trainer4BR.L_RecordWaterfallColosseumClears": "水上竞技场:",
    "SAV_Trainer4BR.L_RecordWiFiBattles": "Wi-Fi对战数:",
    "SAV_Trainer4BR.L_Region": "居住地:",
    "SAV_Trainer4BR.L_Seconds": "秒:",
    "SAV_Trainer4BR.L_SelfIntroduction": "自我介绍:",
    "SAV_Trainer4BR.L_SID": "Nintendo DS里ID:",
    "SAV_Trainer4BR.L_TID": "Nintendo DS表ID:",
    "SAV_Trainer4BR.L_TrainerName": "名字:",
  },
  en: {
    SAV_Trainer4BR: "Trainer Data Editor",
    "SAV_Trainer4BR.B_Cancel": "Cancel",
    "SAV_Trainer4BR.B_MaxCash": "+",
    "SAV_Trainer4BR.B_Save": "Save",
    "SAV_Trainer4BR.CHK_PostGame": "Post-Game",
    "SAV_Trainer4BR.GB_Colosseums": "Colosseums",
    "SAV_Trainer4BR.GB_Profile": "Profile",
    "SAV_Trainer4BR.GB_Records": "Records",
    "SAV_Trainer4BR.L_BirthDay": "Birth Day:",
    "SAV_Trainer4BR.L_BirthMonth": "Birth Month:",
    "SAV_Trainer4BR.L_Country": "Country:",
    "SAV_Trainer4BR.L_Coupons": "Poké Coupons:",
    "SAV_Trainer4BR.L_Hours": "Hrs:",
    "SAV_Trainer4BR.L_Language": "Language:",
    "SAV_Trainer4BR.L_Minutes": "Min:",
    "SAV_Trainer4BR.L_PlayerID": "Player ID:",
    "SAV_Trainer4BR.L_RecordColosseumBattles": "Colosseum Battles:",
    "SAV_Trainer4BR.L_RecordCourtyardColosseumClears": "Courtyard Colosseum:",
    "SAV_Trainer4BR.L_RecordCrystalColosseumClears": "Crystal Colosseum:",
    "SAV_Trainer4BR.L_RecordFreeBattles": "Free Battles:",
    "SAV_Trainer4BR.L_RecordGatewayColosseumClears": "Gateway Colosseum:",
    "SAV_Trainer4BR.L_RecordMagmaColosseumClears": "Magma Colosseum:",
    "SAV_Trainer4BR.L_RecordMainStreetColosseumClears":
      "Main Street Colosseum:",
    "SAV_Trainer4BR.L_RecordNeonColosseumClears": "Neon Colosseum:",
    "SAV_Trainer4BR.L_RecordStargazerColosseumClears": "Stargazer Colosseum:",
    "SAV_Trainer4BR.L_RecordSunnyParkColosseumClears": "Sunny Park Colosseum:",
    "SAV_Trainer4BR.L_RecordSunsetColosseumClears": "Sunset Colosseum:",
    "SAV_Trainer4BR.L_RecordTotalBattles": "Total Battles:",
    "SAV_Trainer4BR.L_RecordWaterfallColosseumClears": "Waterfall Colosseum:",
    "SAV_Trainer4BR.L_RecordWiFiBattles": "Wi-Fi Battles:",
    "SAV_Trainer4BR.L_Region": "Sub Region:",
    "SAV_Trainer4BR.L_Seconds": "Sec:",
    "SAV_Trainer4BR.L_SelfIntroduction": "Self-Introduction:",
    "SAV_Trainer4BR.L_SID": "Nintendo DS SID:",
    "SAV_Trainer4BR.L_TID": "Nintendo DS TID:",
    "SAV_Trainer4BR.L_TrainerName": "Name:",
  },
  ja: {
    SAV_Trainer4BR: "トレーナー情報",
    "SAV_Trainer4BR.B_Cancel": "キャンセル",
    "SAV_Trainer4BR.B_MaxCash": "+",
    "SAV_Trainer4BR.B_Save": "保存",
    "SAV_Trainer4BR.CHK_PostGame": "エンディング後",
    "SAV_Trainer4BR.GB_Colosseums": "コロシアム",
    "SAV_Trainer4BR.GB_Profile": "プロファイル",
    "SAV_Trainer4BR.GB_Records": "プレイきろく",
    "SAV_Trainer4BR.L_BirthDay": "うまれた日",
    "SAV_Trainer4BR.L_BirthMonth": "うまれた月",
    "SAV_Trainer4BR.L_Country": "国",
    "SAV_Trainer4BR.L_Coupons": "ポケクーポン",
    "SAV_Trainer4BR.L_Hours": "時：",
    "SAV_Trainer4BR.L_Language": "言語",
    "SAV_Trainer4BR.L_Minutes": "分：",
    "SAV_Trainer4BR.L_PlayerID": "プレイヤーID",
    "SAV_Trainer4BR.L_RecordColosseumBattles": "コロシアムバトル",
    "SAV_Trainer4BR.L_RecordCourtyardColosseumClears": "キャッスルコロシアム",
    "SAV_Trainer4BR.L_RecordCrystalColosseumClears": "クリスタルコロシアム",
    "SAV_Trainer4BR.L_RecordFreeBattles": "フリーバトル",
    "SAV_Trainer4BR.L_RecordGatewayColosseumClears": "ゲートコロシアム",
    "SAV_Trainer4BR.L_RecordMagmaColosseumClears": "マグマコロシアム",
    "SAV_Trainer4BR.L_RecordMainStreetColosseumClears": "ストリートコロシアム",
    "SAV_Trainer4BR.L_RecordNeonColosseumClears": "カジノシアターコロシアム",
    "SAV_Trainer4BR.L_RecordStargazerColosseumClears": "スタービューコロシアム",
    "SAV_Trainer4BR.L_RecordSunnyParkColosseumClears": "サニーパークコロシアム",
    "SAV_Trainer4BR.L_RecordSunsetColosseumClears": "サンセットコロシアム",
    "SAV_Trainer4BR.L_RecordTotalBattles": "合計バトル回数",
    "SAV_Trainer4BR.L_RecordWaterfallColosseumClears": "ウォーターコロシアム",
    "SAV_Trainer4BR.L_RecordWiFiBattles": "Ｗｉ－Ｆｉバトル",
    "SAV_Trainer4BR.L_Region": "地域",
    "SAV_Trainer4BR.L_Seconds": "秒：",
    "SAV_Trainer4BR.L_SelfIntroduction": "じこしょうかい",
    "SAV_Trainer4BR.L_SID": "ニンテンドーDS 裏ID:",
    "SAV_Trainer4BR.L_TID": "ニンテンドーDS ID:",
    "SAV_Trainer4BR.L_TrainerName": "名前",
  },
};
