// UI labels from pinned PKHeX SAV_HallOfFame; descriptive trainer labels follow the owner language rule.
export const hall6Words = {
  zh: {
    title: "名人堂",
    read: "读取名人堂",
    team: "队伍",
    member: "成员",
    field: "字段",
    empty: "没有记录",
    clear: "通关编号",
    date: "日期",
    level: "等级",
    shiny: "异色",
    item: "持有物",
    moves: "招式",
    trainerName: "训练家姓名",
    notEditable: "此队伍为空或成员超出来源可编辑范围，仅供读取。",
    resave: "按窗口规则重新保存",
    resaveNote:
      "重新保存当前成员会重写昵称和训练家姓名、规范化旧值并按三位输入规则写回通关编号。普通补丁保留未指定字段。",
    delete: "删除队伍",
    deleteNote: "后续队伍将向前移动，最后一队清空；首次通关记录受到保护。",
    special: "特殊字符",
    insert: "插入字符",
    trash: "昵称废字节",
    trashNote:
      "来源昵称工具包含26字节，最后两字节是训练家姓名的首字符。预览会显示关联变化；文本变化还会触发来源整窗写回。",
    raw: "原始数据",
    copy: "复制队伍文本",
    copyError: "无法复制文本，请手动选择并复制。",
    language: "语言",
    generation: "世代",
    invalid: "名人堂字段、位置或操作无效，请核对输入。",
    stale: "存档或预览已变化，请重新读取并预览。",
    trashActions: {
      prepare: "准备来源文本区域",
      hex: "预览原始字节修改",
      text: "预览文本修改",
      clear: "清除废字节",
      layer: "应用种类名称层",
    },
    fields: {
      Species: "种类:",
      HeldItem: "持有道具:",
      Move1: "招式1",
      Move2: "招式2",
      Move3: "招式3",
      Move4: "招式4",
      Ec: "加密常数:",
      Tid: "表ID:",
      Sid: "里ID:",
      Form: "形态:",
      Gender: "性别",
      Level: "等级",
      Shiny: "异色:",
      Nicknamed: "昵称:",
      Nickname: "昵称",
      TrainerName: "训练家姓名",
      TrainerGender: "训练家性别",
      ClearIndex: "通关编号",
      Date: "日期:",
    },
  },
  en: {
    title: "Hall of Fame Editor",
    read: "Read Hall of Fame",
    team: "Team",
    member: "Member",
    field: "Field",
    empty: "No records",
    clear: "Clear index",
    date: "Date",
    level: "Level",
    shiny: "Shiny",
    item: "Held item",
    moves: "Move",
    trainerName: "Trainer name",
    notEditable:
      "This team is empty or the member is outside the source editable range. Read only.",
    resave: "Resave using window rules",
    resaveNote:
      "Resaving rewrites the selected nickname/trainer text, normalizes old values and writes the clear index through the three-digit source input. Ordinary patches preserve unspecified fields.",
    delete: "Delete team",
    deleteNote:
      "Later teams move forward and the final team is cleared. The first clear entry is protected.",
    special: "Special characters",
    insert: "Insert character",
    trash: "Nickname trash bytes",
    trashNote:
      "The source tool covers 26 bytes; its final two bytes contain the first trainer-name character. The preview shows linked changes. Text changes also trigger the source window rewrite.",
    raw: "Raw data",
    copy: "Copy team text",
    copyError: "Cannot copy text. Select and copy it manually.",
    language: "Language",
    generation: "Generation",
    invalid:
      "Invalid Hall of Fame field, position or operation. Check the input.",
    stale: "The save or preview changed. Read and preview it again.",
    trashActions: {
      prepare: "Prepare source text region",
      hex: "Preview raw byte edit",
      text: "Preview text edit",
      clear: "Clear trash",
      layer: "Apply species name layer",
    },
    fields: {
      Species: "Species:",
      HeldItem: "Held Item:",
      Move1: "Move 1",
      Move2: "Move 2",
      Move3: "Move 3",
      Move4: "Move 4",
      Ec: "Encryption Constant:",
      Tid: "TID:",
      Sid: "SID:",
      Form: "Form:",
      Gender: "Gender",
      Level: "Level",
      Shiny: "Shiny:",
      Nicknamed: "Nickname:",
      Nickname: "Nickname",
      TrainerName: "Trainer name",
      TrainerGender: "Trainer gender",
      ClearIndex: "Clear index",
      Date: "Date:",
    },
  },
  ja: {
    title: "殿堂入りデータ",
    read: "殿堂入りを読み込む",
    team: "チーム",
    member: "メンバー",
    field: "項目",
    empty: "記録なし",
    clear: "クリア番号",
    date: "日付",
    level: "レベル",
    shiny: "色違い",
    item: "持ち物",
    moves: "技",
    trainerName: "親の名前",
    notEditable:
      "空のチーム、または元の編集可能範囲外のメンバーです。読み取りのみです。",
    resave: "元の編集ルールで再保存",
    resaveNote:
      "再保存は選択中の名前を書き直し、旧値を正規化し、クリア番号を元の3桁入力で保存します。通常の変更は未指定の値を維持します。",
    delete: "チームを削除",
    deleteNote:
      "後続チームを前へ移動し、最後のチームを消去します。初回記録は保護されます。",
    special: "特殊文字",
    insert: "文字を挿入",
    trash: "ニックネームの余剰バイト",
    trashNote:
      "元の領域は26バイトで、最後の2バイトは親の名前の先頭文字です。関連変化を表示します。文字変更は元の画面の再保存も実行します。",
    raw: "生データ",
    copy: "チームのテキストをコピー",
    copyError: "コピーできません。テキストを選択してコピーしてください。",
    language: "言語",
    generation: "世代",
    invalid: "項目、位置または操作が無効です。入力を確認してください。",
    stale:
      "セーブまたはプレビューが変わりました。再読み込みして確認してください。",
    trashActions: {
      prepare: "元の文字領域を準備",
      hex: "バイト変更を確認",
      text: "文字変更を確認",
      clear: "余剰バイトを消去",
      layer: "種族名の層を適用",
    },
    fields: {
      Species: "ポケモン",
      HeldItem: "持ち物",
      Move1: "技1",
      Move2: "技2",
      Move3: "技3",
      Move4: "技4",
      Ec: "暗号化定数",
      Tid: "ID:",
      Sid: "裏ID:",
      Form: "ﾌｫﾙﾑ",
      Gender: "性別",
      Level: "レベル",
      Shiny: "色違い",
      Nicknamed: "ニックネーム",
      Nickname: "ニックネーム",
      TrainerName: "親の名前",
      TrainerGender: "親の性別",
      ClearIndex: "クリア番号",
      Date: "日付",
    },
  },
};
