// Labels from pinned PKHeX WinForms language resources.
export const medals5Labels = {
  zh: {
    title: "奖牌编辑器",
    medals: "奖牌",
    habitats: "栖息地列表",
    giveAll: "全部给予",
    importAll: "全部导入",
    exportAll: "全部导出",
    clear: "清除",
    complete: "设为完成",
    tutorial: "教程完成",
    viewed: "已查看教程",
    capture: "捕获教程完成",
    pinned: "置顶奖牌:",
    rank: "等级:",
    lastEncounter: "上次遭遇类型:",
    index: "编号",
    name: "名称",
    type: "类型",
    state: "状态",
    unread: "未读",
    date: "日期",
    grass: "草丛",
    surf: "冲浪",
    fish: "垂钓",
    states: ["未获得", "可获提示", "已获提示", "可获得", "已获得"],
    ranks: ["无", "新秀", "精英", "大师", "传说"],
    completion: ["无", "已见", "已捕获", "完成"],
    encounters: ["草丛", "冲浪", "垂钓"],
  },
  en: {
    title: "Medal Editor",
    medals: "Medals",
    habitats: "Habitat",
    giveAll: "Give All",
    importAll: "Import All",
    exportAll: "Export All",
    clear: "Clear",
    complete: "Set Complete",
    tutorial: "Tutorial Complete",
    viewed: "Tutorial Viewed",
    capture: "Tutorial Capture Done",
    pinned: "Pinned Medal:",
    rank: "Rank:",
    lastEncounter: "Last Encounter Type:",
    index: "Index",
    name: "Name",
    type: "Type",
    state: "State",
    unread: "IsUnread",
    date: "Date",
    grass: "Grass",
    surf: "Surf",
    fish: "Fish",
    states: [
      "Unobtained",
      "HintReady",
      "HintObtained",
      "ObtainReady",
      "Obtained",
    ],
    ranks: ["None", "Rookie", "Elite", "Master", "Legend"],
    completion: ["None", "Seen", "Caught", "Complete"],
    encounters: ["Grass", "Surf", "Fish"],
  },
  ja: {
    title: "メダル",
    medals: "メダル",
    habitats: "生息地リスト",
    giveAll: "すべて付与",
    importAll: "すべてインポート",
    exportAll: "すべてエクスポート",
    clear: "クリア",
    complete: "コンプリートにする",
    tutorial: "チュートリアル完了",
    viewed: "チュートリアル閲覧済み",
    capture: "捕獲チュートリアル完了",
    pinned: "ピン留めメダル:",
    rank: "ランク:",
    lastEncounter: "最後の遭遇タイプ:",
    index: "番号",
    name: "名前",
    type: "種類",
    state: "状態",
    unread: "未読",
    date: "日付",
    grass: "草むら",
    surf: "なみのり",
    fish: "釣り",
    states: ["未獲得", "ヒントあり", "ヒント取得済み", "獲得可能", "獲得済み"],
    ranks: [
      "なし",
      "ルーキーメダリスト",
      "エリートメダリスト",
      "マスターメダリスト",
      "レジェンドメダリスト",
    ],
    completion: ["なし", "見つけた", "捕まえた", "コンプリート"],
    encounters: ["草むら", "なみのり", "釣り"],
  },
} as const;
