// SPDX-License-Identifier: GPL-3.0-or-later
// Labels from PKHeX 26.08.26 WinForms Resources/text/lang_{zh-Hans,en,ja}.txt.
export const ath4Labels: Record<"zh" | "en" | "ja", Record<string, string>> = {
  zh: {
    SAV_Pokeathlon4: "宝可全能竞技赛编辑器",
    "PokeathlonEvent4.BlockSmash": "粉碎方块",
    "PokeathlonEvent4.CirclePush": "圆环推进",
    "PokeathlonEvent4.DiscCatch": "飞盘接取",
    "PokeathlonEvent4.GoalRoll": "滚向球门",
    "PokeathlonEvent4.HurdleDash": "跨栏冲刺",
    "PokeathlonEvent4.LampJump": "跳灯赛",
    "PokeathlonEvent4.PennantCapture": "夺旗赛",
    "PokeathlonEvent4.RelayRun": "接力赛跑",
    "PokeathlonEvent4.RingDrop": "投环赛",
    "PokeathlonEvent4.SnowThrow": "雪球投掷",
    "PokeathlonStat4.Jump": "跳跃",
    "PokeathlonStat4.Power": "力量",
    "PokeathlonStat4.Skill": "技巧",
    "PokeathlonStat4.Speed": "速度",
    "PokeathlonStat4.Stamina": "耐力",
    "SAV_Pokeathlon4.B_Cancel": "取消",
    "SAV_Pokeathlon4.B_MedalsClearAll": "全部清空",
    "SAV_Pokeathlon4.B_MedalsGiveAll": "全部获得",
    "SAV_Pokeathlon4.B_Save": "保存",
    "SAV_Pokeathlon4.CHK_IsShiny": "异色",
    "SAV_Pokeathlon4.DGV_Jump": "跳跃",
    "SAV_Pokeathlon4.DGV_Power": "力量",
    "SAV_Pokeathlon4.DGV_Skill": "技巧",
    "SAV_Pokeathlon4.DGV_Species": "种类",
    "SAV_Pokeathlon4.DGV_Speed": "速度",
    "SAV_Pokeathlon4.DGV_Sprite": "精灵",
    "SAV_Pokeathlon4.DGV_Stamina": "耐力",
    "SAV_Pokeathlon4.L_Acquired": "已获得",
    "SAV_Pokeathlon4.L_Attempts": "尝试次数",
    "SAV_Pokeathlon4.L_BlockSmashFirst": "粉碎方块第一",
    "SAV_Pokeathlon4.L_BonusesEarned": "奖励获得",
    "SAV_Pokeathlon4.L_CirclePushFirst": "圆环推进第一",
    "SAV_Pokeathlon4.L_ConnectionFirst": "连接第一",
    "SAV_Pokeathlon4.L_ConnectionIndex": "编号",
    "SAV_Pokeathlon4.L_ConnectionJoined": "连接参加次数",
    "SAV_Pokeathlon4.L_ConnectionLast": "连接最后",
    "SAV_Pokeathlon4.L_CourseIndex": "编号",
    "SAV_Pokeathlon4.L_CourseParticipant0": "参加者1",
    "SAV_Pokeathlon4.L_CourseParticipant1": "参加者2",
    "SAV_Pokeathlon4.L_CourseParticipant2": "参加者3",
    "SAV_Pokeathlon4.L_CourseScore0": "分数1",
    "SAV_Pokeathlon4.L_CourseScore1": "分数2",
    "SAV_Pokeathlon4.L_CourseScore2": "分数3",
    "SAV_Pokeathlon4.L_CourseScoreMax": "最高分",
    "SAV_Pokeathlon4.L_DailyShopFlags": "每日商店",
    "SAV_Pokeathlon4.L_Dashed": "冲刺次数",
    "SAV_Pokeathlon4.L_DataCards": "数据卡",
    "SAV_Pokeathlon4.L_DiscCatchFirst": "飞盘接取第一",
    "SAV_Pokeathlon4.L_Failed": "失败",
    "SAV_Pokeathlon4.L_Fame": "名望",
    "SAV_Pokeathlon4.L_FellDown": "摔倒",
    "SAV_Pokeathlon4.L_GoalRollFirst": "滚向球门第一",
    "SAV_Pokeathlon4.L_HurdleDashFirst": "跨栏冲刺第一",
    "SAV_Pokeathlon4.L_Instructions": "说明",
    "SAV_Pokeathlon4.L_Jumped": "跳跃次数",
    "SAV_Pokeathlon4.L_LampJumpFirst": "跳灯赛第一",
    "SAV_Pokeathlon4.L_Language": "语言",
    "SAV_Pokeathlon4.L_OT": "OT",
    "SAV_Pokeathlon4.L_PennantCaptureFirst": "夺旗赛第一",
    "SAV_Pokeathlon4.L_PID": "PID",
    "SAV_Pokeathlon4.L_PlacedFirst": "第一名次数",
    "SAV_Pokeathlon4.L_PlacedLast": "最后一名次数",
    "SAV_Pokeathlon4.L_Points": "点数",
    "SAV_Pokeathlon4.L_Record": "记录",
    "SAV_Pokeathlon4.L_RelayRunFirst": "接力赛跑第一",
    "SAV_Pokeathlon4.L_RingDropFirst": "投环赛第一",
    "SAV_Pokeathlon4.L_SelfEventIndex": "编号",
    "SAV_Pokeathlon4.L_SelfImpeded": "自我妨碍",
    "SAV_Pokeathlon4.L_SessionsJoined": "参加会话数",
    "SAV_Pokeathlon4.L_SID16": "SID",
    "SAV_Pokeathlon4.L_SnowThrowFirst": "雪球投掷第一",
    "SAV_Pokeathlon4.L_Switched": "切换次数",
    "SAV_Pokeathlon4.L_Tackled": "擒抱",
    "SAV_Pokeathlon4.L_TID16": "TID",
    "SAV_Pokeathlon4.L_TimeSpent": "花费时间",
    "SAV_Pokeathlon4.L_TotalEventFirst": "总赛事第一",
    "SAV_Pokeathlon4.L_TotalEventLast": "总赛事最后",
    "SAV_Pokeathlon4.L_Trainer0": "训练家1",
    "SAV_Pokeathlon4.L_Trainer1": "训练家2",
    "SAV_Pokeathlon4.L_Trainer2": "训练家3",
    "SAV_Pokeathlon4.L_Trainer3": "训练家4",
    "SAV_Pokeathlon4.L_Trainer4": "训练家5",
    "SAV_Pokeathlon4.Tab_Best": "最佳",
    "SAV_Pokeathlon4.Tab_Connection": "连接",
    "SAV_Pokeathlon4.Tab_Counters": "计数",
    "SAV_Pokeathlon4.Tab_Courses": "赛程",
    "SAV_Pokeathlon4.Tab_General": "一般",
    "SAV_Pokeathlon4.Tab_Medals": "奖牌",
    "SAV_Pokeathlon4.Tab_SelfEvent": "个人赛事",
  },
  en: {
    SAV_Pokeathlon4: "Pokéathlon Editor",
    "PokeathlonEvent4.BlockSmash": "Block Smash",
    "PokeathlonEvent4.CirclePush": "Circle Push",
    "PokeathlonEvent4.DiscCatch": "Disc Catch",
    "PokeathlonEvent4.GoalRoll": "Goal Roll",
    "PokeathlonEvent4.HurdleDash": "Hurdle Dash",
    "PokeathlonEvent4.LampJump": "Lamp Jump",
    "PokeathlonEvent4.PennantCapture": "Pennant Capture",
    "PokeathlonEvent4.RelayRun": "Relay Run",
    "PokeathlonEvent4.RingDrop": "Ring Drop",
    "PokeathlonEvent4.SnowThrow": "Snow Throw",
    "PokeathlonStat4.Jump": "Jump",
    "PokeathlonStat4.Power": "Power",
    "PokeathlonStat4.Skill": "Skill",
    "PokeathlonStat4.Speed": "Speed",
    "PokeathlonStat4.Stamina": "Stamina",
    "SAV_Pokeathlon4.B_Cancel": "Cancel",
    "SAV_Pokeathlon4.B_MedalsClearAll": "Clear All",
    "SAV_Pokeathlon4.B_MedalsGiveAll": "Give All",
    "SAV_Pokeathlon4.B_Save": "Save",
    "SAV_Pokeathlon4.CHK_IsShiny": "Shiny",
    "SAV_Pokeathlon4.DGV_Jump": "Jump",
    "SAV_Pokeathlon4.DGV_Power": "Power",
    "SAV_Pokeathlon4.DGV_Skill": "Skill",
    "SAV_Pokeathlon4.DGV_Species": "Species",
    "SAV_Pokeathlon4.DGV_Speed": "Speed",
    "SAV_Pokeathlon4.DGV_Sprite": "Sprite",
    "SAV_Pokeathlon4.DGV_Stamina": "Stamina",
    "SAV_Pokeathlon4.L_Acquired": "Acquired",
    "SAV_Pokeathlon4.L_Attempts": "Attempts",
    "SAV_Pokeathlon4.L_BlockSmashFirst": "Block Smash 1st",
    "SAV_Pokeathlon4.L_BonusesEarned": "Bonuses Earned",
    "SAV_Pokeathlon4.L_CirclePushFirst": "Circle Push 1st",
    "SAV_Pokeathlon4.L_ConnectionFirst": "Connection 1st",
    "SAV_Pokeathlon4.L_ConnectionIndex": "Index",
    "SAV_Pokeathlon4.L_ConnectionJoined": "Connections Joined",
    "SAV_Pokeathlon4.L_ConnectionLast": "Connection Last",
    "SAV_Pokeathlon4.L_CourseIndex": "Index",
    "SAV_Pokeathlon4.L_CourseParticipant0": "Participant 1",
    "SAV_Pokeathlon4.L_CourseParticipant1": "Participant 2",
    "SAV_Pokeathlon4.L_CourseParticipant2": "Participant 3",
    "SAV_Pokeathlon4.L_CourseScore0": "Score 1",
    "SAV_Pokeathlon4.L_CourseScore1": "Score 2",
    "SAV_Pokeathlon4.L_CourseScore2": "Score 3",
    "SAV_Pokeathlon4.L_CourseScoreMax": "Max Score",
    "SAV_Pokeathlon4.L_DailyShopFlags": "Daily Shop",
    "SAV_Pokeathlon4.L_Dashed": "Dashed",
    "SAV_Pokeathlon4.L_DataCards": "Data Cards",
    "SAV_Pokeathlon4.L_DiscCatchFirst": "Disc Catch 1st",
    "SAV_Pokeathlon4.L_Failed": "Failed",
    "SAV_Pokeathlon4.L_Fame": "Fame",
    "SAV_Pokeathlon4.L_FellDown": "Fell Down",
    "SAV_Pokeathlon4.L_GoalRollFirst": "Goal Roll 1st",
    "SAV_Pokeathlon4.L_HurdleDashFirst": "Hurdle Dash 1st",
    "SAV_Pokeathlon4.L_Instructions": "Instructions",
    "SAV_Pokeathlon4.L_Jumped": "Jumped",
    "SAV_Pokeathlon4.L_LampJumpFirst": "Lamp Jump 1st",
    "SAV_Pokeathlon4.L_Language": "Language",
    "SAV_Pokeathlon4.L_OT": "OT",
    "SAV_Pokeathlon4.L_PennantCaptureFirst": "Pennant Capture 1st",
    "SAV_Pokeathlon4.L_PID": "PID",
    "SAV_Pokeathlon4.L_PlacedFirst": "Placed 1st",
    "SAV_Pokeathlon4.L_PlacedLast": "Placed Last",
    "SAV_Pokeathlon4.L_Points": "Points",
    "SAV_Pokeathlon4.L_Record": "Record",
    "SAV_Pokeathlon4.L_RelayRunFirst": "Relay Run 1st",
    "SAV_Pokeathlon4.L_RingDropFirst": "Ring Drop 1st",
    "SAV_Pokeathlon4.L_SelfEventIndex": "Index",
    "SAV_Pokeathlon4.L_SelfImpeded": "Self-Impeded",
    "SAV_Pokeathlon4.L_SessionsJoined": "Sessions Joined",
    "SAV_Pokeathlon4.L_SID16": "SID",
    "SAV_Pokeathlon4.L_SnowThrowFirst": "Snow Throw 1st",
    "SAV_Pokeathlon4.L_Switched": "Switched",
    "SAV_Pokeathlon4.L_Tackled": "Tackled",
    "SAV_Pokeathlon4.L_TID16": "TID",
    "SAV_Pokeathlon4.L_TimeSpent": "Time Spent",
    "SAV_Pokeathlon4.L_TotalEventFirst": "Total Event 1st",
    "SAV_Pokeathlon4.L_TotalEventLast": "Total Event Last",
    "SAV_Pokeathlon4.L_Trainer0": "Trainer 1",
    "SAV_Pokeathlon4.L_Trainer1": "Trainer 2",
    "SAV_Pokeathlon4.L_Trainer2": "Trainer 3",
    "SAV_Pokeathlon4.L_Trainer3": "Trainer 4",
    "SAV_Pokeathlon4.L_Trainer4": "Trainer 5",
    "SAV_Pokeathlon4.Tab_Best": "Best",
    "SAV_Pokeathlon4.Tab_Connection": "Connection",
    "SAV_Pokeathlon4.Tab_Counters": "Counters",
    "SAV_Pokeathlon4.Tab_Courses": "Courses",
    "SAV_Pokeathlon4.Tab_General": "General",
    "SAV_Pokeathlon4.Tab_Medals": "Medals",
    "SAV_Pokeathlon4.Tab_SelfEvent": "Self Event",
  },
  ja: {
    SAV_Pokeathlon4: "ポケスロン",
    "PokeathlonEvent4.BlockSmash": "ブロックスマッシュ",
    "PokeathlonEvent4.CirclePush": "サークルプッシュ",
    "PokeathlonEvent4.DiscCatch": "ディスクキャッチ",
    "PokeathlonEvent4.GoalRoll": "ゴールロール",
    "PokeathlonEvent4.HurdleDash": "ハードルダッシュ",
    "PokeathlonEvent4.LampJump": "ランプジャンプ",
    "PokeathlonEvent4.PennantCapture": "ペナントキャプチャ",
    "PokeathlonEvent4.RelayRun": "リレーラン",
    "PokeathlonEvent4.RingDrop": "リングドロップ",
    "PokeathlonEvent4.SnowThrow": "スノースロー",
    "PokeathlonStat4.Jump": "ジャンプ",
    "PokeathlonStat4.Power": "パワー",
    "PokeathlonStat4.Skill": "テクニック",
    "PokeathlonStat4.Speed": "スピード",
    "PokeathlonStat4.Stamina": "スタミナ",
    "SAV_Pokeathlon4.B_Cancel": "キャンセル",
    "SAV_Pokeathlon4.B_MedalsClearAll": "すべて消去",
    "SAV_Pokeathlon4.B_MedalsGiveAll": "すべて付与",
    "SAV_Pokeathlon4.B_Save": "保存",
    "SAV_Pokeathlon4.CHK_IsShiny": "色違い",
    "SAV_Pokeathlon4.DGV_Jump": "ジャンプ",
    "SAV_Pokeathlon4.DGV_Power": "パワー",
    "SAV_Pokeathlon4.DGV_Skill": "テクニック",
    "SAV_Pokeathlon4.DGV_Species": "ポケモン",
    "SAV_Pokeathlon4.DGV_Speed": "スピード",
    "SAV_Pokeathlon4.DGV_Sprite": "スプライト",
    "SAV_Pokeathlon4.DGV_Stamina": "スタミナ",
    "SAV_Pokeathlon4.L_Acquired": "入手済み",
    "SAV_Pokeathlon4.L_Attempts": "挑戦回数",
    "SAV_Pokeathlon4.L_BlockSmashFirst": "ブロックスマッシュ1位",
    "SAV_Pokeathlon4.L_BonusesEarned": "獲得ボーナス",
    "SAV_Pokeathlon4.L_CirclePushFirst": "サークルプッシュ1位",
    "SAV_Pokeathlon4.L_ConnectionFirst": "通信1位",
    "SAV_Pokeathlon4.L_ConnectionIndex": "番号",
    "SAV_Pokeathlon4.L_ConnectionJoined": "通信参加回数",
    "SAV_Pokeathlon4.L_ConnectionLast": "通信最下位",
    "SAV_Pokeathlon4.L_CourseIndex": "番号",
    "SAV_Pokeathlon4.L_CourseParticipant0": "参加者1",
    "SAV_Pokeathlon4.L_CourseParticipant1": "参加者2",
    "SAV_Pokeathlon4.L_CourseParticipant2": "参加者3",
    "SAV_Pokeathlon4.L_CourseScore0": "スコア1",
    "SAV_Pokeathlon4.L_CourseScore1": "スコア2",
    "SAV_Pokeathlon4.L_CourseScore2": "スコア3",
    "SAV_Pokeathlon4.L_CourseScoreMax": "最高スコア",
    "SAV_Pokeathlon4.L_DailyShopFlags": "日替わりショップ",
    "SAV_Pokeathlon4.L_Dashed": "ダッシュ回数",
    "SAV_Pokeathlon4.L_DataCards": "データカード",
    "SAV_Pokeathlon4.L_DiscCatchFirst": "ディスクキャッチ1位",
    "SAV_Pokeathlon4.L_Failed": "失敗",
    "SAV_Pokeathlon4.L_Fame": "名声",
    "SAV_Pokeathlon4.L_FellDown": "転倒",
    "SAV_Pokeathlon4.L_GoalRollFirst": "ゴールロール1位",
    "SAV_Pokeathlon4.L_HurdleDashFirst": "ハードルダッシュ1位",
    "SAV_Pokeathlon4.L_Instructions": "説明",
    "SAV_Pokeathlon4.L_Jumped": "ジャンプ回数",
    "SAV_Pokeathlon4.L_LampJumpFirst": "ランプジャンプ1位",
    "SAV_Pokeathlon4.L_Language": "言語",
    "SAV_Pokeathlon4.L_OT": "親名",
    "SAV_Pokeathlon4.L_PennantCaptureFirst": "ペナントキャプチャ1位",
    "SAV_Pokeathlon4.L_PID": "PID",
    "SAV_Pokeathlon4.L_PlacedFirst": "1位回数",
    "SAV_Pokeathlon4.L_PlacedLast": "最下位回数",
    "SAV_Pokeathlon4.L_Points": "ポイント",
    "SAV_Pokeathlon4.L_Record": "記録",
    "SAV_Pokeathlon4.L_RelayRunFirst": "リレーラン1位",
    "SAV_Pokeathlon4.L_RingDropFirst": "リングドロップ1位",
    "SAV_Pokeathlon4.L_SelfEventIndex": "番号",
    "SAV_Pokeathlon4.L_SelfImpeded": "自分で妨害",
    "SAV_Pokeathlon4.L_SessionsJoined": "参加セッション数",
    "SAV_Pokeathlon4.L_SID16": "SID",
    "SAV_Pokeathlon4.L_SnowThrowFirst": "スノースロー1位",
    "SAV_Pokeathlon4.L_Switched": "交代",
    "SAV_Pokeathlon4.L_Tackled": "タックル",
    "SAV_Pokeathlon4.L_TID16": "TID",
    "SAV_Pokeathlon4.L_TimeSpent": "経過時間",
    "SAV_Pokeathlon4.L_TotalEventFirst": "総合1位",
    "SAV_Pokeathlon4.L_TotalEventLast": "総合最下位",
    "SAV_Pokeathlon4.L_Trainer0": "トレーナー1",
    "SAV_Pokeathlon4.L_Trainer1": "トレーナー2",
    "SAV_Pokeathlon4.L_Trainer2": "トレーナー3",
    "SAV_Pokeathlon4.L_Trainer3": "トレーナー4",
    "SAV_Pokeathlon4.L_Trainer4": "トレーナー5",
    "SAV_Pokeathlon4.Tab_Best": "ベスト",
    "SAV_Pokeathlon4.Tab_Connection": "通信",
    "SAV_Pokeathlon4.Tab_Counters": "カウンター",
    "SAV_Pokeathlon4.Tab_Courses": "コース",
    "SAV_Pokeathlon4.Tab_General": "基本",
    "SAV_Pokeathlon4.Tab_Medals": "メダル",
    "SAV_Pokeathlon4.Tab_SelfEvent": "自己競技",
  },
};
