// Project translations of PKHeX record labels; original names remain available in details.
type Names = readonly [zh: string, ja: string, en?: string];
const names: Record<string, Names> = {
  "Saved Game": ["存档次数", "セーブ回数"],
  "First Hof Play Time": ["首次殿堂时间", "初回殿堂入り時間"],
  "Started Trends": ["发起流行次数", "流行を始めた回数"],
  "Planted Berries": ["种植树果次数", "きのみを植えた回数"],
  "Traded Bikes": ["更换自行车次数", "自転車交換回数"],
  Steps: ["累计步数", "合計歩数"],
  "Got Interviewed": ["接受采访次数", "取材を受けた回数"],
  "Wild Battles": ["野生对战次数", "野生バトル数"],
  "Entered Hof": ["进入殿堂次数", "殿堂入り回数"],
  "Pokemon Captures": ["捕获宝可梦次数", "ポケモン捕獲数"],
  "Fishing Captures": ["垂钓捕获次数", "釣りで捕獲した数"],
  "Hatched Eggs": ["孵蛋次数", "タマゴ孵化数"],
  "Evolved Pokemon": ["进化次数", "進化回数"],
  "Used Pokecenter": ["使用宝可梦中心次数", "ポケモンセンター利用回数"],
  "Rested At Home": ["在家休息次数", "自宅で休んだ回数"],
  "Entered Safari Zone": ["进入狩猎地带次数", "サファリゾーン入場回数"],
  "Used Cut": ["使用居合斩次数", "いあいぎり使用回数"],
  "Used Rock Smash": ["使用碎岩次数", "いわくだき使用回数"],
  "Moved Secret Base": ["搬迁秘密基地次数", "秘密基地の引っ越し回数"],
  "Pokemon Trades": ["交换宝可梦次数", "ポケモン交換回数"],
  "Unknown 22": ["未知记录 22", "不明な記録 22"],
  "Link Battle Draws": ["连接对战平局", "通信対戦引き分け"],
  "Used Splash": ["使用跃起次数", "はねる使用回数"],
  "Used Struggle": ["使用挣扎次数", "わるあがき使用回数"],
  "Slot Jackpots": ["老虎机大奖次数", "スロット大当たり回数"],
  "Consecutive Roulette Wins": ["轮盘连续胜利", "ルーレット連勝"],
  "Entered Battle Tower": ["进入对战塔次数", "バトルタワー入場回数"],
  "Unknown 31": ["未知记录 31", "不明な記録 31"],
  "Battle Tower Best Streak": ["对战塔最高连胜", "バトルタワー最高連勝"],
  Pokeblocks: ["制作宝可方块次数", "ポロック作成回数"],
  "Pokeblocks With Friends": ["与朋友制作宝可方块", "友達とのポロック作成"],
  "Won Link Contest": ["连接华丽大赛胜利", "通信コンテスト優勝"],
  "Entered Contest": ["参加华丽大赛次数", "コンテスト参加回数"],
  "Won Contest": ["华丽大赛胜利", "コンテスト優勝"],
  Shopped: ["购物次数", "買い物回数"],
  "Used Itemfinder": ["使用探宝器次数", "ダウジングマシン使用回数"],
  "Got Rained On": ["遇雨次数", "雨に遭った回数"],
  "Checked Pokedex": ["查看图鉴次数", "図鑑を見た回数"],
  "Received Ribbons": ["获得奖章次数", "リボン獲得数"],
  "Jumped Down Ledges": ["跳下台阶次数", "段差を飛び降りた回数"],
  "Watched Tv": ["观看电视次数", "テレビを見た回数"],
  "Checked Clock": ["查看时钟次数", "時計を見た回数"],
  "Won Pokemon Lottery": ["宝可梦彩票中奖", "ポケモンくじ当選"],
  "Used Daycare": ["使用培育屋次数", "育て屋利用回数"],
  "Rode Cable Car": ["乘坐缆车次数", "ロープウェイ利用回数"],
  "Entered Hot Springs": ["进入温泉次数", "温泉入場回数"],
  "Union With Friends": ["与朋友进入联合房间", "友達とのユニオンルーム"],
  "Berry Crush With Friends": [
    "与朋友进行树果粉制作",
    "友達とのきのみクラッシュ",
  ],
  egg_hatching: ["孵蛋", "タマゴの孵化", "Eggs hatched"],
  capture_wild: ["野生捕获", "野生での捕獲", "Wild captures"],
  capture_symbol: [
    "可见遭遇捕获",
    "シンボルでの捕獲",
    "Symbol encounter captures",
  ],
  capture_raid: ["极巨团体战捕获", "レイドでの捕獲", "Raid captures"],
  capture_camp: ["露营捕获", "キャンプでの捕獲", "Camp captures"],
  capture_fishing: ["垂钓捕获", "釣りでの捕獲", "Fishing captures"],
  total_capture: ["累计捕获", "捕獲合計", "Total captures"],
  dress_up: ["更换服装", "着替え", "Outfit changes"],
  training: ["训练记录", "トレーニング記録", "Training record"],
  personal_change: [
    "未确认记录（personal_change）",
    "不明な記録（personal_change）",
    "Unconfirmed record (personal_change)",
  ],
  rotomu_circuit: ["洛托姆越野赛", "ロトムラリー", "Rotom Rally"],
  npc_trade: ["与游戏角色交换", "ゲーム内の交換", "NPC trades"],
  pretty: [
    "未确认记录（pretty）",
    "不明な記録（pretty）",
    "Unconfirmed record (pretty)",
  ],
  chain_encount: ["连续相遇", "連続遭遇", "Chained encounters"],
  hall_of_fame: ["进入名人堂", "殿堂入り", "Hall of Fame entries"],
  fossil_restore: ["复原化石", "化石復元", "Fossils restored"],
  wild_pokemon_encount: [
    "野生宝可梦相遇",
    "野生ポケモンとの遭遇",
    "Wild Pokémon encounters",
  ],
  trade: ["交换", "交換", "Trades"],
  magical_trade: ["魔法交换", "マジカル交換", "Surprise trades"],
  one_day_captured: ["单日捕获", "一日の捕獲", "Captures in one day"],
  one_day_evolution: ["单日进化", "一日の進化", "Evolutions in one day"],
  total_walk: ["累计步数", "歩数合計", "Total steps"],
  total_watt: ["累计瓦特", "ワット合計", "Total watts"],
  total_all_battle: ["累计对战", "対戦合計", "Total battles"],
  campin: ["露营", "キャンプ", "Camping"],
  battle_point: ["对战点数记录", "バトルポイント記録", "Battle point record"],
  win_battle_point: ["赢得对战点数", "獲得バトルポイント", "Battle points won"],
  license_trade: ["卡片交换", "カード交換", "Card trades"],
  use_skill_record: [
    "使用招式记录",
    "わざレコード使用",
    "Technical Records used",
  ],
  use_exp_ball: [
    "未确认记录（use_exp_ball）",
    "不明な記録（use_exp_ball）",
    "Unconfirmed record (use_exp_ball)",
  ],
  use_personal_change_item: [
    "未确认记录（use_personal_change_item）",
    "不明な記録（use_personal_change_item）",
    "Unconfirmed record (use_personal_change_item)",
  ],
  clothes: ["服装记录", "服装の記録", "Clothing record"],
  evolution: ["进化", "進化", "Evolutions"],
  net_battle: ["网络对战", "ネット対戦", "Online battles"],
  cooking: ["料理", "料理", "Cooking"],
  poke_job_return: ["宝可帮帮忙归来", "ポケジョブから帰還", "Poké Job returns"],
  get_rare_item: ["获得稀有道具", "珍しい道具の入手", "Rare items obtained"],
  whistle: ["吹口哨", "口笛", "Whistles"],
  bike_dash: ["自行车冲刺", "自転車ダッシュ", "Bike dashes"],
  tree_shake: ["摇树", "木を揺らす", "Trees shaken"],
  tree_nut: ["树果记录", "きのみの記録", "Berry record"],
  battle_lose: ["对战落败", "対戦敗北", "Battles lost"],
  recipe: ["食谱记录", "レシピ記録", "Recipe record"],
  raid_battle: ["极巨团体战", "レイドバトル", "Raid battles"],
  total_money: ["累计金钱", "お金の合計", "Total money"],
  create_license_card: ["制作卡片", "カード作成", "Cards created"],
  change_hair: ["更换发型", "髪型変更", "Hairstyle changes"],
  battle_tower_single_win: [
    "对战塔单打胜利",
    "バトルタワーシングル勝利",
    "Battle Tower singles wins",
  ],
  battle_tower_double_win: [
    "对战塔双打胜利",
    "バトルタワーダブル勝利",
    "Battle Tower doubles wins",
  ],
  now_money: ["当前金钱记录", "現在のお金の記録", "Current money record"],
  cormorant_robo: ["合成机器人", "ウッウロボ", "Cram-o-matic"],
  battle_rom_mark: [
    "未确认记录（battle_rom_mark）",
    "不明な記録（battle_rom_mark）",
    "Unconfirmed record (battle_rom_mark)",
  ],
  CLEAR_TIME: ["通关时间", "クリア時間", "Clear time"],
  DENDOU_CNT: ["名人堂次数", "殿堂入り回数", "Hall of Fame count"],
  CAPTURE_POKE: ["捕获宝可梦", "ポケモン捕獲", "Pokémon caught"],
  FISHING_SUCCESS: ["垂钓成功", "釣り成功", "Successful fishing"],
  TAMAGO_HATCHING: ["孵蛋", "タマゴの孵化", "Eggs hatched"],
  BEAT_DOWN_POKE: ["击败宝可梦", "倒したポケモン", "Pokémon defeated"],
  RENSHOU_SINGLE: ["单打连胜", "シングル連勝", "Singles streak"],
  RENSHOU_SINGLE_NOW: [
    "当前单打连胜",
    "現在のシングル連勝",
    "Current singles streak",
  ],
  RENSHOU_DOUBLE: ["双打连胜", "ダブル連勝", "Doubles streak"],
  RENSHOU_DOUBLE_NOW: [
    "当前双打连胜",
    "現在のダブル連勝",
    "Current doubles streak",
  ],
  RENSHOU_MASTER_SINGLE: [
    "大师单打连胜",
    "マスターシングル連勝",
    "Master singles streak",
  ],
  RENSHOU_MASTER_SINGLE_NOW: [
    "当前大师单打连胜",
    "現在のマスターシングル連勝",
    "Current master singles streak",
  ],
  RENSHOU_MASTER_DOUBLE: [
    "大师双打连胜",
    "マスターダブル連勝",
    "Master doubles streak",
  ],
  RENSHOU_MASTER_DOUBLE_NOW: [
    "当前大师双打连胜",
    "現在のマスターダブル連勝",
    "Current master doubles streak",
  ],
  BTL_TOWER_AVERAGE: [
    "对战塔平均值",
    "バトルタワー平均値",
    "Battle Tower average",
  ],
  CONTEST_STYLE_RANK: [
    "帅气大赛等级",
    "かっこよさランク",
    "Coolness contest rank",
  ],
  CONTEST_BEATIFUL_RANK: [
    "美丽大赛等级",
    "うつくしさランク",
    "Beauty contest rank",
  ],
  CONTEST_CUTE_RANK: [
    "可爱大赛等级",
    "かわいさランク",
    "Cuteness contest rank",
  ],
  CONTEST_CLEVER_RANK: [
    "聪明大赛等级",
    "かしこさランク",
    "Cleverness contest rank",
  ],
  CONTEST_STRONG_RANK: [
    "强壮大赛等级",
    "たくましさランク",
    "Toughness contest rank",
  ],
  CONTEST_PLAY_SINGLE: [
    "单人华丽大赛参加",
    "一人でコンテスト参加",
    "Solo contest entries",
  ],
  CONTEST_PLAY_LOCAL: [
    "本地华丽大赛参加",
    "ローカルコンテスト参加",
    "Local contest entries",
  ],
  CONTEST_PLAY_NETWORK: [
    "网络华丽大赛参加",
    "ネットコンテスト参加",
    "Online contest entries",
  ],
  CONTEST_WIN_SINGLE: [
    "单人华丽大赛胜利",
    "一人でコンテスト勝利",
    "Solo contest wins",
  ],
  CONTEST_WIN_LOCAL: [
    "本地华丽大赛胜利",
    "ローカルコンテスト勝利",
    "Local contest wins",
  ],
  CONTEST_WIN_NETWORK: [
    "网络华丽大赛胜利",
    "ネットコンテスト勝利",
    "Online contest wins",
  ],
  CONTEST_RATE_SINGLE: [
    "单人华丽大赛评分",
    "一人でコンテスト評価",
    "Solo contest rating",
  ],
  CONTEST_RATE_LOCAL: [
    "本地华丽大赛评分",
    "ローカルコンテスト評価",
    "Local contest rating",
  ],
  CONTEST_RATE_NETWORK: [
    "网络华丽大赛评分",
    "ネットコンテスト評価",
    "Online contest rating",
  ],
  CONTEST_GET_RIBBON: [
    "华丽大赛缎带记录",
    "コンテストリボン記録",
    "Contest ribbon record",
  ],
  "Steps Taken": ["行走步数", "歩いた歩数"],
  "Times Saved": ["保存次数", "レポート回数"],
  "Storyline Completed Time": ["主线完成时间", "ストーリークリア時間"],
  "Times Bicycled": ["骑自行车次数", "自転車に乗った回数"],
  "Total Battles": ["总对战次数", "総対戦回数"],
  "Wild Pokémon Battles": ["野生宝可梦对战", "野生ポケモンとの戦闘"],
  "Trainer Battles": ["训练家对战", "トレーナーとの対戦"],
  "Pokemon Caught": ["捕获宝可梦", "捕まえたポケモン"],
  "Pokemon Caught Fishing": ["钓鱼捕获宝可梦", "釣りで捕まえたポケモン"],
  "Eggs Hatched": ["孵化的蛋", "孵化したタマゴ"],
  "Pokémon Evolved": ["宝可梦进化", "ポケモンの進化"],
  "Pokémon Healed at Pokémon Centers": [
    "宝可梦中心回复次数",
    "ポケモンセンターでの回復",
  ],
  "Link Trades": ["连接交换", "通信交換"],
  "Link Battles": ["连接对战", "通信対戦"],
  "Link Battle Wins": ["连接对战胜利", "通信対戦の勝利"],
  "Link Battle Losses": ["连接对战失败", "通信対戦の敗北"],
  "WiFi Trades": ["网络交换", "インターネット交換"],
  "WiFi Battles": ["网络对战", "インターネット対戦"],
  "WiFi Battle Wins": ["网络对战胜利", "インターネット対戦の勝利"],
  "WiFi Battle Losses": ["网络对战失败", "インターネット対戦の敗北"],
  "IR Trades": ["红外线交换", "赤外線交換"],
  "IR Battles": ["红外线对战", "赤外線対戦"],
  "IR Battle Wins": ["红外线对战胜利", "赤外線対戦の勝利"],
  "IR Battle Losses": ["红外线对战失败", "赤外線対戦の敗北"],
  "Mart Stack Purchases": ["商店批量购买", "ショップでのまとめ買い"],
  "Money Spent": ["花费的金钱", "使ったお金"],
  "Times watched TV": ["观看电视次数", "テレビを見た回数"],
  "Pokémon deposited at Nursery": [
    "寄放到培育屋的宝可梦",
    "預かり屋に預けたポケモン",
  ],
  "Pokémon Defeated": ["击败宝可梦", "倒したポケモン"],
  "Exp. Points Collected (Highest)": [
    "获得经验值（最高）",
    "獲得経験値（最高）",
  ],
  "Exp. Points Collected (Today)": ["获得经验值（今日）", "獲得経験値（今日）"],
  "Deposited in the GTS": ["寄放到 GTS", "GTSに預けた回数"],
  "Nicknames Given": ["起昵称次数", "ニックネームを付けた回数"],
  "Bonus Premier Balls Received": ["获赠纪念球", "おまけのプレミアボール"],
  "Battle Points Earned": ["获得的 BP", "獲得BP"],
  "Battle Points Spent": ["使用的 BP", "使用BP"],
  "Nice! Received": ["收到的赞", "もらったナイス"],
  "Birthday Wishes": ["生日祝福", "誕生日のお祝い"],
  "Total People Met Online": ["网络相遇总人数", "ネットで出会った人数"],
  "Total People Passed By": ["擦肩而过总人数", "すれ違った人数"],
  "Current Pokemiles": ["当前宝可里程", "現在のポケマイル"],
  "Total Pokemiles Received": ["累计获得宝可里程", "獲得ポケマイル累計"],
  "Total Pokemiles sent to PGL": [
    "发送到 PGL 的宝可里程",
    "PGLに送ったポケマイル",
  ],
  "Total Super Training Attempts": [
    "超级训练尝试次数",
    "スーパートレーニング挑戦回数",
  ],
  "Total Super Training Cleared": [
    "超级训练完成次数",
    "スーパートレーニングクリア回数",
  ],
  "IV Judge Evaluations": ["个体值评定次数", "個体値ジャッジ回数"],
  "Trash Cans inspected": ["检查垃圾桶次数", "ゴミ箱を調べた回数"],
  "Inverse Battles": ["反转对战", "さかさバトル"],
  "Maison Battles": ["对战屋对战", "バトルハウスでの対戦"],
  "Times changed character clothing": ["更换服装次数", "着替えた回数"],
  "Times changed character hairstyle": ["更换发型次数", "髪型を変えた回数"],
  "Berries harvested": ["收获的树果", "収穫したきのみ"],
  "Berry Field mutations": ["树果田变异", "きのみ畑の突然変異"],
  "PR Videos": ["宣传视频", "トレーナープロモ"],
  "Friend Safari Encounters": ["朋友狩猎相遇", "フレンドサファリでの遭遇"],
  "O-Powers Used": ["使用 O 力", "Oパワー使用"],
  "Secret Base Updates": ["秘密基地更新", "ひみつきちの更新"],
  "Secret Base Flags Captured": ["夺取秘密基地旗帜", "ひみつきちの旗を獲得"],
  "Contests Participated Count": ["参加华丽大赛", "コンテスト参加"],
  "GTS Trades": ["GTS 交换", "GTS交換"],
  "Wonder Trades": ["奇迹交换", "ミラクル交換"],
  "Steps Sneaked": ["潜行步数", "忍び歩きの歩数"],
  "Multiplayer Contests": ["多人华丽大赛", "通信コンテスト"],
  "Pokeblocks used": ["使用宝可方块", "ポロック使用"],
  "Times AreaNav Used": ["使用地图导航", "マップナビ使用"],
  "Times DexNav Used": ["使用图鉴导航", "ずかんナビ使用"],
  "Times BuzzNav Used": ["使用电视导航", "テレビナビ使用"],
  "Times PlayNav Used": ["使用游玩导航", "プレイナビ使用"],
  "Champion Title Defense": ["卫冕冠军", "チャンピオン防衛"],
  "Times rested at home": ["在家休息次数", "家で休んだ回数"],
  "Times Splash used": ["使用跃起", "はねるを使った回数"],
  "Times Struggle used": ["使用挣扎", "わるあがきを使った回数"],
  "Moves used with No Effect": ["使用无效招式", "効果のない技を使った回数"],
  "Own Fainted Pokémon": ["己方宝可梦倒下", "味方ポケモンのひんし"],
  "Times attacked ally in battle": ["战斗中攻击队友", "味方を攻撃した回数"],
  "Failed Run Attempts": ["逃跑失败", "逃走失敗"],
  "Wild encounters that fled": [
    "野生宝可梦逃走",
    "野生ポケモンに逃げられた回数",
  ],
  "Failed Fishing Attempts": ["钓鱼失败", "釣り失敗"],
  "Fossils Restored": ["复原化石", "化石復元"],
  "Sweet Scent Encounters": ["甜甜香气相遇", "あまいかおりでの遭遇"],
  "Battle Institute Tests": ["参加对战测试", "バトル検定への参加"],
  "Battle Institute Rank": ["对战测试等级", "バトル検定のランク"],
  "Battle Institute Score": ["对战测试分数", "バトル検定のスコア"],
  "Photos Taken": ["拍照次数", "写真撮影回数"],
  "Times used Fly": ["使用飞翔", "そらをとぶ使用"],
  "Loto-ID Wins": ["ID 抽奖中奖", "IDくじ当選"],
  "PP Ups used": ["使用 PP 提升剂", "ポイントアップ使用"],
  "PSS Passerby Count (Today)": [
    "PSS 路人数量（今日）",
    "PSSの通りすがり（今日）",
  ],
  "Amie Used": ["使用宝可拍乐乐", "ポケパルレ使用"],
  "Fishing Chains": ["连续钓鱼", "連続釣り"],
  "Secret Base Battles in your base": [
    "在自己秘密基地对战",
    "自分のひみつきちで対戦",
  ],
  "Secret Base Battles in another base": [
    "在他人秘密基地对战",
    "他人のひみつきちで対戦",
  ],
  "Contest Spectacular Photos taken": [
    "华丽大赛实况照片",
    "コンテストライブの写真",
  ],
  "Times used Soaring in the Sky": ["使用自由翱翔", "おおぞらをとぶ使用"],
  "Times used Dive": ["使用潜水", "ダイビング使用"],
  "Times used Sky Holes": ["使用空中洞穴", "空の穴の使用"],
  "Times healed by Mom": ["妈妈帮忙回复", "お母さんに回復してもらった回数"],
  "Times used Escape Rope": ["使用离洞绳", "あなぬけのヒモ使用"],
  "Times used Dowsing Machine": ["使用探宝器", "ダウジングマシン使用"],
  "Trainer's Eye Rematches": ["训练家之眼再战", "トレーナーアイの再戦"],
  "FUREAI Interest ???": ["互动兴趣（含义未确认）", "ふれあい関心（詳細不明）"],
  "Shiny Pokémon Encountered": ["遇到异色宝可梦", "色違いポケモンとの遭遇"],
  "Trick House Clears": ["机关屋完成次数", "カラクリ屋敷クリア"],
  "Eon Ticket 1 (SpotPass)": [
    "无限船票 1（SpotPass）",
    "むげんのチケット1（いつの間に通信）",
  ],
  "Eon Ticket 2 (Mystery Gift)": [
    "无限船票 2（神秘礼物）",
    "むげんのチケット2（ふしぎなおくりもの）",
  ],
  "Battle Spot Battles": ["对战点对战", "バトルスポット対戦"],
  "Battle Spot Wins": ["对战点胜利", "バトルスポット勝利"],
  "Battle Spot Losses": ["对战点失败", "バトルスポット敗北"],
  "Super Effective Moves Used": ["使用效果绝佳招式", "効果抜群の技を使用"],
  "Clothing Count": ["服装数量", "服の数"],
  "Salon Uses": ["使用美发沙龙", "ヘアサロン利用"],
  "Berry Harvests": ["树果收获", "きのみ収穫"],
  "Trades at the GTS": ["GTS 交换", "GTS交換"],
  "Quick Links": ["快捷连接", "クイック通信"],
  "Pokemon Rides": ["宝可骑行", "ポケモンライド"],
  "Beans Given": ["喂食宝可豆", "ポケマメを与えた数"],
  "Festival Coins Spent": ["使用圆庆币", "フェスコイン使用"],
  "Poke Beans Collected": ["收集宝可豆", "ポケマメ収集"],
  "Battle Tree Challenges": ["挑战对战树", "バトルツリー挑戦"],
  "Z-Moves Used": ["使用 Z 招式", "Zワザ使用"],
  "Balls Used": ["使用精灵球", "ボール使用"],
  "Items Thieved": ["偷取道具", "盗んだ道具"],
  "Moves Used": ["使用招式", "技の使用"],
  "Levels Raised": ["提升等级", "上がったレベル"],
  "Ran From Battles": ["从对战中逃跑", "戦闘から逃げた回数"],
  "Rock Smash Items": ["碎岩获得道具", "いわくだきで得た道具"],
  "Medicine Used": ["使用药品", "薬の使用"],
  "Pay Day Money Received": ["聚宝功获得金钱", "ネコにこばんで得たお金"],
  "Total Thumbs-Ups": ["累计点赞", "いいね累計"],
  "Times Twirled (Pirouette)": ["旋转动作次数", "ピルエットの回数"],
  "Record Thumbs-ups": ["最高点赞记录", "いいね最高記録"],
  "Pokemon Petted": ["抚摸宝可梦", "ポケモンをなでた回数"],
  "Poké Pelago Visits": ["访问宝可度假地", "ポケリゾート訪問"],
  "Poké Pelago Bean Trades": ["度假地宝可豆交换", "リゾートのポケマメ交換"],
  "Poké Pelago Tapped Pokémon": [
    "度假地点击宝可梦",
    "リゾートでポケモンをタッチ",
  ],
  "Poké Pelago Bean Stacks put in Crate": [
    "度假地豆筐放入宝可豆",
    "リゾートのマメカゴ投入",
  ],
  "Poké Pelago Levels Gained": ["度假地提升等级", "リゾートでのレベルアップ"],
  "Poké Pelago Friendship Increased": [
    "度假地提升亲密度",
    "リゾートでのなかよし度上昇",
  ],
  "Poké Pelago Eggs Hatched": ["度假地孵蛋", "リゾートでのタマゴ孵化"],
  "Poké Pelago ???": ["宝可度假地（未知记录）", "ポケリゾート（不明な記録）"],
  "Battle Video QR Teams Scanned": [
    "扫描对战视频 QR 队伍",
    "バトルビデオのQRチームをスキャン",
  ],
  "Battle Videos Watched": ["观看对战视频", "バトルビデオ視聴"],
  "Battle Videos Rebattled": ["对战视频再战", "バトルビデオ再戦"],
  "RotomDex Interactions": ["与洛托姆图鉴互动", "ロトム図鑑との交流"],
  "Guests Interacted With": ["与来宾互动", "ゲストとの交流"],
  "Berry Piles (not full) Collected": [
    "拾取树果堆（未满）",
    "きのみの山回収（未満）",
  ],
  "Berry Piles (full) Collected": [
    "拾取树果堆（满）",
    "きのみの山回収（満杯）",
  ],
  "Items Reeled In": ["钓起道具", "釣り上げた道具"],
  "Roto Lotos": ["洛托姆碰碰", "ロトポン"],
  "Stickers Collected": ["收集贴纸", "シール収集"],
  "Mantine Surf BP Earned": ["巨翅飞鱼冲浪获得 BP", "マンタインサーフ獲得BP"],
  "Battle Agency Wins": ["对战代理人胜利", "バトルエージェント勝利"],
  "Photos Rated": ["照片获得评价", "写真の評価"],
  "PP Raised": ["提升 PP", "PPを増やした回数"],
  "Missions Participated In": ["参加任务", "アトラクション参加"],
  "Facilities Hosted": ["开设设施", "施設を招いた回数"],
  "QR Code Scans": ["扫描 QR 码", "QRコードスキャン"],
  "Moves learned with TMs": ["用招式学习器学习招式", "わざマシンで覚えた技"],
  "Café Drinks Bought": ["购买咖啡馆饮料", "カフェで飲み物を購入"],
  "Trainer Card Photos Taken": ["拍摄训练家证照片", "トレーナーパスの写真撮影"],
  "Evolutions Cancelled": ["取消进化", "進化キャンセル"],
  "SOS Battle Allies Called": ["呼叫帮手", "助けを呼んだ回数"],
  "Friendship Raised": ["提升亲密度", "なかよし度上昇"],
  "Battle Royal Dome Battles": ["皇家巨蛋对战", "ロイヤルドーム対戦"],
  "Items Picked Up after Battle": ["战斗后拾取道具", "戦闘後に拾った道具"],
  "Ate in Malasadas Shop": ["在马拉萨达店用餐", "マラサダショップで食事"],
  "Hyper Trainings Received": ["接受极限特训", "すごいとっくん"],
  "Dishes eaten in Battle Buffet": [
    "对战自助餐菜品",
    "バトルバイキングで食べた料理",
  ],
  "Pokémon Refresh Accessed": ["使用宝可清爽乐", "ポケリフレ利用"],
  "Pokémon Storage System Log-outs": [
    "退出宝可梦寄放系统",
    "ポケモン預かりシステム終了",
  ],
  "Lomi Lomi Massages": ["接受按摩", "ロミロミマッサージ"],
  "Ambush/Smash post-battle items received": [
    "伏击／碎岩战后获得道具",
    "待ち伏せ・いわくだき戦後の道具",
  ],
  "Rustling Tree Encounters": ["摇晃树木相遇", "揺れる木での遭遇"],
  "Ledges Jumped Down": ["跳下台阶", "段差を飛び降りた回数"],
  "Water Splash Encounters": ["水花相遇", "水しぶきでの遭遇"],
  "Sand Cloud Encounters": ["沙尘相遇", "砂煙での遭遇"],
  "Outfit Changes": ["更换服装", "着替え"],
  "Battle Royal Dome Wins": ["皇家巨蛋胜利", "ロイヤルドーム勝利"],
  "Pelago Treasure Hunts": ["度假地寻宝", "リゾートの宝探し"],
  "Pelago Training Sessions": ["度假地训练", "リゾートのトレーニング"],
  "Pelago Hot Spring Sessions": ["度假地温泉", "リゾートの温泉"],
  "Special QR 1": ["特殊 QR 1", "特別なQR 1"],
  "Special QR 2": ["特殊 QR 2", "特別なQR 2"],
  "Special QR Code Scans": ["扫描特殊 QR 码", "特別なQRコードスキャン"],
  "Island Scans": ["岛屿扫描", "島スキャン"],
  "Rustling Bush Encounters": ["摇晃灌木相遇", "揺れる茂みでの遭遇"],
  "Fly Shadow Encounters": ["飞行阴影相遇", "飛ぶ影での遭遇"],
  "Rustling Grass Encounters": ["摇晃草丛相遇", "揺れる草むらでの遭遇"],
  "Dirt Cloud Encounters": ["尘土相遇", "土煙での遭遇"],
  "Wimpod Chases": ["追逐胆小虫", "コソクムシを追いかけた回数"],
  "Berry Tree Battles won": ["树果树对战胜利", "きのみの木での戦闘勝利"],
  "Bubbling Spot Encounters/Items": [
    "冒泡点相遇／道具",
    "泡の出る場所での遭遇・道具",
  ],
  "Times laid down in Own Bed": [
    "躺在自己床上的次数",
    "自分のベッドで横になった回数",
  ],
  "Catch a lot of Pokémon!": [
    "全球任务：大量捕获宝可梦",
    "グローバルアトラクション：たくさん捕獲",
  ],
  "Trade Pokémon at the GTS!": [
    "全球任务：GTS 交换",
    "グローバルアトラクション：GTS交換",
  ],
  "Hatch a lot of Eggs!": [
    "全球任务：大量孵蛋",
    "グローバルアトラクション：たくさん孵化",
  ],
  "Harvest Poké Beans!": [
    "全球任务：收获宝可豆",
    "グローバルアトラクション：ポケマメ収穫",
  ],
  "Get high scores with your Poké Finder!": [
    "全球任务：宝可搜寻镜高分",
    "グローバルアトラクション：ポケファインダー高得点",
  ],
  "Find Pokémon using Island Scan!": [
    "全球任务：岛屿扫描相遇",
    "グローバルアトラクション：島スキャン",
  ],
  "Catch Crabrawler!": [
    "全球任务：捕获好胜蟹",
    "グローバルアトラクション：マケンカニ捕獲",
  ],
  "Defend your Champion title!": [
    "全球任务：卫冕冠军",
    "グローバルアトラクション：防衛戦",
  ],
  "Fish Pokémon at rare spots!": [
    "全球任务：稀有钓点垂钓",
    "グローバルアトラクション：珍しい釣り場",
  ],
  "Battle Royal!": [
    "全球任务：皇家对战",
    "グローバルアトラクション：バトルロイヤル",
  ],
  "Try your luck!": ["全球任务：试试运气", "グローバルアトラクション：運試し"],
  "Get BP at the Battle Tree!": [
    "全球任务：对战树获得 BP",
    "グローバルアトラクション：バトルツリーのBP",
  ],
  "Ultra Wormhole Travels": ["究极之洞旅行", "ウルトラホール移動"],
  "Mantine Surf Plays": ["游玩巨翅飞鱼冲浪", "マンタインサーフで遊んだ回数"],
  "Photo Club Photos saved": ["保存摄影俱乐部照片", "フォトクラブの写真保存"],
  "Battle Agency Battles": ["对战代理人对战", "バトルエージェント対戦"],
  "Photo Club Sticker usage": [
    "使用摄影俱乐部贴纸",
    "フォトクラブのシール使用",
  ],
  "Photo Club Photo Shoots": ["摄影俱乐部拍摄", "フォトクラブで撮影"],
  "Highest Wormhole Travel Distance": [
    "究极之洞最远旅行距离",
    "ウルトラホール最長移動距離",
  ],
  "Highest Mantine Surf BP Earned": [
    "巨翅飞鱼冲浪最高 BP",
    "マンタインサーフ最高BP",
  ],
};

const tipLocations: Record<string, Names> = {
  "Restaurant: ★☆☆": ["一星餐厅", "レストラン（一つ星）"],
  "Restaurant: ★★☆": ["二星餐厅", "レストラン（二つ星）"],
  "Restaurant: ★★★": ["三星餐厅", "レストラン（三つ星）"],
  "Restaurant: Sushi High Roller": ["高级寿司店", "高級寿司店"],
  "Café 1": ["咖啡馆 1", "カフェ1"],
  "Café 2": ["咖啡馆 2", "カフェ2"],
  "Café 3": ["咖啡馆 3", "カフェ3"],
  Cameraman: ["摄影师", "カメラマン"],
  "Drink Vendors": ["饮料售货员", "飲み物の販売員"],
  Poet: ["诗人", "詩人"],
  "Furfrou Trimmer": ["多丽米亚犬修剪师", "トリミアンのトリマー"],
  "Battle Maison 1": ["对战屋 1", "バトルハウス1"],
  "Battle Maison 2": ["对战屋 2", "バトルハウス2"],
  "Battle Maison 3": ["对战屋 3", "バトルハウス3"],
  "Battle Maison 4": ["对战屋 4", "バトルハウス4"],
  Maid: ["女仆", "メイド"],
  Butler: ["管家", "執事"],
  "Scary House": ["恐怖之家", "怖い家"],
  "Traveling Minstrel": ["旅行吟游诗人", "旅の吟遊詩人"],
  "Special BGM 1": ["特殊音乐 1", "特別なBGM 1"],
  "Special BGM 2": ["特殊音乐 2", "特別なBGM 2"],
  "Frieser Furfrou": ["Frieser 多丽米亚犬", "Frieser トリミアン"],
};
const daily: Record<string, Names> = {
  "Pokemon Defeated": ["击败宝可梦", "倒したポケモン"],
  "Pokemon Caught": ["捕获宝可梦", "捕まえたポケモン"],
  "Trainers Battled": ["训练家对战", "トレーナーとの対戦"],
  "Pokemon Evolved": ["宝可梦进化", "ポケモンの進化"],
};
const modes: Record<string, Names> = {
  Singles: ["单打", "シングル"],
  Doubles: ["双打", "ダブル"],
  Triples: ["三打", "トリプル"],
  Rotation: ["轮盘", "ローテーション"],
  Multi: ["多人", "マルチ"],
};
const skates: Record<string, Names> = {
  "Spin Left": ["向左旋转", "左回転"],
  "Spin Right": ["向右旋转", "右回転"],
  "Running Start": ["助跑起步", "ランニングスタート"],
  "Parallel Swizzle": ["平行滑步", "パラレルスウィズル"],
  "Drift-and-dash": ["漂移冲刺", "ドリフトダッシュ"],
  "360 right": ["右转 360 度", "右360度"],
  "360 left": ["左转 360 度", "左360度"],
  Flips: ["翻转", "フリップ"],
  "Cosmic Flips": ["宇宙翻转", "コズミックフリップ"],
  Grind: ["滑轨", "グラインド"],
  Combos: ["组合动作", "コンボ"],
};
const beds: Record<string, Names> = {
  Ilima: ["伊利马", "イリマ"],
  Guzma: ["古兹马", "グズマ"],
  Kiawe: ["卡奇", "カキ"],
  Lana: ["水莲", "スイレン"],
  Mallow: ["玛奥", "マオ"],
  Olivia: ["丽姿", "ライチ"],
  Hapu: ["哈普乌", "ハプウ"],
  Lusamine: ["露莎米奈", "ルザミーネ"],
};

export function recordTranslation(source: string): Names | undefined {
  if (names[source]) return names[source];
  let m = source.match(/^(Tips|Last Tip) at (.+)$/);
  if (m && tipLocations[m[2]]) {
    const n = tipLocations[m[2]];
    return [
      `${n[0]}小费${m[1] === "Last Tip" ? "（上次）" : ""}`,
      `${n[1]}のチップ${m[1] === "Last Tip" ? "（前回）" : ""}`,
    ];
  }
  m = source.match(/^(.+) \((Highest|Today)\)$/);
  if (m && daily[m[1]]) {
    const n = daily[m[1]],
      high = m[2] === "Highest";
    return [
      `${n[0]}（${high ? "最高" : "今日"}）`,
      `${n[1]}（${high ? "最高" : "今日"}）`,
    ];
  }
  m = source.match(/^Battle Maison Streak: (.+)$/);
  if (m && modes[m[1]]) {
    const n = modes[m[1]];
    return [`对战屋连胜：${n[0]}`, `バトルハウス連勝：${n[1]}`];
  }
  m = source.match(/^Best \(Super\) (.+) Streak$/);
  if (m && modes[m[1]]) {
    const n = modes[m[1]];
    return [`（超级）${n[0]}最高连胜`, `（スーパー）${n[1]}最高連勝`];
  }
  m = source.match(/^Roller Skate Count: (.+)$/);
  if (m && skates[m[1]]) {
    const n = skates[m[1]];
    return [`轮滑：${n[0]}`, `ローラースケート：${n[1]}`];
  }
  m = source.match(/^Times laid down in (.+)'s Bed$/);
  if (m && beds[m[1]]) {
    const n = beds[m[1]];
    return [`躺在${n[0]}床上的次数`, `${n[1]}のベッドで横になった回数`];
  }
  return undefined;
}

export function saveRecordName(source: string, language: string): string {
  const translated = recordTranslation(source);
  if (translated)
    return language.startsWith("zh")
      ? translated[0]
      : language.startsWith("ja")
        ? translated[1]
        : (translated[2] ?? source);
  if (/^\d+$/.test(source))
    return language.startsWith("zh")
      ? `未命名记录 ${source}`
      : language.startsWith("ja")
        ? `名称不明の記録 ${source}`
        : `Unnamed record ${source}`;
  return source;
}
