import type { Br4Lang } from "./br4";
const en = {
  title: "Secret Base Editor",
  read: "Read secret bases",
  base: "Secret base",
  self: "Own base",
  empty: "Empty",
  group: "Settings group",
  property: "Main",
  placement: "Object placement",
  team: "Trainer Pokémon",
  record: "Captured flags",
  field: "Property",
  slot: "Slot",
  general: "General",
  moves: "Moves",
  stats: "IVs / EVs",
  current: "Current",
  keep: "Keep stored value",
  preview: "Preview changes",
  apply: "Apply preview",
  cancel: "Cancel preview",
  discard: "Discard changes",
  resave: "Resave selected slots using window rules",
  import: "Import sb6",
  export: "Export sb6",
  delete: "Delete selected base",
  goods: "Give all decorations",
  stock: "Decoration stock",
  raw: "Raw data",
  changes: "Actual changes",
  changed: "Changed save bytes",
  noChanges: "No data changes",
  custom: "Numeric value or enum name",
  original: "Stored value",
  yes: "Yes",
  no: "No",
  quantity: "Count",
  newFlag: "New",
  storedText: "Stored character limit",
  linkedEgg: "Shiny and egg share one stored bit",
  captured: "Captured flags",
  rawCaptured: "Raw unsigned flags",
  param: "Read-only parameters",
  defaultTrainer: "Trainer",
  note: "Edit a local save copy. Preview every change before applying; the original stays intact and changes can be undone.",
  resaveNote:
    "Resaving normalizes only the selected placement and team slot, and submits captured flags. Unknown choices, IV masks, EV limits and ability/gender changes are shown in the preview.",
  fileNote:
    "sb6 files must contain 784 or 992 bytes. Import copies the common part or full record. Export normalizes selected slots on a temporary copy without applying edits or submitting captured flags.",
  recordNote:
    "The source accepts 0–4294967295, casts to signed 32-bit and caps positive values at 999999999. The preview shows the actual stored result.",
  placementNote:
    "Decoration -1 stores 65535. Extra parameters remain read-only.",
  textNote:
    "Numeric properties also accept the source hexadecimal format. Text is truncated to the stored limit and clears its buffer; inspect the preview.",
  invalid:
    "Invalid secret base target, fields or file. Check the input and file size.",
  stale: "The save or preview changed. Read and preview it again.",
  iv: "IV",
  ev: "EV",
  move: "Move",
  pp: "PP Ups",
  stat: {
    HP: "HP",
    ATK: "Attack",
    DEF: "Defense",
    SPE: "Speed",
    SPA: "Sp. Atk",
    SPD: "Sp. Def",
  },
  fields: {
    IsNew: "New record",
    BaseLocation: "Base location",
    BoppoyamaScore: "Boppoyama score",
    TrainerName: "Trainer name",
    TeamName: "Team name",
    TeamSlogan: "Team slogan",
    SayHappy: "Happy message",
    SayEncourage: "Encouragement",
    SayBlackboard: "Blackboard message",
    SayConfettiBall: "Confetti ball message",
    Rank: "Rank",
    TotalFlagsFromFriends: "Flags from friends",
    TotalFlagsFromOther: "Flags from others",
    CollectedFlagsToday: "Flags collected today",
    CollectedFlagsYesterday: "Flags collected yesterday",
    Language: "Language code",
    Gender: "Gender",
    Ec: "Encryption Constant",
    Species: "Species",
    HeldItem: "Held item",
    AbilitySlot: "Ability",
    Nature: "Nature",
    Form: "Form",
    Level: "Level",
    Friendship: "Friendship",
    Ball: "Ball",
    Shiny: "Shiny",
    Good: "Decoration",
    X: "X Coordinate",
    Y: "Y Coordinate",
    Rotation: "Rotation",
    IsEmpty: "Empty base",
    IsDummiedLocation: "Unused location",
  },
};
export type Sb6Words = typeof en;
export const sb6Words: Record<Br4Lang, Sb6Words> = {
  en,
  zh: {
    title: "秘密基地编辑器",
    read: "读取秘密基地",
    base: "秘密基地",
    self: "自身基地",
    empty: "空",
    group: "设置分组",
    property: "主要信息",
    placement: "物品布局",
    team: "训练家的宝可梦",
    record: "已获得旗标",
    field: "属性",
    slot: "格位",
    general: "常规",
    moves: "招式",
    stats: "个体／努力值",
    current: "当前值",
    keep: "保留旧值",
    preview: "预览修改",
    apply: "确认应用",
    cancel: "取消预览",
    discard: "放弃修改",
    resave: "按窗口规则重新保存所选格位",
    import: "导入 sb6",
    export: "导出 sb6",
    delete: "删除所选基地",
    goods: "获得所有装饰",
    stock: "装饰库存",
    raw: "原始数据",
    changes: "实际变化",
    changed: "存档变化字节",
    noChanges: "没有数据变化",
    custom: "数值或枚举名称",
    original: "存储值",
    yes: "是",
    no: "否",
    quantity: "数量",
    newFlag: "新获得",
    storedText: "实际存储字符上限",
    linkedEgg: "异色与蛋状态共用同一个存储位",
    captured: "已获得旗标",
    rawCaptured: "原始无符号旗标值",
    param: "只读参数",
    defaultTrainer: "训练家",
    note: "编辑本地存档副本，每次修改先预览再确认，保留原件，可撤销。",
    resaveNote:
      "重新保存只规范化所选摆设和队伍格位，并提交已获得旗标。未选中的旧字段保持；未知候选、个体掩码、努力值上限和特性／性别变化请核对预览。",
    fileNote:
      "sb6 必须为 784 或 992 字节。导入按来源复制共同部分或完整记录；导出在临时副本中规范化所选格位，不应用修改，也不提交旗标记录。",
    recordNote:
      "上游接受 0–4294967295，先转有符号 32 位，正值再截顶 999999999。预览显示实际存储结果。",
    placementNote: "装饰编号 -1 保存为 65535，额外参数只读。",
    textNote:
      "数字属性支持上游十六进制格式。文字按实际上限截取并清空文字缓冲区，请核对预览。",
    invalid: "秘密基地格位、字段或文件无效，请核对输入与文件大小。",
    stale: "存档或预览已变化，请重新读取并预览。",
    iv: "个体",
    ev: "努力值",
    move: "招式",
    pp: "PP提升",
    stat: {
      HP: "HP",
      ATK: "攻击",
      DEF: "防御",
      SPE: "速度",
      SPA: "特攻",
      SPD: "特防",
    },
    fields: {
      IsNew: "新记录",
      BaseLocation: "基地位置",
      BoppoyamaScore: "Boppoyama 分数",
      TrainerName: "训练家姓名",
      TeamName: "队伍名称",
      TeamSlogan: "队伍口号",
      SayHappy: "喜悦留言",
      SayEncourage: "鼓励留言",
      SayBlackboard: "黑板留言",
      SayConfettiBall: "彩球留言",
      Rank: "基地等级",
      TotalFlagsFromFriends: "好友旗标总数",
      TotalFlagsFromOther: "其他旗标总数",
      CollectedFlagsToday: "今日收集旗标",
      CollectedFlagsYesterday: "昨日收集旗标",
      Language: "语言编号",
      Gender: "性别",
      Ec: "加密常数",
      Species: "宝可梦",
      HeldItem: "携带道具",
      AbilitySlot: "特性",
      Nature: "性格",
      Form: "形态",
      Level: "等级",
      Friendship: "亲密度",
      Ball: "精灵球",
      Shiny: "异色",
      Good: "装饰",
      X: "X坐标",
      Y: "Y坐标",
      Rotation: "旋转值",
      IsEmpty: "空基地",
      IsDummiedLocation: "未使用位置",
    },
  },
  ja: {
    title: "ひみつきちエディター",
    read: "ひみつきちを読み込む",
    base: "ひみつきち",
    self: "自分の基地",
    empty: "空",
    group: "設定グループ",
    property: "主な情報",
    placement: "物の配置",
    team: "トレーナーのポケモン",
    record: "獲得フラグ",
    field: "プロパティ",
    slot: "スロット",
    general: "通常",
    moves: "技",
    stats: "個体値／努力値",
    current: "現在の値",
    keep: "保存値を維持",
    preview: "変更を確認",
    apply: "変更を適用",
    cancel: "プレビューを閉じる",
    discard: "変更を破棄",
    resave: "選択したスロットを元のルールで再保存",
    import: "sb6をインポート",
    export: "sb6をエクスポート",
    delete: "選択した基地を削除",
    goods: "すべての装飾を入手",
    stock: "装飾の在庫",
    raw: "元のデータ",
    changes: "実際の変更",
    changed: "セーブの変更バイト数",
    noChanges: "データの変更なし",
    custom: "数値または列挙名",
    original: "保存値",
    yes: "はい",
    no: "いいえ",
    quantity: "個数",
    newFlag: "新規",
    storedText: "保存文字数の上限",
    linkedEgg: "色違いとタマゴは同じ保存ビットを共有します",
    captured: "獲得フラグ",
    rawCaptured: "符号なしの保存値",
    param: "読み取り専用パラメーター",
    defaultTrainer: "トレーナー",
    note: "端末内のセーブのコピーを編集します。適用前に確認してください。元ファイルは維持され、元に戻せます。",
    resaveNote:
      "再保存は選択した配置とポケモンだけを正規化し、獲得フラグを保存します。不明な選択値、個体値のマスク、努力値の上限、特性や性別の変更を確認してください。",
    fileNote:
      "sb6は784または992バイトです。共通部分または全体をインポートします。エクスポートは一時コピーの選択したスロットを正規化し、編集や獲得フラグを適用しません。",
    recordNote:
      "0–4294967295を受け付け、符号付き32ビットに変換して正の値を999999999に制限します。保存結果を確認してください。",
    placementNote:
      "装飾番号-1は65535として保存します。追加パラメーターは読み取り専用です。",
    textNote:
      "数値プロパティは元の16進数形式にも対応します。文字は保存上限で切り詰め、領域を消去します。保存結果を確認してください。",
    invalid:
      "ひみつきちのスロット、項目またはファイルが無効です。入力とサイズを確認してください。",
    stale:
      "セーブまたはプレビューが変わりました。再読み込みして確認してください。",
    iv: "個体値",
    ev: "努力値",
    move: "技",
    pp: "ポイントアップ",
    stat: {
      HP: "HP",
      ATK: "攻撃",
      DEF: "防御",
      SPE: "素早さ",
      SPA: "特攻",
      SPD: "特防",
    },
    fields: {
      IsNew: "新しい記録",
      BaseLocation: "基地の場所",
      BoppoyamaScore: "Boppoyama スコア",
      TrainerName: "トレーナー名",
      TeamName: "チーム名",
      TeamSlogan: "チームの標語",
      SayHappy: "喜びのメッセージ",
      SayEncourage: "励ましのメッセージ",
      SayBlackboard: "黒板のメッセージ",
      SayConfettiBall: "くす玉のメッセージ",
      Rank: "ランク",
      TotalFlagsFromFriends: "友達のフラグ合計",
      TotalFlagsFromOther: "その他のフラグ合計",
      CollectedFlagsToday: "今日の獲得フラグ",
      CollectedFlagsYesterday: "昨日の獲得フラグ",
      Language: "言語番号",
      Gender: "性別",
      Ec: "暗号化定数",
      Species: "種類",
      HeldItem: "持ち物",
      AbilitySlot: "特性",
      Nature: "性格",
      Form: "フォルム",
      Level: "レベル",
      Friendship: "なつき度",
      Ball: "ボール",
      Shiny: "色違い",
      Good: "装飾",
      X: "X座標",
      Y: "Y座標",
      Rotation: "回転値",
      IsEmpty: "空の基地",
      IsDummiedLocation: "未使用の場所",
    },
  },
};
export function sb6Label(id: string, w: Sb6Words) {
  if (/^(IV|EV)_/.test(id)) {
    const [kind, stat] = id.split("_");
    return `${kind === "IV" ? w.iv : w.ev} · ${w.stat[stat as keyof typeof w.stat] ?? stat}`;
  }
  if (/^Move[1-4]$/.test(id)) return `${w.move} ${id.slice(-1)}`;
  if (/^PP[1-4]$/.test(id)) return `${w.pp} ${id.slice(-1)}`;
  return w.fields[id as keyof typeof w.fields] ?? id;
}
