import type { Br4Lang } from "./br4";
const en = {
  title: "Super Training Editor",
  read: "Read Super Training",
  group: "Settings group",
  records: "Records",
  bags: "Training Bags",
  stage: "Stage",
  lane: "Record group",
  slot: "Slot",
  species: "Species",
  form: "Form",
  gender: "Gender",
  time: "Time",
  current: "Current",
  keep: "Keep stored value",
  preview: "Preview changes",
  apply: "Apply preview",
  cancel: "Cancel preview",
  discard: "Discard changes",
  resave: "Resave bags using window rules",
  changed: "Changed save bytes",
  changes: "Actual changes",
  raw: "Raw data",
  noChanges: "No data changes",
  ignored: "Ignored input; stored values stay intact",
  unknownBag:
    "Stored bag cannot be loaded by the source window; select a valid replacement",
  note: "Edit a local save copy. Preview before applying; the original stays intact and changes can be undone.",
  recordNote:
    "Form and gender accept 0–255. Blank or invalid values preserve the old field. Time uses the current UI language, including negative values, exponents and supported special values.",
  bagNote:
    "The source packs nonempty bags toward the front and keeps the old trailing slots. Selecting empty bags does not clear storage. Inspect all twelve resulting slots in the preview.",
  symbols: "Special time values",
  bits: "Stored time bits",
  invalid: "Invalid Super Training fields or target. Check the input.",
  stale: "The save or preview changed. Read and preview it again.",
};
export type St6Words = typeof en;
export const st6Words: Record<Br4Lang, St6Words> = {
  en,
  zh: {
    title: "超级训练编辑器",
    read: "读取超级训练",
    group: "设置分组",
    records: "记录",
    bags: "训练背包",
    stage: "训练阶段",
    lane: "记录分组",
    slot: "格位",
    species: "种类",
    form: "形态",
    gender: "性别",
    time: "时间",
    current: "当前值",
    keep: "保留旧值",
    preview: "预览修改",
    apply: "确认应用",
    cancel: "取消预览",
    discard: "放弃修改",
    resave: "按窗口规则重新保存训练袋",
    changed: "存档变化字节",
    changes: "实际变化",
    raw: "原始数据",
    noChanges: "没有数据变化",
    ignored: "输入被忽略，保持旧值",
    unknownBag: "旧袋编号无法由来源窗口载入，请选择有效替代值",
    note: "编辑本地存档副本，先预览再确认，保留原件，可撤销。",
    recordNote:
      "形态与性别接受 0–255，空值或无效值保留原字段。时间按当前界面语言解析，可输入负数、指数和支持的特殊值。",
    bagNote:
      "上游把非空训练袋向前压紧，但保留尾部旧格位。选择空袋不会清空存储，请核对预览中的全部十二格实际结果。",
    symbols: "时间特殊值",
    bits: "时间存储位",
    invalid: "超级训练字段或格位无效，请核对输入。",
    stale: "存档或预览已变化，请重新读取并预览。",
  },
  ja: {
    title: "スーパートレーニング",
    read: "スパトレを読み込む",
    group: "設定グループ",
    records: "スパトレメニュー",
    bags: "サンドバッグ",
    stage: "トレーニング",
    lane: "記録グループ",
    slot: "スロット",
    species: "ポケモン",
    form: "フォルム",
    gender: "性別",
    time: "タイム",
    current: "現在の値",
    keep: "保存値を維持",
    preview: "変更を確認",
    apply: "変更を適用",
    cancel: "プレビューを閉じる",
    discard: "変更を破棄",
    resave: "元のルールでバッグを再保存",
    changed: "セーブの変更バイト数",
    changes: "実際の変更",
    raw: "元のデータ",
    noChanges: "データの変更なし",
    ignored: "入力を無視し、保存値を維持します",
    unknownBag:
      "保存されたバッグを元の画面で読み込めません。有効な値を選択してください",
    note: "端末内のセーブのコピーを編集します。適用前に確認してください。元ファイルは維持され、元に戻せます。",
    recordNote:
      "フォルムと性別は0–255です。空欄や無効な値は保存値を維持します。タイムは表示言語に従って解析し、負数、指数、対応する特殊値も入力できます。",
    bagNote:
      "元の保存処理は空でないバッグを前に詰めますが、後ろの保存値を残します。空を選んでも保存領域を消去しません。十二スロットの結果を確認してください。",
    symbols: "タイムの特殊値",
    bits: "タイムの保存ビット",
    invalid: "スパトレの項目またはスロットが無効です。入力を確認してください。",
    stale:
      "セーブまたはプレビューが変わりました。再読み込みして確認してください。",
  },
};
