import type { Br4Lang } from "./br4";
const en = {
  title: "Generation VI trainer settings",
  read: "Read trainer settings",
  group: "Settings group",
  sayings: "Saved sayings",
  maison: "Battle Maison streaks",
  multiplayer: "Multiplayer",
  position: "Save position using window rules",
  positionNote:
    "A changed numeric value saves all five position fields and their mirrors. Displayed precision does not limit stored decimals. Out-of-range input is clamped; blank or invalid input keeps the old value.",
  positionUnavailable:
    "The source window cannot load these position values; position editing is disabled.",
  ignoredInput: "Ignored input; stored value preserved",
  chateau: "Battle Chateau and style",
  appearance: "Source appearance properties",
  flags: "Mega Evolution",
  trash: "Trainer name and trash bytes",
  currentNormal: "Current · Normal",
  currentSuper: "Current · Super",
  bestNormal: "Best · Normal",
  bestSuper: "Best · Super",
  preview: "Preview changes",
  apply: "Apply preview",
  cancel: "Cancel preview",
  discard: "Discard changes",
  resave: "Resave the full trainer window",
  accessories: "Unlock all fashion accessories",
  note: "Basic trainer fields remain above. These settings use the same working copy and undo history.",
  resaveNote:
    "Full resave follows the source window: it rewrites visible strings and records, resets the player model, synchronizes current and total Poké Miles and normalizes supported dates. Inspect the preview before applying.",
  draftNote: "Apply or discard drafts before running another operation.",
  ignored: "Unknown stored value",
  changes: "Actual changes",
  changedBytes: "Changed save bytes",
  noChanges: "No data changes",
  model: "Player model",
  name: "Trainer name",
  money: "Money",
  bp: "Battle Points",
  pokeMiles: "Poké Miles",
  started: "Adventure started",
  fame: "Hall of Fame",
  saved: "Last saved",
  playTime: "Play time",
  location: "Country / Region / Console region",
  hex: "26 name bytes (52 hexadecimal characters)",
  text: "Trainer name (up to 12 characters)",
  prepare: "Prepare text bytes",
  clear: "Clear trailing trash bytes",
  layer: "Apply species name layer",
  textAction: "Preview name text",
  hexAction: "Preview raw bytes",
  species: "Species",
  language: "Language",
  generation: "Generation",
  invalid: "Invalid trainer field or operation. Check the input.",
  stale: "The save or preview changed. Read and preview it again.",
};
export const trainer6Words: Record<Br4Lang, typeof en> = {
  en,
  zh: {
    title: "第六世代训练家设置",
    read: "读取训练家设置",
    group: "设置分组",
    sayings: "保存的招呼短语",
    maison: "对战屋连胜数",
    multiplayer: "多人游戏",
    position: "按窗口规则保存位置",
    positionNote:
      "数值实际变化时保存全部五个位置字段及其镜像。显示小数位数不限制实际精度；超范围输入截至边界，空值或无效输入保留旧值。",
    positionUnavailable: "来源窗口无法载入这些位置数值，位置编辑已禁用。",
    ignoredInput: "输入被忽略，保留旧值",
    chateau: "对战城堡与风格",
    appearance: "来源外观属性",
    flags: "超级进化",
    trash: "训练家姓名与废字节",
    currentNormal: "当前 · 普通",
    currentSuper: "当前 · 超级",
    bestNormal: "最佳 · 普通",
    bestSuper: "最佳 · 超级",
    preview: "预览修改",
    apply: "确认应用",
    cancel: "取消预览",
    discard: "放弃修改",
    resave: "按完整训练家窗口重新保存",
    accessories: "解锁所有时装",
    note: "基础训练家字段保留在上方，这些设置使用同一工作副本和撤销记录。",
    resaveNote:
      "完整重新保存沿用来源窗口：重写可见字符串与记录、重置玩家模型、同步当前与累计宝可里程，并规范化适用日期。确认前请核对预览。",
    draftNote: "先应用或放弃草稿，再执行其他操作。",
    ignored: "未知旧值",
    changes: "实际变化",
    changedBytes: "存档变化字节",
    noChanges: "没有数据变化",
    model: "玩家模型",
    name: "训练家姓名",
    money: "金钱",
    bp: "对战点数",
    pokeMiles: "宝可里程",
    started: "开始冒险",
    fame: "进入名人堂",
    saved: "最后存档",
    playTime: "游戏时间",
    location: "国家／区域／3DS区域",
    hex: "姓名的26字节（52位十六进制）",
    text: "训练家姓名（最多12字符）",
    prepare: "准备文本字节",
    clear: "清除尾部废字节",
    layer: "应用宝可梦名称层",
    textAction: "预览姓名文本",
    hexAction: "预览原始字节",
    species: "种类",
    language: "语言",
    generation: "世代",
    invalid: "训练家字段或操作无效，请核对输入。",
    stale: "存档或预览已变化，请重新读取并预览。",
  },
  ja: {
    title: "第六世代のトレーナー設定",
    read: "トレーナー設定を読み込む",
    group: "設定グループ",
    sayings: "保存されたあいさつ",
    maison: "バトルハウス連勝記録",
    multiplayer: "マルチプレイ",
    position: "元の画面のルールで位置を保存",
    positionNote:
      "数値が変わると五つの位置項目と対応する値をすべて保存します。表示桁数は保存精度を制限しません。範囲外は境界値に補正し、空欄や無効な入力は元の値を維持します。",
    positionUnavailable:
      "元の画面で位置を読み込めないため、位置編集は無効です。",
    ignoredInput: "入力を無視し、保存値を維持",
    chateau: "バトルシャトーとスタイル",
    appearance: "元の外観プロパティ",
    flags: "メガシンカ",
    trash: "親の名前と余剰バイト",
    currentNormal: "現在 · ノーマル",
    currentSuper: "現在 · スーパー",
    bestNormal: "最高 · ノーマル",
    bestSuper: "最高 · スーパー",
    preview: "変更を確認",
    apply: "変更を適用",
    cancel: "プレビューを閉じる",
    discard: "変更を破棄",
    resave: "トレーナー画面全体のルールで再保存",
    accessories: "全ファッションを解禁",
    note: "基本項目は上にあります。同じ作業用コピーと元に戻す履歴を使用します。",
    resaveNote:
      "画面全体の再保存は元の処理に従い、文字列と記録の再書き込み、プレイヤーモデルのリセット、ポケマイルの同期、対応する日時の整理を行います。結果を確認してから適用してください。",
    draftNote: "編集内容を適用または破棄してから、別の操作を実行してください。",
    ignored: "未定義の保存値",
    changes: "実際の変更",
    changedBytes: "セーブの変更バイト数",
    noChanges: "データの変更なし",
    model: "プレイヤーモデル",
    name: "親の名前",
    money: "所持金",
    bp: "バトルポイント",
    pokeMiles: "ポケマイル",
    started: "冒険開始",
    fame: "殿堂入り",
    saved: "最終セーブ",
    playTime: "プレイ時間",
    location: "国／地域／3DS地域",
    hex: "名前の26バイト（16進数52桁）",
    text: "親の名前（最大12文字）",
    prepare: "文字列のバイトを準備",
    clear: "末尾の余剰バイトを消去",
    layer: "ポケモン名を重ねる",
    textAction: "名前の文字列を確認",
    hexAction: "元のバイトを確認",
    species: "ポケモン",
    language: "言語",
    generation: "世代",
    invalid: "トレーナー項目または操作が無効です。入力を確認してください。",
    stale: "セーブまたはプレビューが変わりました。再読み込みしてください。",
  },
};
