import type { Br4Lang } from "./br4";
const en = {
  cells: "Zygarde cells",
  stickers: "Totem stickers",
  read: "Read collectibles",
  total: "Stored",
  collected: "Collected",
  location: "Location",
  state: "State",
  states: ["None", "Available", "Received"],
  unknown: "Unknown stored state",
  search: "Find location or number",
  preview: "Preview changes",
  apply: "Apply to working copy",
  cancel: "Discard",
  giveAll: "Receive all",
  resave: "Save using source window rules",
  changed: "Changed bytes",
  invalid:
    "The collectible edit is invalid, unavailable or would overflow a counter. No changes were applied.",
  stale:
    "This preview belongs to an older working copy. Read the current data and preview again.",
  note: "Counts are independent values from 0 to 65535. Receiving all adds only newly received entries; Sun/Moon also increases Stored. Ultra Sun/Ultra Moon synchronizes the collected count with the game record when saved.",
  dirty: "Apply or discard these changes before receiving all or resaving.",
  resaveNote:
    "Resaving preserves all states and counts; Ultra Sun/Ultra Moon synchronizes the game record. Unknown stored states must be explicitly replaced before bulk operations.",
};
export const zygarde7Words: Record<Br4Lang, typeof en> = {
  en,
  zh: {
    cells: "基格尔德细胞",
    stickers: "霸主贴纸",
    read: "读取收集记录",
    total: "储存数量",
    collected: "已收集",
    location: "位置",
    state: "状态",
    states: ["无", "可领取", "已领取"],
    unknown: "未知原始状态",
    search: "搜索位置或编号",
    preview: "预览修改",
    apply: "应用到工作副本",
    cancel: "放弃修改",
    giveAll: "全部领取",
    resave: "按原窗口规则重新保存",
    changed: "修改字节数",
    invalid: "收集记录修改无效、不可用或会导致计数超限。没有应用修改。",
    stale: "此预览来自旧的工作副本。请重新读取并预览。",
    note: "两个计数独立，范围为 0–65535。全部领取只增加本次新领取的数量；日月同时增加储存数量，究极日月保存时将已收集数量同步到游戏记录。",
    dirty: "请先应用或放弃草稿，再执行全部领取或重新保存。",
    resaveNote:
      "重新保存保留全部状态和计数；究极日月会同步游戏记录。未知原始状态需明确替换后才能执行批量操作。",
  },
  ja: {
    cells: "ジガルデ・セル",
    stickers: "ヌシール",
    read: "収集記録を読む",
    total: "キューブ内",
    collected: "回収数",
    location: "場所",
    state: "状態",
    states: ["なし", "取得可能", "取得済み"],
    unknown: "不明な保存状態",
    search: "場所または番号を検索",
    preview: "変更をプレビュー",
    apply: "作業コピーに適用",
    cancel: "変更を破棄",
    giveAll: "全て取得",
    resave: "元の画面の規則で再保存",
    changed: "変更バイト数",
    invalid:
      "収集記録の変更が無効、利用不可、または数の上限を超えます。変更は適用されていません。",
    stale:
      "このプレビューは古い作業コピーのものです。読み直して再確認してください。",
    note: "二つの数は独立した 0–65535 の値です。全て取得は新規取得分だけ加算します。サン・ムーンはキューブ内の数も増加し、ウルトラサン・ウルトラムーンは保存時に回収数をゲーム記録へ同期します。",
    dirty: "全て取得や再保存の前に、変更を適用するか破棄してください。",
    resaveNote:
      "再保存は全ての状態と数を保持します。ウルトラサン・ウルトラムーンはゲーム記録を同期します。不明な状態を明示的に置換してから一括操作してください。",
  },
};
