import type { Gen3GameVersion } from "../profiles/domain";
import { getGen3Personal } from "../shared/gen3Personal";
import type { Gen3StaticTemplate } from "./domain";

export const GEN3_STATIC_CATEGORIES = [
  "starters",
  "fossils",
  "gifts",
  "gameCorner",
  "stationary",
  "legends",
  "events",
  "roamers",
] as const;

export type Gen3StaticCategory = (typeof GEN3_STATIC_CATEGORIES)[number];

const RSE: Gen3GameVersion[] = ["ruby", "sapphire", "emerald"];
const FRLG: Gen3GameVersion[] = ["firered", "leafgreen"];

type EncounterInput = Omit<Gen3StaticTemplate, "id" | "genderRatio">;

const encounterInputs: EncounterInput[] = [
  {
    category: "starters",
    versions: ["emerald"],
    species: 152,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: ["emerald"],
    species: 155,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: ["emerald"],
    species: 158,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: RSE,
    species: 252,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: RSE,
    species: 255,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: RSE,
    species: 258,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: FRLG,
    species: 1,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: FRLG,
    species: 4,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "starters",
    versions: FRLG,
    species: 7,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },

  {
    category: "fossils",
    versions: RSE,
    species: 345,
    form: 0,
    level: 20,
    buggedRoamer: false,
  },
  {
    category: "fossils",
    versions: RSE,
    species: 347,
    form: 0,
    level: 20,
    buggedRoamer: false,
  },
  {
    category: "fossils",
    versions: FRLG,
    species: 138,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "fossils",
    versions: FRLG,
    species: 140,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "fossils",
    versions: FRLG,
    species: 142,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },

  {
    category: "gifts",
    versions: RSE,
    species: 351,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: RSE,
    species: 374,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: RSE,
    species: 360,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 106,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 107,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 129,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 131,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 133,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gifts",
    versions: FRLG,
    species: 175,
    form: 0,
    level: 5,
    buggedRoamer: false,
  },

  {
    category: "gameCorner",
    versions: ["firered"],
    species: 63,
    form: 0,
    level: 9,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["firered"],
    species: 35,
    form: 0,
    level: 8,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["firered"],
    species: 123,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["firered"],
    species: 147,
    form: 0,
    level: 18,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["firered"],
    species: 137,
    form: 0,
    level: 26,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["leafgreen"],
    species: 63,
    form: 0,
    level: 7,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["leafgreen"],
    species: 35,
    form: 0,
    level: 12,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["leafgreen"],
    species: 127,
    form: 0,
    level: 18,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["leafgreen"],
    species: 147,
    form: 0,
    level: 24,
    buggedRoamer: false,
  },
  {
    category: "gameCorner",
    versions: ["leafgreen"],
    species: 137,
    form: 0,
    level: 18,
    buggedRoamer: false,
  },

  {
    category: "stationary",
    versions: RSE,
    species: 352,
    form: 0,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: RSE,
    species: 100,
    form: 0,
    level: 25,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: RSE,
    species: 101,
    form: 0,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: ["emerald"],
    species: 185,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: FRLG,
    species: 143,
    form: 0,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: FRLG,
    species: 101,
    form: 0,
    level: 34,
    buggedRoamer: false,
  },
  {
    category: "stationary",
    versions: FRLG,
    species: 97,
    form: 0,
    level: 30,
    buggedRoamer: false,
  },

  {
    category: "legends",
    versions: RSE,
    species: 377,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: RSE,
    species: 378,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: RSE,
    species: 379,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["ruby", "emerald"],
    species: 380,
    form: 0,
    level: 50,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["sapphire", "emerald"],
    species: 381,
    form: 0,
    level: 50,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["sapphire"],
    species: 382,
    form: 0,
    level: 45,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["emerald"],
    species: 382,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["ruby"],
    species: 383,
    form: 0,
    level: 45,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: ["emerald"],
    species: 383,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: RSE,
    species: 384,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: FRLG,
    species: 144,
    form: 0,
    level: 50,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: FRLG,
    species: 145,
    form: 0,
    level: 50,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: FRLG,
    species: 146,
    form: 0,
    level: 50,
    buggedRoamer: false,
  },
  {
    category: "legends",
    versions: FRLG,
    species: 150,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },

  {
    category: "events",
    versions: ["emerald"],
    species: 151,
    form: 0,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "events",
    versions: ["emerald"],
    species: 386,
    form: 3,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "events",
    versions: ["firered"],
    species: 386,
    form: 1,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "events",
    versions: ["leafgreen"],
    species: 386,
    form: 2,
    level: 30,
    buggedRoamer: false,
  },
  {
    category: "events",
    versions: ["emerald", ...FRLG],
    species: 249,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },
  {
    category: "events",
    versions: ["emerald", ...FRLG],
    species: 250,
    form: 0,
    level: 70,
    buggedRoamer: false,
  },

  {
    category: "roamers",
    versions: FRLG,
    species: 243,
    form: 0,
    level: 50,
    buggedRoamer: true,
  },
  {
    category: "roamers",
    versions: FRLG,
    species: 244,
    form: 0,
    level: 50,
    buggedRoamer: true,
  },
  {
    category: "roamers",
    versions: FRLG,
    species: 245,
    form: 0,
    level: 50,
    buggedRoamer: true,
  },
  {
    category: "roamers",
    versions: ["sapphire"],
    species: 380,
    form: 0,
    level: 40,
    buggedRoamer: true,
  },
  {
    category: "roamers",
    versions: ["ruby"],
    species: 381,
    form: 0,
    level: 40,
    buggedRoamer: true,
  },
  {
    category: "roamers",
    versions: ["emerald"],
    species: 380,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
  {
    category: "roamers",
    versions: ["emerald"],
    species: 381,
    form: 0,
    level: 40,
    buggedRoamer: false,
  },
];

export const GEN3_STATIC_TEMPLATES: Gen3StaticTemplate[] = encounterInputs.map(
  (entry, index) => ({
    ...entry,
    id: `${entry.category}-${index}`,
    genderRatio: getGen3Personal(entry.species, entry.form).genderRatio,
  }),
);

export function gen3StaticTemplatesForVersion(
  version: Gen3GameVersion,
  category?: Gen3StaticCategory,
) {
  return GEN3_STATIC_TEMPLATES.filter(
    (entry) =>
      entry.versions.includes(version) &&
      (category === undefined || entry.category === category),
  );
}

export function gen3StaticCategoriesForVersion(version: Gen3GameVersion) {
  return GEN3_STATIC_CATEGORIES.filter(
    (category) => gen3StaticTemplatesForVersion(version, category).length > 0,
  );
}
