// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using System.Buffers.Binary;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
internal static class Avenue5EditingTests
{
    private static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    private static void Reject(Action action){try{action();throw new Exception("Invalid Avenue5 request accepted");}catch(ArgumentException){}}
    private static SAV5B2W2 Open(byte[] data)=>SaveUtil.GetSaveFile(data.ToArray())as SAV5B2W2??throw new Exception("Unknown B2W2 fixture");
    private static Avenue5Catalog Read(byte[] data)=>JsonSerializer.Deserialize(SaveService.ReadAvenue5(data),SaveJsonContext.Default.Avenue5Catalog)!;
    private static Avenue5Preview Preview(byte[] data,Avenue5Edit e)=>JsonSerializer.Deserialize(SaveService.PreviewAvenue5(data,JsonSerializer.Serialize(e,SaveJsonContext.Default.Avenue5Edit)),SaveJsonContext.Default.Avenue5Preview)!;
    private static byte[] Apply(byte[] data,Avenue5Edit e){var original=data.ToArray();var p=Preview(data,e);var output=SaveService.EditAvenue5(data,JsonSerializer.Serialize(p.Request,SaveJsonContext.Default.Avenue5Edit));Check(data.SequenceEqual(original),"Avenue original immutable");Check(Br4Editing.Hash(output)==p.Request.TargetHash&&p.Result.SourceHash==p.Request.TargetHash,"Avenue full frozen output");Check(p.ChangedOffsets.SequenceEqual(Enumerable.Range(0,data.Length).Where(i=>data[i]!=output[i])),"Avenue complete offsets");Check(SaveService.ExportWorkingCopy(output).SequenceEqual(output),"Avenue full export");return output;}
    private static void Compare(byte[] data,Avenue5Edit e,Action<SAV5B2W2> oracle){var s=Open(data);oracle(s);Check(Apply(data,e).SequenceEqual(s.Write().ToArray()),"Avenue independent whole-file oracle");}
    private static IJoinAvenueEntity5 Target(SAV5B2W2 s,string group,int index)=>group switch{"visitors"=>s.JoinAvenue.GetVisitor(index),"fans"=>s.JoinAvenue.GetFan(index),"occupants"=>s.JoinAvenue.GetOccupant(index),"assistants"=>s.JoinAvenue.GetAssistant(index),"self"=>s.JoinAvenue.Self,_=>throw new Exception("Invalid oracle target")};
    private static IJoinAvenueEntity5 Source(byte[] data)=>data.Length switch{196=>new JoinAvenueVisitor5(data),96=>new JoinAvenueFan5(data),88=>new JoinAvenueAssistant5(data),_=>throw new Exception("Invalid oracle source")};
    public static void Run()
    {
        foreach(var version in new[]{GameVersion.B2,GameVersion.W2}){
            var s=Open(File.ReadAllBytes(".tmp/pkhex-fixtures/B2.sav"));s.Version=version;s.JoinAvenue.Data.Fill(0xA6);
            // Real block offsets; include alignment, unknown flags, invalid dates and out-of-range old selections.
            for(int i=0;i<32;i++)s.JoinAvenue.Settings.SetVisitingPlayerTrainerID(i,0x89AB1234);
            var data=s.Write().ToArray();var original=data.ToArray();var c=Read(data);Check(c.CanEdit&&c.Objects.Length==35,"Avenue all groups and physical slots");
            Check(c.Objects.Count(x=>x.Group=="visitors")==8&&c.Objects.Count(x=>x.Group=="fans")==12&&c.Objects.Count(x=>x.Group=="occupants")==8&&c.Objects.Count(x=>x.Group=="assistants")==4,"Avenue fixed slot counts independent of stored counters");
            Check(c.Objects.All(o=>o.Fields.Select(f=>f.Id).Distinct().Count()==o.Fields.Length),"Avenue unique fields");
            var avenue=new Avenue5Edit("patch",c.SourceHash,"avenue",0,[new("ScriptFlag","1"),new("CountVisitor","4294967295"),new("CountFan","0")]);
            Compare(data,avenue,x=>{var a=x.JoinAvenue.Data;a[0x12F0]|=1;BinaryPrimitives.WriteUInt32LittleEndian(a,uint.MaxValue);BinaryPrimitives.WriteUInt32LittleEndian(a[0x628..],0);});
            // A reverse request order still writes strings around the original Language setter ordering.
            foreach(var o in c.Objects.Where(o=>o.Extension is not null||o.Group=="self")){
                var edit=new Avenue5Edit("patch",c.SourceHash,o.Group,o.Index,[new("Farewell","♀Bye"),new("Greeting","♂Hi"),new("Language","8"),new("Shout","♀Short"),new("Name","♂Name"),new("Country","255"),new("Subregion","255"),new("PlayedMinutes","63"),new("PlayedHours","1023"),new("TID16","65535"),new("MetYear","255"),new("MetMonth","255"),new("MetDay","255"),new("Seed","4294967295")]);
                Compare(data,edit,x=>{var e=Target(x,o.Group,o.Index);e.Name="♂Name";e.Country=255;e.Subregion=255;e.Shout="♀Short";e.Language=8;e.TID16=65535;e.PlayedHours=1023;e.PlayedMinutes=63;e.Greeting="♂Hi";e.Farewell="♀Bye";e.MetYear=255;e.MetMonth=255;e.MetDay=255;e.Seed=uint.MaxValue;});
                foreach(int size in new[]{196,96,88})if(o.Extension is not null){var imported=Enumerable.Range(0,size).Select(i=>(byte)(i*13+7)).ToArray();var source=Source(imported);source.Name="Import";source.Greeting="Hello";source.Language=1;
                    var req=new Avenue5Edit("import",c.SourceHash,o.Group,o.Index,DataBase64:Convert.ToBase64String(imported));Compare(data,req,x=>Target(x,o.Group,o.Index).CopyFrom(Source(imported)));
                }
                if(o.Extension is not null){var req=new Avenue5Edit("export",c.SourceHash,o.Group,o.Index);var bytes=SaveService.ExportAvenue5(data,JsonSerializer.Serialize(req,SaveJsonContext.Default.Avenue5Edit));Check(bytes.SequenceEqual(Convert.FromHexString(o.RawHex)),"Avenue exact export bytes");}
            }
            // Sparse changes retain flags; explicit boolean writes preserve the exact source normalization.
            Compare(data,new("patch",c.SourceHash,"fans",11,[new("Unknown4F","255"),new("IsInteractedToday","1")]),x=>{x.JoinAvenue.Data[0x62C+11*96+0x4E]=255;x.JoinAvenue.Data[0x62C+11*96+0x4F]=1;});
            Compare(data,new("patch",c.SourceHash,"assistants",3,[new("IsInteractedToday","1")]),x=>x.JoinAvenue.Data[0x10CC+3*88+0x33]=1);
            Compare(data,new("patch",c.SourceHash,"visitors",7,[new("Unknown22","15"),new("ShopCounts","0xFF; bad|2,,3\n4;5;6;7;8"),new("Records","0xFFFFFFFF,4294967296, ,+3"),new("Trivia","999,2"),new("Activities","1,2,3,4,5"),new("Date1","0xFFFFFFFF"),new("DateAdventureStart","2001-02-03"),new("ActivityDates","bad,2002-01-03|0xFFFF")]),x=>{var v=x.JoinAvenue.GetVisitor(7);v.Unknown22=15;v.ShopCountRaffle=15;v.ShopCountSalon=0;v.ShopCountMarket=2;v.ShopCountFlorist=3;v.ShopCountDojo=4;v.ShopCountNurse=5;v.ShopCountAntique=6;v.ShopCountCafe=7;for(int i=0;i<8;i++)v.SetRecord((JoinAvenueRecordIndex5)i,i==0?uint.MaxValue:i==2?3u:0);for(int i=0;i<16;i++)v.SetTrivia(i,(byte)(i==0?255:i==1?2:0));for(int i=0;i<4;i++){v.SetActivity(i,(byte)(i+1));v.SetActivityDate(i,new((ushort)(i==1?1059:i==2?65535:0)));}v.Date1=new(65535);v.DateAdventureStart=new(579);});
            Compare(data,new("patch",c.SourceHash,"settings",0,[new("SID31","65536"),new("TID31",""),new("SID0"," 65535 "),new("TID0","+42"),new("Rank","9999"),new("VisitingPlayerDatabaseCount","32"),new("VistiingPlayerDatabaseInsertIndex","31")]),x=>{var settings=x.JoinAvenue.Settings;settings.SetVisitingPlayerTrainerID(31,0);settings.SetVisitingPlayerTrainerID(0,0xFFFF002A);settings.Rank=9999;settings.VisitingPlayerDatabaseCount=32;settings.VistiingPlayerDatabaseInsertIndex=31;});
            // Source EncodeShop has different multipliers than DecodeShop; never replace it with an assumed identity.
            for(int type=-1;type<8;type++)for(int rank=0;rank<10;rank++)for(int game=0;game<4;game++){
                var tuple=type<0?((byte Version,JoinAvenueShopType5 Type,byte Rank)?)null:((byte)game,(JoinAvenueShopType5)type,(byte)rank);var own=Open(data);own.JoinAvenue.GetVisitor(0).ShopTypeTuple=tuple;
                var req=new Avenue5Edit("patch",c.SourceHash,"visitors",0,[new("Shop",$"{type},{rank},{game}")]);Check(Avenue5Editing.Prepare(Open(data),req,c.SourceHash,data.Length).SequenceEqual(own.Write().ToArray()),"Avenue all shop tuple source encodings");
            }
            foreach(var o in c.Objects){var defs=Avenue5Editing.Definitions(Open(data),o.Group,o.Index);foreach(var d in defs.Where(f=>f.Kind is "number" or "boolean")){
                    Reject(()=>Preview(data,new("patch",c.SourceHash,o.Group,o.Index,[new(d.Id,"-1")])));Reject(()=>Preview(data,new("patch",c.SourceHash,o.Group,o.Index,[new(d.Id,(d.Maximum+1).ToString())])));
                }}
            // Explicit settings resave mirrors the pinned window loading/clamping and save order.
            Compare(data,new("resave",c.SourceHash,"settings",0),x=>{var z=x.JoinAvenue.Settings;string name=z.Name,title=z.PlayerTitle;uint exp=z.Experience,flags=z.Flags,seed=z.Seed;ushort rank=(ushort)Math.Min(9999,(int)z.Rank),count=(ushort)Math.Min(32,(int)z.VisitingPlayerDatabaseCount),insert=(ushort)Math.Min(31,(int)z.VistiingPlayerDatabaseInsertIndex),days=z.PromotionDaysElapsed;bool promotion=z.IsPromotionActive;var ceiling=Enum.IsDefined(z.CeilingColor)?z.CeilingColor:(JoinAvenueCeilingColor5)65535;var ids=Enumerable.Range(0,32).Select(z.GetVisitingPlayerTrainerID).ToArray();z.Name=name;z.PlayerTitle=title;z.Experience=exp;z.Rank=rank;z.CeilingColor=ceiling;z.Flags=flags;z.VisitingPlayerDatabaseCount=count;z.VistiingPlayerDatabaseInsertIndex=insert;z.Seed=seed;z.PromotionDaysElapsed=days;z.IsPromotionActive=promotion;for(int i=0;i<32;i++)z.SetVisitingPlayerTrainerID(i,ids[i]);});
            // Common role controls reload old strings and clamp only unknown gender; selected versions/languages fall back to -1.
            foreach(var o in c.Objects.Where(o=>o.Group is "fans" or "assistants")){Compare(data,new("resave",c.SourceHash,o.Group,o.Index),x=>{var z=Target(x,o.Group,o.Index);string name=z.Name,shout=z.Shout,greeting=z.Greeting,farewell=z.Farewell;byte country=z.Country,region=z.Subregion,unknown=z.Unknown22,gender=(byte)Math.Min(2,(int)z.Gender),unused=z.Unused23,u26=z.Unknown26,u27=z.Unknown27,minutes=z.PlayedMinutes,year=z.MetYear,month=z.MetMonth,day=z.MetDay;ushort tid=z.TID16,hours=z.PlayedHours,sprite=z.Sprite;uint seed=z.Seed;byte version=new FilteredGameDataSource(x,new GameDataSource(GameInfo.GetStrings("en"))).Games.Any(c=>c.Value==z.Version)?z.Version:(byte)255;byte language=GameInfo.LanguageDataSource(5,EntityContext.Gen5).Any(c=>c.Value==z.Language)?z.Language:(byte)255;z.Name=name;z.Country=country;z.Subregion=region;z.Shout=shout;z.Version=version;z.Language=language;z.Unknown22=unknown;z.Gender=gender;z.Unused23=unused;z.TID16=tid;z.Unknown26=u26;z.Unknown27=u27;z.PlayedHours=hours;z.PlayedMinutes=minutes;z.Sprite=sprite;z.Greeting=greeting;z.Farewell=farewell;z.MetYear=year;z.MetMonth=month;z.MetDay=day;z.Seed=seed;if(z is JoinAvenueFan5 fan){fan.IsInteractedToday=fan.IsInteractedToday;var choices=new FilteredGameDataSource(x,new GameDataSource(GameInfo.GetStrings("en"))).Species;fan.Species=choices.Any(c=>c.Value==fan.Species)?fan.Species:(ushort)65535;}else if(z is JoinAvenueAssistant5 assistant)assistant.IsInteractedToday=assistant.IsInteractedToday;});}
            // All visitor/occupant/self resaves of the raw A6 fixture: independent byte-level window normalization.
            foreach(var o in c.Objects.Where(o=>o.Group is "visitors" or "occupants" or "self")){Compare(data,new("resave",c.SourceHash,o.Group,o.Index),x=>{int offset=o.Group=="visitors"?8+o.Index*196:o.Group=="occupants"?0xAAC+o.Index*196:0x122C;var block=x.JoinAvenue.Data;block[offset+0x20]=255;block[offset+0x21]=255;block[offset+0x22]=0x26;BinaryPrimitives.WriteUInt16LittleEndian(block[(offset+0xA0)..],65535);block[offset+0xAD]=10;foreach(int shopOffset in new[]{0x2E,0xB4}){uint raw=BinaryPrimitives.ReadUInt16LittleEndian(block[(offset+shopOffset)..])-1u;uint rank=raw%10,type=(raw/10)%8,versionIndex=(raw/80)%4;ushort encoded=(ushort)(((versionIndex*4+type)*8+rank)+1);BinaryPrimitives.WriteUInt16LittleEndian(block[(offset+shopOffset)..],encoded);}});}
            var good=new Avenue5Edit("patch",c.SourceHash,"visitors",0,[new("TID16","1")]);Reject(()=>Preview(data,good with{Fields=[]}));Reject(()=>Preview(data,good with{Index=-1}));Reject(()=>Preview(data,good with{Index=8}));Reject(()=>Preview(data,good with{SourceHash=new string('0',64)}));Reject(()=>Preview(data,good with{Fields=[new("TID16","1"),new("TID16","2")]}));Reject(()=>Preview(data,good with{Fields=[new("Name","12345678")]}));Reject(()=>Preview(data,good with{Fields=[new("Shop","1,10,4")]}));Reject(()=>Preview(data,good with{Fields=[new("missing","0")]}));Reject(()=>Preview(data,good with{Action="import",Fields=null,DataBase64=Convert.ToBase64String(new byte[195])}));Reject(()=>SaveService.EditAvenue5(data,JsonSerializer.Serialize(good,SaveJsonContext.Default.Avenue5Edit)));var frozen=Preview(data,good).Request;Reject(()=>SaveService.EditAvenue5(data,JsonSerializer.Serialize(frozen with{TargetHash=new string('0',64)},SaveJsonContext.Default.Avenue5Edit)));
            var corrupt=data.ToArray();corrupt[0x100]^=1;var bad=Read(corrupt);Check(!bad.CanEdit,"Avenue checksum gate");Reject(()=>Preview(corrupt,good with{SourceHash=bad.SourceHash}));Check(data.SequenceEqual(original),"Avenue original unchanged across reads and rejection");
            Console.WriteLine($"PASS {version}: all 35 objects/33 entities, source limits, string save order, all import type pairs/exports, bit/old-data protection, list/date parsers, 360 shop tuples, complete files and atomic frozen rejection");
        }
        Reject(()=>SaveService.ReadAvenue5(File.ReadAllBytes(".tmp/pkhex-fixtures/B.sav")));
    }
}
