// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
using static System.Buffers.Binary.BinaryPrimitives;
internal static class BattlePass4EditingTests
{
    private static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    private static void Reject(Action action){try{action();throw new Exception("Invalid Battle Pass request accepted");}catch(ArgumentException){}}
    private static SAV4BR Open(byte[] bytes,int profile){var s=(SAV4BR)SaveUtil.GetSaveFile(bytes.ToArray())!;s.CurrentSlot=profile;return s;}
    private static Bp4Catalog Read(byte[] bytes,int index)=>JsonSerializer.Deserialize(SaveService.ReadBattlePass4(bytes,JsonSerializer.Serialize(new Bp4Query(index),SaveJsonContext.Default.Bp4Query)),SaveJsonContext.Default.Bp4Catalog)!;
    private static byte[] Apply(byte[] bytes,Bp4Edit edit){var original=bytes.ToArray();try{return SaveService.EditBattlePass4(bytes,JsonSerializer.Serialize(edit,SaveJsonContext.Default.Bp4Edit));}finally{Check(bytes.SequenceEqual(original),"Immutable encrypted source");}}
    private static void Compare(byte[] bytes,int profile,Bp4Edit edit,Action<SAV4BR> mutate){var expected=Open(bytes,profile);mutate(expected);var actual=Apply(bytes,edit);Check(actual.SequenceEqual(expected.Write().ToArray()),"Whole encrypted container parity and other players/partition protection");Check(SaveService.ExportWorkingCopy(actual).SequenceEqual(actual),"Exact working-copy export");}
    public static void Run()
    {
        foreach(bool japanese in new[]{false,true})foreach(int partition in new[]{0,1})
        {
            var seed=Br4EditingTests.Fixture(japanese,partition);var initial=Open(seed,0);
            for(int player=0;player<4;player++){initial.CurrentSlot=player;for(int i=0;i<187;i++){var p=initial.BattlePasses[i];p.Name=$"P{player}-{i}";p.Model=1;p.Language=BattlePassLanguage.English;p.Available=i%2==0;p.Issued=i%3==0;p.Data[0x1EC]=0x75;p.Data[0x544]|=0x80;p.Data[0x545]|=3;for(int member=0;member<6;member++){p.SetPartySlotBoxSlot(member,(byte)(i%254),(byte)member);p.SetPartySlotFlags(member,(ushort)(0x1000+i+member));}}}
            var bytes=initial.Write().ToArray();
            foreach(int profile in new[]{0,3})
            {
                SaveService.ConfigureBRProfile(profile);var c=Read(bytes,0);Check(c.CanEdit&&c.Profile==profile&&c.Passes.Length==187&&c.Numbers.Length==40&&c.Text.Length==13&&c.Flags.Length==10&&c.Members.Length==6,"Complete window catalog");
                foreach(int index in new[]{0,158,159,170,171,186}){var item=Read(bytes,index);Check(item.Index==index&&item.Passes[index].Name==$"P{profile}-{index}"&&Convert.FromBase64String(SaveService.ExportBattlePass4(bytes,index)).SequenceEqual(Open(bytes,profile).BattlePasses[index].Data.ToArray()),"Actual pass banks and opaque export");}
                Bp4Value[] values=[new(1,"99999"),new(2,""),new(17,"65535"),new(18,"65534"),new(19,"1234"),new(20,"1235"),new(21,"1236"),new(22,"1237"),new(26,int.MinValue.ToString()),new(27,int.MaxValue.ToString()),new(28,"-1"),new(29,"42"),..Enumerable.Range(30,10).Select(i=>new Bp4Value(i,(i+200).ToString()))];
                Compare(bytes,profile,new("numbers",profile,0,values),s=>{var p=s.BattlePasses[0];p.TID=unchecked((ushort)99999);p.SID=0;ushort[] indices=[65535,65534,1234,1235,1236,1237];for(int i=0;i<6;i++)WriteUInt16BigEndian(p.Data[(0x1F0+2*i)..],indices[i]);p.Battles=int.MinValue;p.RecordColosseumBattles=int.MaxValue;p.RecordFreeBattles=-1;p.RecordWiFiBattles=42;for(int i=0;i<10;i++)p.Data[0x6D0+i]=(byte)(230+i);});
                var flags=Enumerable.Range(0,10).Select(i=>new Bp4Value(i,"1")).ToArray();Compare(bytes,profile,new("flags",profile,186,flags),s=>{var p=s.BattlePasses[186];for(int i=1;i<=6;i++)FlagUtil.SetFlag(p.Data,0x1E,i,true);foreach(int bit in new[]{3,4,6,7})FlagUtil.SetFlag(p.Data,0x545,bit,true);p.ResetPresetIndexes();});
                Compare(bytes,profile,new("numbers",profile,0,[new(3,"6")]),s=>{var p=s.BattlePasses[0];p.Model=6;for(int id=0;id<10;id++)p.Data[0x22+id]=(byte)GearUnlock.GetDefault((ModelBR)(id==9?1:6),(GearCategory)id);p.ResetPresetIndexes();});
                Compare(bytes,profile,new("text",profile,159,[new(0,"New"),new(2,"Hello\nⓅ"),new(10,"Intro\nLine"),new(12,"FEDCBA9876543210")]),s=>{var p=s.BattlePasses[159];p.Name="New";p.SentOut="Hello⏎Ⓟ";p.SelfIntroduction="￼Intro⏎Line";p.PlayerID=0xFEDCBA9876543210;});
                Compare(bytes,profile,new("rawText",profile,170,[new(8,"FFFFFFFF1234ABCD")]),s=>Convert.FromHexString("FFFFFFFF1234ABCD").CopyTo(s.BattlePasses[170].Data.Slice(0x568,8)));
                Compare(bytes,profile,new("links",profile,171,Slot:5,Box:255,Position:255,Flags:65535),s=>{var p=s.BattlePasses[171];p.SetPartySlotBoxSlot(5,255,255);p.SetPartySlotFlags(5,65535);});
                foreach(string action in new[]{"unlockCustom","unlockRental","swap","delete","import"}){int index=action=="delete"?initial.BattlePasses.PASS_START_FRIEND:0;string? data=action=="import"?Convert.ToBase64String(Open(bytes,profile).BattlePasses[186].Data):null;Compare(bytes,profile,new(action,profile,index,Other:action=="swap"?1:null,Data:data,SourceHash:c.SourceHash),s=>{switch(action){case "unlockCustom":s.BattlePasses.UnlockAllCustomPasses();break;case "unlockRental":s.BattlePasses.UnlockAllRentalPasses();break;case "swap":s.BattlePasses.Swap(0,1);break;case "delete":s.BattlePasses.Delete(index);break;case "import":Convert.FromBase64String(data!).CopyTo(s.BattlePasses[0].Data);break;}});}
                var pk=new BK4{Species=25,PID=12345,Version=GameVersion.D};pk.RefreshChecksum();var binary=new byte[pk.SIZE_PARTY];pk.WriteDecryptedDataParty(binary);var set=new Bp4Edit("setPokemon",profile,0,Slot:5,Data:Convert.ToBase64String(binary),FileName:"pikachu.bk4",Encrypted:false,SourceHash:c.SourceHash);var preview=JsonSerializer.Deserialize(SaveService.PreviewBattlePassPokemon4(bytes,JsonSerializer.Serialize(set,SaveJsonContext.Default.Bp4Edit)),SaveJsonContext.Default.Bp4PokemonPreview)!;Check(preview.Target==0&&preview.Box==255&&preview.Position==255&&preview.Warnings.Length==0&&preview.Pokemon.Species==25,"Native import preview and real compacted target");Compare(bytes,profile,set,s=>{var pass=s.BattlePasses[0];pk.WriteEncryptedDataStored(pass.Data.Slice(0x1FC,136));pass.SetPartySlotPresent(0,true);pass.SetPartySlotBoxSlot(0,255,255);});var output=Apply(bytes,set);var pkm=Read(output,0);Check(pkm.Members[0] is {Present:true,Pokemon.Species:25,Box:255,Position:255}&&pkm.Members.Skip(1).All(v=>!v.Present),"Party compaction and custom unmatched link");var exported=Convert.FromBase64String(SaveService.ExportBattlePassPokemon4(output,0,0));Check(exported.Length==pk.SIZE_STORED&&StandalonePokemon.Open(exported,"p.bk4",false,true).Entity.Species==25,"Decrypted BK4 export");Compare(output,profile,new("deletePokemon",profile,0,Slot:0,SourceHash:pkm.SourceHash),s=>s.BattlePasses[0].DeletePartySlot(0));
                if(profile==0){pk.Move1=950;pk.RefreshChecksum();pk.WriteDecryptedDataParty(binary);var incompatible=set with{Data=Convert.ToBase64String(binary)};var warnings=JsonSerializer.Deserialize(SaveService.PreviewBattlePassPokemon4(bytes,JsonSerializer.Serialize(incompatible,SaveJsonContext.Default.Bp4Edit)),SaveJsonContext.Default.Bp4PokemonPreview)!;Check(warnings.Warnings.Length==1&&warnings.Warnings[0].Zh.Contains("招式")&&warnings.Warnings[0].Ja!=warnings.Warnings[0].En,"Compatibility warning localization");Reject(()=>Apply(bytes,incompatible));var accepted=Apply(bytes,incompatible with{ConfirmIncompatible=true});Check(Open(accepted,profile).BattlePasses[0].GetPartySlotAtIndex(0).Move1==950,"Explicit compatibility exception confirmation");Reject(()=>SaveService.PreviewBattlePassPokemon4(bytes,JsonSerializer.Serialize(incompatible with{ConfirmIncompatible=true},SaveJsonContext.Default.Bp4Edit)));}
                Bp4Edit[] invalid=[new("numbers",profile,0,[new(1,"100000")]),new("numbers",profile,0,[new(26,"2147483648")]),new("numbers",profile,0,[new(7,"65535")]),new("numbers",profile,0,[new(3,"13")]),new("numbers",profile,0,[new(25,"6")]),new("numbers",profile,0,[new(30,"")]),new("numbers",profile,0,[new(1,"0"),new(1,"1")]),new("text",profile,0,[new(8,"1234")]),new("text",profile,0,[new(1,"\n")]),new("text",profile,0,[new(12,"XYZ")]),new("flags",profile,0,[new(10,"1")]),new("links",profile,0,Slot:6,Box:0),new("links",profile,0,Slot:0,Flags:65536),new("swap",profile,0,Other:2,SourceHash:c.SourceHash),new("delete",profile,initial.BattlePasses.PASS_START_RENTAL,SourceHash:c.SourceHash),new("import",profile,0,Data:"AA==",SourceHash:c.SourceHash),new("delete",profile,0,SourceHash:new string('0',64)),new("numbers",(profile+1)%4,0,[new(1,"0")]),new("numbers",profile,187,[new(1,"0")])];
                foreach(var edit in invalid){Reject(()=>Apply(bytes,edit));var save=Open(bytes,profile);var before=save.Data.ToArray();Reject(()=>BattlePass4Editing.Apply(save,edit,c.SourceHash));Check(before.SequenceEqual(save.Data),"Atomic invalid request");}
            }
            Console.WriteLine($"PASS Battle Pass Japanese={japanese} partition={partition}: complete catalog/banks, records, text/raw, model, flags, links, pass and Pokemon operations, encrypted parity and atomic requests");
        }
        SaveService.ResetBRProfile();
    }
}
