// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
using static System.Buffers.Binary.BinaryPrimitives;
internal static class Misc4EditingTests
{
    private static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    private static void Reject(Action action){try{action();throw new Exception("Invalid Misc4 request accepted");}catch(ArgumentException){}}
    private static SAV4 Open(byte[] data)=>SaveUtil.GetSaveFile(data.ToArray())as SAV4??throw new Exception("Gen4 fixture not recognized");
    private static Misc4Catalog Read(byte[] bytes)=>JsonSerializer.Deserialize(SaveService.ReadMisc4(bytes),SaveJsonContext.Default.Misc4Catalog)!;
    private static Misc4Preview Preview(byte[] bytes,Misc4Edit edit)=>JsonSerializer.Deserialize(SaveService.PreviewMisc4(bytes,JsonSerializer.Serialize(edit,SaveJsonContext.Default.Misc4Edit)),SaveJsonContext.Default.Misc4Preview)!;
    private static byte[] Apply(byte[] bytes,Misc4Edit edit){var original=bytes.ToArray();try{var p=Preview(bytes,edit);return SaveService.EditMisc4(bytes,JsonSerializer.Serialize(p.Request,SaveJsonContext.Default.Misc4Edit));}finally{Check(bytes.SequenceEqual(original),"Misc4 original immutable");}}
    private static void Compare(byte[] bytes,Misc4Edit edit,Action<SAV4> mutate){var expected=Open(bytes);mutate(expected);var output=Apply(bytes,edit);Check(output.SequenceEqual(expected.Write().ToArray()),"Misc4 complete file parity, adjacent data and spare partition");Check(SaveService.ExportWorkingCopy(output).SequenceEqual(output),"Misc4 exact whole export");}
    private static byte[] Fixture(string game,int active)
    {
        var s=Open(File.ReadAllBytes($".tmp/pkhex-fixtures/{game}.sav"));var record=s.Records;for(int i=0;i<record.Record32;i++)record.SetRecord32(i,(uint)(i*31));for(int i=0;i<Record4.Record16;i++)record.SetRecord16(i,(ushort)(i*7));record.EndAccess();
        for(int id=0;id<80;id++)s.SetSealCount((Seal4)id,(byte)(id%99));for(int id=0;id<100;id++)s.SetAccessoryOwnedCount((Accessory4)id,(byte)(id%10));for(int id=0;id<18;id++)s.SetBackdropPosition((Backdrop4)id,(byte)((id+5)%18));
        if(s is SAV4Sinnoh sn){sn.CurrentPoketchApp=0;sn.PoketchUnlockedCount=99;for(int id=0;id<=(int)PoketchApp.Alarm_Clock;id++)sn.SetPoketchAppUnlocked((PoketchApp)id,id%2==0);sn.SetPoketchDotArtistData(Enumerable.Range(0,120).Select(i=>(byte)(i*17+9)).ToArray());}
        if(s is not SAV4DP){int offset=s is SAV4Pt?0x23000:0x26000,extra=s is SAV4Pt?0x2820:0x230C;for(int p=0;p<2;p++){var span=s.Data.Slice(p*0x40000+offset,Hall4.SIZE_USED);span.Clear();WriteUInt32LittleEndian(span,12345);var hall=new Hall4(s.Buffer.Slice(p*0x40000+offset,Hall4.SIZE_USED)){Magic=SAV4.MAGIC_JAPAN_INTL,Revision=(uint)(p+7),BlockSize=0xBA0,BlockID=1};for(int b=0;b<3;b++)for(ushort id=0;id<=493;id++)hall.SetCount(b,id,(ushort)(id+b));hall.RefreshChecksum();s.Data[p*0x40000+offset+Hall4.SIZE_USED]=0xAB;}WriteUInt32LittleEndian(s.General[extra..],12345);WriteUInt32LittleEndian(s.General[(extra+20)..],12345);s.General[extra+40]=(byte)active;}
        return s.Write().ToArray();
    }
    public static void Run()
    {
        foreach(string game in new[]{"D","Pt","HG"})foreach(int active in game=="D"?new[]{0}:new[]{0,1})
        {
            var bytes=Fixture(game,active);var original=bytes.ToArray();var c=Read(bytes);Check(original.SequenceEqual(bytes)&&c.CanEdit&&c.Rows.Select(v=>v.Key).Distinct().Count()==c.Rows.Length,"Misc4 immutable unique catalog");Check(c.Rows.Count(v=>v.Group=="seals")==80&&c.Rows.Count(v=>v.Group=="accessories")==100&&c.Backdrops!.Length==18,"Misc4 collection sizes");Check(c.Rows.Count(v=>v.Group=="records16")==77&&c.Rows.Count(v=>v.Group=="records32")== (game=="D"?44:game=="Pt"?71:72),"Misc4 exact record layouts");Check(c.HallAvailable==(game!="D"),"Misc4 active extra Hall block");
            var s=Open(bytes);var before=s.General.ToArray();Misc4Editing.Read(s,c.SourceHash);Check(before.SequenceEqual(s.General),"Misc4 record read cannot decrypt original");
            Compare(bytes,new("numbers",c.SourceHash,[new("coins",50000)]),x=>x.Coin=50000);Compare(bytes,new("numbers",c.SourceHash,[new("seal.79",99),new("accessory.99",9)]),x=>{x.SetSealCount((Seal4)79,99);x.SetAccessoryOwnedCount((Accessory4)99,9);});
            foreach(string group in new[]{"records16","records32"}){var rows=c.Rows.Where(v=>v.Group==group).ToArray();Compare(bytes,new("numbers",c.SourceHash,rows.Select(r=>new Misc4Value(r.Key,r.Maximum)).ToArray()),x=>{var r=x.Records;foreach(var row in rows){int id=int.Parse(row.Key.Split('.')[1]);if(group=="records16")r.SetRecord16(id,(ushort)row.Maximum);else r.SetRecord32(id,(uint)row.Maximum);}r.EndAccess();});}
            if(game!="D"){var ranks=c.Rows.Where(v=>v.Key.Contains(".rank.")).ToArray();Compare(bytes,new("numbers",c.SourceHash,ranks.Select(r=>new Misc4Value(r.Key,r.Maximum)).ToArray()),x=>{int start=game=="Pt"?0x696C:0x52F0;foreach(var row in ranks){var p=row.Key.Split('.');int b=int.Parse(p[2]),rank=int.Parse(p[5]);WriteInt16LittleEndian(x.General[(start+16*b+10+2*rank)..],(short)row.Maximum);}});for(int b=0;b<3;b++){int battle=b;var rows=c.Rows.Where(v=>v.Group==$"hall.{b}").ToArray();Compare(bytes,new("numbers",c.SourceHash,rows.Select(r=>new Misc4Value(r.Key,9999)).ToArray()),x=>{var h=x.GetHall()!;foreach(var row in rows)h.SetCount(battle,ushort.Parse(row.Key.Split('.')[2]),9999);h.RefreshChecksum();});}}
            foreach(string action in new[]{"all","legal","clear"})foreach(string group in new[]{"seals","accessories"})Compare(bytes,new(action,c.SourceHash,Group:group),x=>{int count=group=="seals"?(action=="legal"?77:80):(action=="legal"?99:100);for(int id=0;id<count;id++){if(group=="seals")x.SetSealCount((Seal4)id,action=="clear"?(byte)0:(byte)99);else x.SetAccessoryOwnedCount((Accessory4)id,action=="clear"?(byte)0:(byte)(id<=60?9:1));}});
            foreach(string action in new[]{"all","legal","clear","resave"})Compare(bytes,new(action,c.SourceHash,Group:"backdrops"),x=>{int[] positions=Enumerable.Repeat(18,18).ToArray();for(int id=0;id<18;id++){int pos=x.GetBackdropPosition((Backdrop4)id);if(pos<18)positions[pos]=id;}if(action=="clear")Array.Fill(positions,18);else if(action!="resave")for(int id=0;id<(action=="legal"?17:18);id++)positions[id]=id;for(int id=0;id<18;id++)x.RemoveBackdrop((Backdrop4)id);byte n=0;foreach(int id in positions)if(id<18)x.SetBackdropPosition((Backdrop4)id,n++);});
            int[] duplicate=Enumerable.Repeat(18,18).ToArray();duplicate[0]=4;duplicate[5]=4;duplicate[9]=17;Compare(bytes,new("backdrops",c.SourceHash,Backdrops:duplicate),x=>{for(int id=0;id<18;id++)x.RemoveBackdrop((Backdrop4)id);x.SetBackdropPosition((Backdrop4)4,1);x.SetBackdropPosition((Backdrop4)17,2);});
            int tower=game=="D"?0x5FCA:game=="Pt"?0x68E0:0x5264,flagAt=game=="D"?0x6601:game=="Pt"?0x723D:0x5BC1,continueAt=flagAt+(game=="D"?3:1);
            foreach(var scenario in new[]{(Old:0,Count:0,Field:"current",Input:10,Current:10,Next:1),(Old:0,Count:1,Field:"current",Input:10,Current:10,Next:1),(Old:0,Count:0,Field:"continueCount",Input:65535,Current:9999,Next:1428),(Old:9999,Count:0,Field:"continueCount",Input:65535,Current:9999,Next:65535),(Old:65000,Count:0,Field:"continueCount",Input:65535,Current:65000,Next:65535)}){var scene=Open(bytes);WriteUInt16LittleEndian(scene.General[(tower+2)..],(ushort)scenario.Old);WriteUInt16LittleEndian(scene.General[continueAt..],(ushort)scenario.Count);var input=scene.Write().ToArray();Compare(input,new("numbers",Read(input).SourceHash,[new($"bf.0.0.0.{scenario.Field}",scenario.Input)]),x=>{WriteUInt16LittleEndian(x.General[(tower+2)..],(ushort)scenario.Current);WriteUInt16LittleEndian(x.General[continueAt..],(ushort)scenario.Next);});}
            if(game!="HG")
            {
                Compare(bytes,new("all",c.SourceHash,Group:"poketch"),x=>{var sn=(SAV4Sinnoh)x;for(int id=0;id<25;id++)sn.SetPoketchAppUnlocked((PoketchApp)id);sn.PoketchUnlockedCount=25;});
                foreach(int pixel in new[]{0,3,4,479})Compare(bytes,new("dotCycle",c.SourceHash,Pixel:pixel),x=>{var sn=(SAV4Sinnoh)x;var raw=sn.GetPoketchDotArtistData();int shift=2*(pixel%4);int value=(raw[pixel/4]>>shift&3)+1;raw[pixel/4]=(byte)((raw[pixel/4]&~(3<<shift))|((value%4)<<shift));sn.SetPoketchDotArtistData(raw);});
                int[] rgb=Enumerable.Range(0,1440).Select(i=>(i/3)%2==0?0:255).ToArray();Compare(bytes,new("dotImport",c.SourceHash,Rgb:rgb,ImageSize:2058),x=>{var sn=(SAV4Sinnoh)x;var raw=sn.GetPoketchDotArtistData();for(int i=0;i<480;i++)raw[i/4]|=(byte)((i%2==0?1:0)<<(2*(i%4)));sn.SetPoketchDotArtistData(raw);});
                int[] overflowRgb=Enumerable.Range(0,1440).Select(i=>i/3<256?0:255).ToArray();Compare(bytes,new("dotImport",c.SourceHash,Rgb:overflowRgb,ImageSize:100),_=>{});
                int[] five=Enumerable.Range(0,1440).Select(i=>(i/3%5)*50).ToArray();Reject(()=>Preview(bytes,new("dotImport",c.SourceHash,Rgb:five,ImageSize:100)));
            }
            else{Compare(bytes,new("all",c.SourceHash,Group:"walker"),x=>((SAV4HGSS)x).PokewalkerCoursesUnlockAll());Compare(bytes,new("numbers",c.SourceHash,[new("athPoints",9999999)]),x=>((SAV4HGSS)x).Pokeathlon.Points=99999);}
            Misc4Edit[] invalid=[new("numbers",c.SourceHash,[]),new("numbers",c.SourceHash,[new("coins",50001)]),new("numbers",c.SourceHash,[new("coins",0),new("coins",1)]),new("numbers",c.SourceHash,[new("missing",0)]),new("all",c.SourceHash,Group:"missing"),new("all",new string('0',64),Group:"seals"),new("backdrops",c.SourceHash,Backdrops:[0]),new("dotCycle",c.SourceHash,Pixel:480)];foreach(var edit in invalid){Reject(()=>Preview(bytes,edit));var local=Open(bytes);var raw=local.Data.ToArray();Reject(()=>Misc4Editing.Prepare(local,edit,c.SourceHash));Check(raw.SequenceEqual(local.Data),"Misc4 atomic invalid request");}
            var frozen=Preview(bytes,new("numbers",c.SourceHash,[new("coins",1)])).Request;Reject(()=>SaveService.EditMisc4(bytes,JsonSerializer.Serialize(frozen with {TargetHash=new string('0',64)},SaveJsonContext.Default.Misc4Edit)));Reject(()=>SaveService.EditMisc4(bytes,JsonSerializer.Serialize(frozen with {TargetHash=null},SaveJsonContext.Default.Misc4Edit)));
            Console.WriteLine($"PASS Misc4 {game} Hall partition={active}: immutable catalog/record reads, exact collection and record sizes, every record upper limit, castle 16-bit protection, all Hall records, frozen preview, atomic requests, original and complete file parity");
        }
        Reject(()=>SaveService.ReadMisc4(File.ReadAllBytes(".tmp/pkhex-fixtures/E.sav")));
    }
}
