// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
using static System.Buffers.Binary.BinaryPrimitives;
internal static class Pokeathlon4EditingTests
{
    private static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    private static SAV4HGSS Open(byte[] data)=>SaveUtil.GetSaveFile(data.ToArray())as SAV4HGSS??throw new Exception("HGSS fixture not recognized");
    private static void Reject(Action action){try{action();throw new Exception("Invalid Pokeathlon4 request accepted");}catch(ArgumentException){}}
    private static byte[] Apply(byte[] data,Pokeathlon4Edit edit){var original=data.ToArray();try{return SaveService.EditPokeathlon4(data,JsonSerializer.Serialize(edit,SaveJsonContext.Default.Pokeathlon4Edit));}finally{Check(data.SequenceEqual(original),"Immutable source on success and rejection");}}
    private static void Compare(byte[] data,Pokeathlon4Edit edit,Action<SAV4HGSS> mutate){var expected=Open(data);mutate(expected);var output=Apply(data,edit);Check(output.SequenceEqual(expected.Write().ToArray()),"Independent whole-file oracle, checksum and untouched region");Check(SaveChecksums.Valid(Open(output))&&SaveService.ExportWorkingCopy(output).SequenceEqual(output),"Valid exact download");}
    private static void Word(SAV4HGSS s,int at,int value)=>WriteUInt16LittleEndian(s.Pokeathlon.Data[at..],(ushort)value);
    private static void DWord(SAV4HGSS s,int at,uint value)=>WriteUInt32LittleEndian(s.Pokeathlon.Data[at..],value);
    public static void Run()
    {
        foreach(var version in new[]{GameVersion.HG,GameVersion.SS})foreach(uint magic in new[]{SAV4.MAGIC_JAPAN_INTL,SAV4.MAGIC_KOREAN})
        {
            var seed=Open(File.ReadAllBytes(".tmp/pkhex-fixtures/HG.sav"));seed.Version=version;seed.Magic=magic;for(int i=-4;i<Pokeathlon4.SIZE+4;i++)seed.General[0xD9D4+i]=(byte)(i*17+91);var data=seed.Write().ToArray();var original=data.ToArray();
            var c=JsonSerializer.Deserialize(SaveService.ReadPokeathlon4(data),SaveJsonContext.Default.Pokeathlon4Catalog)!;
            Check(data.SequenceEqual(original)&&c.CanEdit&&c.Courses.Length==5&&c.Personal.Length==10&&c.Connections.Length==10&&c.Medals.Length==493&&c.Counters.Length==29&&c.Best.Length==10&&c.CardStats.Length==27,"Read-only catalog complete physical dimensions");
            Check(c.SpeciesChoices.Length==494&&c.SpeciesChoices.First().Id==0&&c.SpeciesChoices.Last().Id==493&&c.LanguageChoices.Select(v=>v.Id).Order().SequenceEqual(new[]{0,1,2,3,4,5,7,8}),"Exact source species/language candidates");Check(c.SpeciesChoices.Single(v=>v.Id==201).Forms.Length==28&&c.SpeciesChoices.Single(v=>v.Id==493).Forms.Length==18,"Gen4 form lists including question marks and Arceus curse form");
            Check(c.SpeciesChoices.SelectMany(v=>v.Forms).All(f=>!string.IsNullOrWhiteSpace(f.Name.Zh)&&!string.IsNullOrWhiteSpace(f.Name.En)&&!string.IsNullOrWhiteSpace(f.Name.Ja)),"Every default form has a localized readable label");Check(c.SpeciesChoices.Single(v=>v.Id==449).Forms[0].FemaleSprite!=c.SpeciesChoices.Single(v=>v.Id==449).Forms[0].Sprite,"Female sprite differs from male where supported");
            for(int id=0;id<40;id++){int at=id;foreach(long value in id==0?new long[]{0,99999}:new long[]{0,1})Compare(data,new("general",Values:[new(id,value)]),s=>{if(at==0)DWord(s,0xB74,(uint)value);else if(at<=12){int old=ReadUInt16LittleEndian(s.Pokeathlon.Data[0xB7C..]);Word(s,0xB7C,(old&~(1<<(at-1)))|((int)value<<(at-1)));}else{uint old=ReadUInt32LittleEndian(s.Pokeathlon.Data[0xB78..]);DWord(s,0xB78,(old&~(1u<<(at-13)))|((uint)value<<(at-13)));}});}
            for(int species=1;species<=493;species++){int at=species;int bit=species%5;Compare(data,new("medal",Index:species,Values:[new(bit,0)]),s=>s.Pokeathlon.Data[0xDC+at-1]&=(byte)~(1<<bit));Compare(data,new("medal",Index:species,Values:[new(bit,1)]),s=>s.Pokeathlon.Data[0xDC+at-1]|=(byte)(1<<bit));}
            foreach(bool all in new[]{true,false})Compare(data,new("medalsBatch",Enabled:all,SourceHash:c.SourceHash),s=>s.Pokeathlon.Data.Slice(0xDC,493).Fill(all?(byte)31:(byte)0));
            for(int id=0;id<29;id++){int at=id;long maximum=id==0?59999:id==28?65535:9999999;foreach(long value in new[]{0,maximum})Compare(data,new("counters",Values:[new(id,value)]),s=>DWord(s,0xB00+at*4,(uint)value));Reject(()=>Apply(data,new("counters",Values:[new(id,maximum+1)])));}
            for(int i=0;i<10;i++){int at=i;foreach(long value in new long[]{0,65535})Compare(data,new("best",Values:[new(i,value)]),s=>Word(s,0xAEC+at*2,(int)value));}
            for(int i=0;i<5;i++)for(int k=0;k<4;k++){int at=i*0x2C+k*2;Compare(data,new("course",Index:i,Values:[new(k,65535)]),s=>Word(s,at,65535));}
            for(int i=0;i<5;i++)for(int k=0;k<3;k++)
            {int at=i*0x2C+8+k*12;Compare(data,new("participant",Index:i,Slot:k,Pokemon:new(Species:201,Form:27,Shiny:true,Pid:uint.MaxValue,Tid:65535,Sid:0)),s=>{uint old=ReadUInt32LittleEndian(s.Pokeathlon.Data[at..]);DWord(s,at,(old&~0x13FFFu)|201u|(27u<<9)|(1u<<16));DWord(s,at+4,uint.MaxValue);Word(s,at+8,65535);Word(s,at+10,0);});foreach(int gender in new[]{0,1,2,3}){var genderSeed=Open(data);uint old=ReadUInt32LittleEndian(genderSeed.Pokeathlon.Data[at..]);DWord(genderSeed,at,(old&~0xC000u)|((uint)gender<<14));var bytes=genderSeed.Write().ToArray();if(gender<2)Compare(bytes,new("participant",Index:i,Slot:k,Pokemon:new(Gender:1-gender)),s=>DWord(s,at,(ReadUInt32LittleEndian(s.Pokeathlon.Data[at..])&~0xC000u)|((uint)(1-gender)<<14)));else Reject(()=>Apply(bytes,new("participant",Index:i,Slot:k,Pokemon:new(Gender:0))));}}
            foreach(bool connection in new[]{false,true})for(int i=0;i<10;i++)
            {
                int baseAt=(connection?0x484+i*0xA4:0x2CC+i*0x2C);Compare(data,new("attempts",Index:i,Connection:connection,Values:[new(0,9999999)]),s=>DWord(s,baseAt+0x28,9999999));
                for(int k=0;k<5;k++){int at=baseAt+k*8;Compare(data,new("record",Index:i,Slot:k,Connection:connection,Values:[new(0,65535)]),s=>Word(s,at,65535));for(int m=0;m<3;m++){int entryAt=at+2+m*2;Compare(data,new("entry",Index:i,Slot:k,Member:m,Connection:connection,Pokemon:new(Species:201,Form:27)),s=>Word(s,entryAt,201|(27<<10)));}}
            }
            for(int i=0;i<10;i++)for(int k=0;k<5;k++){int at=0x484+i*0xA4+0x2C+k*0x18;Compare(data,new("trainer",Index:i,Slot:k,Trainer:new(Name:"ABCDEFG",Tid:65535,Sid:0,Language:2)),s=>{Word(s,at,65535);Word(s,at+2,0);s.Pokeathlon.Data[at+0x14]=2;StringConverter4.SetString(s.Pokeathlon.Data.Slice(at+4,16),"ABCDEFG",7,2);});string hex=Convert.ToHexString(Enumerable.Range(0,16).Select(v=>(byte)(v+41)).ToArray());Compare(data,new("trainer",Index:i,Slot:k,Trainer:new(NameHex:hex)),s=>Convert.FromHexString(hex).CopyTo(s.Pokeathlon.Data[(at+4)..]));}
            // All form candidates must fit both storage representations and survive independently.
            foreach(var species in c.SpeciesChoices)foreach(var form in species.Forms){Compare(data,new("entry",Index:0,Slot:0,Member:0,Connection:false,Pokemon:new(Species:species.Id,Form:form.Id)),s=>Word(s,0x2CE,species.Id|(form.Id<<10)));Compare(data,new("participant",Index:0,Slot:0,Pokemon:new(Species:species.Id,Form:form.Id)),s=>DWord(s,8,(ReadUInt32LittleEndian(s.Pokeathlon.Data[8..])&~0x3FFFu)|(uint)species.Id|((uint)form.Id<<9)));}
            Pokeathlon4Edit[] invalid=[new("unknown"),new("general",Values:[]),new("general",Values:[null!]),new("general",Values:[new(null,1)]),new("general",Values:[new(0,null)]),new("general",Values:[new(0,-1)]),new("general",Values:[new(0,100000)]),new("general",Values:[new(40,1)]),new("general",Values:[new(1,2)]),new("general",Values:[new(0,1),new(0,2)]),new("general",Index:0,Values:[new(0,1)]),new("medal",Index:0,Values:[new(0,1)]),new("medal",Index:494,Values:[new(0,1)]),new("medalsBatch",Enabled:true,SourceHash:new string('0',64)),new("medalsBatch",Enabled:true),new("course",Index:5,Values:[new(0,1)]),new("best",Values:[new(10,1)]),new("participant",Index:0,Slot:3,Pokemon:new(Pid:0)),new("participant",Index:0,Slot:0,Pokemon:new(Species:494)),new("participant",Index:0,Slot:0,Pokemon:new(Species:25,Form:1)),new("participant",Index:0,Slot:0,Pokemon:new(Pid:4294967296)),new("entry",Index:0,Slot:0,Member:3,Connection:false,Pokemon:new(Species:25)),new("entry",Index:0,Slot:0,Member:0,Connection:false,Pokemon:new(Shiny:true)),new("attempts",Index:10,Connection:true,Values:[new(0,1)]),new("record",Index:0,Slot:5,Connection:true,Values:[new(0,1)]),new("trainer",Index:0,Slot:0,Trainer:new(Name:"ABCDEFGH")),new("trainer",Index:0,Slot:0,Trainer:new(Name:"A",NameHex:new string('0',32))),new("trainer",Index:0,Slot:0,Trainer:new(Language:6)),new("trainer",Index:0,Slot:0,Trainer:new(NameHex:"00")),new("trainer",Index:0,Slot:0,Trainer:new(Tid:65536))];
            foreach(var edit in invalid){Reject(()=>Apply(data,edit));var s=Open(data);var before=s.General.ToArray();Reject(()=>Pokeathlon4Editing.Apply(s,edit,c.SourceHash));Check(before.SequenceEqual(s.General),"Atomic full-request rejection");}
            var changed=Apply(data,new("general",Values:[new(0,0)]));Reject(()=>Apply(changed,new("medalsBatch",Enabled:true,SourceHash:c.SourceHash)));var corrupt=data.ToArray();corrupt[0x20]^=1;Check(!Pokeathlon4Editing.Read(Open(corrupt),PokeGear4Editing.Hash(corrupt)).CanEdit,"Checksum readonly");Reject(()=>Apply(corrupt,new("best",Values:[new(0,0)])));Reject(()=>SaveService.EditPokeathlon4(data,new string(' ',8193)));
            Console.WriteLine($"PASS Pokeathlon4 {version} magic={magic:X8}: every category/address/form, 493 medals, 29 counters, all event records and participants, trainers/raw names, reserved bits, frozen batches, full-file oracle and atomic rejection");
        }
        Reject(()=>Pokeathlon4Editing.Read(new SAV4DP(),""));Reject(()=>Pokeathlon4Editing.Read(new SAV4Pt(),""));
    }
}
