<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <StartupObject>SaveEditorTests</StartupObject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../StandalonePokemonApi.cs" Link="StandalonePokemonApi.cs" />
    <Compile Include="../StandalonePokemon.cs" Link="StandalonePokemon.cs" />
    <Compile Include="../StandaloneEgg.cs" Link="StandaloneEgg.cs" />
    <Compile Include="../StandaloneGb.cs" Link="StandaloneGb.cs" />
    <Compile Include="../PokeBlocks6.cs" Link="PokeBlocks6.cs" />
    <Compile Include="../FoodCases.cs" Link="FoodCases.cs" />
    <Compile Include="../EventReset1.cs" Link="EventReset1.cs" />
    <Compile Include="../HallOfFame1.cs" Link="HallOfFame1.cs" />
    <Compile Include="../Ferry3Editing.cs" Link="Ferry3Editing.cs" />
    <Compile Include="../Misc3Editing.cs" Link="Misc3Editing.cs" />
    <Compile Include="../SecretBase3Editing.cs" Link="SecretBase3Editing.cs" />
    <Compile Include="../PokeGear4Editing.cs" Link="PokeGear4Editing.cs" />
    <Compile Include="../Pokeathlon4Editing.cs" Link="Pokeathlon4Editing.cs" />
    <Compile Include="../BattlePass4Editing.cs" Link="BattlePass4Editing.cs" />
    <Compile Include="../BrTrainer4Editing.cs" Link="BrTrainer4Editing.cs" />
    <Compile Include="../BattleVideo4Editing.cs" Link="BattleVideo4Editing.cs" />
    <Compile Include="../Geonet4Editing.cs" Link="Geonet4Editing.cs" />
    <Compile Include="../Misc4Editing.cs" Link="Misc4Editing.cs" />
    <Compile Include="../Misc4Frontier.cs" Link="Misc4Frontier.cs" />
    <Compile Include="../Misc4DotImage.cs" Link="Misc4DotImage.cs" />
    <Compile Include="../GlobalLink5Editing.cs" Link="GlobalLink5Editing.cs" />
    <Compile Include="../Dlc5Editing.cs" Link="Dlc5Editing.cs" />
    <Compile Include="../CGear5Editing.cs" Link="CGear5Editing.cs" />
    <Compile Include="../Underground4Editing.cs" Link="Underground4Editing.cs" />
    <Compile Include="../HoneyTree4Editing.cs" Link="HoneyTree4Editing.cs" />
    <Compile Include="../Br4Editing.cs" Link="Br4Editing.cs" />
    <Compile Include="../Joyful3Editing.cs" Link="Joyful3Editing.cs" />
    <Compile Include="../Frontier3Editing.cs" Link="Frontier3Editing.cs" />
    <Compile Include="../GameRecords3.cs" Link="GameRecords3.cs" />
    <Compile Include="../Painting3Editing.cs" Link="Painting3Editing.cs" />
    <Compile Include="../Decoration3Editing.cs" Link="Decoration3Editing.cs" />
    <Compile Include="../Roamer3Editing.cs" Link="Roamer3Editing.cs" />
    <Compile Include="../HallOfFame3.cs" Link="HallOfFame3.cs" />
    <Compile Include="../GsBall2.cs" Link="GsBall2.cs" />
    <Compile Include="../EventEditing.cs" Link="EventEditing.cs" />
    <Compile Include="../RoamerEditing.cs" Link="RoamerEditing.cs" />
    <Compile Include="../RtcEditing.cs" Link="RtcEditing.cs" />
    <Compile Include="../OPowerEditing.cs" Link="OPowerEditing.cs" />
    <Compile Include="../SaveFood.cs" Link="SaveFood.cs" />
    <Compile Include="../StandaloneGbSpecial.cs" Link="StandaloneGbSpecial.cs" />
    <Compile Include="../BoxBinaryApi.cs" Link="BoxBinaryApi.cs" />
    <Compile Include="../BoxBinary.cs" Link="BoxBinary.cs" />
    <Compile Include="../BoxImportApi.cs" Link="BoxImportApi.cs" />
    <Compile Include="../BoxImportFiles.cs" Link="BoxImportFiles.cs" />
    <Compile Include="../BoxImportPreview.cs" Link="BoxImportPreview.cs" />
    <Compile Include="../BoxArchive.cs" Link="BoxArchive.cs" />
    <Compile Include="../FileBatchApi.cs" Link="FileBatchApi.cs" />
    <Compile Include="../FilePropertyBatch.cs" Link="FilePropertyBatch.cs" />
    <Compile Include="../PropertyBatch.cs" Link="PropertyBatch.cs" />
    <Compile Include="../PropertyBatchApi.cs" Link="PropertyBatchApi.cs" />
    <Compile Include="../../../third_party/pkhex/drawing/SpriteName.cs" Link="SpriteName.cs" />
    <Compile Include="../Program.cs" Link="SaveService.cs" />
    <Compile Include="../TrainerGameVersion.cs" Link="TrainerGameVersion.cs" />
    <Compile Include="../TrainerAppearance6.cs" Link="TrainerAppearance6.cs" />
    <Compile Include="../SaveChecksums.cs" Link="SaveChecksums.cs" />
    <Compile Include="../LetsGoPokedex.cs" Link="LetsGoPokedex.cs" />
    <Compile Include="../LetsGoCapture.cs" Link="LetsGoCapture.cs" />
    <Compile Include="../BdspPokedex.cs" Link="BdspPokedex.cs" />
    <Compile Include="../SwshPokedex.cs" Link="SwshPokedex.cs" />
    <Compile Include="../ZaPokedex.cs" Link="ZaPokedex.cs" />
    <Compile Include="../SvPokedex.cs" Link="SvPokedex.cs" />
    <Compile Include="../LegendsPokedex.cs" Link="LegendsPokedex.cs" />
    <Compile Include="../Gen7Pokedex.cs" Link="Gen7Pokedex.cs" />
    <Compile Include="../Gen6Pokedex.cs" Link="Gen6Pokedex.cs" />
    <Compile Include="../Gen5Pokedex.cs" Link="Gen5Pokedex.cs" />
    <Compile Include="../Gen4Pokedex.cs" Link="Gen4Pokedex.cs" />
    <Compile Include="../SimplePokedex.cs" Link="SimplePokedex.cs" />
    <Compile Include="../TrainerEditing.cs" Link="TrainerEditing.cs" />
    <Compile Include="../TrainerBadges.cs" Link="TrainerBadges.cs" />
    <Compile Include="../TrainerCurrencies.cs" Link="TrainerCurrencies.cs" />
    <Compile Include="../TrainerGameOptions.cs" Link="TrainerGameOptions.cs" />
    <Compile Include="../TrainerDates.cs" Link="TrainerDates.cs" />
    <Compile Include="../TrainerSpatialPosition.cs" Link="TrainerSpatialPosition.cs" />
    <Compile Include="../TrainerPosition.cs" Link="TrainerPosition.cs" />
    <Compile Include="../SaveRecords.cs" Link="SaveRecords.cs" />
    <Compile Include="../ApricornInventory.cs" Link="ApricornInventory.cs" />
    <Compile Include="../InventoryReader.cs" Link="InventoryReader.cs" />
    <Compile Include="../InventoryEditing.cs" Link="InventoryEditing.cs" />
    <Compile Include="../InventoryBatch.cs" Link="InventoryBatch.cs" />
    <Compile Include="../PokemonLegality.cs" Link="PokemonLegality.cs" />
    <Compile Include="../BoxEditing.cs" Link="BoxEditing.cs" />
    <Compile Include="../BoxBatch.cs" Link="BoxBatch.cs" />
    <Compile Include="../StorageEditing.cs" Link="StorageEditing.cs" />
    <Compile Include="../PokemonFiles.cs" Link="PokemonFiles.cs" />
    <Compile Include="../PokemonEditing.cs" Link="PokemonEditing.cs" />
    <Compile Include="../PokemonIdentity.cs" Link="PokemonIdentity.cs" />
    <Compile Include="../PokemonRawEditing.cs" Link="PokemonRawEditing.cs" />
    <Compile Include="../PokemonTraining.cs" Link="PokemonTraining.cs" />
    <Compile Include="../PokemonHistory.cs" Link="PokemonHistory.cs" />
    <Compile Include="../PokemonCare.cs" Link="PokemonCare.cs" />
    <Compile Include="../PokemonMemories.cs" Link="PokemonMemories.cs" />
    <Compile Include="../PokemonRibbons.cs" Link="PokemonRibbons.cs" />
    <Compile Include="../PokemonRibbonFields.cs" Link="PokemonRibbonFields.cs" />
    <Compile Include="../PokemonRelearn.cs" Link="PokemonRelearn.cs" />
    <Compile Include="../PokemonShiny.cs" Link="PokemonShiny.cs" />
    <Compile Include="../PokemonEgg.cs" Link="PokemonEgg.cs" />
    <Compile Include="../PokemonOrigin.cs" Link="PokemonOrigin.cs" />
    <Compile Include="../PokemonEncounter.cs" Link="PokemonEncounter.cs" />
    <Compile Include="../PokemonFormArgument.cs" Link="PokemonFormArgument.cs" />
    <Compile Include="../PokemonReader.cs" Link="PokemonReader.cs" />
    <Compile Include="../BrowserCryptography.cs" Link="BrowserCryptography.cs" />
    <ProjectReference Include="../../../third_party/pkhex/PKHeX.Core/PKHeX.Core.csproj" />
  </ItemGroup>
</Project>
