// SPDX-License-Identifier: GPL-3.0-or-later
using System.ComponentModel;
using System.Reflection;
using System.Text.Json;
using System.Buffers.Binary;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
internal static class SecretBase6EditingTests
{
    private static void Check(bool condition,string message){if(!condition)throw new Exception(message);}
    private static void Reject(Action action){try{action();throw new Exception("Invalid SecretBase6 request accepted");}catch(ArgumentException){}}
    private static SAV6AO Open(byte[] data)=>(SAV6AO)SaveUtil.GetSaveFile(data.ToArray())!;
    private static Sb6Catalog Read(byte[] data)=>JsonSerializer.Deserialize(SaveService.ReadSecretBase6(data),SaveJsonContext.Default.Sb6Catalog)!;
    private static string Json(Sb6Edit e)=>JsonSerializer.Serialize(e,SaveJsonContext.Default.Sb6Edit);
    private static Sb6Preview Preview(byte[] data,Sb6Edit e)=>JsonSerializer.Deserialize(SaveService.PreviewSecretBase6(data,Json(e)),SaveJsonContext.Default.Sb6Preview)!;
    private static byte[] Apply(byte[] data,Sb6Edit e){var before=data.ToArray();var p=Preview(data,e);var output=SaveService.EditSecretBase6(data,Json(p.Request));Check(data.SequenceEqual(before),"SecretBase6 immutable source");Check(p.Request.TargetHash==Br4Editing.Hash(output)&&p.Result.SourceHash==p.Request.TargetHash,"SecretBase6 frozen complete target");Check(p.ChangedOffsets.SequenceEqual(Enumerable.Range(0,data.Length).Where(i=>data[i]!=output[i])),"SecretBase6 full-file change offsets");Check(SaveService.ExportWorkingCopy(output).SequenceEqual(output),"SecretBase6 complete export");return output;}
    private static byte[] Compare(byte[] data,Sb6Edit e,Action<SAV6AO> oracle){var expected=Open(data);oracle(expected);var output=Apply(data,e);Check(output.SequenceEqual(expected.Write().ToArray()),"SecretBase6 independent complete-file oracle: "+e.Action);return output;}
    private static SecretBase6 Target(SAV6AO s,int index)=>index==0?s.SecretBase.GetSecretBaseSelf():s.SecretBase.GetSecretBaseOther(index-1);
    private static SecretBase6PKM LegalPokemon(){var p=new SecretBase6PKM();p.Data.Fill(0xA6);p.Species=25;p.Form=0;p.Gender=0;p.Ability=9;p.AbilityNumber=0;p.Nature=0;p.Ball=4;p.HeldItem=0;p.Move1=p.Move2=p.Move3=p.Move4=33;p.Move1_PPUps=p.Move2_PPUps=p.Move3_PPUps=p.Move4_PPUps=3;p.IV_HP=p.IV_ATK=p.IV_DEF=p.IV_SPA=p.IV_SPE=p.IV_SPD=31;p.EV_HP=p.EV_ATK=p.EV_DEF=p.EV_SPA=p.EV_SPE=p.EV_SPD=252;p.CurrentLevel=255;p.CurrentFriendship=255;return p;}
    public static void Run()
    {
        foreach(var version in new[]{GameVersion.OR,GameVersion.AS}){
            var s=Open(File.ReadAllBytes(".tmp/pkhex-fixtures/OR.sav"));s.Version=version;s.SecretBase.Data.Fill(0xA6);s.Records.SetRecord(80,0);
            for(int i=0;i<31;i++){var b=Target(s,i);b.BaseLocation=3+i;b.TrainerName="Base"+i;for(int j=0;j<28;j++){var p=b.GetPlacement(j);p.Good=(ushort)(i+j);p.X=(ushort)(100+i);p.Y=(ushort)(200+j);p.Rotation=(byte)j;}if(b is SecretBase6Other o)for(int j=0;j<3;j++)o.SetParticipant(j,LegalPokemon());}
            var data=s.Write().ToArray();var original=data.ToArray();var c=Read(data);
            Check(c.CanEdit&&c.Bases.Length==31&&c.Stock.Length==200&&c.Bases[0].Pokemon.Length==0&&c.Bases.Skip(1).All(x=>x.Pokemon.Length==3&&x.Placements.Length==28),"SecretBase6 full physical catalog");
            for(int i=0;i<31;i++){var b=Target(Open(data),i);var publicWritable=b.GetType().GetProperties(BindingFlags.Public|BindingFlags.Instance).Where(p=>p.CanRead&&p.CanWrite).Select(p=>p.Name).Order().ToArray();Check(publicWritable.SequenceEqual(c.Bases[i].Properties.Select(x=>x.Id).Order()),"SecretBase6 complete source PropertyGrid coverage");}
            var scalarValues=new Dictionary<string,string>{["IsNew"]="1",["BaseLocation"]="86",["BoppoyamaScore"]="0xFF",["TrainerName"]="ABCDEFGHIJKLMNOP",["TeamName"]="ABCDEFGHIJKLMNOPQRST",["TeamSlogan"]="Slogan",["SayHappy"]="Happy",["SayEncourage"]="Encourage",["SayBlackboard"]="Board",["SayConfettiBall"]="Confetti",["Rank"]="Gold",["TotalFlagsFromFriends"]="0xFFFFFFFF",["TotalFlagsFromOther"]="4294967295",["CollectedFlagsToday"]="255",["CollectedFlagsYesterday"]="0"};
            for(int i=0;i<31;i++){var fields=scalarValues.Select(v=>new Sb6Value(v.Key,v.Value)).ToList();if(i>0){fields.Add(new("Language","255"));fields.Add(new("Gender","255"));}int index=i;Compare(data,new("property",c.SourceHash,i,Fields:fields.ToArray()),x=>{var b=Target(x,index);foreach(var f in fields){var p=b.GetType().GetProperty(f.Id)!;object? value=p.PropertyType==typeof(bool)?f.Value=="1":TypeDescriptor.GetConverter(p.PropertyType).ConvertFromInvariantString(f.Value!);p.SetValue(b,value);}});}
            foreach(int value in new[]{int.MinValue,-1,0,1,2,85,86,int.MaxValue})Compare(data,new("property",c.SourceHash,0,Fields:[new("BaseLocation",value.ToString())]),x=>Target(x,0).BaseLocation=value);
            for(int i=0;i<31;i++)for(int j=0;j<28;j++){int index=i,slot=j;Compare(data,new("placement",c.SourceHash,i,j,Fields:[new("Good","-1"),new("X","65535"),new("Y","0"),new("Rotation","255")]),x=>{var b=Target(x,index);var span=b.Data.Slice(4+slot*12,12);BinaryPrimitives.WriteUInt16LittleEndian(span,65535);BinaryPrimitives.WriteUInt16LittleEndian(span[2..],65535);BinaryPrimitives.WriteUInt16LittleEndian(span[4..],0);span[6]=255;});}
            for(int i=1;i<31;i++)for(int j=0;j<3;j++){int index=i,member=j;Compare(data,new("member",c.SourceHash,i,Member:j,Fields:[new("Ec","x12!AB"),new("IV_HP","99"),new("EV_HP","999"),new("PP1","0"),new("Level","0"),new("Friendship","0"),new("Shiny","0")]),x=>{var o=(SecretBase6Other)Target(x,index);var p=o.GetParticipant(member);BinaryPrimitives.WriteUInt32LittleEndian(p.Data,0x12AB);p.Data[0x28]=3;p.Data[0x16]=252;p.Data[0x24]=0;p.Data[0x30]=0;p.Data[0x2E]=0;p.Data[0x2D]&=0xDF;o.SetParticipant(member,p);});}
            foreach(bool maximum in new[]{false,true}){
                int item=(maximum?c.Items.Last():c.Items.First()).Id,move=(maximum?c.Moves.Last():c.Moves.First()).Id,ball=(maximum?c.Balls.Last():c.Balls.First()).Id,nature=(maximum?c.Natures.Last():c.Natures.First()).Id,slot=maximum?2:0,gender=maximum?1:0,baseIndex=maximum?30:1,member=maximum?2:0;
                var all=new List<Sb6Value>{new("Ec",maximum?"FFFFFFFF":""),new("Species","25"),new("Form","0"),new("Gender",gender.ToString()),new("AbilitySlot",slot.ToString()),new("HeldItem",item.ToString()),new("Nature",nature.ToString()),new("Ball",ball.ToString()),new("Level",maximum?"255":"0"),new("Friendship",maximum?"255":"0"),new("Shiny",maximum?"1":"0")};
                for(int i=0;i<4;i++){all.Add(new($"Move{i+1}",move.ToString()));all.Add(new($"PP{i+1}",maximum?"3":"0"));}string[] names=["HP","ATK","DEF","SPE","SPA","SPD"];foreach(string stat in names){all.Add(new("IV_"+stat,maximum?"99":"0"));all.Add(new("EV_"+stat,maximum?"999":"0"));}
                Compare(data,new("member",c.SourceHash,baseIndex,Member:member,Fields:all.ToArray()),x=>{var o=(SecretBase6Other)Target(x,baseIndex);var p=o.GetParticipant(member);var b=p.Data;BinaryPrimitives.WriteUInt32LittleEndian(b,maximum?uint.MaxValue:0);BinaryPrimitives.WriteUInt16LittleEndian(b[8..],25);BinaryPrimitives.WriteUInt16LittleEndian(b[10..],(ushort)item);b[12]=(byte)PersonalTable.AO.GetFormEntry(25,0).GetAbilityAtIndex(slot);b[13]=(byte)(slot<<1);b[0x14]=(byte)nature;b[0x15]=(byte)((b[0x15]&1)|(gender<<1));for(int i=0;i<6;i++){b[0x16+i]=(byte)(maximum?252:0);if(i<5)b[0x28+i]=(byte)(maximum?3:0);else b[0x2D]=(byte)((b[0x2D]&0xE0)|(maximum?3:0));}for(int i=0;i<4;i++){BinaryPrimitives.WriteUInt16LittleEndian(b[(0x1C+i*2)..],(ushort)move);b[0x24+i]=(byte)(maximum?3:0);}b[0x2D]=(byte)((b[0x2D]&0xDF)|(maximum?0x20:0));b[0x2E]=(byte)(maximum?255:0);b[0x2F]=(byte)ball;b[0x30]=(byte)(maximum?255:0);o.SetParticipant(member,p);});
            }
            Compare(data,new("member",c.SourceHash,1,Member:0,Fields:[new("Species","678"),new("Form","1"),new("Gender","0"),new("AbilitySlot","1")]),x=>{var o=x.SecretBase.GetSecretBaseOther(0);var p=o.GetParticipant(0);p.Species=678;p.Form=1;p.Gender=1;p.Ability=PersonalTable.AO.GetFormEntry(678,1).GetAbilityAtIndex(1);p.AbilityNumber=2;o.SetParticipant(0,p);});
            foreach(uint value in new[]{0u,999999999u,1000000000u,2147483647u,2147483648u,uint.MaxValue})Compare(data,new("record",c.SourceHash,CapturedRecord:value.ToString()),x=>{int signed=unchecked((int)value);BinaryPrimitives.WriteInt32LittleEndian(x.Records.Data[(80*4)..],Math.Min(signed,999999999));});
            var negative=Open(data);BinaryPrimitives.WriteInt32LittleEndian(negative.Records.Data[(80*4)..],-1);var nd=negative.Write().ToArray();var nc=Read(nd);Check(nc.CapturedRecord==-1&&nc.RawCapturedRecord==uint.MaxValue,"SecretBase6 raw signed record readable");Reject(()=>Preview(nd,new("resave",nc.SourceHash,0,0)));Check(SaveService.ExportSecretBase6(nd,Json(new("export",nc.SourceHash,0,0))).Length==0x310,"SecretBase6 source export does not submit captured record");
            Compare(data,new("goods",c.SourceHash),x=>{for(int i=0;i<173;i++)BinaryPrimitives.WriteUInt32LittleEndian(x.SecretBase.Data[(i*4)..],25u|(1u<<16));});
            for(int i=1;i<=30;i++){int index=i;Compare(data,new("delete",c.SourceHash,i),x=>{int offset=0x638+(index-1)*0x3E0,length=(30-index)*0x3E0;x.SecretBase.Data.Slice(offset+0x3E0,length).CopyTo(x.SecretBase.Data.Slice(offset,length));x.SecretBase.Data.Slice(0x638+29*0x3E0,0x3E0).Clear();});}
            foreach(int size in new[]{0x310,0x3E0})foreach(int index in new[]{0,1,30}){var file=Enumerable.Repeat((byte)0x35,size).ToArray();Compare(data,new("import",c.SourceHash,index,DataBase64:Convert.ToBase64String(file)),x=>file.AsSpan(0,index==0?0x310:size).CopyTo(Target(x,index).Data));}
            var fieldsPatch=new Sb6Value[]{new("Species","29"),new("Form","0"),new("AbilitySlot","2"),new("Gender","0")};Compare(data,new("member",c.SourceHash,1,Member:0,Fields:fieldsPatch),x=>{var o=x.SecretBase.GetSecretBaseOther(0);var p=o.GetParticipant(0);p.Species=29;p.Form=0;p.Gender=1;var pi=PersonalTable.AO.GetFormEntry(29,0);p.Ability=pi.GetAbilityAtIndex(2);p.AbilityNumber=4;o.SetParticipant(0,p);});
            var odd=Open(data);var ob=odd.SecretBase.GetSecretBaseOther(0);var op=ob.GetParticipant(0);op.IV_HP=255;op.EV_HP=255;op.HeldItem=60000;op.Move1=60000;op.AbilityNumber=255;op.Gender=3;ob.SetParticipant(0,op);var old=odd.Write().ToArray();var oc=Read(old);
            Compare(old,new("member",oc.SourceHash,1,Member:0,Fields:[new("Species","29")]),x=>{var o=x.SecretBase.GetSecretBaseOther(0);var p=o.GetParticipant(0);p.Species=29;p.Form=0;p.Gender=1;p.Ability=PersonalTable.AO.GetFormEntry(29,0).GetAbilityAtIndex(0);p.AbilityNumber=0;o.SetParticipant(0,p);});
            void ResaveOracle(SAV6AO x){var o=x.SecretBase.GetSecretBaseOther(0);var p=o.GetParticipant(0);p.IV_HP=25;p.EV_HP=252;p.HeldItem=65535;p.Move1=65535;p.Ability=9;p.AbilityNumber=0;p.Gender=0;o.SetParticipant(0,p);}
            var resaved=Compare(old,new("resave",oc.SourceHash,1,0,0),ResaveOracle);var exportOriginal=old.ToArray();var fileOut=SaveService.ExportSecretBase6(old,Json(new("export",oc.SourceHash,1,0,0)));Check(fileOut.SequenceEqual(Target(Open(resaved),1).Data.ToArray())&&old.SequenceEqual(exportOriginal),"SecretBase6 source Export SaveCurrent without mutating working copy");
            var badPP=Open(data);var badPk=badPP.SecretBase.GetSecretBaseOther(0).GetParticipant(0);badPk.Move1_PPUps=4;badPP.SecretBase.GetSecretBaseOther(0).SetParticipant(0,badPk);var invalid=badPP.Write().ToArray();var ic=Read(invalid);Check(ic.Bases[1].Pokemon[0].Fields.Single(x=>x.Id=="PP1").Value=="4","SecretBase6 abnormal old PP readable");Reject(()=>Preview(invalid,new("resave",ic.SourceHash,1,0,0)));
            foreach(var e in new Sb6Edit[]{new("delete",c.SourceHash,0),new("property",c.SourceHash,0,Fields:[new("Language","1")]),new("property",c.SourceHash,0,Fields:[new("IsEmpty","1")]),new("placement",c.SourceHash,0,28,Fields:[new("X","0")]),new("placement",c.SourceHash,0,0,Fields:[new("Param1","0")]),new("member",c.SourceHash,0,Member:0,Fields:[new("Level","1")]),new("member",c.SourceHash,1,Member:3,Fields:[new("Level","1")]),new("member",c.SourceHash,1,Member:0,Fields:[new("IsEgg","1")]),new("member",c.SourceHash,1,Member:0,Fields:[new("IV_HP","")]),new("member",c.SourceHash,1,Member:0,Fields:[new("Level","256")]),new("member",c.SourceHash,1,Member:0,Fields:[new("PP1","4")]),new("record",c.SourceHash,CapturedRecord:"4294967296"),new("import",c.SourceHash,0,DataBase64:Convert.ToBase64String(new byte[785])),new("goods",c.SourceHash,0),new("property",c.SourceHash,0,Fields:[new("Rank","invalid")]),new("property",c.SourceHash,0,Fields:[new("Gender","1"),new("Gender","0")]),new("record",new string('0',64),CapturedRecord:"0")})Reject(()=>Preview(data,e));
            var good=new Sb6Edit("property",c.SourceHash,0,Fields:[new("BoppoyamaScore","0")]);Reject(()=>SaveService.EditSecretBase6(data,Json(good)));var frozen=Preview(data,good).Request;Reject(()=>SaveService.EditSecretBase6(data,Json(frozen with{TargetHash=new string('0',64)})));Check(data.SequenceEqual(original),"SecretBase6 all read/edit/rejections preserve original");
            Console.WriteLine($"PASS {version}: all 31 bases/28 placements/90 members, complete public PropertyGrid/type conversion, source numeric masks and side effects, six flag boundaries, 173 goods, all deletions/sb6 layouts, source export, whole-file frozen oracles and atomic rejection");
        }
        Reject(()=>SaveService.ReadSecretBase6(File.ReadAllBytes(".tmp/pkhex-fixtures/X.sav")));
    }
}
