// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using System.Buffers.Binary;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
internal static class Trainer6DemoTests
{
    private static void Check(bool value,string message){if(!value)throw new Exception(message);}
    private static void Reject(Action action){try{action();throw new Exception("Invalid demo edit accepted");}catch(ArgumentException){}}
    private static SAV6AODemo Open(byte[] bytes)=>(SAV6AODemo)SaveUtil.GetSaveFile(bytes.ToArray())!;
    private static string Json(Tr6Edit e)=>JsonSerializer.Serialize(e,SaveJsonContext.Default.Tr6Edit);
    private static Tr6Catalog Read(byte[] bytes)=>JsonSerializer.Deserialize(SaveService.ReadTrainer6(bytes),SaveJsonContext.Default.Tr6Catalog)!;
    private static byte[] Apply(byte[] bytes,Tr6Edit edit){var original=bytes.ToArray();var preview=JsonSerializer.Deserialize(SaveService.PreviewTrainer6(bytes,Json(edit)),SaveJsonContext.Default.Tr6Preview)!;var output=SaveService.EditTrainer6(bytes,Json(preview.Request));Check(bytes.SequenceEqual(original),"Demo original immutable");Check(preview.Request.TargetHash==Br4Editing.Hash(output)&&preview.Result.SourceHash==preview.Request.TargetHash,"Demo frozen full hash");Check(preview.ChangedOffsets.SequenceEqual(Enumerable.Range(0,bytes.Length).Where(i=>bytes[i]!=output[i])),"Demo exact changed addresses");Check(SaveService.ExportWorkingCopy(output).SequenceEqual(output),"Demo exact working copy export");return output;}
    private static byte[] Compare(byte[] bytes,Tr6Edit edit,Action<SAV6AODemo> oracle){var expected=Open(bytes);oracle(expected);var output=Apply(bytes,edit);Check(output.SequenceEqual(expected.Write().ToArray()),"Demo complete source output parity: "+edit.Action);return output;}
    public static void Run()
    {
        foreach(var version in new[]{GameVersion.OR,GameVersion.AS})foreach(byte gender in new byte[]{0,1}){
            // Synthetic demo layout: real 0x5A00 size, sixteen source blocks, BEEF marker and Core checksums.
            var s=new SAV6AODemo();s.Version=version;s.Gender=gender;s.Language=2;s.Country=0;s.Region=0;s.ConsoleRegion=1;s.OT="Demo";s.TID16=123;s.SID16=456;s.Money=12345;s.BP=23;s.Badges=85;s.Vivillon=0;s.Situation.M=3;s.Situation.R=2;s.Situation.X=18;s.Situation.Y=36;s.Situation.Z=-18;s.Situation.Style=215;s.SecondsToStart=0;s.SecondsToFame=0;s.PlayedHours=12;s.PlayedMinutes=34;s.PlayedSeconds=56;s.Played.LastSavedDate=new(2025,6,7,8,9,0);s.Status.Saying1="One";s.Status.Saying2="Two";s.Status.Saying3="Three";s.Status.Saying4="Four";s.Status.Saying5="Five";s.Status.Data[0x14A]=0xA7;s.Status.Data[6]=201;s.Status.Data[7]=202;s.Overworld.Data[0]=0x43;BinaryPrimitives.WriteUInt16LittleEndian(s.Overworld.Data[8..],999);BinaryPrimitives.WriteUInt32LittleEndian(s.Data[(s.Data.Length-0x1F0)..],0x42454546);
            var pikachu=new PK6{Species=25,Version=version,Language=2,OriginalTrainerName="Demo",TID16=123,SID16=456,Nickname="Pika",Gender=0,EXP=1000};pikachu.RefreshChecksum();s.SetPartySlotAtIndex(pikachu,0);var bytes=s.Write().ToArray();var original=bytes.ToArray();Check(bytes.Length==0x5A00&&Open(bytes).ChecksumsValid,"Demo genuine parser and all block CRCs");
            var report=JsonSerializer.Deserialize(SaveService.Inspect(bytes),SaveJsonContext.Default.SaveReport)!;Check(report.Format=="SAV6AODemo"&&!report.CanEdit&&report.TrainerOnly,"Demo dedicated capability does not unlock generic edits");Check(report.BoxCount==0&&report.Boxes.Length==0&&!report.BoxOptions.CanSwap&&!report.BoxOptions.CanName&&report.BoxOptions.BatchActions.Length==0,"Demo actual no-box capability, no ghost boxes or batch actions");Check(report.PartyCount==1&&report.Pokemon.Single().Species==25&&report.Pokemon[0].Box==-1,"Demo party Pokemon still readable with artwork");Check(report.Trainer.CanGender&&report.Trainer.CanPlayTime&&report.Trainer.Geography is not null&&report.Trainer.Languages.Length>0&&report.Trainer.Badges is not null&&report.Trainer.Currencies.Length==2&&report.Trainer.CanRecords,"Demo visible basic source controls");
            var c=Read(bytes);Check(c.CanEdit&&c.Fields.Length==1&&c.Fields[0].Key=="Vivillon"&&c.Position.CanEdit,"Demo source removes Multiplayer and Maison, retains Overview Vivillon");
            foreach(var choice in c.Fields[0].Choices)Compare(bytes,new("patch",c.SourceHash,[new("Vivillon",choice.Id.ToString())]),copy=>copy.Vivillon=choice.Id);
            Compare(bytes,new("position",c.SourceHash,[new("x","12.3456789")],UiLanguage:"zh"),copy=>{var p=copy.Situation;p.M=3;p.X=(float)(12.3456789m*18);p.Z=-18;p.Y=36;p.R=2;});
            Compare(bytes,new("trash",c.SourceHash,Trash:new("text",Text:"")),copy=>copy.SetString(copy.Status.OriginalTrainerTrash,"",0,StringConverterOption.None));
            Compare(bytes,new("resave",c.SourceHash),copy=>{copy.Overworld.ResetPlayerModel();copy.Region=255;copy.Status.Saying1=copy.Status.Saying1;copy.Status.Saying2=copy.Status.Saying2;copy.Status.Saying3=copy.Status.Saying3;copy.Status.Saying4=copy.Status.Saying4;copy.Status.Saying5=copy.Status.Saying5;copy.SetRecord(64,copy.GetRecord(63));});
            var trainer=new TrainerEdit("",321,654,76543,Gender:1-gender,Hours:65535,Minutes:99,Seconds:99,Badges:255,Currencies:new(Bp:9999,PokeMiles:1234567));var expected=Open(bytes);expected.OT="";expected.TID16=321;expected.SID16=654;expected.Money=76543;expected.Gender=(byte)(1-gender);expected.PlayedHours=65535;expected.PlayedMinutes=39;expected.PlayedSeconds=39;expected.Badges=255;expected.BP=9999;expected.SetRecord(63,1234567);expected.SetRecord(64,1234567);var edited=SaveService.Export(bytes,JsonSerializer.Serialize(trainer,SaveJsonContext.Default.TrainerEdit));Check(edited.SequenceEqual(expected.Write().ToArray()),"Demo basic trainer source addresses and full export");
            var recordExpected=Open(bytes);recordExpected.SetRecord(2,123456);var recordBytes=SaveService.EditRecord(bytes,JsonSerializer.Serialize(new SaveRecordEdit(2,123456),SaveJsonContext.Default.SaveRecordEdit));Check(recordBytes.SequenceEqual(recordExpected.Write().ToArray()),"Demo source trainer stats edit and CRCs");
            foreach(string key in new[]{"Mega","Rayquaza","Sprite","Saying0","Maison0","Style","Rank","Appearance.Version"})Reject(()=>Apply(bytes,new("patch",c.SourceHash,[new(key,"0")])));Reject(()=>Apply(bytes,new("accessories",c.SourceHash)));Reject(()=>SaveService.EditPokemon(bytes,"{}"));Reject(()=>SaveService.EditBox(bytes,"{}"));Reject(()=>SaveService.EditInventory(bytes,"{}"));var corrupt=bytes.ToArray();corrupt[0]^=1;Check(!Read(corrupt).CanEdit,"Demo invalid checksum read-only");Reject(()=>SaveService.ExportWorkingCopy(corrupt));Check(bytes.SequenceEqual(original),"Demo all reads/rejections preserve original");Console.WriteLine($"PASS ORAS demo {version}/gender={gender}: actual party/no boxes, dedicated capabilities, visible/hidden source fields, trainer/records/position/trash/full-window parity and immutable frozen export");
        }
    }
}
