// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using System.ComponentModel;
using System.Globalization;
using System.Buffers.Binary;
using PKHeX.Core;
using PokeRNGKit.SaveEditor;
internal static class Trainer6EditingTests
{
    private static void Check(bool ok,string message){if(!ok)throw new Exception(message);}
    private static void Reject(Action a){try{a();throw new Exception("Invalid Trainer6 input accepted");}catch(ArgumentException){}}
    private static SAV6 Open(byte[] d)=>(SAV6)SaveUtil.GetSaveFile(d.ToArray())!;
    private static string Json(Tr6Edit e)=>JsonSerializer.Serialize(e,SaveJsonContext.Default.Tr6Edit);
    private static Tr6Catalog Read(byte[] d)=>JsonSerializer.Deserialize(SaveService.ReadTrainer6(d),SaveJsonContext.Default.Tr6Catalog)!;
    private static Tr6Preview Preview(byte[] d,Tr6Edit e)=>JsonSerializer.Deserialize(SaveService.PreviewTrainer6(d,Json(e)),SaveJsonContext.Default.Tr6Preview)!;
    private static byte[] Apply(byte[] d,Tr6Edit e){var old=d.ToArray();var p=Preview(d,e);var output=SaveService.EditTrainer6(d,Json(p.Request));Check(d.SequenceEqual(old),"Trainer6 immutable original");Check(p.Request.TargetHash==Br4Editing.Hash(output)&&p.Result.SourceHash==p.Request.TargetHash,"Trainer6 frozen full hash");Check(p.ChangedOffsets.SequenceEqual(Enumerable.Range(0,d.Length).Where(i=>d[i]!=output[i])),"Trainer6 exact changed addresses");Check(SaveService.ExportWorkingCopy(output).SequenceEqual(output),"Trainer6 complete export");return output;}
    private static byte[] Compare(byte[] d,Tr6Edit e,Action<SAV6> oracle){var expected=Open(d);oracle(expected);var output=Apply(d,e);var expectedBytes=expected.Write().ToArray();Check(output.SequenceEqual(expectedBytes),"Trainer6 independent whole-file oracle: "+e.Action+" "+string.Join(",",Enumerable.Range(0,output.Length).Where(i=>output[i]!=expectedBytes[i]).Take(32).Select(i=>$"{i:X}:{output[i]:X2}/{expectedBytes[i]:X2}")));return output;}
    private static MaisonBlock Maison(SAV6 s)=>((ISaveBlock6Main)s).Maison;
    private static int MaskPrefix(int n,int width){var provider=new MaskedTextProvider(new string('0',width),CultureInfo.InvariantCulture);int pos=0;foreach(char c in n.ToString(CultureInfo.InvariantCulture)){int at=provider.FindEditPositionFrom(pos,true);if(at<0)continue;if(provider.Replace(c,at))pos=at+1;}return int.Parse(provider.ToString(),CultureInfo.InvariantCulture);}
    private static byte[] Seed(string version){var s=Open(File.ReadAllBytes(".tmp/pkhex-fixtures/"+(version is "X" or "Y"?"X":"OR")+".sav"));s.Version=Enum.Parse<GameVersion>(version);s.Gender=1;s.OT="A";s.Country=0;s.Region=0;s.ConsoleRegion=1;s.Language=2;s.Vivillon=0;s.BP=65535;s.Money=uint.MaxValue;s.PlayedMinutes=255;s.PlayedSeconds=199;s.SecondsToStart=0;s.SecondsToFame=0;s.Played.LastSavedDate=new(2025,6,7,8,9,59);s.Situation.M=12;s.Situation.R=2;s.Situation.X=18;s.Situation.Y=36;s.Situation.Z=-18;s.Situation.Style=255;s.Overworld.Data.Clear();s.Overworld.Data[0]=0x43;BinaryPrimitives.WriteUInt16LittleEndian(s.Overworld.Data[8..],999);s.Status.Data[6]=255;s.Status.Data[7]=213;s.Status.Data[0x14A]=0xFE;s.Status.Saying1="Old";s.Status.Saying2="Two";s.Status.Saying3="Three";s.Status.Saying4="Four";s.Status.Saying5="Five";s.Status.Data.Slice(0x48+4,22).Fill(0xA5);s.Status.Data.Slice(0x7C+8,26).Fill(0xA5);for(int i=0;i<20;i++)Maison(s).SetMaisonStat(i,(ushort)(65000+i));BinaryPrimitives.WriteInt32LittleEndian(s.Records.Data[s.GetRecordOffset(63)..],123456789);BinaryPrimitives.WriteInt32LittleEndian(s.Records.Data[s.GetRecordOffset(64)..],987654321);if(s is SAV6XY xy){xy.SUBE.SetChateau(15,4095);xy.Status.Nickname="Nick";xy.Status.Data.Slice(0x62+10,16).Fill(0xA5);}return s.Write().ToArray();}
    public static void Run()
    {
        Check(MaskPrefix(65535,4)==6553&&MaskPrefix(-1234567,4)==1234&&MaskPrefix(255,2)==25,"Trainer6 framework mask replacement prefix");
        foreach(string version in new[]{"X","Y","OR","AS"})
        {
            var data=Seed(version);var original=data.ToArray();var c=Read(data);var seed=Open(data);Check(c.Fields.Length==(seed is SAV6XY?31+((SAV6XY)seed).Status.Fashion.GetType().GetProperties().Length:29)&&c.NameTrash.Length==52&&c.PlayerModel==999,"Trainer6 complete catalog");var sprite=c.Fields.Single(v=>v.Key=="Sprite");Check(sprite.Value=="255"&&c.Sprite=="tr_255","Trainer6 unknown sprite readable");Check(sprite.Choices.Length==(seed is SAV6XY?36:73),"Trainer6 source enum prefix count");if(seed is SAV6XY)Check(sprite.Choices[^1].Id==37,"Trainer6 XY prefix includes Brendan");Check(c.Fields.Where(v=>v.Key.StartsWith("Maison")).Count()==20&&c.Fields.Where(v=>v.Kind=="text").All(v=>v.MaxLength==16),"Trainer6 all source fields and widths");
            var geo=c.Existing.Geography!;Check(geo.Orders is {Length:3},"Trainer6 source orders for three UI languages");foreach(var order in geo.Orders!){string language=order.Language=="zh"?"zh-Hans":order.Language;Check(order.Countries.SequenceEqual(Util.GetCountryRegionList("countries",language).Select(v=>v.Value)),"Trainer6 exact source country order");foreach(var regions in order.Regions)Check(regions.Ids.SequenceEqual(regions.Country==0?[]:Util.GetCountryRegionList($"sr_{regions.Country:000}",language).Select(v=>v.Value)),"Trainer6 every source region order and initial empty country-zero list");}
            uint lastDate=(uint)(new DateTime(2050,12,31)-new DateTime(2000,1,1)).TotalSeconds;foreach(uint seconds in new[]{lastDate+1,uint.MaxValue}){var outside=Open(data);outside.SecondsToStart=seconds;var bytes=outside.Write().ToArray();var catalog=Read(bytes);Reject(()=>Preview(bytes,new("resave",catalog.SourceHash)));}
            var lateSaved=Open(data);lateSaved.Played.LastSavedDate=new DateTime(2050,12,31,0,1,0);var lateSavedBytes=lateSaved.Write().ToArray();Reject(()=>Preview(lateSavedBytes,new("resave",Read(lateSavedBytes).SourceHash)));
            foreach(int value in new[]{0,86400,86400+3599,int.MaxValue})foreach(uint bias in new[]{0u,lastDate,(uint)int.MaxValue,uint.MaxValue}){var timing=Open(data);BinaryPrimitives.WriteInt32LittleEndian(timing.Records.Data[timing.GetRecordOffset(2)..],value);timing.SecondsToStart=bias;var record=SaveRecords.Read(timing).Entries[2];int sourceBias=bias<=int.MaxValue?(int)bias:-1;Check(record.TimeHint==DateUtil.ConvertDateValueToString(value,sourceBias),"Trainer6 legacy source duration/date unchanged");var localized=record.TimeHintLocalized!;string clock=new TimeOnly((value%86400)*TimeSpan.TicksPerSecond).ToString("HH:mm:ss",CultureInfo.InvariantCulture);Check(localized.Zh.Contains(clock)&&localized.En.Contains(clock)&&localized.Ja.Contains(clock),"Trainer6 all localized clocks");if(sourceBias>=0){string expectedDate=new DateTime(2000,1,1).AddSeconds(unchecked(value%86400+sourceBias)).ToString("yyyy-MM-dd HH:mm:ss",CultureInfo.InvariantCulture);Check(localized.Zh.EndsWith("日期："+expectedDate)&&localized.En.EndsWith("Date: "+expectedDate)&&localized.Ja.EndsWith("日時："+expectedDate),"Trainer6 localized date preserves source remainder and int addition");}else Check(!localized.Zh.Contains("日期")&&!localized.En.Contains("Date:"),"Trainer6 unavailable source bias yields duration only");}
            var basic=Open(data);basic.Money=12;var basicData=basic.Write().ToArray();var basicExpected=Open(basicData);basicExpected.OT="";var basicEdit=new TrainerEdit("",basic.TID16,basic.SID16,basic.Money);var basicOutput=SaveService.Export(basicData,JsonSerializer.Serialize(basicEdit,SaveJsonContext.Default.TrainerEdit));Check(basicOutput.SequenceEqual(basicExpected.Write().ToArray())&&Open(basicOutput).OT=="","Trainer6 source empty name and complete generic export");
            var positioned=Open(data);positioned.Situation.X=2.2222223f;positioned.Situation.Data.Slice(0xF4,0x1C).Fill(0xA5);var positionData=positioned.Write().ToArray();var positionCatalog=Read(positionData);Check(positionCatalog.Position.CanEdit&&positionCatalog.Position.Fields.Length==5,"Trainer6 complete source numeric position catalog");
            void PositionOracle(SAV6 s,Tr6Value[] rows,string language){var p=s.Situation;decimal[] values=[p.M,(decimal)(p.X/18.0),(decimal)(p.Z/18.0),(decimal)(p.Y/18.0),p.R];string[] keys=["map","x","z","y","rotation"];decimal[] min=[0,0,-65535,0,0],max=[1000,65535,65535,65535,7];bool dirty=false;foreach(var row in rows){int i=Array.IndexOf(keys,row.Key);try{decimal parsed=decimal.Parse(row.Value,CultureInfo.GetCultureInfo(language=="zh"?"zh-Hans":language));parsed=parsed<min[i]?min[i]:parsed>max[i]?max[i]:parsed;if(parsed!=values[i]){values[i]=parsed;dirty=true;}}catch(FormatException){}catch(OverflowException){}}if(dirty){p.M=(int)values[0];p.X=(float)(values[1]*18);p.Z=(float)(values[2]*18);p.Y=(float)(values[3]*18);p.R=(int)values[4];}}
            foreach(string language in new[]{"zh","en","ja"}){
                foreach(string key in new[]{"map","x","z","y","rotation"})foreach(string value in new[]{"0","65535","-65535","1,234.5","+1.2345678901234567890123456789","12.9","79228162514264337593543950335","-79228162514264337593543950335"}){Tr6Value[] rows=[new(key,value)];Compare(positionData,new("position",positionCatalog.SourceHash,rows,UiLanguage:language),s=>PositionOracle(s,rows,language));}
                foreach(string value in new[]{"","-","NaN","Infinity","1e2","bad","79228162514264337593543950336"}){var e=new Tr6Edit("position",positionCatalog.SourceHash,[new("x",value)],UiLanguage:language);var p=Preview(positionData,e);Check(p.IgnoredFields.SequenceEqual(new[]{"x"}),"Trainer6 invalid numeric input reported");Check(Apply(positionData,e).SequenceEqual(positionData),"Trainer6 invalid numeric input keeps all old fields/mirrors");}
            }
            var identical=positionCatalog.Position.Fields.Select(v=>new Tr6Value(v.Key,v.Value)).ToArray();Check(Apply(positionData,new("position",positionCatalog.SourceHash,identical,UiLanguage:"en")).SequenceEqual(positionData),"Trainer6 unchanged NUD Value does not mark MapUpdated or sync mirrors");
            var fractional=Compare(positionData,new("position",positionCatalog.SourceHash,[new("map","12.9")],UiLanguage:"zh"),s=>PositionOracle(s,[new("map","12.9")],"zh"));Check(!fractional.SequenceEqual(positionData)&&Open(fractional).Situation.M==12,"Trainer6 zero displayed places do not limit decimal Value; int save truncates but synchronizes all mirrors");
            foreach(float bad in new[]{float.NaN,float.PositiveInfinity,-1f,65536f*18f}){var malformed=Open(positionData);malformed.Situation.X=bad;var bytes=malformed.Write().ToArray();var catalog=Read(bytes);Check(!catalog.Position.CanEdit,"Trainer6 source GB_Map disabled for unloadable floats");Reject(()=>Preview(bytes,new("position",catalog.SourceHash,[new("z","1")],UiLanguage:"zh")));}
            Reject(()=>Preview(positionData,new("position",positionCatalog.SourceHash,[],UiLanguage:"en")));Reject(()=>Preview(positionData,new("position",positionCatalog.SourceHash,[new("scaleX","1")],UiLanguage:"en")));Reject(()=>Preview(positionData,new("position",positionCatalog.SourceHash,[new("x","1"),new("x","2")],UiLanguage:"en")));Reject(()=>Preview(positionData,new("position",positionCatalog.SourceHash,[new("x","1")])));Reject(()=>Preview(positionData,new("patch",positionCatalog.SourceHash,[new("Mega","1")],UiLanguage:"en")));
            Tr6Edit Patch(params Tr6Value[] fields)=>new("patch",c.SourceHash,fields);
            for(int i=0;i<20;i++){int at=i;foreach(int n in new[]{0,9999})Compare(data,Patch(new Tr6Value("Maison"+i,n.ToString())),s=>BinaryPrimitives.WriteUInt16LittleEndian(Maison(s).Data[(0x1C0+at*2)..],(ushort)n));}
            Compare(data,Patch(new Tr6Value("Maison0","")),s=>Maison(s).SetMaisonStat(0,0));
            string[] sayings=["","abcdefghijklmnop","汉字あいうえおＡＢＣ","\uE081\uE08D"];
            for(int i=0;i<5;i++){int at=i;foreach(string text in sayings)Compare(data,Patch(new Tr6Value("Saying"+i,text)),s=>s.SetString(s.Status.Data.Slice(0x7C+at*0x22,0x22),text,17,StringConverterOption.ClearZero));}
            if(seed is SAV6XY){
                foreach(byte gender in new byte[]{0,1}){
                    var appearanceSeed=Open(data);appearanceSeed.Gender=gender;var appearanceData=appearanceSeed.Write().ToArray();var appearanceCatalog=Read(appearanceData);var properties=((SAV6XY)appearanceSeed).Status.Fashion.GetType().GetProperties();
                    Check(appearanceCatalog.Fields.Count(v=>v.Group=="appearance")==properties.Length,"Trainer6 every public appearance property");
                    foreach(var property in properties){
                        string[] values=property.PropertyType==typeof(bool)?new[]{"0","1"}:property.PropertyType==typeof(uint)?new[]{"0","4294967295","0xFFFFFFFF"}:new[]{"0","-1","2147483647",Enum.GetNames(property.PropertyType)[0]};
                        foreach(string value in values)Compare(appearanceData,new("patch",appearanceCatalog.SourceHash,[new("Appearance."+property.Name,value)]),s=>{var xy=(SAV6XY)s;var fashion=xy.Status.Fashion;object parsed=property.PropertyType==typeof(bool)?value=="1":TypeDescriptor.GetConverter(property.PropertyType).ConvertFromInvariantString(value)!;property.SetValue(fashion,parsed);xy.Status.Fashion=fashion;});
                    }
                    Reject(()=>Preview(appearanceData,new("patch",appearanceCatalog.SourceHash,[new("Appearance.Version","4294967296")])));
                    Reject(()=>Preview(appearanceData,new("patch",appearanceCatalog.SourceHash,[new("Appearance.Skin","2147483648")])));
                    Reject(()=>Preview(appearanceData,new("patch",appearanceCatalog.SourceHash,[new("Appearance.Version","")])));
                }
            }
            foreach(var choice in sprite.Choices)Compare(data,Patch(new Tr6Value("Sprite",choice.Id.ToString())),s=>{s.Status.Data[6]=(byte)choice.Id;s.Status.Data[7]=(byte)choice.Id;});
            foreach(var choice in c.Fields.Single(v=>v.Key=="Vivillon").Choices)Compare(data,Patch(new Tr6Value("Vivillon",choice.Id.ToString())),s=>s.Vivillon=choice.Id);
            foreach(int n in new[]{0,1}){Compare(data,Patch(new Tr6Value("Mega",n.ToString())),s=>s.Status.Data[0x14A]=(byte)((s.Status.Data[0x14A]&0xFE)|n));if(seed is SAV6AO)Compare(data,Patch(new Tr6Value("Rayquaza",n.ToString())),s=>s.Status.Data[0x14A]=(byte)((s.Status.Data[0x14A]&~2)|(n<<1)));}
            if(seed is SAV6XY){foreach(int rank in Enumerable.Range(0,6))Compare(data,Patch(new Tr6Value("Rank",rank.ToString())),s=>((SAV6XY)s).SUBE.SetChateauByRank((ushort)rank));foreach(int points in new[]{0,4095})Compare(data,Patch(new Tr6Value("Points",points.ToString())),s=>((SAV6XY)s).SUBE.ChateauPoints=(ushort)points);foreach(var rows in new[]{new[]{new Tr6Value("Rank","2"),new("Points","234")},new[]{new Tr6Value("Points","234"),new("Rank","2")}})Compare(data,Patch(rows),s=>((SAV6XY)s).SUBE.SetChateau(2,234));Compare(data,Patch(new Tr6Value("Style","999")),s=>s.Situation.Style=255);Compare(data,new("accessories",c.SourceHash),s=>((SAV6XY)s).Blocks.Fashion.UnlockAllAccessories());}else{Reject(()=>Preview(data,Patch(new Tr6Value("Rank","1"))));Reject(()=>Preview(data,Patch(new Tr6Value("Style","1"))));Reject(()=>Preview(data,new("accessories",c.SourceHash)));}
            Compare(data,new("resave",c.SourceHash),s=>{s.Overworld.ResetPlayerModel();s.Money=4294967;s.Region=255;var sayings=new[]{s.Status.Saying1,s.Status.Saying2,s.Status.Saying3,s.Status.Saying4,s.Status.Saying5};for(int i=0;i<5;i++)s.SetString(s.Status.Data.Slice(0x7C+i*34,34),sayings[i],17,StringConverterOption.ClearZero);for(int i=0;i<20;i++)Maison(s).SetMaisonStat(i,(ushort)MaskPrefix(Maison(s).GetMaisonStat(i),4));s.BP=6553;s.SetRecord(63,1234567);s.SetRecord(64,1234567);s.PlayedMinutes=25;s.PlayedSeconds=19;((IMultiplayerSprite)s).MultiplayerSpriteID=255;if(s is SAV6XY xy){xy.SUBE.ChateauRank=5;xy.Status.Fashion=xy.Status.Fashion;xy.Status.Nickname=xy.Status.Nickname;}s.Played.LastSavedDate=new(2025,6,7,8,9,0);});
            Compare(data,new("trash",c.SourceHash,Trash:new("prepare")),s=>s.SetString(s.Status.OriginalTrainerTrash,s.OT,12,StringConverterOption.None));
            Compare(data,new("trash",c.SourceHash,Trash:new("clear")),s=>{var bytes=s.Status.OriginalTrainerTrash;s.SetString(bytes,s.OT,12,StringConverterOption.None);bytes[4..].Clear();});
            Compare(data,new("trash",c.SourceHash,Trash:new("text",Text:"Z")),s=>s.SetString(s.Status.OriginalTrainerTrash,"Z",1,StringConverterOption.None));
            string hex="41000000"+new string('0',40)+"AABB";Compare(data,new("trash",c.SourceHash,Trash:new("hex",Hex:hex)),s=>Convert.FromHexString(hex).CopyTo(s.Status.OriginalTrainerTrash));
            var layer=Apply(data,new("trash",c.SourceHash,Trash:new("layer",Species:25,Language:2,Generation:6,UiLanguage:"zh")));var layerSave=Open(layer);Check(layerSave.OT=="A"&&layerSave.Status.OriginalTrainerTrash[4..16].SequenceEqual(new byte[]{107,0,97,0,99,0,104,0,117,0,0,0}),"Trainer6 source trash layer");
            foreach(var rows in new[]{new[]{new Tr6Value("Maison0","10000")},new[]{new Tr6Value("Maison0","-1")},new[]{new Tr6Value("Maison0","1e2")},new[]{new Tr6Value("Saying0",new string('A',17))},new[]{new Tr6Value("Mega","")},new[]{new Tr6Value("Sprite","17")},new[]{new Tr6Value("Vivillon","99")},new[]{new Tr6Value("Unknown","0")},new[]{new Tr6Value("Maison0","1"),new("Maison0","2")}})Reject(()=>Preview(data,Patch(rows)));
            Reject(()=>Preview(data,new("patch",c.SourceHash,[])));Reject(()=>Preview(data,new("resave",c.SourceHash,Fields:[])));Reject(()=>Preview(data,new("trash",c.SourceHash,Trash:new("hex",Hex:"00"))));Reject(()=>Preview(data,new("trash",c.SourceHash,Trash:new("text",Text:new string('a',13)))));Reject(()=>Preview(data,new("patch",new string('0',64),[new("Mega","1")])));Reject(()=>SaveService.EditTrainer6(data,Json(Patch(new Tr6Value("Mega","1")))));var frozen=Preview(data,Patch(new Tr6Value("Mega","1"))).Request;Reject(()=>SaveService.EditTrainer6(data,Json(frozen with{TargetHash=new string('0',64)})));Check(data.SequenceEqual(original),"Trainer6 all reads/rejections preserve original");Console.WriteLine($"PASS {version}: source field addresses/masks/choices, five sayings/twenty records, images/flags/chateau linkage, accessories, source full resave, trainer trash, whole-file frozen oracles and atomic requests");
        }
        Reject(()=>SaveService.ReadTrainer6(File.ReadAllBytes(".tmp/pkhex-fixtures/B2.sav")));
    }
}
