// SPDX-License-Identifier: GPL-3.0-or-later
using System.Text.Json;
using PKHeX.Core;
using static System.Buffers.Binary.BinaryPrimitives;
namespace PokeRNGKit.SaveEditor;
public sealed record Bp4Summary(int Index,int Type,string Name,bool Available,bool Issued);
public sealed record Bp4Number(int Id,string Source,long Value,long Minimum,long Maximum,OriginChoice[]? Choices=null);
public sealed record Bp4Text(int Id,string Source,string Value,string Hex,int Maximum,int Bytes,bool Multiline);
public sealed record Bp4Member(int Slot,bool Present,int Box,int Position,int Flags,PokemonEntry? Pokemon);
public sealed record Bp4Catalog(bool CanEdit,int Profile,int Index,string SourceHash,Bp4Summary[] Passes,Bp4Number[] Numbers,Bp4Text[] Text,bool[] Flags,Bp4Member[] Members,GeoRegions[] Regions);
public sealed record Bp4Query(int? Index);
public sealed record Bp4Value(int? Id,string? Value);
public sealed record Bp4Edit(string Action,int? Profile,int? Index,Bp4Value[]? Values=null,int? Other=null,int? Slot=null,int? Box=null,int? Position=null,int? Flags=null,string? Data=null,string? FileName=null,bool? Encrypted=null,string? SourceHash=null,bool? ConfirmIncompatible=null);
public sealed record Bp4PokemonPreview(PokemonEntry Pokemon,LocalizedText[] Warnings,int Target,int Box,int Position);
internal static class BattlePass4Editing
{
    private static readonly string[] NumberNames=["TrainerTitle","TID","SID","Model","SkinColor","PictureType","PassDesign","Head","Hair","Face","Top","Bottom","Shoes","Hands","Bag","Glasses","Badge","PresetGreetingIndex","PresetSentOutIndex","PresetShift1Index","PresetShift2Index","PresetWinIndex","PresetLoseIndex","Country","Region","Language","Battles","RecordColosseumBattles","RecordFreeBattles","RecordWiFiBattles","RecordGatewayColosseumClears","RecordMainStreetColosseumClears","RecordWaterfallColosseumClears","RecordNeonColosseumClears","RecordCrystalColosseumClears","RecordSunnyParkColosseumClears","RecordMagmaColosseumClears","RecordCourtyardColosseumClears","RecordSunsetColosseumClears","RecordStargazerColosseumClears"];
    private static readonly string[] TextNames=["Name","Greeting","SentOut","Shift1","Shift2","Win","Lose","CreatorName","BirthMonth","BirthDay","SelfIntroduction","RegionCode","PlayerID"];
    private static readonly int[] TextOffsets=[4,0x2C,0x60,0x98,0xCC,0x100,0x168,0x548,0x568,0x570,0x57C,0x5ED,0x6DC];
    private static readonly int[] TextBytes=[24,52,56,52,52,104,104,32,8,8,108,4,8];
    private static readonly int[] TextLimits=[11,25,27,25,25,51,51,11,4,4,53,4,16];
    private static void Index(int? index,int count){if(index is null||index<0||index>=count)throw new ArgumentException("Invalid Battle Pass position.");}
    internal static BattlePass Pass(SAV4BR s,int? index){Index(index,BattlePassAccessor.PASS_COUNT);return s.BattlePasses[index!.Value];}
    private static long[] Numbers(BattlePass p)=>[p.TrainerTitle,p.TID,p.SID,p.Model,p.Skin,p.PictureType,p.PassDesign,p.Head,p.Hair,p.Face,p.Top,p.Bottom,p.Shoes,p.Hands,p.Bag,p.Glasses,p.Badge,p.PresetGreetingIndex,p.PresetSentOutIndex,p.PresetShift1Index,p.PresetShift2Index,p.PresetWinIndex,p.PresetLoseIndex,p.Country,p.Region,(int)p.Language,p.Battles,p.RecordColosseumBattles,p.RecordFreeBattles,p.RecordWiFiBattles,p.RecordGatewayColosseumClears,p.RecordMainStreetColosseumClears,p.RecordWaterfallColosseumClears,p.RecordNeonColosseumClears,p.RecordCrystalColosseumClears,p.RecordSunnyParkColosseumClears,p.RecordMagmaColosseumClears,p.RecordCourtyardColosseumClears,p.RecordSunsetColosseumClears,p.RecordStargazerColosseumClears];
    private static bool[] Flags(BattlePass p)=>[p.PresetGreeting,p.PresetSentOut,p.PresetShift1,p.PresetShift2,p.PresetWin,p.PresetLose,p.Available,p.Issued,p.Rental,p.Friend];
    private static string[] Text(BattlePass p)=>[p.Name,p.Greeting,p.SentOut,p.Shift1,p.Shift2,p.Win,p.Lose,p.CreatorName,p.BirthMonth,p.BirthDay,p.SelfIntroduction.TrimStart(StringConverter4GC.Proportional),p.RegionCode,p.PlayerID.ToString("X16")];
    private static OriginChoice[] Choices(int id,BattlePass p)
    {
        OriginChoice[] Range(int count,string? resource=null,int offset=0){string[] z=resource is null?[]:GameLanguage.GetStrings(resource,"zh-Hans"),e=resource is null?[]:GameLanguage.GetStrings(resource,"en"),j=resource is null?[]:GameLanguage.GetStrings(resource,"ja");return Enumerable.Range(0,count).Select(i=>new OriginChoice(i,new(resource is null?i.ToString():z[offset+i],resource is null?i.ToString():e[offset+i],resource is null?i.ToString():j[offset+i]))).ToArray();}
        if(id==0){var result=new List<OriginChoice>{new(0,new("无","None","なし"))};foreach(var (name,offset) in new[]{("trainer_title",11057),("trainer_title_npc",18015)}){var z=GameLanguage.GetStrings(name,"zh-Hans");var e=GameLanguage.GetStrings(name,"en");var j=GameLanguage.GetStrings(name,"ja");result.AddRange(Enumerable.Range(0,e.Length).Select(i=>new OriginChoice(offset+i,new($"{z[i]} [{offset+i}]",$"{e[i]} [{offset+i}]",$"{j[i]} [{offset+i}]"))));}return result.ToArray();}
        if(id==3)return Range(13);if(id==4)return Range(3);if(id==5)return Range(2);if(id==6)return Range(GameLanguage.GetStrings("pass_design","en").Length,"pass_design");
        if(id is >=7 and <=16){if(p.Model is <1 or >6)return [];int category=id switch{7=>0,8=>1,9=>2,10=>3,11=>4,12=>5,13=>6,14=>7,15=>8,_=>9};var (offset,count)=GearUnlock.GetOffsetCount((ModelBR)(category==9?1:p.Model),(GearCategory)category);return Range(count,"gear",offset);}
        if(id==23)return GeographicCatalog.Gen4Countries.Value;if(id==24)return GeographicCatalog.Gen4Regions.Value.FirstOrDefault(v=>v.Country==p.Country)?.Choices??[];
        if(id==25){var z=GameInfo.GetStrings("zh-Hans").languageNames;var e=GameInfo.GetStrings("en").languageNames;var j=GameInfo.GetStrings("ja").languageNames;return Enumerable.Range(0,6).Select(i=>{int lang=(int)((BattlePassLanguage)i).ToLanguageID();return new OriginChoice(i,new(z[lang],e[lang],j[lang]));}).ToArray();}return [];
    }
    internal static Bp4Catalog Read(SaveFile save,int? index,string hash)
    {
        var s=Br4Editing.Save(save);var p=Pass(s,index);var values=Numbers(p);var numbers=values.Select((v,i)=>new Bp4Number(i,NumberNames[i],v,i is >=26 and <=29?int.MinValue:0,i is 1 or 2?99999:i is >=26 and <=29?int.MaxValue:i>=30?255:65535,i is 0 or >=3 and <=16 or >=23 and <=25?Choices(i,p):null)).ToArray();var texts=Text(p).Select((v,i)=>new Bp4Text(i,TextNames[i],i is 2 or 5 or 6 or 10?v.Replace(StringConverter4GC.LineBreak,'\n'):v,Convert.ToHexString(p.Data.Slice(TextOffsets[i],TextBytes[i])),i==10&&p.Language!=BattlePassLanguage.Japanese?51:TextLimits[i],TextBytes[i],i is 2 or 5 or 6 or 10)).ToArray();
        var summaries=Enumerable.Range(0,BattlePassAccessor.PASS_COUNT).Select(i=>{var item=s.BattlePasses[i];return new Bp4Summary(i,(int)s.BattlePasses.GetPassType(i),item.Name,item.Available,item.Issued);}).ToArray();var members=Enumerable.Range(0,6).Select(i=>{var (box,slot)=p.GetPartySlotBoxSlot(i);bool present=p.GetPartySlotPresent(i);var pk=p.GetPartySlotAtIndex(i);return new Bp4Member(i,present,box,slot,p.GetPartySlotFlags(i),present&&pk.Species>0&&pk.Species<=s.MaxSpeciesID?PokemonReader.Read(pk,-1,i):null);}).ToArray();return new(s.State.Exportable&&SaveChecksums.Valid(s),s.CurrentSlot,index!.Value,hash,summaries,numbers,texts,Flags(p),members,GeographicCatalog.Gen4Regions.Value);
    }
    private static void Number(BattlePass p,int id,long value)
    {
        switch(id){case 0:p.TrainerTitle=(short)value;break;case 1:p.TID=unchecked((ushort)value);break;case 2:p.SID=unchecked((ushort)value);break;case 3:p.Model=(int)value;break;case 4:p.Skin=(int)value;break;case 5:p.PictureType=(int)value;break;case 6:p.PassDesign=(int)value;break;case >=7 and <=16:p.Data[0x22+id-7]=(byte)value;break;case >=17 and <=22:WriteUInt16BigEndian(p.Data[(0x1F0+(id-17)*2)..],(ushort)value);break;case 23:p.Country=(int)value;break;case 24:p.Region=(int)value;break;case 25:p.Language=(BattlePassLanguage)value;break;case 26:p.Battles=(int)value;break;case 27:p.RecordColosseumBattles=(int)value;break;case 28:p.RecordFreeBattles=(int)value;break;case 29:p.RecordWiFiBattles=(int)value;break;case >=30 and <=39:p.Data[0x6D0+id-30]=(byte)value;break;default:throw new ArgumentException("Invalid Battle Pass number field.");}
    }
    private static void Flag(BattlePass p,int id,bool value){if(id<6)FlagUtil.SetFlag(p.Data,0x1E,id+1,value);else if(id is >=6 and <=9)FlagUtil.SetFlag(p.Data,0x545,id switch{6=>3,7=>4,8=>6,_=>7},value);else throw new ArgumentException("Invalid Battle Pass flag.");}
    private static BK4 ImportPokemon(Bp4Edit edit)
    {
        if(edit.Data is null||edit.FileName is null)throw new ArgumentException("Missing Battle Pass Pokemon file.");byte[] input;try{input=Convert.FromBase64String(edit.Data);}catch(FormatException){throw new ArgumentException("Invalid Battle Pass Pokemon binary.");}
        var pk=StandalonePokemon.Open(input,edit.FileName,edit.Encrypted??false,true).Entity;pk=EntityConverter.ConvertToType(pk,typeof(BK4),out _)??throw new ArgumentException("Battle Pass Pokemon cannot be converted to BK4.");if(pk is not BK4 result||pk.Species==0||pk.Species>pk.MaxSpeciesID||!pk.ChecksumValid)throw new ArgumentException("Battle Pass Pokemon has invalid data.");result.IsDecryptedStateBox=true;result.IsDecryptedStateParty=false;return result;
    }
    private static string[] Compatibility(SAV4BR s,PKM pk,string language)
    {
        var original=GameInfo.Strings;try{GameInfo.Strings=GameInfo.GetStrings(language);var messages=Util.GetStringList($"MessageStrings_{language}").Select(line=>line.Split(" = ",2)).Where(pair=>pair.Length==2).ToDictionary(pair=>pair[0],pair=>pair[1]);(string Key,string Text)[] prefixes=[(nameof(MessageStrings.MsgIndexItemGame),MessageStrings.MsgIndexItemGame),(nameof(MessageStrings.MsgIndexItemHeld),MessageStrings.MsgIndexItemHeld),(nameof(MessageStrings.MsgIndexSpeciesRange),MessageStrings.MsgIndexSpeciesRange),(nameof(MessageStrings.MsgIndexSpeciesGame),MessageStrings.MsgIndexSpeciesGame),(nameof(MessageStrings.MsgIndexMoveRange),MessageStrings.MsgIndexMoveRange),(nameof(MessageStrings.MsgIndexMoveGame),MessageStrings.MsgIndexMoveGame),(nameof(MessageStrings.MsgIndexAbilityRange),MessageStrings.MsgIndexAbilityRange),(nameof(MessageStrings.MsgIndexAbilityGame),MessageStrings.MsgIndexAbilityGame)];return s.EvaluateCompatibility(pk,language).Select(line=>{foreach(var prefix in prefixes)if(line.StartsWith(prefix.Text,StringComparison.Ordinal)&&messages.TryGetValue(prefix.Key,out var translated))return translated+line[prefix.Text.Length..];return line;}).ToArray();}finally{GameInfo.Strings=original;}
    }
    internal static Bp4PokemonPreview PreviewPokemon(SaveFile save,Bp4Edit edit,string hash)
    {
        var s=Br4Editing.Save(save);if(edit.Action!="setPokemon"||edit.Profile!=s.CurrentSlot||edit.SourceHash!=hash||edit.Values is not null||edit.Other is not null||edit.Box is not null||edit.Position is not null||edit.Flags is not null||edit.ConfirmIncompatible is not null)throw new ArgumentException("Invalid Battle Pass Pokemon preview.");Index(edit.Slot,6);var p=Pass(s,edit.Index);var pk=ImportPokemon(edit);int target=edit.Slot!.Value;while(target>0&&!p.GetPartySlotPresent(target-1))target--;var type=s.BattlePasses.GetPassType(edit.Index!.Value);var link=type==BattlePassType.Custom?s.FindSlot(pk):type==BattlePassType.Rental?((byte)255,(byte)0):p.GetPartySlotBoxSlot(target);var en=Compatibility(s,pk,"en");var zh=Compatibility(s,pk,"zh-Hans");var ja=Compatibility(s,pk,"ja");return new(PokemonReader.Read(pk,-1,target),Enumerable.Range(0,en.Length).Select(i=>new LocalizedText(zh[i],en[i],ja[i])).ToArray(),target,link.Item1,link.Item2);
    }
    internal static void Apply(SaveFile save,Bp4Edit edit,string hash)
    {
        var s=Br4Editing.Save(save);if(!s.State.Exportable||!SaveChecksums.Valid(s))throw new ArgumentException("Battle Pass requires valid checksums.");if(edit.Profile!=s.CurrentSlot)throw new ArgumentException("Battle Pass player changed. Read it again.");if(edit.Action!="setPokemon"&&edit.ConfirmIncompatible is not null)throw new ArgumentException("Invalid Battle Pass compatibility confirmation.");Pass(s,edit.Index);var scratch=(SAV4BR)s.Clone();var p=Pass(scratch,edit.Index);
        if(edit.Action is "numbers" or "flags" or "text" or "rawText"&&edit.Other is null&&edit.Slot is null&&edit.Box is null&&edit.Position is null&&edit.Flags is null&&edit.Data is null&&edit.FileName is null&&edit.Encrypted is null&&edit.SourceHash is null&&edit.Values is {} fields)
        {
            if(fields.Length is 0 or >40||fields.Any(v=>v is null||v.Id is null||v.Value is null)||fields.Select(v=>v.Id).Distinct().Count()!=fields.Length)throw new ArgumentException("Invalid Battle Pass fields.");
            if(edit.Action=="numbers")
            {
                var parsed=fields.Select(v=>new{Id=v.Id!.Value,Value=long.TryParse(v.Value,System.Globalization.NumberStyles.Integer,System.Globalization.CultureInfo.InvariantCulture,out var value)?value:(v.Id is 1 or 2&&string.IsNullOrWhiteSpace(v.Value)?0:throw new ArgumentException("Invalid Battle Pass number."))}).ToArray();
                foreach(var v in parsed){Index(v.Id,40);long min=v.Id is >=26 and <=29?int.MinValue:0,max=v.Id is 1 or 2?99999:v.Id is >=26 and <=29?int.MaxValue:v.Id>=30?255:65535;if(v.Value<min||v.Value>max)throw new ArgumentException("Battle Pass number exceeds the control range.");}
                var model=parsed.FirstOrDefault(v=>v.Id==3);if(model is not null){if(model.Value>12)throw new ArgumentException("Invalid Battle Pass model.");Number(p,3,model.Value);for(int id=7;id<=16;id++){int category=id-7;Number(p,id,p.Model is >=1 and <=6?GearUnlock.GetDefault((ModelBR)(category==9?1:p.Model),(GearCategory)category):0);}p.ResetPresetIndexes();}
                var country=parsed.FirstOrDefault(v=>v.Id==23);if(country is not null){if(!Choices(23,p).Any(c=>c.Id==country.Value))throw new ArgumentException("Invalid Battle Pass country.");Number(p,23,country.Value);if(!parsed.Any(v=>v.Id==24))Number(p,24,Choices(24,p).FirstOrDefault()?.Id??0);}
                foreach(var v in parsed){var choices=Choices(v.Id,p);if(v.Id is 0 or >=3 and <=16 or >=23 and <=25 && (!choices.Any(c=>c.Id==v.Value)))throw new ArgumentException("Invalid Battle Pass candidate.");Number(p,v.Id,v.Value);}
                // Model/Title/Rental helper follows upstream only for fields wired to UpdatePresetIndexes.
                if(model is not null&&!parsed.Any(v=>v.Id is >=17 and <=22))p.ResetPresetIndexes();
            }
            else if(edit.Action=="flags")
            {foreach(var v in fields){Index(v.Id,10);if(v.Value is not("0" or "1"))throw new ArgumentException("Invalid Battle Pass boolean.");Flag(p,v.Id!.Value,v.Value=="1");}if(fields.Any(v=>v.Id==8))p.ResetPresetIndexes();}
            else foreach(var v in fields)
            {
                Index(v.Id,13);int id=v.Id!.Value;var target=p.Data.Slice(TextOffsets[id],TextBytes[id]);
                if(edit.Action=="rawText"){if(v.Value!.Length!=target.Length*2||v.Value.Any(c=>!Uri.IsHexDigit(c)))throw new ArgumentException("Invalid Battle Pass raw text bytes.");Convert.FromHexString(v.Value).CopyTo(target);continue;}
                var input=v.Value!;int limit=id==10&&p.Language!=BattlePassLanguage.Japanese?51:TextLimits[id];if(input.Length>limit)throw new ArgumentException("Battle Pass text exceeds the control length.");if(id==12){if(input.Length>16||input.Any(c=>!Uri.IsHexDigit(c)))throw new ArgumentException("Invalid Battle Pass player ID.");p.PlayerID=input.Length==0?0:Convert.ToUInt64(input,16);continue;}if(id==11){if(input.Any(c=>c>127))throw new ArgumentException("Battle Pass region code must be ASCII.");p.RegionCode=input;continue;}
                bool multiline=id is 2 or 5 or 6 or 10;if(!multiline&&input.Contains('\n'))throw new ArgumentException("Battle Pass field is single-line.");input=input.Replace("\r\n","\n").Replace('\r','\n').Replace('\n',StringConverter4GC.LineBreak);int weight=input.Sum(c=>c is StringConverter4GC.LineBreak or StringConverter4GC.Proportional or StringConverter4GC.PokemonName?2:1);if(weight>limit)throw new ArgumentException("Battle Pass variable text exceeds encoded length.");if(id==10&&p.Language!=BattlePassLanguage.Japanese)input=StringConverter4GC.Proportional+input;
                if(input==StringConverter4GC.GetStringUnicodeBR(target))continue;StringConverter4GC.SetStringUnicodeBR(input,target);if(StringConverter4GC.GetStringUnicodeBR(target)!=input)throw new ArgumentException("Battle Pass text cannot be encoded without loss.");
            }
        }
        else if(edit.Action is "delete" or "swap" or "unlockCustom" or "unlockRental" or "import"&&edit.Values is null&&edit.Slot is null&&edit.Box is null&&edit.Position is null&&edit.Flags is null&&edit.FileName is null&&edit.Encrypted is null&&edit.SourceHash is {} source)
        {if(source!=hash||source.Length!=64)throw new ArgumentException("Battle Pass preview is stale. Read it again.");switch(edit.Action){case "delete" when edit.Other is null&&edit.Data is null:if(scratch.BattlePasses.GetPassType(edit.Index!.Value)==BattlePassType.Rental)throw new ArgumentException("Rental Battle Pass cannot be deleted.");scratch.BattlePasses.Delete(edit.Index.Value);break;case "swap" when edit.Data is null:Index(edit.Other,187);if(Math.Abs(edit.Other!.Value-edit.Index!.Value)!=1)throw new ArgumentException("Battle Pass swap must be adjacent.");scratch.BattlePasses.Swap(edit.Index.Value,edit.Other.Value);break;case "unlockCustom" when edit.Other is null&&edit.Data is null:scratch.BattlePasses.UnlockAllCustomPasses();break;case "unlockRental" when edit.Other is null&&edit.Data is null:scratch.BattlePasses.UnlockAllRentalPasses();break;case "import" when edit.Other is null&&edit.Data is {} data:byte[] bytes;try{bytes=Convert.FromBase64String(data);}catch(FormatException){throw new ArgumentException("Invalid Battle Pass binary.");}if(bytes.Length!=BattlePass.Size)throw new ArgumentException("Battle Pass binary must contain exactly 0x6EC bytes.");bytes.CopyTo(p.Data);break;default:throw new ArgumentException("Invalid Battle Pass operation fields.");}}
        else if(edit.Action=="links"&&edit.Values is null&&edit.Other is null&&edit.Data is null&&edit.FileName is null&&edit.Encrypted is null&&edit.SourceHash is null)
        {Index(edit.Slot,6);if(edit.Box is null&&edit.Position is null&&edit.Flags is null||edit.Box is <0 or >255||edit.Position is <0 or >255||edit.Flags is <0 or >65535)throw new ArgumentException("Invalid Battle Pass link values.");var link=p.GetPartySlotBoxSlot(edit.Slot!.Value);p.SetPartySlotBoxSlot(edit.Slot.Value,(byte)(edit.Box??link.Box),(byte)(edit.Position??link.Slot));if(edit.Flags is {} flags)p.SetPartySlotFlags(edit.Slot.Value,(ushort)flags);}
        else if(edit.Action is "deletePokemon" or "setPokemon"&&edit.Values is null&&edit.Other is null&&edit.Box is null&&edit.Position is null&&edit.Flags is null&&edit.SourceHash is {} pokemonSource)
        {Index(edit.Slot,6);if(pokemonSource!=hash||pokemonSource.Length!=64)throw new ArgumentException("Battle Pass preview is stale. Read it again.");if(edit.Action=="deletePokemon"&&edit.Data is null&&edit.FileName is null&&edit.Encrypted is null)p.DeletePartySlot(edit.Slot!.Value);else if(edit.Action=="setPokemon"&&edit.Data is {} data&&edit.FileName is {} file){var pk=ImportPokemon(edit);if(scratch.EvaluateCompatibility(pk).Count!=0&&edit.ConfirmIncompatible!=true)throw new ArgumentException("Battle Pass Pokemon compatibility warnings require explicit confirmation.");int target=edit.Slot!.Value;while(target>0&&!p.GetPartySlotPresent(target-1))target--;// Upstream uses a party writer for a stored-size span; preserve the four link bytes.
            pk.WriteEncryptedDataStored(p.Data.Slice(0x1FC+BattlePass.PokeSize*target,pk.SIZE_STORED));p.SetPartySlotPresent(target,true);var type=scratch.BattlePasses.GetPassType(edit.Index!.Value);if(type==BattlePassType.Custom){var (box,slot)=s.FindSlot(pk);p.SetPartySlotBoxSlot(target,box,slot);}else if(type==BattlePassType.Rental)p.SetPartySlotBoxSlot(target,255,0);}else throw new ArgumentException("Invalid Battle Pass Pokemon fields.");}
        else throw new ArgumentException("Invalid Battle Pass action or mixed fields.");
        s.BattlePasses.CopyChangesFrom(scratch.BattlePasses);
    }
    internal static byte[] Snapshot(SaveFile save){var s=Br4Editing.Save(save);return Enumerable.Range(0,187).SelectMany(i=>s.BattlePasses[i].Data.ToArray()).ToArray();}
}
public static partial class SaveService
{
    public static string PreviewBattlePassPokemon4(byte[] data,string json){if(json.Length>2*1024*1024)throw new ArgumentException("Battle Pass request is too large.");var edit=JsonSerializer.Deserialize(json,SaveJsonContext.Default.Bp4Edit)??throw new ArgumentException("Missing Battle Pass preview.");return JsonSerializer.Serialize(BattlePass4Editing.PreviewPokemon(Open(data),edit,Br4Editing.Hash(data)),SaveJsonContext.Default.Bp4PokemonPreview);}
    public static string ReadBattlePass4(byte[] data,string json){if(json.Length>1024)throw new ArgumentException("Battle Pass query is too large.");var query=JsonSerializer.Deserialize(json,SaveJsonContext.Default.Bp4Query)??throw new ArgumentException("Missing Battle Pass query.");return JsonSerializer.Serialize(BattlePass4Editing.Read(Open(data),query.Index,Br4Editing.Hash(data)),SaveJsonContext.Default.Bp4Catalog);}
    public static byte[] EditBattlePass4(byte[] data,string json){if(json.Length>2*1024*1024)throw new ArgumentException("Battle Pass request is too large.");var edit=JsonSerializer.Deserialize(json,SaveJsonContext.Default.Bp4Edit)??throw new ArgumentException("Missing Battle Pass edit.");var s=Br4Editing.Save(Open(data));BattlePass4Editing.Apply(s,edit,Br4Editing.Hash(data));var expected=BattlePass4Editing.Snapshot(s);var output=s.Write().ToArray();var check=Br4Editing.Save(Open(output));if(output.Length!=data.Length||check.CurrentSlot!=s.CurrentSlot||!SaveChecksums.Valid(check)||!expected.SequenceEqual(BattlePass4Editing.Snapshot(check)))throw new InvalidOperationException("Battle Pass export verification failed.");return output;}
    public static string ExportBattlePass4(byte[] data,int index){var s=Br4Editing.Save(Open(data));return Convert.ToBase64String(BattlePass4Editing.Pass(s,index).Data);}
    public static string ExportBattlePassPokemon4(byte[] data,int index,int slot){if(slot is <0 or >=6)throw new ArgumentException("Invalid Battle Pass Pokemon position.");var p=BattlePass4Editing.Pass(Br4Editing.Save(Open(data)),index).GetPartySlotAtIndex(slot);if(p.Species==0||!p.ChecksumValid)throw new ArgumentException("Battle Pass Pokemon is empty or invalid.");var output=new byte[p.SIZE_STORED];p.WriteDecryptedDataStored(output);return Convert.ToBase64String(output);}
}
