// SPDX-License-Identifier: GPL-3.0-or-later
namespace PokeRNGKit.SaveEditor;
internal static class Misc5Subway
{
    private static LocalizedText Merge(LocalizedText a,LocalizedText b)=>new(a.Zh+" / "+b.Zh,a.En+" / "+b.En,a.Ja+" / "+b.Ja);
    internal static void Add(List<Misc5Definition> list)
    {
        list.Add(new("singlePast","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Singles"),Misc5Text.Get("SAV_Misc5.L_SinglePast")),0,9999,false,x=>x.BattleSubway.SinglePast,(x,v)=>{var b=x.BattleSubway;bool active=b.SingleSet==b.SinglePast/7+1;b.SinglePast=(int)v;b.SingleSet=active?b.SinglePast/7+1:0;}));
        list.Add(new("singleRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Singles"),Misc5Text.Get("SAV_Misc5.L_SingleRecord")),0,9999,false,x=>x.BattleSubway.SingleRecord,(x,v)=>x.BattleSubway.SingleRecord=(int)v));
        list.Add(new("singleActive","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Singles"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.SingleSet==x.BattleSubway.SinglePast/7+1?1:0,(x,v)=>x.BattleSubway.SingleSet=v==1?x.BattleSubway.SinglePast/7+1:0));
        list.Add(new("doublePast","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Doubles"),Misc5Text.Get("SAV_Misc5.L_DoublePast")),0,9999,false,x=>x.BattleSubway.DoublePast,(x,v)=>{var b=x.BattleSubway;bool active=b.DoubleSet==b.DoublePast/7+1;b.DoublePast=(int)v;b.DoubleSet=active?b.DoublePast/7+1:0;}));
        list.Add(new("doubleRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Doubles"),Misc5Text.Get("SAV_Misc5.L_DoubleRecord")),0,9999,false,x=>x.BattleSubway.DoubleRecord,(x,v)=>x.BattleSubway.DoubleRecord=(int)v));
        list.Add(new("doubleActive","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_Doubles"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.DoubleSet==x.BattleSubway.DoublePast/7+1?1:0,(x,v)=>x.BattleSubway.DoubleSet=v==1?x.BattleSubway.DoublePast/7+1:0));
        list.Add(new("multiNpcPast","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiNPC"),Misc5Text.Get("SAV_Misc5.L_MultiNpcPast")),0,9999,false,x=>x.BattleSubway.MultiNPCPast,(x,v)=>{var b=x.BattleSubway;bool active=b.MultiNPCSet==b.MultiNPCPast/7+1;b.MultiNPCPast=(int)v;b.MultiNPCSet=active?b.MultiNPCPast/7+1:0;}));
        list.Add(new("multiNpcRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiNPC"),Misc5Text.Get("SAV_Misc5.L_MultiNpcRecord")),0,9999,false,x=>x.BattleSubway.MultiNPCRecord,(x,v)=>x.BattleSubway.MultiNPCRecord=(int)v));
        list.Add(new("multiNpcActive","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiNPC"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.MultiNPCSet==x.BattleSubway.MultiNPCPast/7+1?1:0,(x,v)=>x.BattleSubway.MultiNPCSet=v==1?x.BattleSubway.MultiNPCPast/7+1:0));
        list.Add(new("multiFriendsPast","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiFriends"),Misc5Text.Get("SAV_Misc5.L_MultiFriendsPast")),0,9999,false,x=>x.BattleSubway.MultiFriendsPast,(x,v)=>{var b=x.BattleSubway;bool active=b.MultiFriendsSet==b.MultiFriendsPast/7+1;b.MultiFriendsPast=(int)v;b.MultiFriendsSet=active?b.MultiFriendsPast/7+1:0;}));
        list.Add(new("multiFriendsRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiFriends"),Misc5Text.Get("SAV_Misc5.L_MultiFriendsRecord")),0,9999,false,x=>x.BattleSubway.MultiFriendsRecord,(x,v)=>x.BattleSubway.MultiFriendsRecord=(int)v));
        list.Add(new("multiFriendsActive","subway",Merge(Misc5Text.Get("SAV_Misc5.L_MultiFriends"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.MultiFriendsSet==x.BattleSubway.MultiFriendsPast/7+1?1:0,(x,v)=>x.BattleSubway.MultiFriendsSet=v==1?x.BattleSubway.MultiFriendsPast/7+1:0));
        list.Add(new("superSinglePast","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperSingles"),Misc5Text.Get("SAV_Misc5.L_SSinglePast")),0,9999,false,x=>x.BattleSubway.SuperSinglePast,(x,v)=>{var b=x.BattleSubway;bool active=b.SuperSingleSet==b.SuperSinglePast/7+1;b.SuperSinglePast=(int)v;b.SuperSingleSet=active?b.SuperSinglePast/7+1:0;}));
        list.Add(new("superSingleRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperSingles"),Misc5Text.Get("SAV_Misc5.L_SSingleRecord")),0,9999,false,x=>x.BattleSubway.SuperSingleRecord,(x,v)=>x.BattleSubway.SuperSingleRecord=(int)v));
        list.Add(new("superSingleActive","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperSingles"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.SuperSingleSet==x.BattleSubway.SuperSinglePast/7+1?1:0,(x,v)=>x.BattleSubway.SuperSingleSet=v==1?x.BattleSubway.SuperSinglePast/7+1:0));
        list.Add(new("superDoublePast","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperDoubles"),Misc5Text.Get("SAV_Misc5.L_SDoublePast")),0,9999,false,x=>x.BattleSubway.SuperDoublePast,(x,v)=>{var b=x.BattleSubway;bool active=b.SuperDoubleSet==b.SuperDoublePast/7+1;b.SuperDoublePast=(int)v;b.SuperDoubleSet=active?b.SuperDoublePast/7+1:0;}));
        list.Add(new("superDoubleRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperDoubles"),Misc5Text.Get("SAV_Misc5.L_SDoubleRecord")),0,9999,false,x=>x.BattleSubway.SuperDoubleRecord,(x,v)=>x.BattleSubway.SuperDoubleRecord=(int)v));
        list.Add(new("superDoubleActive","subway",Merge(Misc5Text.Get("SAV_Misc5.GB_SuperDoubles"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.SuperDoubleSet==x.BattleSubway.SuperDoublePast/7+1?1:0,(x,v)=>x.BattleSubway.SuperDoubleSet=v==1?x.BattleSubway.SuperDoublePast/7+1:0));
        list.Add(new("superMultiNpcPast","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiNPC"),Misc5Text.Get("SAV_Misc5.L_SMultiNpcPast")),0,9999,false,x=>x.BattleSubway.SuperMultiNPCPast,(x,v)=>{var b=x.BattleSubway;bool active=b.SuperMultiNPCSet==b.SuperMultiNPCPast/7+1;b.SuperMultiNPCPast=(int)v;b.SuperMultiNPCSet=active?b.SuperMultiNPCPast/7+1:0;}));
        list.Add(new("superMultiNpcRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiNPC"),Misc5Text.Get("SAV_Misc5.L_SMultiNpcRecord")),0,9999,false,x=>x.BattleSubway.SuperMultiNPCRecord,(x,v)=>x.BattleSubway.SuperMultiNPCRecord=(int)v));
        list.Add(new("superMultiNpcActive","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiNPC"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.SuperMultiNPCSet==x.BattleSubway.SuperMultiNPCPast/7+1?1:0,(x,v)=>x.BattleSubway.SuperMultiNPCSet=v==1?x.BattleSubway.SuperMultiNPCPast/7+1:0));
        list.Add(new("superMultiFriendsPast","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiFriends"),Misc5Text.Get("SAV_Misc5.L_SMultiFriendsPast")),0,9999,false,x=>x.BattleSubway.SuperMultiFriendsPast,(x,v)=>{var b=x.BattleSubway;bool active=b.SuperMultiFriendsSet==b.SuperMultiFriendsPast/7+1;b.SuperMultiFriendsPast=(int)v;b.SuperMultiFriendsSet=active?b.SuperMultiFriendsPast/7+1:0;}));
        list.Add(new("superMultiFriendsRecord","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiFriends"),Misc5Text.Get("SAV_Misc5.L_SMultiFriendsRecord")),0,9999,false,x=>x.BattleSubway.SuperMultiFriendsRecord,(x,v)=>x.BattleSubway.SuperMultiFriendsRecord=(int)v));
        list.Add(new("superMultiFriendsActive","subway",Merge(Misc5Text.Get("SAV_Misc5.L_SMultiFriends"),Misc5Text.Get("SAV_Misc5.GB_SubwaySets")),0,1,true,x=>x.BattleSubway.SuperMultiFriendsSet==x.BattleSubway.SuperMultiFriendsPast/7+1?1:0,(x,v)=>x.BattleSubway.SuperMultiFriendsSet=v==1?x.BattleSubway.SuperMultiFriendsPast/7+1:0));
    }
}
