// SPDX-License-Identifier: GPL-3.0-or-later
// Generated from PKHeX 26.08.26 PKHeX.WinForms/Subforms/Save Editors/Gen7/SAV_ZygardeCell.cs; SHA-256 b035ed7effe76aa8ce9228924e60df5c6d74b236e0320e56a8b11cfe43646cef.
namespace PokeRNGKit.SaveEditor;
internal static class Zygarde7Locations {
internal static LocalizedText[] Read(bool stickers)=>stickers?locationsUSUM:locationsSM;
private static readonly LocalizedText[] locationsSM = [
new("葱郁洞窟 - 考验地点","Verdant Cave - Trial Site","しげみのどうくつ - 試練の場"),
new("战争遗迹 - 室外","Ruins of Conflict - Outside","いくさのいせき - 屋外"),
new("１号道路 (白天)","Route 1 (Day)","１ばんどうろ (昼)"),
new("３号道路","Route 3","３ばんどうろ"),
new("３号道路 (白天)","Route 3 (Day)","３ばんどうろ (昼)"),
new("卡拉蔚湾","Kala'e Bay","カーラエわん"),
new("好奥乐墓园","Hau'oli Cemetery","ハウオリれいえん"),
new("２号道路","Route 2","２ばんどうろ"),
new("１号道路 - 训练家学校 (夜晚)","Route 1 - Trainer School (Night)","１ばんどうろ - トレーナーズスクール (夜)"),
new("好奥乐市 - 商业区","Hau'oli City - Shopping District","ハウオリシティ - ショッピングエリア"),
new("１号道路 - 郊外","Route 1 - Outskirts","１ばんどうろ - はずれ"),
new("好奥乐市 - 商业区 (夜晚)","Hau'oli City - Shopping District (Night)","ハウオリシティ - ショッピングエリア (夜)"),
new("１号道路","Route 1","１ばんどうろ"),
new("利利小镇 (夜晚)","Iki Town (Night)","リリィタウン (夜)"),
new("４号道路","Route 4","４ばんどうろ"),
new("欧哈纳牧场 (夜晚)","Paniola Ranch (Night)","オハナぼくじょう (夜)"),
new("欧哈纳牧场 (白天)","Paniola Ranch (Day)","オハナぼくじょう (昼)"),
new("维拉火山公园 - 顶部","Wela Volcano Park - Top","ヴェラかざんこうえん - 頂上"),
new("树荫丛林 - 洞穴","Lush Jungle - Cave","シェードジャングル - 洞窟"),
new("７号道路","Route 7","７ばんどうろ"),
new("阿卡拉岛郊外","Akala Outskirts","アーカラじまはずれ"),
new("皇家大道 (白天)","Royal Avenue (Day)","ロイヤルアベニュー (昼)"),
new("皇家大道 (夜晚)","Royal Avenue (Night)","ロイヤルアベニュー (夜)"),
new("可霓可市 (夜晚)","Konikoni City (Night)","コニコシティ (夜)"),
new("慷待市 (夜晚)","Heahea City (Night)","カンタイシティ (夜)"),
new("８号道路","Route 8","８ばんどうろ"),
new("８号道路 (白天)","Route 8 (Day)","８ばんどうろ (昼)"),
new("５号道路","Route 5","５ばんどうろ"),
new("豪诺豪诺海滩 (白天)","Hano Beach (Day)","ハノハノビーチ (昼)"),
new("慷待市","Heahea City","カンタイシティ"),
new("地鼠隧道","Diglett's Tunnel","ディグダトンネル"),
new("豪诺豪诺海滩","Hano Beach","ハノハノビーチ"),
new("马利埃庭园","Malie Garden","マリエていえん"),
new("马利埃静市 - 社区中心 (夜晚)","Malie City - Community Center (Night)","マリエシティ - 地域センター (夜)"),
new("马利埃静市 (白天)","Malie City (Day)","マリエシティ (昼)"),
new("马利埃静市 - 外侧海岬 (白天)","Malie City - Outer Cape (Day)","マリエシティ - はずれの岬 (昼)"),
new("１１号道路 (夜晚)","Route 11 (Night)","１１ばんどうろ (夜)"),
new("１２号道路 (白天)","Route 12 (Day)","１２ばんどうろ (昼)"),
new("１２号道路","Route 12","１２ばんどうろ"),
new("乌拉乌拉海滩 (夜晚)","Secluded Shore (Night)","ウラウラうらかいがん (夜)"),
new("火特力山","Blush Mountain","ホテリやま"),
new("１３号道路","Route 13","１３ばんどうろ"),
new("哈伊纳沙漠","Haina Desert","ハイナさばく"),
new("丰收遗迹 - 室外","Ruins of Abundance - Outside","みのりのいせき - 屋外"),
new("１４号道路","Route 14","１４ばんどうろ"),
new("１４号道路 (夜晚)","Route 14 (Night)","１４ばんどうろ (夜)"),
new("卡璞村","Tapu Village","カプのむら"),
new("１５号水路","Route 15","１５ばんすいどう"),
new("以太之家 (白天)","Aether House (Day)","エーテルハウス (昼)"),
new("乌拉乌拉花园 - 木板步道","Ula'ula Meadow - Boardwalk","ウラウラのはなぞの - 木道"),
new("１６号道路 (白天)","Route 16 (Day)","１６ばんどうろ (昼)"),
new("乌拉乌拉花园 - 草地","Ula'ula Meadow - Grass","ウラウラのはなぞの - 草むら"),
new("１７号道路 - 建筑","Route 17 - Building","１７ばんどうろ - 建物"),
new("１７号道路 - 高台","Route 17 - Ledge","１７ばんどうろ - 段差"),
new("魄镇 (夜晚)","Po Town (Night)","ポータウン (夜)"),
new("１０号道路 (白天)","Route 10 (Day)","１０ばんどうろ (昼)"),
new("辉克拉尼天文台 (夜晚)","Hokulani Observatory (Night)","ホクラニてんもんだい (夜)"),
new("拉纳基拉山 - 山腰","Mount Lanakila - Mountainside","ラナキラマウンテン - 山腹"),
new("拉纳基拉山 - 高处山腰","Mount Lanakila - High Mountainside","ラナキラマウンテン - 山腹の高所"),
new("乌拉乌拉海滩 (白天)","Secluded Shore (Day)","ウラウラうらかいがん (昼)"),
new("１３号道路 (夜晚)","Route 13 (Night)","１３ばんどうろ (夜)"),
new("魄镇 (白天)","Po Town (Day)","ポータウン (昼)"),
new("海洋居民之村 - 蓝色餐饮船","Seafolk Village - Blue Food Boat","うみのたみのむら - 青い飲食船"),
new("海洋居民之村 - 未建成的房屋","Seafolk Village - Unbuilt House","うみのたみのむら - 未完成の家"),
new("波尼原野 (白天)","Poni Wilds (Day)","ポニのげんや (昼)"),
new("波尼原野 (夜晚)","Poni Wilds (Night)","ポニのげんや (夜)"),
new("波尼原野","Poni Wilds","ポニのげんや"),
new("波尼古道 - 井旁 (白天)","Ancient Poni Path - Near Well (Day)","ポニのこどう - 井戸の近く (昼)"),
new("波尼古道 (夜晚)","Ancient Poni Path (Night)","ポニのこどう (夜)"),
new("波尼鼓浪岩岸 (白天)","Poni Breaker Coast (Day)","ポニのあらいそ (昼)"),
new("彼岸遗迹","Ruins of Hope","ひがんのいせき"),
new("波尼树林 - 山脚角落","Poni Grove - Mountain Corner","ポニのじゅりん - 山の角"),
new("波尼树林 - 灌木旁","Poni Grove - Near a Bush","ポニのじゅりん - 茂みの近く"),
new("波尼旷野 (白天)","Poni Plains (Day)","ポニのこうや (昼)"),
new("波尼旷野 (夜晚)","Poni Plains (Night)","ポニのこうや (夜)"),
new("波尼旷野","Poni Plains","ポニのこうや"),
new("波尼花园","Poni Meadow","ポニのはなぞの"),
new("波尼海岸 (夜晚)","Poni Coast (Night)","ポニのかいがん (夜)"),
new("波尼海岸","Poni Coast","ポニのかいがん"),
new("波尼险路 - 桥上","Poni Gauntlet - On Bridge","ポニのけんろ - 橋の上"),
new("波尼险路 - 有训练家的小岛","Poni Gauntlet - Island w/ Trainer","ポニのけんろ - トレーナーのいる島"),
new("终结洞窟 - 1F (白天)","Resolution Cave - 1F (Day)","エンドケイブ - 1F (昼)"),
new("终结洞窟 - B1F (夜晚)","Resolution Cave - B1F (Night)","エンドケイブ - B1F (夜)"),
new("波尼大峡谷 - 3F","Vast Poni Canyon - 3F","ポニのだいきょうこく - 3F"),
new("波尼大峡谷 - 2F","Vast Poni Canyon - 2F","ポニのだいきょうこく - 2F"),
new("波尼大峡谷 - 顶部","Vast Poni Canyon - Top","ポニのだいきょうこく - 頂上"),
new("波尼大峡谷 - 内部","Vast Poni Canyon - Inside","ポニのだいきょうこく - 内部"),
new("波尼古道 - 砖墙 (白天)","Ancient Poni Path - Brickwall (Day)","ポニのこどう - レンガの壁 (昼)"),
new("波尼鼓浪岩岸 (夜晚)","Poni Breaker Coast (Night)","ポニのあらいそ (夜)"),
new("终结洞窟 - B1F","Resolution Cave - B1F","エンドケイブ - B1F"),
new("以太乐园 B2F - 右侧走廊","Aether Foundation B2F - Right Hallway","エーテルパラダイス B2F - 右の通路"),
new("以太乐园 1F - 室外 - 右侧","Aether Foundation 1F - Outside - Right Side","エーテルパラダイス 1F - 屋外 - 右側"),
new("以太乐园 1F - 室外 (白天)","Aether Foundation 1F - Outside (Day)","エーテルパラダイス 1F - 屋外 (昼)"),
new("以太乐园 1F - 入口 (夜晚)","Aether Foundation 1F - Entrance (Night)","エーテルパラダイス 1F - 入口 (夜)"),
new("以太乐园 1F - 主楼","Aether Foundation 1F - Main Building","エーテルパラダイス 1F - 本館"),
];
private static readonly LocalizedText[] locationsUSUM = [
new("好奥乐市 (商业区) - 美发店 (室外)","Hau'oli City (Shopping) - Salon (Outside)","ハウオリシティ (ショッピングエリア) - ヘアサロン (屋外)"),
new("好奥乐市 (商业区) - 马拉萨达店 (室外)","Hau'oli City (Shopping) - Malasada Shop (Outside)","ハウオリシティ (ショッピングエリア) - マラサダショップ (屋外)"),
new("好奥乐市 (商业区) - 伊利马家 (2F)","Hau'oli City (Shopping) - Ilima's House (2F)","ハウオリシティ (ショッピングエリア) - イリマの家 (2F)"),
new("马利埃静市 - 图书馆 (1F)","Malie City - Library (1F)","マリエシティ - 図書館 (1F)"),
new("好奥乐市 (港口区) - 栈桥","Hau'oli City (Marina) - Pier","ハウオリシティ (ポートエリア) - 桟橋"),
new("２号道路 - 东南房屋","Route 2 - Southeast House","２ばんどうろ - 南東の家"),
new("好奥乐市 (商业区) - 伊利马家 (室外)","Hau'oli City (Shopping) - Ilima's House (Outside)","ハウオリシティ (ショッピングエリア) - イリマの家 (屋外)"),
new("好奥乐市 (商业区) - 市政厅","Hau'oli City (Shopping) - City Hall","ハウオリシティ (ショッピングエリア) - 市役所"),
new("慷待市 - 酒店 (3F)","Heahea City - Hotel (3F)","カンタイシティ - ホテル (3F)"),
new("２号道路 - 树果园房屋","Route 2 - Berry Fields House","２ばんどうろ - きのみ畑の家"),
new("２号道路 - 树果园房屋 (室外)","Route 2 - Berry Fields House (Outside)","２ばんどうろ - きのみ畑の家 (屋外)"),
new("皇家大道 - 东北","Royal Avenue - Northeast","ロイヤルアベニュー - 北東"),
new("好奥乐市 (商业区) - 宝可梦中心 (室外)","Hau'oli City (Shopping) - Pokemon Center (Outside)","ハウオリシティ (ショッピングエリア) - ポケモンセンター (屋外)"),
new("皇家大道 - 南侧","Royal Avenue - South","ロイヤルアベニュー - 南"),
new("辉克拉尼天文台 - 房间","Hokulani Observatory - Room","ホクラニてんもんだい - 部屋"),
new("辉克拉尼天文台 - 接待处","Hokulani Observatory - Reception","ホクラニてんもんだい - 受付"),
new("好奥乐市 (商业区) - 市政厅 (室外)","Hau'oli City (Shopping) - City Hall (Outside)","ハウオリシティ (ショッピングエリア) - 市役所 (屋外)"),
new("可霓可市 - 丽姿的宝石店 (2F)","Konikoni City - Olivia's Jewelry Shop (2F)","コニコシティ - ライチの宝石店 (2F)"),
new("慷待市 - 冲浪板 (室外)","Heahea City - Surfboard (Outside)","カンタイシティ - サーフボード (屋外)"),
new("魄镇 - 西南","Po Town - Southwest","ポータウン - 南西"),
new("豪诺豪诺度假地 大厅 - 西南水域","Hano Resort Lobby - Southwest Water","ハノハノリゾート ロビー - 南西の水辺"),
new("好奥乐市 (商业区) - 警察局西北","Hau'oli City (Shopping) - Northwest of Police Station","ハウオリシティ (ショッピングエリア) - 交番の北西"),
new("好奥乐市 (港口区) - 渡轮码头 (室外)","Hau'oli City (Marina) - Ferry Terminal (Outside)","ハウオリシティ (ポートエリア) - フェリーターミナル (屋外)"),
new("２号道路 - 东南房屋 (室外)","Route 2 - Southeast House (Outside)","２ばんどうろ - 南東の家 (屋外)"),
new("２号道路 - 宝可梦中心 (室外)","Route 2 - Pokemon Center (Outside)","２ばんどうろ - ポケモンセンター (屋外)"),
new("慷待市 - 西侧","Heahea City - West","カンタイシティ - 西"),
new("慷待市 - 酒店 西侧 (室外)","Heahea City - Hotel West (Outside)","カンタイシティ - ホテル 西 (屋外)"),
new("慷待市 - 酒店 东侧 (室外)","Heahea City - Hotel East (Outside)","カンタイシティ - ホテル 東 (屋外)"),
new("慷待市 - 研究所 东侧 (室外)","Heahea City - Research Lab East (Outside)","カンタイシティ - 研究所 東 (屋外)"),
new("慷待市 - 研究所 南侧 (室外)","Heahea City - Research Lab South (Outside)","カンタイシティ - 研究所 南 (屋外)"),
new("慷待市 - GAME FREAK","Heahea City - Game Freak","カンタイシティ - ゲームフリーク"),
new("辉克拉尼天文台 - 尽头","Hokulani Observatory - Dead End","ホクラニてんもんだい - 行き止まり"),
new("慷待市 - GAME FREAK 大楼 (3F)","Heahea City - Game Freak Building (3F)","カンタイシティ - ゲームフリークのビル (3F)"),
new("慷待市 - 研究所","Heahea City - Research Lab","カンタイシティ - 研究所"),
new("慷待市 - 酒店 (1F)","Heahea City - Hotel (1F)","カンタイシティ - ホテル (1F)"),
new("皇家巨蛋 - 2F","Battle Royal Dome - 2F","ロイヤルドーム - 2F"),
new("欧哈纳镇 - 西侧","Paniola Town - West","オハナタウン - 西"),
new("欧哈纳镇 - 卡奇家 (1F)","Paniola Town - Kiawe's House (1F)","オハナタウン - カキの家 (1F)"),
new("欧哈纳镇 - 卡奇家 (2F)","Paniola Town - Kiawe's House (2F)","オハナタウン - カキの家 (2F)"),
new("欧哈纳牧场 - 西北","Paniola Ranch - Northwest","オハナぼくじょう - 北西"),
new("欧哈纳牧场 - 东南","Paniola Ranch - Southeast","オハナぼくじょう - 南東"),
new("豪诺豪诺海滩","Hano Beach","ハノハノビーチ"),
new("豪诺豪诺度假地 - 南侧","Hano Resort - South","ハノハノリゾート - 南"),
new("豪诺豪诺度假地 - 北侧","Hano Resort - North","ハノハノリゾート - 北"),
new("可霓可市 灯塔 (经地鼠隧道)","Konikoni City Lighthouse (Through Diglett's Tunnel)","コニコシティ 灯台 (ディグダトンネル経由)"),
new("皇家巨蛋 - 1F","Battle Royal Dome - 1F","ロイヤルドーム - 1F"),
new("８号道路 - 以太基地 (室外)","Route 8 - Aether Base (Outside)","８ばんどうろ - エーテルベース (屋外)"),
new("８号道路 - 化石复原所 (室外)","Route 8 - Fossil Restoration Center (Outside)","８ばんどうろ - 化石復元所 (屋外)"),
new("可霓可市 - 西侧","Konikoni City - West","コニコシティ - 西"),
new("可霓可市 - 餐厅 (1F)","Konikoni City - Restaurant (1F)","コニコシティ - レストラン (1F)"),
new("利利小镇 - 西南","Iki Town - Southwest","リリィタウン - 南西"),
new("好奥乐市 (商业区) - 伊利马家游泳池","Hau'oli City (Shopping) - Ilima's House Pool","ハウオリシティ (ショッピングエリア) - イリマの家・プール"),
new("维拉火山公园 - 路牌后岩石","Wela Volcano Park - Rocks Behind Sign","ヴェラかざんこうえん - 看板の裏の岩"),
new("５号道路 - 宝可梦中心南侧","Route 5 - South of Pokemon Center","５ばんどうろ - ポケモンセンターの南"),
new("豪诺豪诺海滩 - 沙丘娃下方","Hano Beach - Below Sandygast","ハノハノビーチ - スナバァの下"),
new("马利埃静市 (外侧海岬) - 回收工厂 (室外)","Malie City (Outer Cape) - Recycling Plant (Outside)","マリエシティ (はずれの岬) - リサイクルプラント (屋外)"),
new("马利埃静市 - 渡轮码头 (室外)","Malie City - Ferry Terminal (Outside)","マリエシティ - フェリーターミナル (屋外)"),
new("马利埃静市 - 服装店 (室外)","Malie City - Apparel Shop (Outside)","マリエシティ - ブティック (屋外)"),
new("马利埃静市 - 美发店 (室外)","Malie City - Salon (Outside)","マリエシティ - ヘアサロン (屋外)"),
new("１６号道路 - 以太基地 (室外)","Route 16 - Aether Base (Outside)","１６ばんどうろ - エーテルベース (屋外)"),
new("火特力山 - 发电厂 (室外)","Blush Mountain - Power Plant (Outside)","ホテリやま - 発電所 (屋外)"),
new("马利埃静市 - 图书馆 (2F)","Malie City - Library (2F)","マリエシティ - 図書館 (2F)"),
new("马利埃庭园 - 东北","Malie Garden - Northeast","マリエていえん - 北東"),
new("马利埃静市 - 社区中心","Malie City - CommunityCenter","マリエシティ - 地域センター"),
new("辉克拉尼天文台 - 室外","Hokulani Observatory - Outside","ホクラニてんもんだい - 屋外"),
new("辉克拉尼山","Mount Hokulani","ホクラニだけ"),
new("火特力山 - 发电厂","Blush Mountain - Power Plant","ホテリやま - 発電所"),
new("１３号道路","Route 13","１３ばんどうろ"),
new("１４号道路 - 超值超市旧址前","Route 14 - Front of Abandoned Megamart","１４ばんどうろ - スーパー・メガやす跡地の前"),
new("１４号道路 - 北侧","Route 14 - North","１４ばんどうろ - 北"),
new("１５号水路 - 小岛冲浪板 (室外)","Route 15 - Islet Surfboard (Outside)","１５ばんすいどう - 小島のサーフボード (屋外)"),
new("１７号道路 - 警察局 (室外)","Route 17 - Police Station (Outside)","１７ばんどうろ - 交番 (屋外)"),
new("１７号道路 - 警察局","Route 17 - Police Station","１７ばんどうろ - 交番"),
new("魄镇 - 宝可梦中心 (室外)","Po Town - Pokemon Center (Outside)","ポータウン - ポケモンセンター (屋外)"),
new("椰蛋树岛 - 岩石下","Exeggutor Island - Under Rock","ナッシー・アイランド - 岩の下"),
new("魄镇 - 可疑宅邸 东侧 (室外)","Po Town - Shady House East (Outside)","ポータウン - いかがわしき屋敷 東 (屋外)"),
new("魄镇 - 宝可梦中心","Po Town - Pokemon Center","ポータウン - ポケモンセンター"),
new("魄镇 - 可疑宅邸 (1F)","Po Town - Shady House (1F)","ポータウン - いかがわしき屋敷 (1F)"),
new("１３号道路 - 汽车旅馆 (室外)","Route 13 - Motel (Outside)","１３ばんどうろ - モーテル (屋外)"),
new("魄镇 - 可疑宅邸 2F (室外)","Po Town - Shady House 2F (Outside)","ポータウン - いかがわしき屋敷 2F (屋外)"),
new("１７号道路 - 魄镇南侧","Route 17 - South of Po Town","１７ばんどうろ - ポータウンの南"),
new("乌拉乌拉花园","Ula'ula Meadow","ウラウラのはなぞの"),
new("魄镇 - 可疑宅邸 西侧 岩石 (室外) 1","Po Town - Shady House West Rocks (Outside) 1","ポータウン - いかがわしき屋敷 西 岩 (屋外) 1"),
new("魄镇 - 可疑宅邸 西侧 岩石 (室外) 2","Po Town - Shady House West Rocks (Outside) 2","ポータウン - いかがわしき屋敷 西 岩 (屋外) 2"),
new("魄镇 - 可疑宅邸 西侧 岩石 (室外) 3","Po Town - Shady House West Rocks (Outside) 3","ポータウン - いかがわしき屋敷 西 岩 (屋外) 3"),
new("海洋居民之村 - 东南鲶鱼王船 (茉莉的船) (室外)","Seafolk Village - Southeast Whiscash (Mina's Ship) (Outside)","うみのたみのむら - 南東・ナマズン船 (マツリカの船) (屋外)"),
new("海洋居民之村 - 西南猎斑鱼船","Seafolk Village - Southwest Huntail","うみのたみのむら - 南西・ハンテール船"),
new("海洋居民之村 - 西南猎斑鱼船 (室外)","Seafolk Village - Southwest Huntail (Outside)","うみのたみのむら - 南西・ハンテール船 (屋外)"),
new("海洋居民之村 - 东南鲶鱼王船 (茉莉的船)","Seafolk Village - Southeast Whiscash (Mina's Ship)","うみのたみのむら - 南東・ナマズン船 (マツリカの船)"),
new("海洋居民之村 - 西侧吼鲸王船 (餐厅)","Seafolk Village - West Wailord (Restaurant)","うみのたみのむら - 西・ホエルオー船 (レストラン)"),
new("海洋居民之村 - 东侧大钢蛇船","Seafolk Village - East Steelix","うみのたみのむら - 東・ハガネール船"),
new("波尼原野 - 东南","Poni Wilds - Southeast","ポニのげんや - 南東"),
new("波尼古道 - 哈普乌家 (厨房)","Ancient Poni Path - Hapu's House (Kitchen)","ポニのこどう - ハプウの家 (台所)"),
new("海洋居民之村 - 东北","Seafolk Village - Northeast","うみのたみのむら - 北東"),
new("波尼古道 - 哈普乌家 (卧室)","Ancient Poni Path - Hapu's House (Bedroom)","ポニのこどう - ハプウの家 (寝室)"),
new("波尼古道 - 西南","Ancient Poni Path - Southwest","ポニのこどう - 南西"),
new("波尼古道 - 哈普乌家 (庭院)","Ancient Poni Path - Hapu's House (Courtyard)","ポニのこどう - ハプウの家 (庭)"),
new("波尼古道 - 哈普乌家 (室外井后)","Ancient Poni Path - Hapu's House (Outside Behind Well)","ポニのこどう - ハプウの家 (屋外・井戸の裏)"),
new("波尼古道 - 东北","Ancient Poni Path - Northeast","ポニのこどう - 北東"),
new("对战树 - 入口","Battle Tree - Entrance","バトルツリー - 入口"),
];
}
