import type { Gen7EggFrameRequest } from "./domain";

export const GEN7_EGG_TEST_REQUEST: Gen7EggFrameRequest = {
  mode: "frames",
  state: [0x1234_5678, 0x9abc_def0, 0x0fed_cba9, 0x8765_4321],
  minFrame: 0,
  maxFrame: 2,
  tsv: 1234,
  trv: 8,
  male: {
    ivs: [31, 31, 31, 31, 31, 31],
    item: "destiny-knot",
    ability: 0,
    ditto: false,
  },
  female: {
    ivs: [0, 1, 2, 3, 4, 5],
    item: "everstone",
    ability: 2,
    ditto: false,
  },
  genderRatio: "one-to-one",
  shinyCharm: true,
  masudaMethod: true,
  nidoType: false,
  homogeneous: true,
  considerOtherTsv: true,
  otherTsvs: [1, 2048, 4095],
  shinyReminder: true,
  filters: {
    disabled: true,
    shiny: "shiny",
    gender: "any",
    ability: "any",
    natureMask: 0x1ff_ffff,
    hiddenPowerMask: 0xffff,
    ivMin: [0, 0, 0, 0, 0, 0],
    ivMax: [31, 31, 31, 31, 31, 31],
    perfectIvValue: 31,
    perfectIvCount: 0,
    ball: "any",
    natureInheritance: "any",
  },
  resultLimit: 100,
};
