// PokeFinder 4.3.2 Core/Resources/i18n ability tables, IDs 1..77.
const names = {
  en: [
    "Stench",
    "Drizzle",
    "Speed Boost",
    "Battle Armor",
    "Sturdy",
    "Damp",
    "Limber",
    "Sand Veil",
    "Static",
    "Volt Absorb",
    "Water Absorb",
    "Oblivious",
    "Cloud Nine",
    "Compound Eyes",
    "Insomnia",
    "Color Change",
    "Immunity",
    "Flash Fire",
    "Shield Dust",
    "Own Tempo",
    "Suction Cups",
    "Intimidate",
    "Shadow Tag",
    "Rough Skin",
    "Wonder Guard",
    "Levitate",
    "Effect Spore",
    "Synchronize",
    "Clear Body",
    "Natural Cure",
    "Lightning Rod",
    "Serene Grace",
    "Swift Swim",
    "Chlorophyll",
    "Illuminate",
    "Trace",
    "Huge Power",
    "Poison Point",
    "Inner Focus",
    "Magma Armor",
    "Water Veil",
    "Magnet Pull",
    "Soundproof",
    "Rain Dish",
    "Sand Stream",
    "Pressure",
    "Thick Fat",
    "Early Bird",
    "Flame Body",
    "Run Away",
    "Keen Eye",
    "Hyper Cutter",
    "Pickup",
    "Truant",
    "Hustle",
    "Cute Charm",
    "Plus",
    "Minus",
    "Forecast",
    "Sticky Hold",
    "Shed Skin",
    "Guts",
    "Marvel Scale",
    "Liquid Ooze",
    "Overgrow",
    "Blaze",
    "Torrent",
    "Swarm",
    "Rock Head",
    "Drought",
    "Arena Trap",
    "Vital Spirit",
    "White Smoke",
    "Pure Power",
    "Shell Armor",
    "Air Lock",
    "Tangled Feet",
  ],
  zh: [
    "恶臭",
    "降雨",
    "加速",
    "战斗盔甲",
    "结实",
    "湿气",
    "柔软",
    "沙隐",
    "静电",
    "蓄电",
    "储水",
    "迟钝",
    "无关天气",
    "复眼",
    "不眠",
    "变色",
    "免疫",
    "引火",
    "鳞粉",
    "我行我素",
    "吸盘",
    "威吓",
    "踩影",
    "粗糙皮肤",
    "神奇守护",
    "飘浮",
    "孢子",
    "同步",
    "恒净之躯",
    "自然回复",
    "避雷针",
    "天恩",
    "悠游自如",
    "叶绿素",
    "发光",
    "复制",
    "大力士",
    "毒刺",
    "精神力",
    "熔岩铠甲",
    "水幕",
    "磁力",
    "隔音",
    "雨盘",
    "扬沙",
    "压迫感",
    "厚脂肪",
    "早起",
    "火焰之躯",
    "逃跑",
    "锐利目光",
    "怪力钳",
    "捡拾",
    "懒惰",
    "活力",
    "迷人之躯",
    "正电",
    "负电",
    "阴晴不定",
    "黏着",
    "蜕皮",
    "毅力",
    "神奇鳞片",
    "污泥浆",
    "茂盛",
    "猛火",
    "激流",
    "虫之预感",
    "坚硬脑袋",
    "日照",
    "沙穴",
    "干劲",
    "白色烟雾",
    "瑜伽之力",
    "硬壳盔甲",
    "气闸",
    "蹒跚",
  ],
  ja: [
    "あくしゅう",
    "あめふらし",
    "かそく",
    "カブトアーマー",
    "がんじょう",
    "しめりけ",
    "じゅうなん",
    "すながくれ",
    "せいでんき",
    "ちくでん",
    "ちょすい",
    "どんかん",
    "ノーてんき",
    "ふくがん",
    "ふみん",
    "へんしょく",
    "めんえき",
    "もらいび",
    "りんぷん",
    "マイペース",
    "きゅうばん",
    "いかく",
    "かげふみ",
    "さめはだ",
    "ふしぎなまもり",
    "ふゆう",
    "ほうし",
    "シンクロ",
    "クリアボディ",
    "しぜんかいふく",
    "ひらいしん",
    "てんのめぐみ",
    "すいすい",
    "ようりょくそ",
    "はっこう",
    "トレース",
    "ちからもち",
    "どくのトゲ",
    "せいしんりょく",
    "マグマのよろい",
    "みずのベール",
    "じりょく",
    "ぼうおん",
    "あめうけざら",
    "すなおこし",
    "プレッシャー",
    "あついしぼう",
    "はやおき",
    "ほのおのからだ",
    "にげあし",
    "するどいめ",
    "かいりきバサミ",
    "ものひろい",
    "なまけ",
    "はりきり",
    "メロメロボディ",
    "プラス",
    "マイナス",
    "てんきや",
    "ねんちゃく",
    "だっぴ",
    "こんじょう",
    "ふしぎなうろこ",
    "ヘドロえき",
    "しんりょく",
    "もうか",
    "げきりゅう",
    "むしのしらせ",
    "いしあたま",
    "ひでり",
    "ありじごく",
    "やるき",
    "しろいけむり",
    "ヨガパワー",
    "シェルアーマー",
    "エアロック",
    "ちどりあし",
  ],
} as const;

export function getGen3AbilityName(language: string, ability: number) {
  const table = language.startsWith("zh")
    ? names.zh
    : language.startsWith("ja")
      ? names.ja
      : names.en;
  return table[ability - 1] ?? String(ability);
}
