/*!
 * Generated from PokeFinder 4.3.2 Gen IV personal and i18n resources.
 * GPL-3.0-or-later. Do not hand-edit; rerun scripts/generate_gen4_iv_data.mjs.
 */

export type Gen4PersonalDataSet = "platinum" | "hgss";
export type Gen4PersonalVersion = "diamond" | "pearl" | Gen4PersonalDataSet;
export type Gen4IvDataLanguage = "en" | "ja" | "zh";
export type Gen4BaseStats = [number, number, number, number, number, number];

const encodedPersonal: Record<Gen4PersonalVersion, string> = {
  diamond:
    "AAAAAAAAAAAtMTFBQS1BQTw+P1BQPEFBUFJTZGRQQUEnNCs8MkFCQjpAOlBBUEJCTlRObVVkQkIsMEEyQCtDQzs/UEFQOkNDT1NkVWlOQ0MtHiMUFC0TEzIUNxkZHj09PC0yUFBGDg4oIx4UFDITEy0ZMhkZIz09QVAoLVBLREQoLSgjIzgzTT88NzIyRzNNU1BLRkZbM00eOCMZI0gyPjdRPDJGYTI+KDweHx9GMzNBWkE9PWQzMyM8LCg2NxY9PFVFQU9QFj0jNx4yKFoJCTxaN1pQZAkJMktVFB4oCAhLZG4tN0EICDcvNCgoKSZPRj5DNzc4Jk9aUldLVUwmTy45KCgoMiZPPUg5NzdBJk9RXE1VS1UmT0YtMDxBIzhiX0ZJVVo8OGImKSgyQUESEklMS1FkZBIScy0ULRkUODiMRi1LMi04OCgtIx4oNycnS1BGQUtaJyctMjdLQR4iIjxBRlVLKCIiS1BVZFoyIiIjRjctNxkbVzxfUDxQHhtXPDcyKDctDm5GQTxaS1oTbgo3GSMtXwhHI1AyMkZ4CEcoLSMoKFo1ZUFGPEFBcwdlMjQwQTI3Bg1QUk5fUFUGDShQIyMtRkhTQWk8PEZfSFM3Ri1GMjwWElpuUGRQXxYSKDIoKChaCwZBQUEyMloLBlpVX0ZaRgsGGRQPaTdaHCcoIx54RmkcJzcyLYdVeBwnRlAyIyMjPmNQZEYyPC0+Y1qCUEFVNz5jMksjRh4oIiJBWjJVLTciIlBpQWQ8RiIiKCgjMmRGHUBQRkFQeGQdQChQZB4eFEUFN19zLS0jRQVQboI3QS1FBTJVN0FBWjISQWRGUFBpMhJaQUEoKA8MFF9LbmRQHgwUGSNGXzctKgUyPF94RkYqBTRBNzo+PDMnI1UtIyNLMjA8bkY8PGQyMEEtNy1GLS9dWkZQRl9GL11QUDIoMhkBPGlpS0FkMgE8HkFkLRkoS1wyX7RVLUZLXB4jHmQjUBoaLTItczdfGho8QTyCS24aGiMtoB4tRkUFPDAtK1oqD2xVSUZJc0MPbB5pWhkZMjRLN4JzMjJLNEsoHjI3N2QrCTwyRlBQjCsJPChQPC0oIiJfX1V9QTciIjIyXygyI0UfPFBuMlAtRR8yeDUjblcHeDJpTyNuTDNZWjdLPEseFAwoQV88LSMaGkFaeFVGPBoaUFVfHh4ZH0VpgngtLSgfRfoFBSNpMh4gQTdzZCg8ImZpX1AoUFowcR4oRkYZPCFhN0FfXy1VJmEtQzwjMj8hKVBcQUFQRCEpHi03RjdVIx48S1VkVXMjHigtQWR4WitvRm5QN1BpRGVBMiNzX18MbEFTOV9VaQkJQV85ZFVdMTFBfWQ3RlU0aEtkXyhGbhZTFAo3DxRQISFffU88ZFEWFoJVUFVfPAtLMDAwMDAwBwc3NzItQTcyW4JBPG5fQQsLQUE8bl+CCgpBgjxfbkESEkE8RlVLKCRYIyhkWjcjIUtGPH1zRjchSx5QWjctNyEEPHNpQUZQIQRQaUE8S4JFLqBuQUFuHhEvWlVkX31VLi5aWlV9WmQuLlpkWn1VWi4uKUAtMjIyPT09VEFGRkY9PVuGX2RkUCcnam5amlqCLi5kZGRkZGQcHC0xQTFBLUFBPD5QP1A8QUFQUmRTZFBBQSc0KzwyQUJCOkA6UEFQQkJOVE5tVWRCQjJBQCwwK0NDQVBQOz86Q0NVaWRPU05DQyMuIiMtFDIzVUxALTdaMjM8Hh4kODIPM2QyMkxgRg8zKBQeKFA3RDA3IzI3blVEMCg8KCgoHkQPRlpGPDwoRA9VWlBGUIInJ0smJjg4QwojfTo6TExDCiMUKA8jIzwJCTIZHC03DzhiWh4PKBQPODgjFEEoQRQ3IDcoVVBpKDcgKDItRi1GHDBBS0ZfRl8cMDcoKEEtIwkJRjc3UDwtCQlaS0tzWjcJCUtQVVpkMiIiRhQyFDIoLyVkMlAyUDIvJUZkcx5BHgVFWktLWmRGCwYjIygjNzIiZjctMi1BUCJmSzdGN1VuImY3RjcoN1UyNR4eHh4eHiJeS0s3aVUeIl5BQS1LLV8DDjctLRkZDwYLX1VVQUEjBgtBQTyCX24cHF9BbjyCQRwcPFUqVSpbD2lfS1Bkbh4MFDw8PFVVVRoaMEgwSDAwGhq+ITohOiEXF0ZQQVpBVScwMkFaIyMPBQVLWow8PCgFBWRGRkFBLSAyQUtpI0FVNAhLVcg3QR5FBTxQMigoHhYyWnhLPDwtFl9BX0s3N1UmIUaCZDdQQURlFArmCuYFBVJQfUsoX1VEPjdfNyNLcyczPFAyMjIoNV9agktLSzc+XygoKEYoFCgxMjJ4UFAeKDEyMigeHjIMUWRkUDw8MgxRNzdVQVUjNx4jQSNBI0E3YUtpS2lLLRVhLTctQS1LSDdBKEZQjEYhC0FQjChGRjMFLTweUDJBMBJLWjJuUF8wEktfX19fVSFhWjw8KCgoNTVaeHg8PDIFBVVQWmlfPCRYSV8+VUFVFnc3FCMULUsUZSMjIyMjIz5QMl9fI25GFmUtHg9VQUEMbC0/JUE3XwkJLUslRjdTMTFfUGkoRmQvcf8KCkuHNx4gWlVLc2RzLi5zc1VaS2QuLmRLc1pzVS4uMkAyLTIpPj5GVEZBRjM9PWSGbl9kPS0talqCWppuLi5qglpumlouLmRkZGRkZB4eKC0jQTdGQUEyQS1VQV9BQUZVQWlVeEFBLTwoRjItQkI8VTxVPDdCQlB4Rm5GUEJCMkYyMjIoQ0NGVUY8RjJDQ2RuWlVaPENDIzcjHh4jMl9GWkY8PEYWXyYeKR4pPDVSTkY9Mj1kNVItLSMUHhQTEzIjNxkZDz09PEYyWjJBREQyIzcZGQ89PTwyRjJaQRMTKB4eKDIeISw8MjI8RjIhLFBGRlpkRiEsKCgyHh4eIjBGRig8KDwiMFpkPFo8UCIwKDceHh5VPj48VTwyMn0+PigeHjceVTMzPDJkVUZBMzMcGRktIygcJCYjI0E3MhwkREFBfXNQHCQoHiAyNEEhIUY8PlBSPBYWPCg8KDwjG1o8glA8PEYbWjw8PCMjHjY2UFBQNzdaSEiWoGRfQWQ2Nh8tWh4eKA4OPVotMjKgAwMBWi0eHigZGUAzFzMXHCsrVEcrRyswKytoWz9bP0QrK0g8HhQeGS8+kHg8KDwyLz4yFCgUKBQvJR4thy1aHgUqMi0tIyMyOGBGQUE3N0Y4YDJLS0FBMjNkMlVVNzcyNBYyRmQoKB4FRTxajDIyKAVFRm60PDwyBUUeKDcoNzxKSjw8SzxLUEpKKC0oQShBCR9GSzxpPGkJHzwyKFVLXzk5PCgyS1VfOjpBSTcvS1UjREEvN0lLVQxuMjwtZFBBHiZGKzUrNShAPGRJU0lTN0A8LVoUQRRBGBhGeChfKF8YGIJGI0YjPCkMqlotWi08KQw8PChBLSMMVkZkRmlLKCh0RlWMVUYUSUk8GSNGUDwvFFAtQVpuUC8UPDw8PDw8FE0tZC0tLQo0RzJGMjIyRhoaUGRQUFBkGhoyVShVKCMICEZzPHM8NwgILSg8KEsyHh5LRlpGaVAeHklzPDw8WhERSWQ8ZDxBPT1GN0FfVUYaGkZfVTdBRhoaMjArLik8DGtuTklMRzwMaytQQTIjIzRLP3hVWjc3NEsoKDcoRjcaGjxGaUZ4SxoaQilNPVcXFRVWUWFRaysVFS1fMigySwQES31kRlAtBAQUDxQKN1AhIV88T2R9UT8/RkZGRkZGOzs8WkY8eCgQECxLIz8hLQ93QHNBUz9BD3cUKFoeWhkaGihGgjyCGS4uY0RTSFczIl5BMkZfUEEaGkGCPEs8Sy5pXxcwFzAXFxcyMjIyMjInc1BQUFBQUCdzRigyNzIZL3NaPEZLRi0vc25QWl9aQS9zI0BVSjcgS0s3aGleSzQhITdUaXJLNCEhZFqCLUE3IUUrHjcoQWEhIS1LPCgeMkVFQV9kPDIyRUVfh1BuUGQWFig3UCM8Hh0dPEtkN1AyHR1Qh4JfWkYdHVBkyDJkMh0dUDJkZMgyHR1QS5ZLljIdHVBQWm6CbhoaUFpQgm5uGhpkZFqWjFoCAmSWjGRaWkZGaZZallpfTExkZGRkZGQgIDKWMpYyli4uN0RALTcfQUFLWVU3QSRBQV9taUtVOEFBLDosOiw9QkJATjRONFFCQkxoR2hHbEJCNTM1PTgoQ0NAQkRRTDJDQ1RWWG9lPENDKDceHh48MzM3SzIoKFAWFlV4RjIyZBYWOy0oIygfVm1PVTw3PEdWbSUZKRkpGT09TVUzNzNBREQtQSIoIi1PFjxVMTwxPE8WUHhPX09GTxYoHiMyRjceJjxGN31pWh4mQ30oHh46aGhhpTxBMjpoaB4qdipYHgUFPDSoL4oeBQUoHS0dLSQ9PTw7VU9pJGtrRl4yXjJCREQeHioeKkZ2dkZQZlBmKC4uPC1GLVpfMjU3QSM8HlUhIVVpN1UycyEhLSMtPjUjIiJGPEZXTlV6ekwwMDk+Ijxyb1NEXFInPHJLZEI8QnNlNVoyIjwsRmpUllAsWjZQalQ3QiwsOFUyZ0FMVDZgaThnPDw8aWlpGhpkfTRpNEcPaTE3KiolVQcUR1JAQDtwLxQtHjJBMi0aGj8/LykpSgFqZ11DRz1UAWo5GFYYVhcaVUNZdE90IRpVMlBfCi0KBUUUGS1GWjwrb2QFBQ9BHh4gTEEtXCpbM00yXGxcbCMuLjpGLSgtKggIRFpBMjdSCAhsgl9QVWYICIdVKChVBTUvKEYoIyg8UCdGbkZzRlpQJ0RITiYqIC0tbHB2REgvLS0oMloeN0EEYUZabjxLXwRhMD0oPSgya1dTakFWQVVrV0pkSFpILhoaMTE4MT1CIXJFRUxFVlshci0UMjx4MiELPD4yPjwodXVaXEtcVTx1dUZ4QS1VfS4uRkZzglo8KgVuVV9QXzIUDHOMgjc3KB90ZGR9bjIyImZLe0NfVV9OTktfQ31fUzExVTJfeHNQNyBWTFZ0OF8DbkFugjxBX2ZmQTxugl9BUVFLX30tS180CG6CUEY8UAxRVVBGh0taW1hEfUFBc1BQUDw3kUuWKAUqLWSHQYctLi5GUEZQRm5RUTIyTV9NWxoaS0uCS4JfGhpQaWlpaVAaGkt9Rn1GcxoaZHh4lmRaLi5aeGSWeGQuLltaaoJqTRISbqBuUG5kcHCWZHhkeFouLnhGeEuCVRoaUFBQUFBQXV1kZGRkZGRdXUZaWodafXt7ZGRkZGRkHh54eHh4eHh5eQoKCgoKCgAACgoKCgoKAAAytBS0FJYuLjJGoEagWi4uMl9aX1q0Li48T2k7VSRrazxFX0VfJGtr",
  pearl:
    "AAAAAAAAAAAtMTFBQS1BQTw+P1BQPEFBUFJTZGRQQUEnNCs8MkFCQjpAOlBBUEJCTlRObVVkQkIsMEEyQCtDQzs/UEFQOkNDT1NkVWlOQ0MtHiMUFC0TEzIUNxkZHj09PC0yUFBGDg4oIx4UFDITEy0ZMhkZIz09QVAoLVBLREQoLSgjIzgzTT88NzIyRzNNU1BLRkZbM00eOCMZI0gyPjdRPDJGYTI+KDweHx9GMzNBWkE9PWQzMyM8LCg2NxY9PFVFQU9QFj0jNx4yKFoJCTxaN1pQZAkJMktVFB4oCAhLZG4tN0EICDcvNCgoKSZPRj5DNzc4Jk9aUldLVUwmTy45KCgoMiZPPUg5NzdBJk9RXE1VS1UmT0YtMDxBIzhiX0ZJVVo8OGImKSgyQUESEklMS1FkZBIScy0ULRkUODiMRi1LMi04OCgtIx4oNycnS1BGQUtaJyctMjdLQR4iIjxBRlVLKCIiS1BVZFoyIiIjRjctNxkbVzxfUDxQHhtXPDcyKDctDm5GQTxaS1oTbgo3GSMtXwhHI1AyMkZ4CEcoLSMoKFo1ZUFGPEFBcwdlMjQwQTI3Bg1QUk5fUFUGDShQIyMtRkhTQWk8PEZfSFM3Ri1GMjwWElpuUGRQXxYSKDIoKChaCwZBQUEyMloLBlpVX0ZaRgsGGRQPaTdaHCcoIx54RmkcJzcyLYdVeBwnRlAyIyMjPmNQZEYyPC0+Y1qCUEFVNz5jMksjRh4oIiJBWjJVLTciIlBpQWQ8RiIiKCgjMmRGHUBQRkFQeGQdQChQZB4eFEUFN19zLS0jRQVQboI3QS1FBTJVN0FBWjISQWRGUFBpMhJaQUEoKA8MFF9LbmRQHgwUGSNGXzctKgUyPF94RkYqBTRBNzo+PDMnI1UtIyNLMjA8bkY8PGQyMEEtNy1GLS9dWkZQRl9GL11QUDIoMhkBPGlpS0FkMgE8HkFkLRkoS1wyX7RVLUZLXB4jHmQjUBoaLTItczdfGho8QTyCS24aGiMtoB4tRkUFPDAtK1oqD2xVSUZJc0MPbB5pWhkZMjRLN4JzMjJLNEsoHjI3N2QrCTwyRlBQjCsJPChQPC0oIiJfX1V9QTciIjIyXygyI0UfPFBuMlAtRR8yeDUjblcHeDJpTyNuTDNZWjdLPEseFAwoQV88LSMaGkFaeFVGPBoaUFVfHh4ZH0VpgngtLSgfRfoFBSNpMh4gQTdzZCg8ImZpX1AoUFowcR4oRkYZPCFhN0FfXy1VJmEtQzwjMj8hKVBcQUFQRCEpHi03RjdVIx48S1VkVXMjHigtQWR4WitvRm5QN1BpRGVBMiNzX18MbEFTOV9VaQkJQV85ZFVdMTFBfWQ3RlU0aEtkXyhGbhZTFAo3DxRQISFffU88ZFEWFoJVUFVfPAtLMDAwMDAwBwc3NzItQTcyW4JBPG5fQQsLQUE8bl+CCgpBgjxfbkESEkE8RlVLKCRYIyhkWjcjIUtGPH1zRjchSx5QWjctNyEEPHNpQUZQIQRQaUE8S4JFLqBuQUFuHhEvWlVkX31VLi5aWlV9WmQuLlpkWn1VWi4uKUAtMjIyPT09VEFGRkY9PVuGX2RkUCcnam5amlqCLi5kZGRkZGQcHC0xQTFBLUFBPD5QP1A8QUFQUmRTZFBBQSc0KzwyQUJCOkA6UEFQQkJOVE5tVWRCQjJBQCwwK0NDQVBQOz86Q0NVaWRPU05DQyMuIiMtFDIzVUxALTdaMjM8Hh4kODIPM2QyMkxgRg8zKBQeKFA3RDA3IzI3blVEMCg8KCgoHkQPRlpGPDwoRA9VWlBGUIInJ0smJjg4QwojfTo6TExDCiMUKA8jIzwJCTIZHC03DzhiWh4PKBQPODgjFEEoQRQ3IDcoVVBpKDcgKDItRi1GHDBBS0ZfRl8cMDcoKEEtIwkJRjc3UDwtCQlaS0tzWjcJCUtQVVpkMiIiRhQyFDIoLyVkMlAyUDIvJUZkcx5BHgVFWktLWmRGCwYjIygjNzIiZjctMi1BUCJmSzdGN1VuImY3RjcoN1UyNR4eHh4eHiJeS0s3aVUeIl5BQS1LLV8DDjctLRkZDwYLX1VVQUEjBgtBQTyCX24cHF9BbjyCQRwcPFUqVSpbD2lfS1Bkbh4MFDw8PFVVVRoaMEgwSDAwGhq+ITohOiEXF0ZQQVpBVScwMkFaIyMPBQVLWow8PCgFBWRGRkFBLSAyQUtpI0FVNAhLVcg3QR5FBTxQMigoHhYyWnhLPDwtFl9BX0s3N1UmIUaCZDdQQURlFArmCuYFBVJQfUsoX1VEPjdfNyNLcyczPFAyMjIoNV9agktLSzc+XygoKEYoFCgxMjJ4UFAeKDEyMigeHjIMUWRkUDw8MgxRNzdVQVUjNx4jQSNBI0E3YUtpS2lLLRVhLTctQS1LSDdBKEZQjEYhC0FQjChGRjMFLTweUDJBMBJLWjJuUF8wEktfX19fVSFhWjw8KCgoNTVaeHg8PDIFBVVQWmlfPCRYSV8+VUFVFnc3FCMULUsUZSMjIyMjIz5QMl9fI25GFmUtHg9VQUEMbC0/JUE3XwkJLUslRjdTMTFfUGkoRmQvcf8KCkuHNx4gWlVLc2RzLi5zc1VaS2QuLmRLc1pzVS4uMkAyLTIpPj5GVEZBRjM9PWSGbl9kPS0talqCWppuLi5qglpumlouLmRkZGRkZB4eKC0jQTdGQUEyQS1VQV9BQUZVQWlVeEFBLTwoRjItQkI8VTxVPDdCQlB4Rm5GUEJCMkYyMjIoQ0NGVUY8RjJDQ2RuWlVaPENDIzcjHh4jMl9GWkY8PEYWXyYeKR4pPDVSTkY9Mj1kNVItLSMUHhQTEzIjNxkZDz09PEYyWjJBREQyIzcZGQ89PTwyRjJaQRMTKB4eKDIeISw8MjI8RjIhLFBGRlpkRiEsKCgyHh4eIjBGRig8KDwiMFpkPFo8UCIwKDceHh5VPj48VTwyMn0+PigeHjceVTMzPDJkVUZBMzMcGRktIygcJCYjI0E3MhwkREFBfXNQHCQoHiAyNEEhIUY8PlBSPBYWPCg8KDwjG1o8glA8PEYbWjw8PCMjHjY2UFBQNzdaSEiWoGRfQWQ2Nh8tWh4eKA4OPVotMjKgAwMBWi0eHigZGUAzFzMXHCsrVEcrRyswKytoWz9bP0QrK0g8HhQeGS8+kHg8KDwyLz4yFCgUKBQvJR4thy1aHgUqMi0tIyMyOGBGQUE3N0Y4YDJLS0FBMjNkMlVVNzcyNBYyRmQoKB4FRTxajDIyKAVFRm60PDwyBUUeKDcoNzxKSjw8SzxLUEpKKC0oQShBCR9GSzxpPGkJHzwyKFVLXzk5PCgyS1VfOjpBSTcvS1UjREEvN0lLVQxuMjwtZFBBHiZGKzUrNShAPGRJU0lTN0A8LVoUQRRBGBhGeChfKF8YGIJGI0YjPCkMqlotWi08KQw8PChBLSMMVkZkRmlLKCh0RlWMVUYUSUk8GSNGUDwvFFAtQVpuUC8UPDw8PDw8FE0tZC0tLQo0RzJGMjIyRhoaUGRQUFBkGhoyVShVKCMICEZzPHM8NwgILSg8KEsyHh5LRlpGaVAeHklzPDw8WhERSWQ8ZDxBPT1GN0FfVUYaGkZfVTdBRhoaMjArLik8DGtuTklMRzwMaytQQTIjIzRLP3hVWjc3NEsoKDcoRjcaGjxGaUZ4SxoaQilNPVcXFRVWUWFRaysVFS1fMigySwQES31kRlAtBAQUDxQKN1AhIV88T2R9UT8/RkZGRkZGOzs8WkY8eCgQECxLIz8hLQ93QHNBUz9BD3cUKFoeWhkaGihGgjyCGS4uY0RTSFczIl5BMkZfUEEaGkGCPEs8Sy5pXxcwFzAXFxcyMjIyMjInc1BQUFBQUCdzRigyNzIZL3NaPEZLRi0vc25QWl9aQS9zI0BVSjcgS0s3aGleSzQhITdUaXJLNCEhZFqCLUE3IUUrHjcoQWEhIS1LPCgeMkVFQV9kPDIyRUVfh1BuUGQWFig3UCM8Hh0dPEtkN1AyHR1Qh4JfWkYdHVBkyDJkMh0dUDJkZMgyHR1QS5ZLljIdHVBQWm6CbhoaUFpQgm5uGhpkZFqWjFoCAmSWjGRaWkZGaZZallpfTExkZGRkZGQgIDKWMpYyli4uN0RALTcfQUFLWVU3QSRBQV9taUtVOEFBLDosOiw9QkJATjRONFFCQkxoR2hHbEJCNTM1PTgoQ0NAQkRRTDJDQ1RWWG9lPENDKDceHh48MzM3SzIoKFAWFlV4RjIyZBYWOy0oIygfVm1PVTw3PEdWbSUZKRkpGT09TVUzNzNBREQtQSIoIi1PFjxVMTwxPE8WUHhPX09GTxYoHiMyRjceJjxGN31pWh4mQ30oHh46aGhhpTxBMjpoaB4qdipYHgUFPDSoL4oeBQUoHS0dLSQ9PTw7VU9pJGtrRl4yXjJCREQeHioeKkZ2dkZQZlBmKC4uPC1GLVpfMjU3QSM8HlUhIVVpN1UycyEhLSMtPjUjIiJGPEZXTlV6ekwwMDk+Ijxyb1NEXFInPHJLZEI8QnNlNVoyIjwsRmpUllAsWjZQalQ3QiwsOFUyZ0FMVDZgaThnPDw8aWlpGhpkfTRpNEcPaTE3KiolVQcUR1JAQDtwLxQtHjJBMi0aGj8/LykpSgFqZ11DRz1UAWo5GFYYVhcaVUNZdE90IRpVMlBfCi0KBUUUGS1GWjwrb2QFBQ9BHh4gTEEtXCpbM00yXGxcbCMuLjpGLSgtKggIRFpBMjdSCAhsgl9QVWYICIdVKChVBTUvKEYoIyg8UCdGbkZzRlpQJ0RITiYqIC0tbHB2REgvLS0oMloeN0EEYUZabjxLXwRhMD0oPSgya1dTakFWQVVrV0pkSFpILhoaMTE4MT1CIXJFRUxFVlshci0UMjx4MiELPD4yPjwodXVaXEtcVTx1dUZ4QS1VfS4uRkZzglo8KgVuVV9QXzIUDHOMgjc3KB90ZGR9bjIyImZLe0NfVV9OTktfQ31fUzExVTJfeHNQNyBWTFZ0OF8DbkFugjxBX2ZmQTxugl9BUVFLX30tS180CG6CUEY8UAxRVVBGh0taW1hEfUFBc1BQUDw3kUuWKAUqLWSHQYctLi5GUEZQRm5RUTIyTV9NWxoaS0uCS4JfGhpQaWlpaVAaGkt9Rn1GcxoaZHh4lmRaLi5aeGSWeGQuLltaaoJqTRISbqBuUG5kcHCWZHhkeFouLnhGeEuCVRoaUFBQUFBQXV1kZGRkZGRdXUZaWodafXt7ZGRkZGRkHh54eHh4eHh5eQoKCgoKCgAACgoKCgoKAAAytBS0FJYuLjJGoEagWi4uMl9aX1q0Li48T2k7VSRrazxFX0VfJGtr",
  platinum:
    "AAAAAAAAAAAtMTFBQS1BQTw+P1BQPEFBUFJTZGRQQUEnNCs8MkFCQjpAOlBBUEJCTlRObVVkQkIsMEEyQCtDQzs/UEFQOkNDT1NkVWlOQ0MtHiMUFC0TEzIUNxkZHj09PC0yUFBGDg4oIx4UFDITEy0ZMhkZIz09QVAoLVBLREQoLSgjIzgzTT88NzIyRzNNU1BLRkZbM00eOCMZI0gyPjdRPDJGYTI+KDweHx9GMzNBWkE9PWQzMyM8LCg2NxY9PFVFQU9QFj0jNx4yKFoJCTxaN1pQZAkJMktVFB4oCAhLZG4tN0EICDcvNCgoKSZPRj5DNzc4Jk9aUldLVUwmTy45KCgoMiZPPUg5NzdBJk9RXE1VS1UmT0YtMDxBIzhiX0ZJVVo8OGImKSgyQUESEklMS1FkZBIScy0ULRkUODiMRi1LMi04OCgtIx4oNycnS1BGQUtaJyctMjdLQR4iIjxBRlVLKCIiS1BVZFoyIiIjRjctNxkbVzxfUDxQHhtXPDcyKDctDm5GQTxaS1oTbgo3GSMtXwhHI1AyMkZ4CEcoLSMoKFo1ZUFGPEFBcwdlMjQwQTI3Bg1QUk5fUFUGDShQIyMtRkhTQWk8PEZfSFM3Ri1GMjwWElpuUGRQXxYSKDIoKChaCwZBQUEyMloLBlpVX0ZaRgsGGRQPaTdaHCcoIx54RmkcJzcyLYdVeBwnRlAyIyMjPmNQZEYyPC0+Y1qCUEFVNz5jMksjRh4oIiJBWjJVLTciIlBpQWQ8RiIiKCgjMmRGHUBQRkFQeGQdQChQZB4eFEUFN19zLS0jRQVQboI3QS1FBTJVN0FBWjISQWRGUFBpMhJaQUEoKA8MFF9LbmRQHgwUGSNGXzctKgUyPF94RkYqBTRBNzo+PDMnI1UtIyNLMjA8bkY8PGQyMEEtNy1GLS9dWkZQRl9GL11QUDIoMhkBPGlpS0FkMgE8HkFkLRkoS1wyX7RVLUZLXB4jHmQjUBoaLTItczdfGho8QTyCS24aGiMtoB4tRkUFPDAtK1oqD2xVSUZJc0MPbB5pWhkZMjRLN4JzMjJLNEsoHjI3N2QrCTwyRlBQjCsJPChQPC0oIiJfX1V9QTciIjIyXygyI0UfPFBuMlAtRR8yeDUjblcHeDJpTyNuTDNZWjdLPEseFAwoQV88LSMaGkFaeFVGPBoaUFVfHh4ZH0VpgngtLSgfRfoFBSNpMh4gQTdzZCg8ImZpX1AoUFowcR4oRkYZPCFhN0FfXy1VJmEtQzwjMj8hKVBcQUFQRCEpHi03RjdVIx48S1VkVXMjHigtQWR4WitvRm5QN1BpRGVBMiNzX18MbEFTOV9VaQkJQV85ZFVdMTFBfWQ3RlU0aEtkXyhGbhZTFAo3DxRQISFffU88ZFEWFoJVUFVfPAtLMDAwMDAwBwc3NzItQTcyW4JBPG5fQQsLQUE8bl+CCgpBgjxfbkESEkE8RlVLKCRYIyhkWjcjIUtGPH1zRjchSx5QWjctNyEEPHNpQUZQIQRQaUE8S4JFLqBuQUFuHhEvWlVkX31VLi5aWlV9WmQuLlpkWn1VWi4uKUAtMjIyPT09VEFGRkY9PVuGX2RkUCcnam5amlqCLi5kZGRkZGQcHC0xQTFBLUFBPD5QP1A8QUFQUmRTZFBBQSc0KzwyQUJCOkA6UEFQQkJOVE5tVWRCQjJBQCwwK0NDQVBQOz86Q0NVaWRPU05DQyMuIiMtFDIzVUxALTdaMjM8Hh4kODIPM2QyMkxgRg8zKBQeKFA3RDA3IzI3blVEMCg8KCgoHkQPRlpGPDwoRA9VWlBGUIInJ0smJjg4QwojfTo6TExDCiMUKA8jIzwJCTIZHC03DzhiWh4PKBQPODgjFEEoQRQ3IDcoVVBpKDcgKDItRi1GHDBBS0ZfRl8cMDcoKEEtIwkJRjc3UDwtCQlaS0tzWjcJCUtQVVpkMiIiRhQyFDIoLyVkMlAyUDIvJUZkcx5BHgVFWktLWmRGCwYjIygjNzIiZjctMi1BUCJmSzdGN1VuImY3RjcoN1UyNR4eHh4eHiJeS0s3aVUeIl5BQS1LLV8DDjctLRkZDwYLX1VVQUEjBgtBQTyCX24cHF9BbjyCQRwcPFUqVSpbD2lfS1Bkbh4MFDw8PFVVVRoaMEgwSDAwGhq+ITohOiEXF0ZQQVpBVScwMkFaIyMPBQVLWow8PCgFBWRGRkFBLSAyQUtpI0FVNAhLVcg3QR5FBTxQMigoHhYyWnhLPDwtFl9BX0s3N1UmIUaCZDdQQURlFArmCuYFBVJQfUsoX1VEPjdfNyNLcyczPFAyMjIoNV9agktLSzc+XygoKEYoFCgxMjJ4UFAeKDEyMigeHjIMUWRkUDw8MgxRNzdVQVUjNx4jQSNBI0E3YUtpS2lLLRVhLTctQS1LSDdBKEZQjEYhC0FQjChGRjMFLTweUDJBMBJLWjJuUF8wEktfX19fVSFhWjw8KCgoNTVaeHg8PDIFBVVQWmlfPCRYSV8+VUFVFnc3FCMULUsUZSMjIyMjIz5QMl9fI25GFmUtHg9VQUEMbC0/JUE3XwkJLUslRjdTMTFfUGkoRmQvcf8KCkuHNx4gWlVLc2RzLi5zc1VaS2QuLmRLc1pzVS4uMkAyLTIpPj5GVEZBRjM9PWSGbl9kPS0talqCWppuLi5qglpumlouLmRkZGRkZB4eKC0jQTdGQUEyQS1VQV9BQUZVQWlVeEFBLTwoRjItQkI8VTxVPDdCQlB4Rm5GUEJCMkYyMjIoQ0NGVUY8RjJDQ2RuWlVaPENDIzcjHh4jMl9GWkY8PEYWXyYeKR4pPDVSTkY9Mj1kNVItLSMUHhQTEzIjNxkZDz09PEYyWjJBREQyIzcZGQ89PTwyRjJaQRMTKB4eKDIeISw8MjI8RjIhLFBGRlpkRiEsKCgyHh4eIjBGRig8KDwiMFpkPFo8UCIwKDceHh5VPj48VTwyMn0+PigeHjceVTMzPDJkVUZBMzMcGRktIygcJCYjI0E3MhwkREFBfXNQHCQoHiAyNEEhIUY8PlBSPBYWPCg8KDwjG1o8glA8PEYbWjw8PCMjHjY2UFBQNzdaSEiWoGRfQWQ2Nh8tWh4eKA4OPVotMjKgAwMBWi0eHigZGUAzFzMXHCsrVEcrRyswKytoWz9bP0QrK0g8HhQeGS8+kHg8KDwyLz4yFCgUKBQvJR4thy1aHgUqMi0tIyMyOGBGQUE3N0Y4YDJLS0FBMjNkMlVVNzcyNBYyRmQoKB4FRTxajDIyKAVFRm60PDwyBUUeKDcoNzxKSjw8SzxLUEpKKC0oQShBCR9GSzxpPGkJHzwyKFVLXzk5PCgyS1VfOjpBSTcvS1UjREEvN0lLVQxuMjwtZFBBHiZGKzUrNShAPGRJU0lTN0A8LVoUQRRBGBhGeChfKF8YGIJGI0YjPCkMqlotWi08KQw8PChBLSMMVkZkRmlLKCh0RlWMVUYUSUk8GSNGUDwvFFAtQVpuUC8UPDw8PDw8FE0tZC0tLQo0RzJGMjIyRhoaUGRQUFBkGhoyVShVKCMICEZzPHM8NwgILSg8KEsyHh5LRlpGaVAeHklzPDw8WhERSWQ8ZDxBPT1GN0FfVUYaGkZfVTdBRhoaMjArLik8DGtuTklMRzwMaytQQTIjIzRLP3hVWjc3NEsoKDcoRjcaGjxGaUZ4SxoaQilNPVcXFRVWUWFRaysVFS1fMigySwQES31kRlAtBAQUDxQKN1AhIV88T2R9UT8/RkZGRkZGOzs8WkY8eCgQECxLIz8hLQ93QHNBUz9BD3cUKFoeWhkaGihGgjyCGS4uY0RTSFczIl5BMkZfUEEaGkGCPEs8Sy5pXxcwFzAXFxcyMjIyMjInc1BQUFBQUCdzRigyNzIZL3NaPEZLRi0vc25QWl9aQS9zI0BVSjcgS0s3aGleSzQhITdUaXJLNCEhZFqCLUE3IUUrHjcoQWEhIS1LPCgeMkVFQV9kPDIyRUVfh1BuUGQWFig3UCM8Hh0dPEtkN1AyHR1Qh4JfWkYdHVBkyDJkMh0dUDJkZMgyHR1QS5ZLljIdHVBQWm6CbhoaUFpQgm5uGhpkZFqWjFoCAmSWjGRaWkZGaZZallpfTExkZGRkZGQgIDKWMpYyli4uN0RALTcfQUFLWVU3QSRBQV9taUtVOEFBLDosOiw9QkJATjRONFFCQkxoR2hHbEJCNTM1PTgoQ0NAQkRRTDJDQ1RWWG9lPENDKDceHh48MzM3SzIoKFAWFlV4RjIyZBYWOy0oIygfVm1PVTw3PEdWbSUZKRkpGT09TVUzNzNBREQtQSIoIi1PFjxVMTwxPE8WUHhPX09GTxYoHiMyRjceJjxGN31pWh4mQ30oHh46aGhhpTxBMjpoaB4qdipYHgUFPDSoL4oeBQUoHS0dLSQ9PTw7VU9pJGtrRl4yXjJCREQeHioeKkZ2dkZQZlBmKC4uPC1GLVpfMjU3QSM8HlUhIVVpN1UycyEhLSMtPjUjIiJGPEZXTlV6ekwwMDk+Ijxyb1NEXFInPHJLZEI8QnNlNVoyIjwsRmpUllAsWjZQalQ3QiwsOFUyZ0FMVDZgaThnPDw8aWlpGhpkfTRpNEcPaTE3KiolVQcUR1JAQDtwLxQtHjJBMi0aGj8/LykpSgFqZ11DRz1UAWo5GFYYVhcaVUNZdE90IRpVMlBfCi0KBUUUGS1GWjwrb2QFBQ9BHh4gTEEtXCpbM00yXGxcbCMuLjpGLSgtKggIRFpBMjdSCAhsgl9QVWYICIdVKChVBTUvKEYoIyg8UCdGbkZzRlpQJ0RITiYqIC0tbHB2REgvLS0oMloeN0EEYUZabjxLXwRhMD0oPSgya1dTakFWQVVrV0pkSFpILhoaMTE4MT1CIXJFRUxFVlshci0UMjx4MiELPD4yPjwodXVaXEtcVTx1dUZ4QS1VfS4uRkZzglo8KgVuVV9QXzIUDHOMgjc3KB90ZGR9bjIyImZLe0NfVV9OTktfQ31fUzExVTJfeHNQNyBWTFZ0OF8DbkFugjxBX2ZmQTxugl9BUVFLX30tS180CG6CUEY8UAxRVVBGh0taW1hEfUFBc1BQUDw3kUuWKAUqLWSHQYctLi5GUEZQRm5RUTIyTV9NWxoaS0uCS4JfGhpQaWlpaVAaGkt9Rn1GcxoaZHh4lmRaLi5aeGSWeGQuLltaaoJqTRISbqBuUG5kcHCWZHhkeFouLnhGeEuCVRoaUFBQUFBQXV1kZGRkZGRdXUZaWodafXt7ZGRkZGRkHh54eHh4eHh5eQoKCgoKCgAACgoKCgoKAAAytBS0FJYuLjJGoEagWi4uMl9aX1q0Li48T2k7VSRrazxFX0VfJGtrlnhkeGRaGhpkZ0t4S38gIDJBa2lrVhoaMkFraWtWGhoyQWtpa1YaGjJBa2lrVhoaMkFraWtWGho=",
  hgss: "AAAAAAAAAAAtMTFBQS1BQTw+P1BQPEFBUFJTZGRQQUEnNCs8MkFCQjpAOlBBUEJCTlRObVVkQkIsMEEyQCtDQzs/UEFQOkNDT1NkVWlOQ0MtHiMUFC0TEzIUNxkZHj09PC0yUFBGDg4oIx4UFDITEy0ZMhkZIz09QVAoLVBLREQoLSgjIzgzTT88NzIyRzNNU1BLRkZbM00eOCMZI0gyPjdRPDJGYTI+KDweHx9GMzNBWkE9PWQzMyM8LCg2NxY9PFVFQU9QFj0jNx4yKFoJCTxaN1pQZAkJMktVFB4oCAhLZG4tN0EICDcvNCgoKSZPRj5DNzc4Jk9aUldLVUwmTy45KCgoMiZPPUg5NzdBJk9RXE1VS1UmT0YtMDxBIzhiX0ZJVVo8OGImKSgyQUESEklMS1FkZBIScy0ULRkUODiMRi1LMi04OCgtIx4oNycnS1BGQUtaJyctMjdLQR4iIjxBRlVLKCIiS1BVZFoyIiIjRjctNxkbVzxfUDxQHhtXPDcyKDctDm5GQTxaS1oTbgo3GSMtXwhHI1AyMkZ4CEcoLSMoKFo1ZUFGPEFBcwdlMjQwQTI3Bg1QUk5fUFUGDShQIyMtRkhTQWk8PEZfSFM3Ri1GMjwWElpuUGRQXxYSKDIoKChaCwZBQUEyMloLBlpVX0ZaRgsGGRQPaTdaHCcoIx54RmkcJzcyLYdVeBwnRlAyIyMjPmNQZEYyPC0+Y1qCUEFVNz5jMksjRh4oIiJBWjJVLTciIlBpQWQ8RiIiKCgjMmRGHUBQRkFQeGQdQChQZB4eFEUFN19zLS0jRQVQboI3QS1FBTJVN0FBWjISQWRGUFBpMhJaQUEoKA8MFF9LbmRQHgwUGSNGXzctKgUyPF94RkYqBTRBNzo+PDMnI1UtIyNLMjA8bkY8PGQyMEEtNy1GLS9dWkZQRl9GL11QUDIoMhkBPGlpS0FkMgE8HkFkLRkoS1wyX7RVLUZLXB4jHmQjUBoaLTItczdfGho8QTyCS24aGiMtoB4tRkUFPDAtK1oqD2xVSUZJc0MPbB5pWhkZMjRLN4JzMjJLNEsoHjI3N2QrCTwyRlBQjCsJPChQPC0oIiJfX1V9QTciIjIyXygyI0UfPFBuMlAtRR8yeDUjblcHeDJpTyNuTDNZWjdLPEseFAwoQV88LSMaGkFaeFVGPBoaUFVfHh4ZH0VpgngtLSgfRfoFBSNpMh4gQTdzZCg8ImZpX1AoUFowcR4oRkYZPCFhN0FfXy1VJmEtQzwjMj8hKVBcQUFQRCEpHi03RjdVIx48S1VkVXMjHigtQWR4WitvRm5QN1BpRGVBMiNzX18MbEFTOV9VaQkJQV85ZFVdMTFBfWQ3RlU0aEtkXyhGbhZTFAo3DxRQISFffU88ZFEWFoJVUFVfPAtLMDAwMDAwBwc3NzItQTcyW4JBPG5fQQsLQUE8bl+CCgpBgjxfbkESEkE8RlVLKCRYIyhkWjcjIUtGPH1zRjchSx5QWjctNyEEPHNpQUZQIQRQaUE8S4JFLqBuQUFuHhEvWlVkX31VLi5aWlV9WmQuLlpkWn1VWi4uKUAtMjIyPT09VEFGRkY9PVuGX2RkUCcnam5amlqCLi5kZGRkZGQcHC0xQTFBLUFBPD5QP1A8QUFQUmRTZFBBQSc0KzwyQUJCOkA6UEFQQkJOVE5tVWRCQjJBQCwwK0NDQVBQOz86Q0NVaWRPU05DQyMuIiMtFDIzVUxALTdaMjM8Hh4kODIPM2QyMkxgRg8zKBQeKFA3RDA3IzI3blVEMCg8KCgoHkQPRlpGPDwoRA9VWlBGUIInJ0smJjg4QwojfTo6TExDCiMUKA8jIzwJCTIZHC03DzhiWh4PKBQPODgjFEEoQRQ3IDcoVVBpKDcgKDItRi1GHDBBS0ZfRl8cMDcoKEEtIwkJRjc3UDwtCQlaS0tzWjcJCUtQVVpkMiIiRhQyFDIoLyVkMlAyUDIvJUZkcx5BHgVFWktLWmRGCwYjIygjNzIiZjctMi1BUCJmSzdGN1VuImY3RjcoN1UyNR4eHh4eHiJeS0s3aVUeIl5BQS1LLV8DDjctLRkZDwYLX1VVQUEjBgtBQTyCX24cHF9BbjyCQRwcPFUqVSpbD2lfS1Bkbh4MFDw8PFVVVRoaMEgwSDAwGhq+ITohOiEXF0ZQQVpBVScwMkFaIyMPBQVLWow8PCgFBWRGRkFBLSAyQUtpI0FVNAhLVcg3QR5FBTxQMigoHhYyWnhLPDwtFl9BX0s3N1UmIUaCZDdQQURlFArmCuYFBVJQfUsoX1VEPjdfNyNLcyczPFAyMjIoNV9agktLSzc+XygoKEYoFCgxMjJ4UFAeKDEyMigeHjIMUWRkUDw8MgxRNzdVQVUjNx4jQSNBI0E3YUtpS2lLLRVhLTctQS1LSDdBKEZQjEYhC0FQjChGRjMFLTweUDJBMBJLWjJuUF8wEktfX19fVSFhWjw8KCgoNTVaeHg8PDIFBVVQWmlfPCRYSV8+VUFVFnc3FCMULUsUZSMjIyMjIz5QMl9fI25GFmUtHg9VQUEMbC0/JUE3XwkJLUslRjdTMTFfUGkoRmQvcf8KCkuHNx4gWlVLc2RzLi5zc1VaS2QuLmRLc1pzVS4uMkAyLTIpPj5GVEZBRjM9PWSGbl9kPS0talqCWppuLi5qglpumlouLmRkZGRkZB4eKC0jQTdGQUEyQS1VQV9BQUZVQWlVeEFBLTwoRjItQkI8VTxVPDdCQlB4Rm5GUEJCMkYyMjIoQ0NGVUY8RjJDQ2RuWlVaPENDIzcjHh4jMl9GWkY8PEYWXyYeKR4pPDVSTkY9Mj1kNVItLSMUHhQTEzIjNxkZDz09PEYyWjJBREQyIzcZGQ89PTwyRjJaQRMTKB4eKDIeISw8MjI8RjIhLFBGRlpkRiEsKCgyHh4eIjBGRig8KDwiMFpkPFo8UCIwKDceHh5VPj48VTwyMn0+PigeHjceVTMzPDJkVUZBMzMcGRktIygcJCYjI0E3MhwkREFBfXNQHCQoHiAyNEEhIUY8PlBSPBYWPCg8KDwjG1o8glA8PEYbWjw8PCMjHjY2UFBQNzdaSEiWoGRfQWQ2Nh8tWh4eKA4OPVotMjKgAwMBWi0eHigZGUAzFzMXHCsrVEcrRyswKytoWz9bP0QrK0g8HhQeGS8+kHg8KDwyLz4yFCgUKBQvJR4thy1aHgUqMi0tIyMyOGBGQUE3N0Y4YDJLS0FBMjNkMlVVNzcyNBYyRmQoKB4FRTxajDIyKAVFRm60PDwyBUUeKDcoNzxKSjw8SzxLUEpKKC0oQShBCR9GSzxpPGkJHzwyKFVLXzk5PCgyS1VfOjpBSTcvS1UjREEvN0lLVQxuMjwtZFBBHiZGKzUrNShAPGRJU0lTN0A8LVoUQRRBGBhGeChfKF8YGIJGI0YjPCkMqlotWi08KQw8PChBLSMMVkZkRmlLKCh0RlWMVUYUSUk8GSNGUDwvFFAtQVpuUC8UPDw8PDw8FE0tZC0tLQo0RzJGMjIyRhoaUGRQUFBkGhoyVShVKCMICEZzPHM8NwgILSg8KEsyHh5LRlpGaVAeHklzPDw8WhERSWQ8ZDxBPT1GN0FfVUYaGkZfVTdBRhoaMjArLik8DGtuTklMRzwMaytQQTIjIzRLP3hVWjc3NEsoKDcoRjcaGjxGaUZ4SxoaQilNPVcXFRVWUWFRaysVFS1fMigySwQES31kRlAtBAQUDxQKN1AhIV88T2R9UT8/RkZGRkZGOzs8WkY8eCgQECxLIz8hLQ93QHNBUz9BD3cUKFoeWhkaGihGgjyCGS4uY0RTSFczIl5BMkZfUEEaGkGCPEs8Sy5pXxcwFzAXFxcyMjIyMjInc1BQUFBQUCdzRigyNzIZL3NaPEZLRi0vc25QWl9aQS9zI0BVSjcgS0s3aGleSzQhITdUaXJLNCEhZFqCLUE3IUUrHjcoQWEhIS1LPCgeMkVFQV9kPDIyRUVfh1BuUGQWFig3UCM8Hh0dPEtkN1AyHR1Qh4JfWkYdHVBkyDJkMh0dUDJkZMgyHR1QS5ZLljIdHVBQWm6CbhoaUFpQgm5uGhpkZFqWjFoCAmSWjGRaWkZGaZZallpfTExkZGRkZGQgIDKWMpYyli4uN0RALTcfQUFLWVU3QSRBQV9taUtVOEFBLDosOiw9QkJATjRONFFCQkxoR2hHbEJCNTM1PTgoQ0NAQkRRTDJDQ1RWWG9lPENDKDceHh48MzM3SzIoKFAWFlV4RjIyZBYWOy0oIygfVm1PVTw3PEdWbSUZKRkpGT09TVUzNzNBREQtQSIoIi1PFjxVMTwxPE8WUHhPX09GTxYoHiMyRjceJjxGN31pWh4mQ30oHh46aGhhpTxBMjpoaB4qdipYHgUFPDSoL4oeBQUoHS0dLSQ9PTw7VU9pJGtrRl4yXjJCREQeHioeKkZ2dkZQZlBmKC4uPC1GLVpfMjU3QSM8HlUhIVVpN1UycyEhLSMtPjUjIiJGPEZXTlV6ekwwMDk+Ijxyb1NEXFInPHJLZEI8QnNlNVoyIjwsRmpUllAsWjZQalQ3QiwsOFUyZ0FMVDZgaThnPDw8aWlpGhpkfTRpNEcPaTE3KiolVQcUR1JAQDtwLxQtHjJBMi0aGj8/LykpSgFqZ11DRz1UAWo5GFYYVhcaVUNZdE90IRpVMlBfCi0KBUUUGS1GWjwrb2QFBQ9BHh4gTEEtXCpbM00yXGxcbCMuLjpGLSgtKggIRFpBMjdSCAhsgl9QVWYICIdVKChVBTUvKEYoIyg8UCdGbkZzRlpQJ0RITiYqIC0tbHB2REgvLS0oMloeN0EEYUZabjxLXwRhMD0oPSgya1dTakFWQVVrV0pkSFpILhoaMTE4MT1CIXJFRUxFVlshci0UMjx4MiELPD4yPjwodXVaXEtcVTx1dUZ4QS1VfS4uRkZzglo8KgVuVV9QXzIUDHOMgjc3KB90ZGR9bjIyImZLe0NfVV9OTktfQ31fUzExVTJfeHNQNyBWTFZ0OF8DbkFugjxBX2ZmQTxugl9BUVFLX30tS180CG6CUEY8UAxRVVBGh0taW1hEfUFBc1BQUDw3kUuWKAUqLWSHQYctLi5GUEZQRm5RUTIyTV9NWxoaS0uCS4JfGhpQaWlpaVAaGkt9Rn1GcxoaZHh4lmRaLi5aeGSWeGQuLltaaoJqTRISbqBuUG5kcHCWZHhkeFouLnhGeEuCVRoaUFBQUFBQXV1kZGRkZGRdXUZaWodafXt7ZGRkZGRkHh54eHh4eHh5eQoKCgoKCgAACgoKCgoKAAAytBS0FJYuLjJGoEagWi4uMl9aX1q0Li48T2k7VSRrazxFX0VfJGtrlnhkeGRaGhpkZ0t4S38gIDJBa2lrVhoaMkFraWtWGhoyQWtpa1YaGjJBa2lrVhoaMkFraWtWGho=",
};

const speciesNames: Record<Gen4IvDataLanguage, readonly string[]> = {
  en: [
    "Bulbasaur",
    "Ivysaur",
    "Venusaur",
    "Charmander",
    "Charmeleon",
    "Charizard",
    "Squirtle",
    "Wartortle",
    "Blastoise",
    "Caterpie",
    "Metapod",
    "Butterfree",
    "Weedle",
    "Kakuna",
    "Beedrill",
    "Pidgey",
    "Pidgeotto",
    "Pidgeot",
    "Rattata",
    "Raticate",
    "Spearow",
    "Fearow",
    "Ekans",
    "Arbok",
    "Pikachu",
    "Raichu",
    "Sandshrew",
    "Sandslash",
    "Nidoran♀",
    "Nidorina",
    "Nidoqueen",
    "Nidoran♂",
    "Nidorino",
    "Nidoking",
    "Clefairy",
    "Clefable",
    "Vulpix",
    "Ninetales",
    "Jigglypuff",
    "Wigglytuff",
    "Zubat",
    "Golbat",
    "Oddish",
    "Gloom",
    "Vileplume",
    "Paras",
    "Parasect",
    "Venonat",
    "Venomoth",
    "Diglett",
    "Dugtrio",
    "Meowth",
    "Persian",
    "Psyduck",
    "Golduck",
    "Mankey",
    "Primeape",
    "Growlithe",
    "Arcanine",
    "Poliwag",
    "Poliwhirl",
    "Poliwrath",
    "Abra",
    "Kadabra",
    "Alakazam",
    "Machop",
    "Machoke",
    "Machamp",
    "Bellsprout",
    "Weepinbell",
    "Victreebel",
    "Tentacool",
    "Tentacruel",
    "Geodude",
    "Graveler",
    "Golem",
    "Ponyta",
    "Rapidash",
    "Slowpoke",
    "Slowbro",
    "Magnemite",
    "Magneton",
    "Farfetch’d",
    "Doduo",
    "Dodrio",
    "Seel",
    "Dewgong",
    "Grimer",
    "Muk",
    "Shellder",
    "Cloyster",
    "Gastly",
    "Haunter",
    "Gengar",
    "Onix",
    "Drowzee",
    "Hypno",
    "Krabby",
    "Kingler",
    "Voltorb",
    "Electrode",
    "Exeggcute",
    "Exeggutor",
    "Cubone",
    "Marowak",
    "Hitmonlee",
    "Hitmonchan",
    "Lickitung",
    "Koffing",
    "Weezing",
    "Rhyhorn",
    "Rhydon",
    "Chansey",
    "Tangela",
    "Kangaskhan",
    "Horsea",
    "Seadra",
    "Goldeen",
    "Seaking",
    "Staryu",
    "Starmie",
    "Mr. Mime",
    "Scyther",
    "Jynx",
    "Electabuzz",
    "Magmar",
    "Pinsir",
    "Tauros",
    "Magikarp",
    "Gyarados",
    "Lapras",
    "Ditto",
    "Eevee",
    "Vaporeon",
    "Jolteon",
    "Flareon",
    "Porygon",
    "Omanyte",
    "Omastar",
    "Kabuto",
    "Kabutops",
    "Aerodactyl",
    "Snorlax",
    "Articuno",
    "Zapdos",
    "Moltres",
    "Dratini",
    "Dragonair",
    "Dragonite",
    "Mewtwo",
    "Mew",
    "Chikorita",
    "Bayleef",
    "Meganium",
    "Cyndaquil",
    "Quilava",
    "Typhlosion",
    "Totodile",
    "Croconaw",
    "Feraligatr",
    "Sentret",
    "Furret",
    "Hoothoot",
    "Noctowl",
    "Ledyba",
    "Ledian",
    "Spinarak",
    "Ariados",
    "Crobat",
    "Chinchou",
    "Lanturn",
    "Pichu",
    "Cleffa",
    "Igglybuff",
    "Togepi",
    "Togetic",
    "Natu",
    "Xatu",
    "Mareep",
    "Flaaffy",
    "Ampharos",
    "Bellossom",
    "Marill",
    "Azumarill",
    "Sudowoodo",
    "Politoed",
    "Hoppip",
    "Skiploom",
    "Jumpluff",
    "Aipom",
    "Sunkern",
    "Sunflora",
    "Yanma",
    "Wooper",
    "Quagsire",
    "Espeon",
    "Umbreon",
    "Murkrow",
    "Slowking",
    "Misdreavus",
    "Unown",
    "Wobbuffet",
    "Girafarig",
    "Pineco",
    "Forretress",
    "Dunsparce",
    "Gligar",
    "Steelix",
    "Snubbull",
    "Granbull",
    "Qwilfish",
    "Scizor",
    "Shuckle",
    "Heracross",
    "Sneasel",
    "Teddiursa",
    "Ursaring",
    "Slugma",
    "Magcargo",
    "Swinub",
    "Piloswine",
    "Corsola",
    "Remoraid",
    "Octillery",
    "Delibird",
    "Mantine",
    "Skarmory",
    "Houndour",
    "Houndoom",
    "Kingdra",
    "Phanpy",
    "Donphan",
    "Porygon2",
    "Stantler",
    "Smeargle",
    "Tyrogue",
    "Hitmontop",
    "Smoochum",
    "Elekid",
    "Magby",
    "Miltank",
    "Blissey",
    "Raikou",
    "Entei",
    "Suicune",
    "Larvitar",
    "Pupitar",
    "Tyranitar",
    "Lugia",
    "Ho-Oh",
    "Celebi",
    "Treecko",
    "Grovyle",
    "Sceptile",
    "Torchic",
    "Combusken",
    "Blaziken",
    "Mudkip",
    "Marshtomp",
    "Swampert",
    "Poochyena",
    "Mightyena",
    "Zigzagoon",
    "Linoone",
    "Wurmple",
    "Silcoon",
    "Beautifly",
    "Cascoon",
    "Dustox",
    "Lotad",
    "Lombre",
    "Ludicolo",
    "Seedot",
    "Nuzleaf",
    "Shiftry",
    "Taillow",
    "Swellow",
    "Wingull",
    "Pelipper",
    "Ralts",
    "Kirlia",
    "Gardevoir",
    "Surskit",
    "Masquerain",
    "Shroomish",
    "Breloom",
    "Slakoth",
    "Vigoroth",
    "Slaking",
    "Nincada",
    "Ninjask",
    "Shedinja",
    "Whismur",
    "Loudred",
    "Exploud",
    "Makuhita",
    "Hariyama",
    "Azurill",
    "Nosepass",
    "Skitty",
    "Delcatty",
    "Sableye",
    "Mawile",
    "Aron",
    "Lairon",
    "Aggron",
    "Meditite",
    "Medicham",
    "Electrike",
    "Manectric",
    "Plusle",
    "Minun",
    "Volbeat",
    "Illumise",
    "Roselia",
    "Gulpin",
    "Swalot",
    "Carvanha",
    "Sharpedo",
    "Wailmer",
    "Wailord",
    "Numel",
    "Camerupt",
    "Torkoal",
    "Spoink",
    "Grumpig",
    "Spinda",
    "Trapinch",
    "Vibrava",
    "Flygon",
    "Cacnea",
    "Cacturne",
    "Swablu",
    "Altaria",
    "Zangoose",
    "Seviper",
    "Lunatone",
    "Solrock",
    "Barboach",
    "Whiscash",
    "Corphish",
    "Crawdaunt",
    "Baltoy",
    "Claydol",
    "Lileep",
    "Cradily",
    "Anorith",
    "Armaldo",
    "Feebas",
    "Milotic",
    "Castform",
    "Kecleon",
    "Shuppet",
    "Banette",
    "Duskull",
    "Dusclops",
    "Tropius",
    "Chimecho",
    "Absol",
    "Wynaut",
    "Snorunt",
    "Glalie",
    "Spheal",
    "Sealeo",
    "Walrein",
    "Clamperl",
    "Huntail",
    "Gorebyss",
    "Relicanth",
    "Luvdisc",
    "Bagon",
    "Shelgon",
    "Salamence",
    "Beldum",
    "Metang",
    "Metagross",
    "Regirock",
    "Regice",
    "Registeel",
    "Latias",
    "Latios",
    "Kyogre",
    "Groudon",
    "Rayquaza",
    "Jirachi",
    "Deoxys",
    "Turtwig",
    "Grotle",
    "Torterra",
    "Chimchar",
    "Monferno",
    "Infernape",
    "Piplup",
    "Prinplup",
    "Empoleon",
    "Starly",
    "Staravia",
    "Staraptor",
    "Bidoof",
    "Bibarel",
    "Kricketot",
    "Kricketune",
    "Shinx",
    "Luxio",
    "Luxray",
    "Budew",
    "Roserade",
    "Cranidos",
    "Rampardos",
    "Shieldon",
    "Bastiodon",
    "Burmy",
    "Wormadam",
    "Mothim",
    "Combee",
    "Vespiquen",
    "Pachirisu",
    "Buizel",
    "Floatzel",
    "Cherubi",
    "Cherrim",
    "Shellos",
    "Gastrodon",
    "Ambipom",
    "Drifloon",
    "Drifblim",
    "Buneary",
    "Lopunny",
    "Mismagius",
    "Honchkrow",
    "Glameow",
    "Purugly",
    "Chingling",
    "Stunky",
    "Skuntank",
    "Bronzor",
    "Bronzong",
    "Bonsly",
    "Mime Jr.",
    "Happiny",
    "Chatot",
    "Spiritomb",
    "Gible",
    "Gabite",
    "Garchomp",
    "Munchlax",
    "Riolu",
    "Lucario",
    "Hippopotas",
    "Hippowdon",
    "Skorupi",
    "Drapion",
    "Croagunk",
    "Toxicroak",
    "Carnivine",
    "Finneon",
    "Lumineon",
    "Mantyke",
    "Snover",
    "Abomasnow",
    "Weavile",
    "Magnezone",
    "Lickilicky",
    "Rhyperior",
    "Tangrowth",
    "Electivire",
    "Magmortar",
    "Togekiss",
    "Yanmega",
    "Leafeon",
    "Glaceon",
    "Gliscor",
    "Mamoswine",
    "Porygon-Z",
    "Gallade",
    "Probopass",
    "Dusknoir",
    "Froslass",
    "Rotom",
    "Uxie",
    "Mesprit",
    "Azelf",
    "Dialga",
    "Palkia",
    "Heatran",
    "Regigigas",
    "Giratina",
    "Cresselia",
    "Phione",
    "Manaphy",
    "Darkrai",
    "Shaymin",
    "Arceus",
  ],
  ja: [
    "フシギダネ",
    "フシギソウ",
    "フシギバナ",
    "ヒトカゲ",
    "リザード",
    "リザードン",
    "ゼニガメ",
    "カメール",
    "カメックス",
    "キャタピー",
    "トランセル",
    "バタフリー",
    "ビードル",
    "コクーン",
    "スピアー",
    "ポッポ",
    "ピジョン",
    "ピジョット",
    "コラッタ",
    "ラッタ",
    "オニスズメ",
    "オニドリル",
    "アーボ",
    "アーボック",
    "ピカチュウ",
    "ライチュウ",
    "サンド",
    "サンドパン",
    "ニドラン♀",
    "ニドリーナ",
    "ニドクイン",
    "ニドラン♂",
    "ニドリーノ",
    "ニドキング",
    "ピッピ",
    "ピクシー",
    "ロコン",
    "キュウコン",
    "プリン",
    "プクリン",
    "ズバット",
    "ゴルバット",
    "ナゾノクサ",
    "クサイハナ",
    "ラフレシア",
    "パラス",
    "パラセクト",
    "コンパン",
    "モルフォン",
    "ディグダ",
    "ダグトリオ",
    "ニャース",
    "ペルシアン",
    "コダック",
    "ゴルダック",
    "マンキー",
    "オコリザル",
    "ガーディ",
    "ウインディ",
    "ニョロモ",
    "ニョロゾ",
    "ニョロボン",
    "ケーシィ",
    "ユンゲラー",
    "フーディン",
    "ワンリキー",
    "ゴーリキー",
    "カイリキー",
    "マダツボミ",
    "ウツドン",
    "ウツボット",
    "メノクラゲ",
    "ドククラゲ",
    "イシツブテ",
    "ゴローン",
    "ゴローニャ",
    "ポニータ",
    "ギャロップ",
    "ヤドン",
    "ヤドラン",
    "コイル",
    "レアコイル",
    "カモネギ",
    "ドードー",
    "ドードリオ",
    "パウワウ",
    "ジュゴン",
    "ベトベター",
    "ベトベトン",
    "シェルダー",
    "パルシェン",
    "ゴース",
    "ゴースト",
    "ゲンガー",
    "イワーク",
    "スリープ",
    "スリーパー",
    "クラブ",
    "キングラー",
    "ビリリダマ",
    "マルマイン",
    "タマタマ",
    "ナッシー",
    "カラカラ",
    "ガラガラ",
    "サワムラー",
    "エビワラー",
    "ベロリンガ",
    "ドガース",
    "マタドガス",
    "サイホーン",
    "サイドン",
    "ラッキー",
    "モンジャラ",
    "ガルーラ",
    "タッツー",
    "シードラ",
    "トサキント",
    "アズマオウ",
    "ヒトデマン",
    "スターミー",
    "バリヤード",
    "ストライク",
    "ルージュラ",
    "エレブー",
    "ブーバー",
    "カイロス",
    "ケンタロス",
    "コイキング",
    "ギャラドス",
    "ラプラス",
    "メタモン",
    "イーブイ",
    "シャワーズ",
    "サンダース",
    "ブースター",
    "ポリゴン",
    "オムナイト",
    "オムスター",
    "カブト",
    "カブトプス",
    "プテラ",
    "カビゴン",
    "フリーザー",
    "サンダー",
    "ファイヤー",
    "ミニリュウ",
    "ハクリュー",
    "カイリュー",
    "ミュウツー",
    "ミュウ",
    "チコリータ",
    "ベイリーフ",
    "メガニウム",
    "ヒノアラシ",
    "マグマラシ",
    "バクフーン",
    "ワニノコ",
    "アリゲイツ",
    "オーダイル",
    "オタチ",
    "オオタチ",
    "ホーホー",
    "ヨルノズク",
    "レディバ",
    "レディアン",
    "イトマル",
    "アリアドス",
    "クロバット",
    "チョンチー",
    "ランターン",
    "ピチュー",
    "ピィ",
    "ププリン",
    "トゲピー",
    "トゲチック",
    "ネイティ",
    "ネイティオ",
    "メリープ",
    "モココ",
    "デンリュウ",
    "キレイハナ",
    "マリル",
    "マリルリ",
    "ウソッキー",
    "ニョロトノ",
    "ハネッコ",
    "ポポッコ",
    "ワタッコ",
    "エイパム",
    "ヒマナッツ",
    "キマワリ",
    "ヤンヤンマ",
    "ウパー",
    "ヌオー",
    "エーフィ",
    "ブラッキー",
    "ヤミカラス",
    "ヤドキング",
    "ムウマ",
    "アンノーン",
    "ソーナンス",
    "キリンリキ",
    "クヌギダマ",
    "フォレトス",
    "ノコッチ",
    "グライガー",
    "ハガネール",
    "ブルー",
    "グランブル",
    "ハリーセン",
    "ハッサム",
    "ツボツボ",
    "ヘラクロス",
    "ニューラ",
    "ヒメグマ",
    "リングマ",
    "マグマッグ",
    "マグカルゴ",
    "ウリムー",
    "イノムー",
    "サニーゴ",
    "テッポウオ",
    "オクタン",
    "デリバード",
    "マンタイン",
    "エアームド",
    "デルビル",
    "ヘルガー",
    "キングドラ",
    "ゴマゾウ",
    "ドンファン",
    "ポリゴン２",
    "オドシシ",
    "ドーブル",
    "バルキー",
    "カポエラー",
    "ムチュール",
    "エレキッド",
    "ブビィ",
    "ミルタンク",
    "ハピナス",
    "ライコウ",
    "エンテイ",
    "スイクン",
    "ヨーギラス",
    "サナギラス",
    "バンギラス",
    "ルギア",
    "ホウオウ",
    "セレビィ",
    "キモリ",
    "ジュプトル",
    "ジュカイン",
    "アチャモ",
    "ワカシャモ",
    "バシャーモ",
    "ミズゴロウ",
    "ヌマクロー",
    "ラグラージ",
    "ポチエナ",
    "グラエナ",
    "ジグザグマ",
    "マッスグマ",
    "ケムッソ",
    "カラサリス",
    "アゲハント",
    "マユルド",
    "ドクケイル",
    "ハスボー",
    "ハスブレロ",
    "ルンパッパ",
    "タネボー",
    "コノハナ",
    "ダーテング",
    "スバメ",
    "オオスバメ",
    "キャモメ",
    "ペリッパー",
    "ラルトス",
    "キルリア",
    "サーナイト",
    "アメタマ",
    "アメモース",
    "キノココ",
    "キノガッサ",
    "ナマケロ",
    "ヤルキモノ",
    "ケッキング",
    "ツチニン",
    "テッカニン",
    "ヌケニン",
    "ゴニョニョ",
    "ドゴーム",
    "バクオング",
    "マクノシタ",
    "ハリテヤマ",
    "ルリリ",
    "ノズパス",
    "エネコ",
    "エネコロロ",
    "ヤミラミ",
    "クチート",
    "ココドラ",
    "コドラ",
    "ボスゴドラ",
    "アサナン",
    "チャーレム",
    "ラクライ",
    "ライボルト",
    "プラスル",
    "マイナン",
    "バルビート",
    "イルミーゼ",
    "ロゼリア",
    "ゴクリン",
    "マルノーム",
    "キバニア",
    "サメハダー",
    "ホエルコ",
    "ホエルオー",
    "ドンメル",
    "バクーダ",
    "コータス",
    "バネブー",
    "ブーピッグ",
    "パッチール",
    "ナックラー",
    "ビブラーバ",
    "フライゴン",
    "サボネア",
    "ノクタス",
    "チルット",
    "チルタリス",
    "ザングース",
    "ハブネーク",
    "ルナトーン",
    "ソルロック",
    "ドジョッチ",
    "ナマズン",
    "ヘイガニ",
    "シザリガー",
    "ヤジロン",
    "ネンドール",
    "リリーラ",
    "ユレイドル",
    "アノプス",
    "アーマルド",
    "ヒンバス",
    "ミロカロス",
    "ポワルン",
    "カクレオン",
    "カゲボウズ",
    "ジュペッタ",
    "ヨマワル",
    "サマヨール",
    "トロピウス",
    "チリーン",
    "アブソル",
    "ソーナノ",
    "ユキワラシ",
    "オニゴーリ",
    "タマザラシ",
    "トドグラー",
    "トドゼルガ",
    "パールル",
    "ハンテール",
    "サクラビス",
    "ジーランス",
    "ラブカス",
    "タツベイ",
    "コモルー",
    "ボーマンダ",
    "ダンバル",
    "メタング",
    "メタグロス",
    "レジロック",
    "レジアイス",
    "レジスチル",
    "ラティアス",
    "ラティオス",
    "カイオーガ",
    "グラードン",
    "レックウザ",
    "ジラーチ",
    "デオキシス",
    "ナエトル",
    "ハヤシガメ",
    "ドダイトス",
    "ヒコザル",
    "モウカザル",
    "ゴウカザル",
    "ポッチャマ",
    "ポッタイシ",
    "エンペルト",
    "ムックル",
    "ムクバード",
    "ムクホーク",
    "ビッパ",
    "ビーダル",
    "コロボーシ",
    "コロトック",
    "コリンク",
    "ルクシオ",
    "レントラー",
    "スボミー",
    "ロズレイド",
    "ズガイドス",
    "ラムパルド",
    "タテトプス",
    "トリデプス",
    "ミノムッチ",
    "ミノマダム",
    "ガーメイル",
    "ミツハニー",
    "ビークイン",
    "パチリス",
    "ブイゼル",
    "フローゼル",
    "チェリンボ",
    "チェリム",
    "カラナクシ",
    "トリトドン",
    "エテボース",
    "フワンテ",
    "フワライド",
    "ミミロル",
    "ミミロップ",
    "ムウマージ",
    "ドンカラス",
    "ニャルマー",
    "ブニャット",
    "リーシャン",
    "スカンプー",
    "スカタンク",
    "ドーミラー",
    "ドータクン",
    "ウソハチ",
    "マネネ",
    "ピンプク",
    "ペラップ",
    "ミカルゲ",
    "フカマル",
    "ガバイト",
    "ガブリアス",
    "ゴンベ",
    "リオル",
    "ルカリオ",
    "ヒポポタス",
    "カバルドン",
    "スコルピ",
    "ドラピオン",
    "グレッグル",
    "ドクロッグ",
    "マスキッパ",
    "ケイコウオ",
    "ネオラント",
    "タマンタ",
    "ユキカブリ",
    "ユキノオー",
    "マニューラ",
    "ジバコイル",
    "ベロベルト",
    "ドサイドン",
    "モジャンボ",
    "エレキブル",
    "ブーバーン",
    "トゲキッス",
    "メガヤンマ",
    "リーフィア",
    "グレイシア",
    "グライオン",
    "マンムー",
    "ポリゴンＺ",
    "エルレイド",
    "ダイノーズ",
    "ヨノワール",
    "ユキメノコ",
    "ロトム",
    "ユクシー",
    "エムリット",
    "アグノム",
    "ディアルガ",
    "パルキア",
    "ヒードラン",
    "レジギガス",
    "ギラティナ",
    "クレセリア",
    "フィオネ",
    "マナフィ",
    "ダークライ",
    "シェイミ",
    "アルセウス",
  ],
  zh: [
    "妙蛙种子",
    "妙蛙草",
    "妙蛙花",
    "小火龙",
    "火恐龙",
    "喷火龙",
    "杰尼龟",
    "卡咪龟",
    "水箭龟",
    "绿毛虫",
    "铁甲蛹",
    "巴大蝶",
    "独角虫",
    "铁壳蛹",
    "大针蜂",
    "波波",
    "比比鸟",
    "大比鸟",
    "小拉达",
    "拉达",
    "烈雀",
    "大嘴雀",
    "阿柏蛇",
    "阿柏怪",
    "皮卡丘",
    "雷丘",
    "穿山鼠",
    "穿山王",
    "尼多兰",
    "尼多娜",
    "尼多后",
    "尼多朗",
    "尼多力诺",
    "尼多王",
    "皮皮",
    "皮可西",
    "六尾",
    "九尾",
    "胖丁",
    "胖可丁",
    "超音蝠",
    "大嘴蝠",
    "走路草",
    "臭臭花",
    "霸王花",
    "派拉斯",
    "派拉斯特",
    "毛球",
    "摩鲁蛾",
    "地鼠",
    "三地鼠",
    "喵喵",
    "猫老大",
    "可达鸭",
    "哥达鸭",
    "猴怪",
    "火暴猴",
    "卡蒂狗",
    "风速狗",
    "蚊香蝌蚪",
    "蚊香君",
    "蚊香泳士",
    "凯西",
    "勇基拉",
    "胡地",
    "腕力",
    "豪力",
    "怪力",
    "喇叭芽",
    "口呆花",
    "大食花",
    "玛瑙水母",
    "毒刺水母",
    "小拳石",
    "隆隆石",
    "隆隆岩",
    "小火马",
    "烈焰马",
    "呆呆兽",
    "呆壳兽",
    "小磁怪",
    "三合一磁怪",
    "大葱鸭",
    "嘟嘟",
    "嘟嘟利",
    "小海狮",
    "白海狮",
    "臭泥",
    "臭臭泥",
    "大舌贝",
    "刺甲贝",
    "鬼斯",
    "鬼斯通",
    "耿鬼",
    "大岩蛇",
    "催眠貘",
    "引梦貘人",
    "大钳蟹",
    "巨钳蟹",
    "霹雳电球",
    "顽皮雷弹",
    "蛋蛋",
    "椰蛋树",
    "卡拉卡拉",
    "嘎啦嘎啦",
    "飞腿郎",
    "快拳郎",
    "大舌头",
    "瓦斯弹",
    "双弹瓦斯",
    "独角犀牛",
    "钻角犀兽",
    "吉利蛋",
    "蔓藤怪",
    "袋兽",
    "墨海马",
    "海刺龙",
    "角金鱼",
    "金鱼王",
    "海星星",
    "宝石海星",
    "魔墙人偶",
    "飞天螳螂",
    "迷唇姐",
    "电击兽",
    "鸭嘴火兽",
    "凯罗斯",
    "肯泰罗",
    "鲤鱼王",
    "暴鲤龙",
    "拉普拉斯",
    "百变怪",
    "伊布",
    "水伊布",
    "雷伊布",
    "火伊布",
    "多边兽",
    "菊石兽",
    "多刺菊石兽",
    "化石盔",
    "镰刀盔",
    "化石翼龙",
    "卡比兽",
    "急冻鸟",
    "闪电鸟",
    "火焰鸟",
    "迷你龙",
    "哈克龙",
    "快龙",
    "超梦",
    "梦幻",
    "菊草叶",
    "月桂叶",
    "大竺葵",
    "火球鼠",
    "火岩鼠",
    "火暴兽",
    "小锯鳄",
    "蓝鳄",
    "大力鳄",
    "尾立",
    "大尾立",
    "咕咕",
    "猫头夜鹰",
    "芭瓢虫",
    "安瓢虫",
    "圆丝蛛",
    "阿利多斯",
    "叉字蝠",
    "灯笼鱼",
    "电灯怪",
    "皮丘",
    "皮宝宝",
    "宝宝丁",
    "波克比",
    "波克基古",
    "天然雀",
    "天然鸟",
    "咩利羊",
    "茸茸羊",
    "电龙",
    "美丽花",
    "玛力露",
    "玛力露丽",
    "树才怪",
    "蚊香蛙皇",
    "毽子草",
    "毽子花",
    "毽子棉",
    "长尾怪手",
    "向日种子",
    "向日花怪",
    "蜻蜻蜓",
    "乌波",
    "沼王",
    "太阳伊布",
    "月亮伊布",
    "黑暗鸦",
    "呆呆王",
    "梦妖",
    "未知图腾",
    "果然翁",
    "麒麟奇",
    "榛果球",
    "佛烈托斯",
    "土龙弟弟",
    "天蝎",
    "大钢蛇",
    "布鲁",
    "布鲁皇",
    "千针鱼",
    "巨钳螳螂",
    "壶壶",
    "赫拉克罗斯",
    "狃拉",
    "熊宝宝",
    "圈圈熊",
    "熔岩虫",
    "熔岩蜗牛",
    "小山猪",
    "长毛猪",
    "太阳珊瑚",
    "铁炮鱼",
    "章鱼桶",
    "信使鸟",
    "巨翅飞鱼",
    "盔甲鸟",
    "戴鲁比",
    "黑鲁加",
    "刺龙王",
    "小小象",
    "顿甲",
    "多边兽Ⅱ",
    "惊角鹿",
    "图图犬",
    "无畏小子",
    "战舞郎",
    "迷唇娃",
    "电击怪",
    "鸭嘴宝宝",
    "大奶罐",
    "幸福蛋",
    "雷公",
    "炎帝",
    "水君",
    "幼基拉斯",
    "沙基拉斯",
    "班基拉斯",
    "洛奇亚",
    "凤王",
    "时拉比",
    "木守宫",
    "森林蜥蜴",
    "蜥蜴王",
    "火稚鸡",
    "力壮鸡",
    "火焰鸡",
    "水跃鱼",
    "沼跃鱼",
    "巨沼怪",
    "土狼犬",
    "大狼犬",
    "蛇纹熊",
    "直冲熊",
    "刺尾虫",
    "甲壳茧",
    "狩猎凤蝶",
    "盾甲茧",
    "毒粉蛾",
    "莲叶童子",
    "莲帽小童",
    "乐天河童",
    "橡实果",
    "长鼻叶",
    "狡猾天狗",
    "傲骨燕",
    "大王燕",
    "长翅鸥",
    "大嘴鸥",
    "拉鲁拉丝",
    "奇鲁莉安",
    "沙奈朵",
    "溜溜糖球",
    "雨翅蛾",
    "蘑蘑菇",
    "斗笠菇",
    "懒人獭",
    "过动猿",
    "请假王",
    "土居忍士",
    "铁面忍者",
    "脱壳忍者",
    "咕妞妞",
    "吼爆弹",
    "爆音怪",
    "幕下力士",
    "铁掌力士",
    "露力丽",
    "朝北鼻",
    "向尾喵",
    "优雅猫",
    "勾魂眼",
    "大嘴娃",
    "可可多拉",
    "可多拉",
    "波士可多拉",
    "玛沙那",
    "恰雷姆",
    "落雷兽",
    "雷电兽",
    "正电拍拍",
    "负电拍拍",
    "电萤虫",
    "甜甜萤",
    "毒蔷薇",
    "溶食兽",
    "吞食兽",
    "利牙鱼",
    "巨牙鲨",
    "吼吼鲸",
    "吼鲸王",
    "呆火驼",
    "喷火驼",
    "煤炭龟",
    "跳跳猪",
    "噗噗猪",
    "晃晃斑",
    "大颚蚁",
    "超音波幼虫",
    "沙漠蜻蜓",
    "刺球仙人掌",
    "梦歌仙人掌",
    "青绵鸟",
    "七夕青鸟",
    "猫鼬斩",
    "饭匙蛇",
    "月石",
    "太阳岩",
    "泥泥鳅",
    "鲶鱼王",
    "龙虾小兵",
    "铁螯龙虾",
    "天秤偶",
    "念力土偶",
    "触手百合",
    "摇篮百合",
    "太古羽虫",
    "太古盔甲",
    "丑丑鱼",
    "美纳斯",
    "飘浮泡泡",
    "变隐龙",
    "怨影娃娃",
    "诅咒娃娃",
    "夜巡灵",
    "彷徨夜灵",
    "热带龙",
    "风铃铃",
    "阿勃梭鲁",
    "小果然",
    "雪童子",
    "冰鬼护",
    "海豹球",
    "海魔狮",
    "帝牙海狮",
    "珍珠贝",
    "猎斑鱼",
    "樱花鱼",
    "古空棘鱼",
    "爱心鱼",
    "宝贝龙",
    "甲壳龙",
    "暴飞龙",
    "铁哑铃",
    "金属怪",
    "巨金怪",
    "雷吉洛克",
    "雷吉艾斯",
    "雷吉斯奇鲁",
    "拉帝亚斯",
    "拉帝欧斯",
    "盖欧卡",
    "固拉多",
    "烈空坐",
    "基拉祈",
    "代欧奇希斯",
    "草苗龟",
    "树林龟",
    "土台龟",
    "小火焰猴",
    "猛火猴",
    "烈焰猴",
    "波加曼",
    "波皇子",
    "帝王拿波",
    "姆克儿",
    "姆克鸟",
    "姆克鹰",
    "大牙狸",
    "大尾狸",
    "圆法师",
    "音箱蟀",
    "小猫怪",
    "勒克猫",
    "伦琴猫",
    "含羞苞",
    "罗丝雷朵",
    "头盖龙",
    "战槌龙",
    "盾甲龙",
    "护城龙",
    "结草儿",
    "结草贵妇",
    "绅士蛾",
    "三蜜蜂",
    "蜂女王",
    "帕奇利兹",
    "泳圈鼬",
    "浮潜鼬",
    "樱花宝",
    "樱花儿",
    "无壳海兔",
    "海兔兽",
    "双尾怪手",
    "飘飘球",
    "随风球",
    "卷卷耳",
    "长耳兔",
    "梦妖魔",
    "乌鸦头头",
    "魅力喵",
    "东施喵",
    "铃铛响",
    "臭鼬噗",
    "坦克臭鼬",
    "铜镜怪",
    "青铜钟",
    "盆才怪",
    "魔尼尼",
    "小福蛋",
    "聒噪鸟",
    "花岩怪",
    "圆陆鲨",
    "尖牙陆鲨",
    "烈咬陆鲨",
    "小卡比兽",
    "利欧路",
    "路卡利欧",
    "沙河马",
    "河马兽",
    "钳尾蝎",
    "龙王蝎",
    "不良蛙",
    "毒骷蛙",
    "尖牙笼",
    "荧光鱼",
    "霓虹鱼",
    "小球飞鱼",
    "雪笠怪",
    "暴雪王",
    "玛狃拉",
    "自爆磁怪",
    "大舌舔",
    "超甲狂犀",
    "巨蔓藤",
    "电击魔兽",
    "鸭嘴炎兽",
    "波克基斯",
    "远古巨蜓",
    "叶伊布",
    "冰伊布",
    "天蝎王",
    "象牙猪",
    "多边兽Ｚ",
    "艾路雷朵",
    "大朝北鼻",
    "黑夜魔灵",
    "雪妖女",
    "洛托姆",
    "由克希",
    "艾姆利多",
    "亚克诺姆",
    "帝牙卢卡",
    "帕路奇亚",
    "席多蓝恩",
    "雷吉奇卡斯",
    "骑拉帝纳",
    "克雷色利亚",
    "霏欧纳",
    "玛纳霏",
    "达克莱伊",
    "谢米",
    "阿尔宙斯",
  ],
};

const formNames: Record<
  Gen4IvDataLanguage,
  Readonly<Record<number, readonly string[]>>
> = {
  en: {
    "201": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "!",
      "?",
    ],
    "351": ["Normal", "Sunny", "Rainy", "Snowy"],
    "386": ["Normal", "Attack", "Defense", "Speed"],
    "412": ["Plant", "Sandy", "Trash"],
    "413": ["Plant", "Sandy", "Trash"],
    "421": ["Overcast", "Sunshine"],
    "422": ["West", "East"],
    "423": ["West", "East"],
    "479": ["Normal", "Heat", "Wash", "Frost", "Fan", "Mow"],
    "487": ["Altered", "Origin"],
    "492": ["Land", "Sky"],
  },
  ja: {
    "201": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "!",
      "?",
    ],
    "351": ["Normal", "Sunny", "Rainy", "Snowy"],
    "386": ["Normal", "Attack", "Defense", "Speed"],
    "412": ["Plant", "Sandy", "Trash"],
    "413": ["Plant", "Sandy", "Trash"],
    "421": ["Overcast", "Sunshine"],
    "422": ["West", "East"],
    "423": ["West", "East"],
    "479": ["Normal", "Heat", "Wash", "Frost", "Fan", "Mow"],
    "487": ["Altered", "Origin"],
    "492": ["Land", "Sky"],
  },
  zh: {
    "201": [
      "A",
      "B",
      "C",
      "D",
      "E",
      "F",
      "G",
      "H",
      "I",
      "J",
      "K",
      "L",
      "M",
      "N",
      "O",
      "P",
      "Q",
      "R",
      "S",
      "T",
      "U",
      "V",
      "W",
      "X",
      "Y",
      "Z",
      "!",
      "?",
    ],
    "351": ["普通形态", "太阳形态", "雨水形态", "雪云形态"],
    "386": ["普通形态", "攻击形态", "防御形态", "速度形态"],
    "412": ["草木蓑衣", "砂土蓑衣", "垃圾蓑衣"],
    "413": ["草木蓑衣", "砂土蓑衣", "垃圾蓑衣"],
    "421": ["阴天形态", "晴天形态"],
    "422": ["西海", "东海"],
    "423": ["西海", "东海"],
    "479": [
      "普通形态",
      "加热形态",
      "清洗形态",
      "结冰形态",
      "旋转形态",
      "切割形态",
    ],
    "487": ["别种形态", "起源形态"],
    "492": ["陆上形态", "天空形态"],
  },
};

const characteristicNames: Record<Gen4IvDataLanguage, readonly string[]> = {
  en: [
    "Loves to eat",
    "Often dozes off",
    "Often scatters things",
    "Scatters things often",
    "Likes to relax",
    "Proud of its power",
    "Likes to thrash about",
    "A little quick tempered",
    "Likes to fight",
    "Quick tempered",
    "Sturdy body",
    "Capable of taking hits",
    "Highly persistent",
    "Good endurance",
    "Good perseverance",
    "Likes to run",
    "Alert to sounds",
    "Impetuous and silly",
    "Somewhat of a clown",
    "Quick to flee",
    "Highly curious",
    "Mischievous",
    "Thoroughly cunning",
    "Often lost in thought",
    "Very finicky",
    "Strong willed",
    "Somewhat vain",
    "Strongly defiant",
    "Hates to lose",
    "Somewhat stubborn",
  ],
  ja: [
    "たべるのが だいすき",
    "ひるねを よくする",
    "いねむりが おおい",
    "ものを よく ちらかす",
    "のんびりするのが すき",
    "ちからが じまん",
    "あばれることが すき",
    "ちょっと おこりっぽい",
    "ケンカを するのが すき",
    "ちのけが おおい",
    "からだが じょうぶ",
    "うたれ づよい",
    "ねばり づよい",
    "しんぼう づよい",
    "がまん づよい",
    "かけっこが すき",
    "ものおとに びんかん",
    "おっちょこちょい",
    "すこし おちょうしもの",
    "にげるのが はやい",
    "こうきしんが つよい",
    "イタズラが すき",
    "ぬけめが ない",
    "かんがえごとが おおい",
    "とても きちょうめん",
    "きが つよい",
    "ちょっぴり みえっぱり",
    "まけんきが つよい",
    "まけずぎらい",
    "ちょっぴり ごうじょう",
  ],
  zh: [
    "非常喜欢吃东西",
    "经常睡午觉",
    "常常打瞌睡",
    "经常乱扔东西",
    "喜欢悠然自在",
    "以力气大为傲",
    "喜欢胡闹",
    "有点容易生气",
    "喜欢打架",
    "血气方刚",
    "身体强壮",
    "抗打能力强",
    "顽强不屈",
    "能吃苦耐劳",
    "善于忍耐",
    "喜欢比谁跑得快",
    "对声音敏感",
    "冒冒失失",
    "有点容易得意忘形",
    "逃得快",
    "好奇心强",
    "喜欢恶作剧",
    "做事万无一失",
    "经常思考",
    "一丝不苟",
    "性格强势",
    "有一点点爱慕虚荣",
    "争强好胜",
    "不服输",
    "有一点点固执",
  ],
};

const abilityNames: Record<Gen4IvDataLanguage, readonly string[]> = {
  en: [
    "Stench",
    "Drizzle",
    "Speed Boost",
    "Battle Armor",
    "Sturdy",
    "Damp",
    "Limber",
    "Sand Veil",
    "Static",
    "Volt Absorb",
    "Water Absorb",
    "Oblivious",
    "Cloud Nine",
    "Compound Eyes",
    "Insomnia",
    "Color Change",
    "Immunity",
    "Flash Fire",
    "Shield Dust",
    "Own Tempo",
    "Suction Cups",
    "Intimidate",
    "Shadow Tag",
    "Rough Skin",
    "Wonder Guard",
    "Levitate",
    "Effect Spore",
    "Synchronize",
    "Clear Body",
    "Natural Cure",
    "Lightning Rod",
    "Serene Grace",
    "Swift Swim",
    "Chlorophyll",
    "Illuminate",
    "Trace",
    "Huge Power",
    "Poison Point",
    "Inner Focus",
    "Magma Armor",
    "Water Veil",
    "Magnet Pull",
    "Soundproof",
    "Rain Dish",
    "Sand Stream",
    "Pressure",
    "Thick Fat",
    "Early Bird",
    "Flame Body",
    "Run Away",
    "Keen Eye",
    "Hyper Cutter",
    "Pickup",
    "Truant",
    "Hustle",
    "Cute Charm",
    "Plus",
    "Minus",
    "Forecast",
    "Sticky Hold",
    "Shed Skin",
    "Guts",
    "Marvel Scale",
    "Liquid Ooze",
    "Overgrow",
    "Blaze",
    "Torrent",
    "Swarm",
    "Rock Head",
    "Drought",
    "Arena Trap",
    "Vital Spirit",
    "White Smoke",
    "Pure Power",
    "Shell Armor",
    "Air Lock",
    "Tangled Feet",
    "Motor Drive",
    "Rivalry",
    "Steadfast",
    "Snow Cloak",
    "Gluttony",
    "Anger Point",
    "Unburden",
    "Heatproof",
    "Simple",
    "Dry Skin",
    "Download",
    "Iron Fist",
    "Poison Heal",
    "Adaptability",
    "Skill Link",
    "Hydration",
    "Solar Power",
    "Quick Feet",
    "Normalize",
    "Sniper",
    "Magic Guard",
    "No Guard",
    "Stall",
    "Technician",
    "Leaf Guard",
    "Klutz",
    "Mold Breaker",
    "Super Luck",
    "Aftermath",
    "Anticipation",
    "Forewarn",
    "Unaware",
    "Tinted Lens",
    "Filter",
    "Slow Start",
    "Scrappy",
    "Storm Drain",
    "Ice Body",
    "Solid Rock",
    "Snow Warning",
    "Honey Gather",
    "Frisk",
    "Reckless",
    "Multitype",
    "Flower Gift",
    "Bad Dreams",
    "Pickpocket",
    "Sheer Force",
    "Contrary",
    "Unnerve",
    "Defiant",
    "Defeatist",
    "Cursed Body",
    "Healer",
    "Friend Guard",
    "Weak Armor",
    "Heavy Metal",
    "Light Metal",
    "Multiscale",
    "Toxic Boost",
    "Flare Boost",
    "Harvest",
    "Telepathy",
    "Moody",
    "Overcoat",
    "Poison Touch",
    "Regenerator",
    "Big Pecks",
    "Sand Rush",
    "Wonder Skin",
    "Analytic",
    "Illusion",
    "Imposter",
    "Infiltrator",
    "Mummy",
    "Moxie",
    "Justified",
    "Rattled",
    "Magic Bounce",
    "Sap Sipper",
    "Prankster",
    "Sand Force",
    "Iron Barbs",
    "Zen Mode",
    "Victory Star",
    "Turboblaze",
    "Teravolt",
    "Aroma Veil",
    "Flower Veil",
    "Cheek Pouch",
    "Protean",
    "Fur Coat",
    "Magician",
    "Bulletproof",
    "Competitive",
    "Strong Jaw",
    "Refrigerate",
    "Sweet Veil",
    "Stance Change",
    "Gale Wings",
    "Mega Launcher",
    "Grass Pelt",
    "Symbiosis",
    "Tough Claws",
    "Pixilate",
    "Gooey",
    "Aerilate",
    "Parental Bond",
    "Dark Aura",
    "Fairy Aura",
    "Aura Break",
    "Primordial Sea",
    "Desolate Land",
    "Delta Stream",
    "Stamina",
    "Wimp Out",
    "Emergency Exit",
    "Water Compaction",
    "Merciless",
    "Shields Down",
    "Stakeout",
    "Water Bubble",
    "Steelworker",
    "Berserk",
    "Slush Rush",
    "Long Reach",
    "Liquid Voice",
    "Triage",
    "Galvanize",
    "Surge Surfer",
    "Schooling",
    "Disguise",
    "Battle Bond",
    "Power Construct",
    "Corrosion",
    "Comatose",
    "Queenly Majesty",
    "Innards Out",
    "Dancer",
    "Battery",
    "Fluffy",
    "Dazzling",
    "Soul-Heart",
    "Tangling Hair",
    "Receiver",
    "Power of Alchemy",
    "Beast Boost",
    "RKS System",
    "Electric Surge",
    "Psychic Surge",
    "Misty Surge",
    "Grassy Surge",
    "Full Metal Body",
    "Shadow Shield",
    "Prism Armor",
    "Neuroforce",
    "Intrepid Sword",
    "Dauntless Shield",
    "Libero",
    "Ball Fetch",
    "Cotton Down",
    "Propeller Tail",
    "Mirror Armor",
    "Gulp Missile",
    "Stalwart",
    "Steam Engine",
    "Punk Rock",
    "Sand Spit",
    "Ice Scales",
    "Ripen",
    "Ice Face",
    "Power Spot",
    "Mimicry",
    "Screen Cleaner",
    "Steely Spirit",
    "Perish Body",
    "Wandering Spirit",
    "Gorilla Tactics",
    "Neutralizing Gas",
    "Pastel Veil",
    "Hunger Switch",
  ],
  ja: [
    "あくしゅう",
    "あめふらし",
    "かそく",
    "カブトアーマー",
    "がんじょう",
    "しめりけ",
    "じゅうなん",
    "すながくれ",
    "せいでんき",
    "ちくでん",
    "ちょすい",
    "どんかん",
    "ノーてんき",
    "ふくがん",
    "ふみん",
    "へんしょく",
    "めんえき",
    "もらいび",
    "りんぷん",
    "マイペース",
    "きゅうばん",
    "いかく",
    "かげふみ",
    "さめはだ",
    "ふしぎなまもり",
    "ふゆう",
    "ほうし",
    "シンクロ",
    "クリアボディ",
    "しぜんかいふく",
    "ひらいしん",
    "てんのめぐみ",
    "すいすい",
    "ようりょくそ",
    "はっこう",
    "トレース",
    "ちからもち",
    "どくのトゲ",
    "せいしんりょく",
    "マグマのよろい",
    "みずのベール",
    "じりょく",
    "ぼうおん",
    "あめうけざら",
    "すなおこし",
    "プレッシャー",
    "あついしぼう",
    "はやおき",
    "ほのおのからだ",
    "にげあし",
    "するどいめ",
    "かいりきバサミ",
    "ものひろい",
    "なまけ",
    "はりきり",
    "メロメロボディ",
    "プラス",
    "マイナス",
    "てんきや",
    "ねんちゃく",
    "だっぴ",
    "こんじょう",
    "ふしぎなうろこ",
    "ヘドロえき",
    "しんりょく",
    "もうか",
    "げきりゅう",
    "むしのしらせ",
    "いしあたま",
    "ひでり",
    "ありじごく",
    "やるき",
    "しろいけむり",
    "ヨガパワー",
    "シェルアーマー",
    "エアロック",
    "ちどりあし",
    "でんきエンジン",
    "とうそうしん",
    "ふくつのこころ",
    "ゆきがくれ",
    "くいしんぼう",
    "いかりのつぼ",
    "かるわざ",
    "たいねつ",
    "たんじゅん",
    "かんそうはだ",
    "ダウンロード",
    "てつのこぶし",
    "ポイズンヒール",
    "てきおうりょく",
    "スキルリンク",
    "うるおいボディ",
    "サンパワー",
    "はやあし",
    "ノーマルスキン",
    "スナイパー",
    "マジックガード",
    "ノーガード",
    "あとだし",
    "テクニシャン",
    "リーフガード",
    "ぶきよう",
    "かたやぶり",
    "きょううん",
    "ゆうばく",
    "きけんよち",
    "よちむ",
    "てんねん",
    "いろめがね",
    "フィルター",
    "スロースタート",
    "きもったま",
    "よびみず",
    "アイスボディ",
    "ハードロック",
    "ゆきふらし",
    "みつあつめ",
    "おみとおし",
    "すてみ",
    "マルチタイプ",
    "フラワーギフト",
    "ナイトメア",
    "わるいてぐせ",
    "ちからずく",
    "あまのじゃく",
    "きんちょうかん",
    "まけんき",
    "よわき",
    "のろわれボディ",
    "いやしのこころ",
    "フレンドガード",
    "くだけるよろい",
    "ヘヴィメタル",
    "ライトメタル",
    "マルチスケイル",
    "どくぼうそう",
    "ねつぼうそう",
    "しゅうかく",
    "テレパシー",
    "ムラっけ",
    "ぼうじん",
    "どくしゅ",
    "さいせいりょく",
    "はとむね",
    "すなかき",
    "ミラクルスキン",
    "アナライズ",
    "イリュージョン",
    "かわりもの",
    "すりぬけ",
    "ミイラ",
    "じしんかじょう",
    "せいぎのこころ",
    "びびり",
    "マジックミラー",
    "そうしょく",
    "いたずらごころ",
    "すなのちから",
    "てつのトゲ",
    "ダルマモード",
    "しょうりのほし",
    "ターボブレイズ",
    "テラボルテージ",
    "アロマベール",
    "フラワーベール",
    "ほおぶくろ",
    "へんげんじざい",
    "ファーコート",
    "マジシャン",
    "ぼうだん",
    "かちき",
    "がんじょうあご",
    "フリーズスキン",
    "スイートベール",
    "バトルスイッチ",
    "はやてのつばさ",
    "メガランチャー",
    "くさのけがわ",
    "きょうせい",
    "かたいツメ",
    "フェアリースキン",
    "ぬめぬめ",
    "スカイスキン",
    "おやこあい",
    "ダークオーラ",
    "フェアリーオーラ",
    "オーラブレイク",
    "はじまりのうみ",
    "おわりのだいち",
    "デルタストリーム",
    "じきゅうりょく",
    "にげごし",
    "ききかいひ",
    "みずがため",
    "ひとでなし",
    "リミットシールド",
    "はりこみ",
    "すいほう",
    "はがねつかい",
    "ぎゃくじょう",
    "ゆきかき",
    "えんかく",
    "うるおいボイス",
    "ヒーリングシフト",
    "エレキスキン",
    "サーフテール",
    "ぎょぐん",
    "ばけのかわ",
    "きずなへんげ",
    "スワームチェンジ",
    "ふしょく",
    "ぜったいねむり",
    "じょおうのいげん",
    "とびだすなかみ",
    "おどりこ",
    "バッテリー",
    "もふもふ",
    "ビビッドボディ",
    "ソウルハート",
    "カーリーヘアー",
    "レシーバー",
    "かがくのちから",
    "ビーストブースト",
    "ＡＲシステム",
    "エレキメイカー",
    "サイコメイカー",
    "ミストメイカー",
    "グラスメイカー",
    "メタルプロテクト",
    "ファントムガード",
    "プリズムアーマー",
    "ブレインフォース",
    "ふとうのけん",
    "ふくつのたて",
    "リベロ",
    "たまひろい",
    "わたげ",
    "スクリューおびれ",
    "ミラーアーマー",
    "うのミサイル",
    "すじがねいり",
    "じょうききかん",
    "パンクロック",
    "すなはき",
    "こおりのりんぷん",
    "じゅくせい",
    "アイスフェイス",
    "パワースポット",
    "ぎたい",
    "バリアフリー",
    "はがねのせいしん",
    "ほろびのボディ",
    "さまようたましい",
    "ごりむちゅう",
    "かがくへんかガス",
    "パステルベール",
    "はらぺこスイッチ",
  ],
  zh: [
    "恶臭",
    "降雨",
    "加速",
    "战斗盔甲",
    "结实",
    "湿气",
    "柔软",
    "沙隐",
    "静电",
    "蓄电",
    "储水",
    "迟钝",
    "无关天气",
    "复眼",
    "不眠",
    "变色",
    "免疫",
    "引火",
    "鳞粉",
    "我行我素",
    "吸盘",
    "威吓",
    "踩影",
    "粗糙皮肤",
    "神奇守护",
    "飘浮",
    "孢子",
    "同步",
    "恒净之躯",
    "自然回复",
    "避雷针",
    "天恩",
    "悠游自如",
    "叶绿素",
    "发光",
    "复制",
    "大力士",
    "毒刺",
    "精神力",
    "熔岩铠甲",
    "水幕",
    "磁力",
    "隔音",
    "雨盘",
    "扬沙",
    "压迫感",
    "厚脂肪",
    "早起",
    "火焰之躯",
    "逃跑",
    "锐利目光",
    "怪力钳",
    "捡拾",
    "懒惰",
    "活力",
    "迷人之躯",
    "正电",
    "负电",
    "阴晴不定",
    "黏着",
    "蜕皮",
    "毅力",
    "神奇鳞片",
    "污泥浆",
    "茂盛",
    "猛火",
    "激流",
    "虫之预感",
    "坚硬脑袋",
    "日照",
    "沙穴",
    "干劲",
    "白色烟雾",
    "瑜伽之力",
    "硬壳盔甲",
    "气闸",
    "蹒跚",
    "电气引擎",
    "斗争心",
    "不屈之心",
    "雪隐",
    "贪吃鬼",
    "愤怒穴位",
    "轻装",
    "耐热",
    "单纯",
    "干燥皮肤",
    "下载",
    "铁拳",
    "毒疗",
    "适应力",
    "连续攻击",
    "湿润之躯",
    "太阳之力",
    "飞毛腿",
    "一般皮肤",
    "狙击手",
    "魔法防守",
    "无防守",
    "慢出",
    "技术高手",
    "叶子防守",
    "笨拙",
    "破格",
    "超幸运",
    "引爆",
    "危险预知",
    "预知梦",
    "纯朴",
    "有色眼镜",
    "过滤",
    "慢启动",
    "胆量",
    "引水",
    "冰冻之躯",
    "坚硬岩石",
    "降雪",
    "采蜜",
    "察觉",
    "舍身",
    "多属性",
    "花之礼",
    "梦魇",
    "顺手牵羊",
    "强行",
    "唱反调",
    "紧张感",
    "不服输",
    "软弱",
    "诅咒之躯",
    "治愈之心",
    "友情防守",
    "碎裂铠甲",
    "重金属",
    "轻金属",
    "多重鳞片",
    "中毒激升",
    "受热激升",
    "收获",
    "心灵感应",
    "心情不定",
    "防尘",
    "毒手",
    "再生力",
    "健壮胸肌",
    "拨沙",
    "奇迹皮肤",
    "分析",
    "幻觉",
    "变身者",
    "穿透",
    "木乃伊",
    "自信过度",
    "正义之心",
    "胆怯",
    "魔法镜",
    "食草",
    "恶作剧之心",
    "沙之力",
    "铁刺",
    "达摩模式",
    "胜利之星",
    "涡轮火焰",
    "兆级电压",
    "芳香幕",
    "花幕",
    "颊囊",
    "变幻自如",
    "毛皮大衣",
    "魔术师",
    "防弹",
    "好胜",
    "强壮之颚",
    "冰冻皮肤",
    "甜幕",
    "战斗切换",
    "疾风之翼",
    "超级发射器",
    "草之毛皮",
    "共生",
    "硬爪",
    "妖精皮肤",
    "黏滑",
    "飞行皮肤",
    "亲子爱",
    "暗黑气场",
    "妖精气场",
    "气场破坏",
    "始源之海",
    "终结之地",
    "德尔塔气流",
    "持久力",
    "跃跃欲逃",
    "危险回避",
    "遇水凝固",
    "不仁不义",
    "界限盾壳",
    "蹲守",
    "水泡",
    "钢能力者",
    "怒火冲天",
    "拨雪",
    "远隔",
    "湿润之声",
    "先行治疗",
    "电气皮肤",
    "冲浪之尾",
    "鱼群",
    "画皮",
    "牵绊变身",
    "群聚变形",
    "腐蚀",
    "绝对睡眠",
    "女王的威严",
    "飞出的内在物",
    "舞者",
    "蓄电池",
    "毛茸茸",
    "鲜艳之躯",
    "魂心",
    "卷发",
    "接球手",
    "化学之力",
    "异兽提升",
    "ＡＲ系统",
    "电气制造者",
    "精神制造者",
    "薄雾制造者",
    "青草制造者",
    "金属防护",
    "幻影防守",
    "棱镜装甲",
    "脑核之力",
    "不挠之剑",
    "不屈之盾",
    "自由者",
    "捡球",
    "棉絮",
    "螺旋尾鳍",
    "镜甲",
    "一口导弹",
    "坚毅",
    "蒸汽机",
    "庞克摇滚",
    "吐沙",
    "冰鳞粉",
    "熟成",
    "结冻头",
    "能量点",
    "拟态",
    "除障",
    "钢之意志",
    "灭亡之躯",
    "游魂",
    "一猩一意",
    "化学变化气体",
    "粉彩护幕",
    "饱了又饿",
  ],
};

const decodedPersonal: Partial<Record<Gen4PersonalVersion, Uint8Array>> = {};
const formData: Readonly<Record<number, { count: number; index: number }>> = {
  386: { count: 4, index: 496 },
  413: { count: 3, index: 499 },
  479: { count: 6, index: 503 },
  487: { count: 2, index: 501 },
  492: { count: 2, index: 502 },
};

function languageKey(language: string): Gen4IvDataLanguage {
  if (language.startsWith("zh")) return "zh";
  if (language.startsWith("ja")) return "ja";
  return "en";
}

function personal(dataSet: Gen4PersonalVersion) {
  return (decodedPersonal[dataSet] ??= Uint8Array.from(
    atob(encodedPersonal[dataSet]),
    (character) => character.charCodeAt(0),
  ));
}

export function getGen4FormCount(species: number) {
  return formData[species]?.count ?? 1;
}

export function getGen4BaseStats(
  dataSet: Gen4PersonalVersion,
  species: number,
  form = 0,
): Gen4BaseStats {
  if (!Number.isInteger(species) || species < 1 || species > 493) {
    throw new RangeError("Generation IV species must be between 1 and 493.");
  }
  const formInfo = formData[species];
  if (!Number.isInteger(form) || form < 0 || form >= (formInfo?.count ?? 1)) {
    throw new RangeError("Invalid Generation IV form.");
  }
  const record = form === 0 ? species : formInfo.index + form - 1;
  const bytes = personal(dataSet);
  const offset = record * 8;
  if (offset + 8 > bytes.length) {
    throw new RangeError("Generation IV form is unavailable in this game.");
  }
  return [
    bytes[offset],
    bytes[offset + 1],
    bytes[offset + 2],
    bytes[offset + 3],
    bytes[offset + 4],
    bytes[offset + 5],
  ];
}

export function getGen4Abilities(
  dataSet: Gen4PersonalVersion,
  species: number,
  form = 0,
): [number, number] {
  const formInfo = formData[species];
  const record = form === 0 ? species : formInfo.index + form - 1;
  const bytes = personal(dataSet);
  const offset = record * 8;
  return [bytes[offset + 6], bytes[offset + 7]];
}

export function getGen4Species(language: string) {
  return speciesNames[languageKey(language)].map((name, index) => ({
    id: index + 1,
    name,
  }));
}

export function getGen4Characteristics(language: string) {
  return characteristicNames[languageKey(language)];
}

export function getGen4AbilityName(language: string, ability: number) {
  return abilityNames[languageKey(language)][ability - 1] ?? String(ability);
}

export function getGen4SpeciesName(
  language: string,
  species: number,
  form = 0,
) {
  const selectedLanguage = languageKey(language);
  const speciesName =
    speciesNames[selectedLanguage][species - 1] ?? `#${species}`;
  if (form === 0) return speciesName;
  const formName = formNames[selectedLanguage][species]?.[form] ?? String(form);
  return `${speciesName} (${formName})`;
}
