/*!
 * Generated from EncounterTableGenerator Gen4/encounters.json and
 * PokeFinder 4.3.2 personal_pt.bin. GPL-3.0-or-later.
 * Do not hand-edit; rerun scripts/generate_gen4_static_data.mjs.
 */
import type { Gen4StaticTemplate } from "./domain";

export const GEN4_STATIC_TEMPLATES: readonly Gen4StaticTemplate[] = [
  {
    id: "starters-00",
    category: "starters",
    label: "Turtwig @ Lake Verity / Route 201",
    versions: ["diamond", "pearl", "platinum"],
    species: 387,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-01",
    category: "starters",
    label: "Chimchar @ Lake Verity / Route 201",
    versions: ["diamond", "pearl", "platinum"],
    species: 390,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-02",
    category: "starters",
    label: "Piplup @ Lake Verity / Route 201",
    versions: ["diamond", "pearl", "platinum"],
    species: 393,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-03",
    category: "starters",
    label: "Bulbasaur @ Pallet Town",
    versions: ["heartgold", "soulsilver"],
    species: 1,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-04",
    category: "starters",
    label: "Charmander @ Pallet Town",
    versions: ["heartgold", "soulsilver"],
    species: 4,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-05",
    category: "starters",
    label: "Squirtle @ Pallet Town",
    versions: ["heartgold", "soulsilver"],
    species: 7,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-06",
    category: "starters",
    label: "Chikorita @ New Bark Town",
    versions: ["heartgold", "soulsilver"],
    species: 152,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-07",
    category: "starters",
    label: "Cyndaquil @ New Bark Town",
    versions: ["heartgold", "soulsilver"],
    species: 155,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-08",
    category: "starters",
    label: "Totodile @ New Bark Town",
    versions: ["heartgold", "soulsilver"],
    species: 158,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-09",
    category: "starters",
    label: "Treecko @ Saffron City",
    versions: ["heartgold", "soulsilver"],
    species: 252,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-10",
    category: "starters",
    label: "Torchic @ Saffron City",
    versions: ["heartgold", "soulsilver"],
    species: 255,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "starters-11",
    category: "starters",
    label: "Mudkip @ Saffron City",
    versions: ["heartgold", "soulsilver"],
    species: 258,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-00",
    category: "fossils",
    label: "Omanyte @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 138,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-01",
    category: "fossils",
    label: "Kabuto @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 140,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-02",
    category: "fossils",
    label: "Aerodactyl @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 142,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-03",
    category: "fossils",
    label: "Lileep @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 345,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-04",
    category: "fossils",
    label: "Anorith @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 347,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-05",
    category: "fossils",
    label: "Cranidos @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 408,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "fossils-06",
    category: "fossils",
    label: "Shieldon @ Mining Museum",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 410,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-00",
    category: "gifts",
    label: "Eevee @ Hearthome City",
    versions: ["diamond", "pearl"],
    species: 133,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-01",
    category: "gifts",
    label: "Eevee @ Hearthome City",
    versions: ["platinum"],
    species: 133,
    form: 0,
    level: 20,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-02",
    category: "gifts",
    label: "Porygon @ Veilstone City",
    versions: ["platinum"],
    species: 137,
    form: 0,
    level: 25,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-03",
    category: "gifts",
    label: "Togepi egg @ Cynthia",
    versions: ["platinum"],
    species: 175,
    form: 0,
    level: 1,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-04",
    category: "gifts",
    label: "Happiny egg @ Traveling Man",
    versions: ["diamond", "pearl"],
    species: 440,
    form: 0,
    level: 1,
    genderRatio: 254,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-05",
    category: "gifts",
    label: "Riolu egg @ Riley",
    versions: ["diamond", "pearl", "platinum"],
    species: 447,
    form: 0,
    level: 1,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-06",
    category: "gifts",
    label: "Tentacool @ Cianwood City",
    versions: ["heartgold", "soulsilver"],
    species: 72,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-07",
    category: "gifts",
    label: "Eevee @ Goldenrod City",
    versions: ["heartgold", "soulsilver"],
    species: 133,
    form: 0,
    level: 5,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-08",
    category: "gifts",
    label: "Dratini @ Dragon",
    versions: ["heartgold", "soulsilver"],
    species: 147,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-09",
    category: "gifts",
    label: "Tyrogue @ Mt. Mortar",
    versions: ["heartgold", "soulsilver"],
    species: 236,
    form: 0,
    level: 10,
    genderRatio: 0,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-10",
    category: "gifts",
    label: "Togepi Egg @ Mr. Pokemon",
    versions: ["heartgold", "soulsilver"],
    species: 175,
    form: 0,
    level: 1,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-11",
    category: "gifts",
    label: "Mareep Egg @ Primo",
    versions: ["heartgold", "soulsilver"],
    species: 179,
    form: 0,
    level: 1,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-12",
    category: "gifts",
    label: "Wooper Egg @ Primo",
    versions: ["heartgold", "soulsilver"],
    species: 194,
    form: 0,
    level: 1,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gifts-13",
    category: "gifts",
    label: "Slugma Egg @ Primo",
    versions: ["heartgold", "soulsilver"],
    species: 218,
    form: 0,
    level: 1,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-00",
    category: "gameCorner",
    label: "Mr. Mime @ Celadon City Game Corner",
    versions: ["heartgold", "soulsilver"],
    species: 122,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-01",
    category: "gameCorner",
    label: "Eevee @ Celadon City Game Corner",
    versions: ["heartgold", "soulsilver"],
    species: 133,
    form: 0,
    level: 15,
    genderRatio: 31,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-02",
    category: "gameCorner",
    label: "Porygon @ Celadon City Game Corner",
    versions: ["heartgold", "soulsilver"],
    species: 137,
    form: 0,
    level: 15,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-03",
    category: "gameCorner",
    label: "Abra @ Goldenrod City Game Corner",
    versions: ["heartgold", "soulsilver"],
    species: 63,
    form: 0,
    level: 15,
    genderRatio: 63,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-04",
    category: "gameCorner",
    label: "Ekans @ Goldenrod City Game Corner",
    versions: ["heartgold"],
    species: 23,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-05",
    category: "gameCorner",
    label: "Sandshrew @ Goldenrod City Game Corner",
    versions: ["soulsilver"],
    species: 27,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "gameCorner-06",
    category: "gameCorner",
    label: "Dratini @ Goldenrod City Game Corner",
    versions: ["heartgold", "soulsilver"],
    species: 147,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "stationary-00",
    category: "stationary",
    label: "Drifloon @ Valley Windworks",
    versions: ["diamond", "pearl"],
    species: 425,
    form: 0,
    level: 22,
    genderRatio: 127,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "stationary-01",
    category: "stationary",
    label: "Drifloon @ Valley Windworks",
    versions: ["platinum"],
    species: 425,
    form: 0,
    level: 15,
    genderRatio: 127,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "stationary-02",
    category: "stationary",
    label: "Rotom @ Old Chateau",
    versions: ["diamond", "pearl"],
    species: 479,
    form: 0,
    level: 15,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "stationary-03",
    category: "stationary",
    label: "Rotom @ Old Chateau",
    versions: ["platinum"],
    species: 479,
    form: 0,
    level: 20,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "stationary-04",
    category: "stationary",
    label: "Spiritomb @ Route 209",
    versions: ["diamond", "pearl", "platinum"],
    species: 442,
    form: 0,
    level: 25,
    genderRatio: 127,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "stationary-05",
    category: "stationary",
    label: "Voltorb @ Team Rocket HQ Trap Floor",
    versions: ["heartgold", "soulsilver"],
    species: 100,
    form: 0,
    level: 23,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-06",
    category: "stationary",
    label: "Geodude @ Team Rocket HQ Trap Floor",
    versions: ["heartgold", "soulsilver"],
    species: 74,
    form: 0,
    level: 21,
    genderRatio: 127,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-07",
    category: "stationary",
    label: "Koffing @ Team Rocket HQ Trap Floor",
    versions: ["heartgold", "soulsilver"],
    species: 109,
    form: 0,
    level: 21,
    genderRatio: 127,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-08",
    category: "stationary",
    label: "Gyrados @ Lake of Rage",
    versions: ["heartgold", "soulsilver"],
    species: 130,
    form: 0,
    level: 30,
    genderRatio: 127,
    method: "method1",
    shinyLock: "always",
  },
  {
    id: "stationary-09",
    category: "stationary",
    label: "Lapras @ Union Cave",
    versions: ["heartgold", "soulsilver"],
    species: 131,
    form: 0,
    level: 20,
    genderRatio: 127,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-10",
    category: "stationary",
    label: "Electrode @ Team Rocket HQ",
    versions: ["heartgold", "soulsilver"],
    species: 101,
    form: 0,
    level: 23,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-11",
    category: "stationary",
    label: "Snorlax @ Route 11",
    versions: ["heartgold", "soulsilver"],
    species: 143,
    form: 0,
    level: 50,
    genderRatio: 31,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "stationary-12",
    category: "stationary",
    label: "Sudowoodo @ Route 36",
    versions: ["heartgold", "soulsilver"],
    species: 185,
    form: 0,
    level: 20,
    genderRatio: 127,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-00",
    category: "legends",
    label: "Regirock @ Rock Peak Ruins",
    versions: ["platinum"],
    species: 377,
    form: 0,
    level: 30,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-01",
    category: "legends",
    label: "Regice @ Iceberg Ruins",
    versions: ["platinum"],
    species: 378,
    form: 0,
    level: 30,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-02",
    category: "legends",
    label: "Registeel @ Iron Ruins",
    versions: ["platinum"],
    species: 379,
    form: 0,
    level: 30,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-03",
    category: "legends",
    label: "Uxie @ Acuity Cavern",
    versions: ["diamond", "pearl", "platinum"],
    species: 480,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-04",
    category: "legends",
    label: "Azelf @ Valor Cavern",
    versions: ["diamond", "pearl", "platinum"],
    species: 482,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-05",
    category: "legends",
    label: "Diagla @ Spear Pillar",
    versions: ["diamond"],
    species: 483,
    form: 0,
    level: 47,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-06",
    category: "legends",
    label: "Palkia @ Spear Pillar",
    versions: ["pearl"],
    species: 484,
    form: 0,
    level: 47,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-07",
    category: "legends",
    label: "Diagla @ Spear Pillar",
    versions: ["platinum"],
    species: 483,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-08",
    category: "legends",
    label: "Palkia @ Spear Pillar",
    versions: ["platinum"],
    species: 484,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-09",
    category: "legends",
    label: "Heatran @ Stark Mountain",
    versions: ["diamond", "pearl"],
    species: 485,
    form: 0,
    level: 70,
    genderRatio: 127,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-10",
    category: "legends",
    label: "Heatran @ Stark Mountain",
    versions: ["platinum"],
    species: 485,
    form: 0,
    level: 50,
    genderRatio: 127,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-11",
    category: "legends",
    label: "Regigigas @ Snowpoint Temple",
    versions: ["diamond", "pearl"],
    species: 486,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-12",
    category: "legends",
    label: "Regigigas @ Snowpoint Temple",
    versions: ["platinum"],
    species: 486,
    form: 0,
    level: 1,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-13",
    category: "legends",
    label: "Giratina @ Turnback Cave",
    versions: ["diamond", "pearl"],
    species: 487,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-14",
    category: "legends",
    label: "Giratina @ Turnback Cave",
    versions: ["platinum"],
    species: 487,
    form: 0,
    level: 47,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-15",
    category: "legends",
    label: "Giratina @ Distortion World",
    versions: ["platinum"],
    species: 487,
    form: 1,
    level: 47,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "legends-16",
    category: "legends",
    label: "Articuno @ Seafoam Islands",
    versions: ["heartgold", "soulsilver"],
    species: 144,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-17",
    category: "legends",
    label: "Zapdos @ Route 10",
    versions: ["heartgold", "soulsilver"],
    species: 145,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-18",
    category: "legends",
    label: "Moltres @ Mt. Silver Cave",
    versions: ["heartgold", "soulsilver"],
    species: 146,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-19",
    category: "legends",
    label: "Mewtwo @ Cerulean Cave",
    versions: ["heartgold", "soulsilver"],
    species: 150,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-20",
    category: "legends",
    label: "Suicune @ Route 25",
    versions: ["heartgold", "soulsilver"],
    species: 245,
    form: 0,
    level: 40,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-21",
    category: "legends",
    label: "Lugia @ Whirl Islands",
    versions: ["heartgold"],
    species: 249,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-22",
    category: "legends",
    label: "Lugia @ Whirl Islands",
    versions: ["soulsilver"],
    species: 249,
    form: 0,
    level: 45,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-23",
    category: "legends",
    label: "Ho-Oh @ Bell Tower",
    versions: ["heartgold"],
    species: 250,
    form: 0,
    level: 45,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-24",
    category: "legends",
    label: "Ho-Oh @ Bell Tower",
    versions: ["soulsilver"],
    species: 250,
    form: 0,
    level: 70,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-25",
    category: "legends",
    label: "Latios @ Pewter City",
    versions: ["heartgold"],
    species: 381,
    form: 0,
    level: 40,
    genderRatio: 0,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-26",
    category: "legends",
    label: "Latias @ Pewter City",
    versions: ["soulsilver"],
    species: 380,
    form: 0,
    level: 40,
    genderRatio: 254,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-27",
    category: "legends",
    label: "Kyogre @ Embedded Tower",
    versions: ["heartgold"],
    species: 382,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-28",
    category: "legends",
    label: "Groudon @ Embedded Tower",
    versions: ["soulsilver"],
    species: 383,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-29",
    category: "legends",
    label: "Rayquaza @ Embedded Tower",
    versions: ["heartgold", "soulsilver"],
    species: 384,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodK",
    shinyLock: "random",
  },
  {
    id: "legends-30",
    category: "legends",
    label: "Dialga @ Sinjoh Ruins",
    versions: ["heartgold", "soulsilver"],
    species: 483,
    form: 0,
    level: 1,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "legends-31",
    category: "legends",
    label: "Palkia @ Sinjoh Ruins",
    versions: ["heartgold", "soulsilver"],
    species: 484,
    form: 0,
    level: 1,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "legends-32",
    category: "legends",
    label: "Giratina @ Sinjoh Ruins",
    versions: ["heartgold", "soulsilver"],
    species: 487,
    form: 1,
    level: 1,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "events-00",
    category: "events",
    label: "Manaphy @ Pokemon Ranger",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 490,
    form: 0,
    level: 1,
    genderRatio: 255,
    method: "method1",
    shinyLock: "never",
  },
  {
    id: "events-01",
    category: "events",
    label: "Manaphy @ Pokemon Ranger",
    versions: ["diamond", "pearl", "platinum", "heartgold", "soulsilver"],
    species: 490,
    form: 0,
    level: 1,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "events-02",
    category: "events",
    label: "Darkrai @ Newmoon Island",
    versions: ["platinum"],
    species: 491,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "events-03",
    category: "events",
    label: "Shaymin @ Flower Paradise",
    versions: ["platinum"],
    species: 492,
    form: 0,
    level: 30,
    genderRatio: 255,
    method: "methodJ",
    shinyLock: "random",
  },
  {
    id: "roamers-00",
    category: "roamers",
    label: "Mesprit",
    versions: ["diamond", "pearl", "platinum"],
    species: 481,
    form: 0,
    level: 50,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-01",
    category: "roamers",
    label: "Cresselia",
    versions: ["diamond", "pearl", "platinum"],
    species: 488,
    form: 0,
    level: 50,
    genderRatio: 254,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-02",
    category: "roamers",
    label: "Articuno",
    versions: ["platinum"],
    species: 144,
    form: 0,
    level: 60,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-03",
    category: "roamers",
    label: "Zapdos",
    versions: ["platinum"],
    species: 145,
    form: 0,
    level: 60,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-04",
    category: "roamers",
    label: "Moltres",
    versions: ["platinum"],
    species: 146,
    form: 0,
    level: 60,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-05",
    category: "roamers",
    label: "Raikou",
    versions: ["heartgold", "soulsilver"],
    species: 243,
    form: 0,
    level: 40,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-06",
    category: "roamers",
    label: "Entei",
    versions: ["heartgold", "soulsilver"],
    species: 244,
    form: 0,
    level: 40,
    genderRatio: 255,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-07",
    category: "roamers",
    label: "Latias",
    versions: ["heartgold"],
    species: 380,
    form: 0,
    level: 35,
    genderRatio: 254,
    method: "method1",
    shinyLock: "random",
  },
  {
    id: "roamers-08",
    category: "roamers",
    label: "Latios",
    versions: ["soulsilver"],
    species: 381,
    form: 0,
    level: 35,
    genderRatio: 0,
    method: "method1",
    shinyLock: "random",
  },
];
