import fs from "node:fs";
import path from "node:path";
import process from "node:process";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const upstreamRoot =
  "C:/Users/Hakuhiro/Documents/Github/3DSRNGTool_CHN/3DSRNGTool";
const personalPath = path.join(upstreamRoot, "Resources/bytes/personal_ao");
const outputTs = path.join(root, "src/features/gen6event/data.ts");
const outputCpp = path.join(
  root,
  "wasm/modules/gen6event/bridge/gen6_event_personal.inc",
);

const recordSize = 0x50;
const formIndexOffset = 0x1c;
const genderOffset = 0x12;
const formCountOffset = 0x20;
const personal = fs.readFileSync(personalPath);
const speciesCount = 722;

const species = [];
const forms = [];
for (let speciesId = 0; speciesId < speciesCount; speciesId += 1) {
  const baseOffset = speciesId * recordSize;
  const formCount = Math.max(1, personal[baseOffset + formCountOffset]);
  const formIndex = personal.readUInt16LE(baseOffset + formIndexOffset);
  const offset = forms.length;
  for (let form = 0; form < formCount; form += 1) {
    const resolved =
      form === 0 || formIndex === 0 ? speciesId : formIndex + form - 1;
    const resolvedOffset = resolved * recordSize;
    forms.push(personal[resolvedOffset + genderOffset]);
  }
  species.push({ offset, formCount });
}

const ts = `/*
 * Generated from 3DSRNGTool revision 359bdd7a9ff7c145fec12302cf43da932923fa62.
 * 3DSRNGTool is licensed under MIT; bundled species and personal data retain
 * their upstream attribution. Do not hand-edit; rerun
 * scripts/generate_gen6_event_data.mjs.
 */

import {
  GEN6_STATIONARY_NATURES,
  GEN6_STATIONARY_SPECIES,
} from "../gen6stationary/data";

export type Gen6EventLanguage = "en" | "ja" | "zh";
export type Gen6EventVersion = "x" | "y" | "omega-ruby" | "alpha-sapphire";
export type Gen6EventGenderRatio =
  | 0
  | 31
  | 63
  | 127
  | 191
  | 225
  | 254
  | 255;

export interface Gen6EventPersonalForm {
  readonly genderRatio: number;
}

export interface Gen6EventPersonalEntry {
  readonly species: number;
  readonly forms: readonly Gen6EventPersonalForm[];
}

export const GEN6_EVENT_SPECIES = GEN6_STATIONARY_SPECIES;
export const GEN6_EVENT_NATURES = GEN6_STATIONARY_NATURES;

const GEN6_EVENT_GENDER_RATIOS = ${JSON.stringify(forms)} as const;
const GEN6_EVENT_FORM_RANGES = ${JSON.stringify(species)} as const;

export const GEN6_EVENT_PERSONAL: readonly Gen6EventPersonalEntry[] =
  GEN6_EVENT_FORM_RANGES.map((range, species) => ({
    species,
    forms: GEN6_EVENT_GENDER_RATIOS.slice(
      range.offset,
      range.offset + range.formCount,
    ).map((genderRatio) => ({ genderRatio })),
  }));

export function gen6EventPersonalForm(species: number, form: number) {
  const entry = GEN6_EVENT_PERSONAL[species];
  if (!entry || !entry.forms[form])
    throw new RangeError("Species or form is outside the Gen VI personal table.");
  return entry.forms[form];
}

export function gen6EventFormCount(species: number) {
  return GEN6_EVENT_PERSONAL[species]?.forms.length ?? 0;
}
`;

const cppSpecies = species
  .map(({ offset, formCount }) => `    {${offset}, ${formCount}}`)
  .join(",\n");
const cppForms = forms.join(", ");
const cpp = `/* Generated by scripts/generate_gen6_event_data.mjs. */
#pragma once

#include <array>
#include <cstdint>

struct Gen6EventSpeciesInfo {
    std::uint16_t formOffset;
    std::uint8_t formCount;
};

constexpr std::array<Gen6EventSpeciesInfo, ${speciesCount}> gen6EventSpecies = {{
${cppSpecies}
}};

constexpr std::array<std::uint8_t, ${forms.length}> gen6EventFormGenders = {${cppForms}};
`;

fs.mkdirSync(path.dirname(outputTs), { recursive: true });
fs.mkdirSync(path.dirname(outputCpp), { recursive: true });
fs.writeFileSync(outputTs, ts);
fs.writeFileSync(outputCpp, cpp);
process.stdout.write(`Generated ${outputTs} and ${outputCpp}.\n`);
